### PR TITLE
network: add leb128; add block response size limit

### LINKED ISSUE #484: Implement LEB128 variable-length encoding
## Expected Behavior

We have LEB123 variable-length encoding implemented. 

## Current Behavior

We have an unused `leb128ToUint64` method that decodes a byte array to uint64 using LEB128 variable-length encoding. We previously thought we needed this to send and receive messages with Alexander. We need to investigate whether we still need this and implement it if we do.

### LINKED ISSUE #672: Investigate core/network syncing errors
## Current Behavior

- "genesis hash" error
- open/close multiple streams within milliseconds
- message type not supported (see #650)

```
DBUG[03-04|15:49:11] Broadcasting message from core service   host=12D3KooWCxm3tCeWfCcgUgjPd5tfLhafZJGt6N9LsbCU8xfpdU1R type=3
TRCE[03-04|15:49:11] Sent message                             host=12D3KooWCxm3tCeWfCcgUgjPd5tfLhafZJGt6N9LsbCU8xfpdU1R peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg type=3
TRCE[03-04|15:49:11] Opened stream                            host=12D3KooWCxm3tCeWfCcgUgjPd5tfLhafZJGt6N9LsbCU8xfpdU1R peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg protocol=
TRCE[03-04|15:49:11] Opened stream                            host=12D3KooWCxm3tCeWfCcgUgjPd5tfLhafZJGt6N9LsbCU8xfpdU1R peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg protocol=
TRCE[03-04|15:49:11] Opened stream                            host=12D3KooWCxm3tCeWfCcgUgjPd5tfLhafZJGt6N9LsbCU8xfpdU1R peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg protocol=
TRCE[03-04|15:49:11] Opened stream                            host=12D3KooWCxm3tCeWfCcgUgjPd5tfLhafZJGt6N9LsbCU8xfpdU1R peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg protocol=
TRCE[03-04|15:49:11] Closed stream                            host=12D3KooWCxm3tCeWfCcgUgjPd5tfLhafZJGt6N9LsbCU8xfpdU1R peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg protocol=/ipfs/id/1.0.0
TRCE[03-04|15:49:11] Opened stream                            host=12D3KooWCxm3tCeWfCcgUgjPd5tfLhafZJGt6N9LsbCU8xfpdU1R peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg protocol=
TRCE[03-04|15:49:11] Opened stream                            host=12D3KooWCxm3tCeWfCcgUgjPd5tfLhafZJGt6N9LsbCU8xfpdU1R peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg protocol=/gossamer/gssmr/0
TRCE[03-04|15:49:11] Sent message                             host=12D3KooWCxm3tCeWfCcgUgjPd5tfLhafZJGt6N9LsbCU8xfpdU1R peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg type=0
TRCE[03-04|15:49:11] Received message from peer               host=12D3KooWCxm3tCeWfCcgUgjPd5tfLhafZJGt6N9LsbCU8xfpdU1R peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg type=0
TRCE[03-04|15:49:11] Opened stream                            host=12D3KooWCxm3tCeWfCcgUgjPd5tfLhafZJGt6N9LsbCU8xfpdU1R peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg protocol=/gossamer/gssmr/0
TRCE[03-04|15:49:11] Sent message                             host=12D3KooWCxm3tCeWfCcgUgjPd5tfLhafZJGt6N9LsbCU8xfpdU1R peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg type=0
TRCE[03-04|15:49:11] Opened stream                            host=12D3KooWCxm3tCeWfCcgUgjPd5tfLhafZJGt6N9LsbCU8xfpdU1R peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg protocol=/gossamer/gssmr/0
TRCE[03-04|15:49:11] Sent message                             host=12D3KooWCxm3tCeWfCcgUgjPd5tfLhafZJGt6N9LsbCU8xfpdU1R peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg type=0
TRCE[03-04|15:49:11] Opened stream                            host=12D3KooWCxm3tCeWfCcgUgjPd5tfLhafZJGt6N9LsbCU8xfpdU1R peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg protocol=/gossamer/gssmr/0
TRCE[03-04|15:49:11] Sent message                             host=12D3KooWCxm3tCeWfCcgUgjPd5tfLhafZJGt6N9LsbCU8xfpdU1R peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg type=0
TRCE[03-04|15:49:11] Received message from peer               host=12D3KooWCxm3tCeWfCcgUgjPd5tfLhafZJGt6N9LsbCU8xfpdU1R peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg type=1
EROR[03-04|15:49:11] [core] failed to handle message from network service err="Received unsupported message type 1"
TRCE[03-04|15:49:11] Received message from peer               host=12D3KooWCxm3tCeWfCcgUgjPd5tfLhafZJGt6N9LsbCU8xfpdU1R peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg type=0
EROR[03-04|15:49:11] Failed to validate status message        err="genesis hash"
EROR[03-04|15:49:11] Failed to decode message from peer       peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg err="stream reset"
EROR[03-04|15:49:11] Failed to decode message from peer       peer=12D3KooWBdQPJ5EHy2fCD6UsyfiKYxV5hu1xhqDb5eWrekVzzvKg err="stream reset"
```

## Steps to Reproduce

```
make gossamer
```

```
./bin/gossamer --key alice --datadir tmp/alice init
./bin/gossamer --key alice --datadir tmp/alice
```

```
./bin/gossamer --key bob --datadir tmp/bob --port 7002 init
./bin/gossamer --key bob --datadir tmp/bob --port 7002 
```

### LINKED ISSUE #675: network: gossip should not send message to peer they received message from
right now, gossip sends a message received to all their peers. however they should not re-send the message to the peer they received it from.

### PR DESCRIPTION
**Pull request by noot**
## Changes
- re-add leb128
- update gossip not to send to peer it received from
- add limit to block response message (# of block data it will respond with at a time) currently set somewhat arbitrarily to 8, I noticed if the message got too big it got corrupted.
- updated "imported" to "saved" unless AddBlock is called; we should have different terms for saving a seen block to the DB, versus adding it to the canonical chain. additionally, we should discuss if we even want to save a block to the DB unless it's been validated 

## Tests:
```
go test ./... -short
```

trying out 2 node sync, you should see block responses being imported.

```
make gossamer
./bin/gossamer --key alice
```

let alice run for a while, then:
```
./bin/gossamer --key bob --datadir .bob --port 7002  --authority=false 
```
bob will request the blocks he doesn't have from alice and then import them

### Issues:
closes #675 closes #484 
somewhat closes #672

### CODE REVIEW

File: dot/core/service.go [hunk 1]
```diff
@@ -444,12 +446,12 @@ func (s *Service) ProcessBlockAnnounceMessage(msg network.Message) error {
 		// send block request message to network service
 		log.Debug("send blockRequest message to network service")
 
+		// TODO: safe channel checking
```
Comment (ryanchristo) [inline dot/core/service.go]: #679

File: dot/core/service.go [hunk 2]
```diff
@@ -491,6 +493,10 @@ func (s *Service) ProcessBlockRequestMessage(msg network.Message) error {
 	// get sub-chain of block hashes
 	subchain := s.blockState.SubChain(startHash, endHash)
 
+	if len(subchain) > maxResponseSize {
+		subchain = subchain[:maxResponseSize]
+	}
```
Comment (ryanchristo) [inline dot/core/service.go]: should we log a warning that we are trimming the subchain due to max response size?

File: dot/core/service.go [hunk 3]
```diff
@@ -558,16 +564,33 @@ func (s *Service) ProcessBlockRequestMessage(msg network.Message) error {
...
+			existingHeader, err := s.blockState.GetHeader(bd.Hash)
+			if err != nil && existingHeader == nil {
+				err = s.blockState.SetHeader(header)
+				if err != nil {
+					return err
+				}
+
+				log.Info("[core] saved block header", "hash", header.Hash(), "number", header.Number)
+
+				// TODO: handle consensus digest, if first in epoch
```
Comment (ryanchristo) [inline dot/core/service.go]: #599

File: dot/core/service.go [hunk 4]
```diff
@@ -587,33 +610,34 @@ func (s *Service) ProcessBlockResponseMessage(msg network.Message) error {
 				Body:   body,
 			}
 
-			enc, err := block.Encode()
-			if err != nil {
-				return err
-			}
+			// TODO: why doesn't execute block work with block we built?
```
Comment (ryanchristo) [inline dot/core/service.go]: was this happening before? should we open an issue to address or are you planning to address here?

File: dot/core/service.go [hunk 5]
```diff
@@ -724,6 +748,7 @@ func (s *Service) ProcessTransactionMessage(msg network.Message) error {
 }
 
 // handle authority and randomness changes over transitions from one epoch to the next
+//nolint
```
Comment (ryanchristo) [inline dot/core/service.go]: what are we ignoring?

File: dot/network/service.go [hunk 6]
```diff
@@ -124,11 +124,7 @@ func (s *Service) Stop() error {
 		log.Error("Failed to close host", "err", err)
 	}
 
-	// close channel to core service
-	if s.msgSend != nil {
-		close(s.msgSend)
-	}
-
+	// TODO: close s.msgSend, need channel close handling
```
Comment (ryanchristo) [inline dot/network/service.go]: #679

File: dot/network/service.go [hunk 7]
```diff
@@ -195,11 +191,33 @@ func (s *Service) handleStream(stream libp2pnetwork.Stream) {
 	// create buffer stream for non-blocking read
 	r := bufio.NewReader(stream)
 
+	go s.read(r, remotePeer)
+	// the stream stays open until closed or reset
+}
+
+func (s *Service) read(r *bufio.Reader, remotePeer peer.ID) {
```
Comment (ryanchristo) [inline dot/network/service.go]: maybe `readStream` to be more specific?

File: dot/network/status.go [hunk 8]
```diff
@@ -121,8 +122,10 @@ func (status *status) validMessage(msg *StatusMessage) bool {
 		return false
 	}
 
+	log.Debug("[network]", "peer's genesis hash", msg.GenesisHash)
+
 	switch {
-	case msg.GenesisHash != status.hostMessage.GenesisHash:
+	case !bytes.Equal(msg.GenesisHash[:], status.hostMessage.GenesisHash[:]):
```
Comment (ryanchristo) [inline dot/network/status.go]: was this the solution to the genesis hash mismatch error?

File: dot/network/status.go [hunk 9]
```diff
@@ -121,8 +122,10 @@ func (status *status) validMessage(msg *StatusMessage) bool {
 		return false
 	}
 
+	log.Debug("[network]", "peer's genesis hash", msg.GenesisHash)
```
Comment (ryanchristo) [inline dot/network/status.go]: `log.Debug("[network] Validating peer status message", "GenesisHash", msg.GenesisHash)`

File: dot/core/service.go (hunk 2 above)
Comment (noot) [reply dot/core/service.go]: I don't think it needs a warning, it's not really something the sender of the block response would need to worry about

File: dot/core/service.go (hunk 4 above)
Comment (noot) [reply dot/core/service.go]: I don't think it was every tested :/ I'll open an issue to address it

Comment (noot) [reply dot/core/service.go]: #681

File: dot/core/service.go (hunk 5 above)
Comment (noot) [reply dot/core/service.go]: this function isn't used anywhere anymore, it was in `ProcessBlockResponseMessage` but it's been commented out since putting this isn't to digest isn't implemented yet so it just causes problems

File: dot/network/service.go (hunk 7 above)
Comment (noot) [reply dot/network/service.go]: will update

File: dot/network/status.go (hunk 8 above)
Comment (noot) [reply dot/network/status.go]: I don't think so, it seems to have improved but I did run into it once still, after running nodes for a long time then stopping/restarting

File: dot/core/service.go [hunk 10]
```diff
@@ -431,7 +433,7 @@ func (s *Service) ProcessBlockAnnounceMessage(msg network.Message) error {
 
 		blockRequest := &network.BlockRequestMessage{
 			ID:            randomID, // random
-			RequestedData: 2,        // block body
+			RequestedData: 3,        // block header + body
```
Comment (ryanchristo) [inline dot/core/service.go]: :+1:

File: dot/network/gossip.go [hunk 11]
```diff
@@ -50,6 +51,6 @@ func (g *gossip) handleMessage(msg Message) {
 		)
 
 		// broadcast message to connected peers
-		g.host.broadcast(msg)
+		g.host.broadcastExcluding(msg, from)
```
Comment (ryanchristo) [inline dot/network/gossip.go]: closes #675 :+1:

File: dot/network/host.go [hunk 12]
```diff
@@ -179,7 +179,9 @@ func (h *host) send(p peer.ID, msg Message) (err error) {
 		return err
 	}
 
-	// TODO: append leb128 variable-length encoding #484
+	lenBytes := uint64ToLEB128(uint64(len(encMsg)))
+	encMsg = append(lenBytes, encMsg...)
```
Comment (ryanchristo) [inline dot/network/host.go]: maybe break this up and use `lebEnc` to be clear what we are appending the message to:

```
lenBytes := uint64(len(encMsg))
lebEnc := uint64ToLEB128(lenBytes)
encMsg = append(lebEnc, encMsg...)
```

File: dot/network/service.go [hunk 13]
```diff
@@ -198,11 +194,33 @@ func (s *Service) handleStream(stream libp2pnetwork.Stream) {
 	// create buffer stream for non-blocking read
 	r := bufio.NewReader(stream)
 
+	go s.readStream(r, peer)
+	// the stream stays open until closed or reset
+}
+
+func (s *Service) readStream(r *bufio.Reader, peer peer.ID) {
 	for {
 		// TODO: re-add leb128 variable-length encoding #484
```
Comment (ryanchristo) [inline dot/network/service.go]: remove TODO, this is completed in this pull request

File: dot/network/host.go (hunk 12 above)
Comment (noot) [reply dot/network/host.go]: done

File: cmd/gossamer/configcmd.go [hunk 14]
```diff
@@ -44,6 +44,8 @@ import (
 	"github.com/urfave/cli"
 )
 
+var channelSize = 128
```
Comment (thomasmodeneis) [inline cmd/gossamer/configcmd.go]: this magic number here is a const ?

File: dot/core/service.go [hunk 15]
```diff
@@ -43,6 +43,8 @@ import (
 
 var _ services.Service = &Service{}
 
+var maxResponseSize = 8 // maximum number of block datas to reply with in a BlockResponse message.
```
Comment (thomasmodeneis) [inline dot/core/service.go]: is this configurable ?

File: go.mod [hunk 16]
```diff
@@ -11,27 +11,32 @@ require (
...
 	github.com/libp2p/go-libp2p v0.5.1
 	github.com/libp2p/go-libp2p-core v0.3.0
 	github.com/libp2p/go-libp2p-kad-dht v0.5.0
+	github.com/mattn/go-colorable v0.1.4 // indirect
 	github.com/mattn/go-isatty v0.0.11 // indirect
 	github.com/multiformats/go-multiaddr v0.2.0
 	github.com/naoina/go-stringutil v0.1.0 // indirect
 	github.com/naoina/toml v0.1.1
+	github.com/onsi/ginkgo v1.11.0 // indirect
+	github.com/onsi/gomega v1.8.1 // indirect
```
Comment (thomasmodeneis) [inline go.mod]: why gomega/ginkgo keeps coming back, are we using this anywhere ?

File: go.mod [hunk 17]
```diff
@@ -11,27 +11,32 @@ require (
 	github.com/disiqueira/gotree v1.0.0
 	github.com/docker/docker v1.13.1
 	github.com/ethereum/go-ethereum v1.9.6
-	github.com/filecoin-project/go-leb128 v0.0.0-20190212224330-8d79a5489543
+	github.com/go-interpreter/wagon v0.6.1-0.20200227184901-6803234760a6
+	github.com/golang/protobuf v1.3.2 // indirect
 	github.com/golang/snappy v0.0.1
-	github.com/golangci/golangci-lint v1.23.1 // indirect
```
Comment (thomasmodeneis) [inline go.mod]: why is golangci-lint removed ?

File: go.mod (hunk 16 above)
Comment (noot) [reply go.mod]: good question, I just did `go mod tidy` to clean stuff up, same with below, I can try removing it since we aren't using it explicity

File: cmd/gossamer/configcmd.go (hunk 14 above)
Comment (noot) [reply cmd/gossamer/configcmd.go]: yes, I was noticing that the node would stall on writing to a channel because it was full, so I added a buffer. it's arbitrary right now

File: dot/core/service.go (hunk 15 above)
Comment (noot) [reply dot/core/service.go]: not right now, I picked it based on what I saw to work and not work. we could change it in the future if needed
