### PR TITLE
Elizabeth/trie fix header

### LINKED ISSUE #113: Inconsistencies with spec
I am implementing [Trie](https://github.com/ChainSafe/gossamer/tree/development/trie) for C++ looking at [spec](https://github.com/w3f/polkadot-re-spec) and your trie implementation.

I've found some inconsistencies and I want to get some feedback on them.

Lets start with this one:
https://sourcegraph.com/github.com/ChainSafe/gossamer/-/blob/trie/node.go#L151

According to spec, depending on a node type, two **most significant** bits must be set according to the rule below.
image

In your current code, you set two **least significant bits**. Why?

```go
func (l *leaf) header() []byte {
	var header byte = 1
        ...

func (b *branch) header() []byte {
	var header byte
	if b.value == nil {
		header = 2
	} else {
		header = 3
	}
         ...
```

Is this an implementation mistake?

### PR DESCRIPTION
**Pull request by noot**
## Changes
- changed node header encoding to match the spec. previously, the node prefix was at the least two significant bits when it should have been at the two most significant bits.
- updated tests to reflect changes

## Tests:
```
go test ./trie/...
```

### Fixes:
closes #113

### CODE REVIEW

File: trie/node_test.go [hunk 1]
```diff
@@ -97,15 +97,15 @@ func TestLeafHeader(t *testing.T) {
...
-		{&leaf{nil, nil, true}, []byte{1}},
-		{&leaf{[]byte{0x00}, nil, true}, []byte{5}},
-		{&leaf{[]byte{0x00, 0x00, 0xf, 0x3}, nil, true}, []byte{17}},
-		{&leaf{byteArray(62), nil, true}, []byte{0xf9}},
-		{&leaf{byteArray(63), nil, true}, []byte{253, 0}},
-		{&leaf{byteArray(64), []byte{0x01}, true}, []byte{253, 1}},
-
-		{&leaf{byteArray(318), []byte{0x01}, true}, []byte{253, 255, 0}},
-		{&leaf{byteArray(573), []byte{0x01}, true}, []byte{253, 255, 255, 0}},
+		{&leaf{nil, nil}, []byte{0x40}},
```
Comment (golangcibot) [inline trie/node_test.go]: too few values in struct literal (from `typecheck`)
