### PR TITLE
p2p: migrate mdns logic and update tests

### LINKED ISSUE #423: Investigate and resolve mdns dial errors
## Expected Behavior

We should not have to disable mdns in our p2p tests.

## Current Behavior

Without disabling mdns in our p2p tests (ie, adding `NoMdns: true` to the configuration for each node that we start), we are receiving `failed dial` and `connection refused` in our debug logs.

## Possible Solution

This might be an issue with the generated addresses we are dialing, how we are configuring libp2p within the service, or an issue in the go-libp2p package that we need to investigate.

## Steps to Reproduce

Remove the `NoMdns: true` configuration property in any of the `p2p_test.go` tests and observe the `failed dial` and `connection refused` in the debug logs.

### PR DESCRIPTION
**Pull request by ryanchristo**
## Changes

This pull request adds `TestDiscovery` to `p2p_test.go` and updates each test to use `connect` as a standard if we are not testing bootstrap or discovery.

This pull request also resolves #423. The issue with failed dials was attempting to connect manually or via bootstrap and using mdns discovery. With mdns enabled, nodes will connect automatically.

## Tests:
```
go test ./p2p -v
```

### Issues:
closes #423

### CODE REVIEW

File: p2p/discovery.go [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+const mdnsPeriod = time.Minute
+
+// See https://godoc.org/github.com/libp2p/go-libp2p/p2p/discovery#Notifee
+type Notifee struct {
+	ctx  context.Context
+	host libp2phost.Host
+}
+
+// discovery submodule
+type disc struct {
```
Comment (ansermino) [inline p2p/discovery.go]: pls name `discovery`

File: p2p/discovery.go [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+		// close mDNS discovery service
+		err := d.mdns.Close()
+		if err != nil {
+			return err
+		}
+
+	}
+
+	return nil
+}
```
Comment (ansermino) [inline p2p/discovery.go]: This seems unnecessary. Either use `d.mdns.Close()` instead or rename this `close` and add the same logic for any future components.
