### PR TITLE
fix(dot/subscription): check websocket message from untrusted data

### LINKED ISSUE #2413: Assumption of JSON Fields from Untrusted Input (GSR-15)
Websocket RPC messages are unmarshalled from JSON into a map, which should have certain fields.

If the expected fields are not present then `nil` will be returned. This may lead to unexpected `nil` pointer exceptions being raised when these pointers are used.

The issue may be resolved by first ensuring each of the required fields are present in the map before accessing them.

```go
var reqid float64
if val, ok := msg["id"]; ok {
	if reqid, ok := val.(float64); !ok {
		// handle error
		return
	}
} else {
	// handle error
	return
}
var method string
if val, ok := msg["method"]; ok {
	if method, ok := val.(string); !ok {
		// handle error
		return
	}
} else {
	// handle error
	return
}
```

### PR DESCRIPTION
**Pull request by EclesioMeloJunior**
## Changes

- Created a struct with the required fields: `ID float64`, `Method string` and `Params any` to ensure the types and avoid conversions over `interface{}`
- Created a condition to don't allow an empty `Method` field

## Tests

```sh
go test github.com/ChainSafe/gossamer/dot/rpc/subscription
```

## Issues

- Closes #2413

## Primary Reviewer

@jimjbrettj

### CODE REVIEW

**Review by qdm12 — APPROVED** [review]
Nice :+1:

File: dot/rpc/subscription/websocket_test.go [hunk 1]
```diff
@@ -21,6 +21,53 @@ import (
 	"github.com/stretchr/testify/require"
 )
 
+func TestWSConn_CheckWebsocketInvalidData(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply dot/rpc/subscription/websocket_test.go:24]: Yes, created a issue to address this -> https://github.com/ChainSafe/gossamer/issues/2555

File: dot/rpc/subscription/websocket.go [hunk 2]
```diff
@@ -52,28 +52,27 @@ type WSConn struct {
...
+		return bytes, msg, errCannotUnmarshalMessage
 	}
 
-	return mbytes, msg, nil
+	return bytes, msg, nil
 }
 
-//HandleComm handles messages received on websocket connections
-func (c *WSConn) HandleComm() {
+//HandleConn handles messages received on websocket connections
```
Comment (qdm12) [inline dot/rpc/subscription/websocket.go:74]: supernit

```suggestion
// HandleConn handles messages received on websocket connections
```

File: dot/rpc/subscription/websocket.go [hunk 3]
```diff
@@ -52,28 +52,27 @@ type WSConn struct {
 }
 
 // readWebsocketMessage will read and parse the message data to a string->interface{} data
-func (c *WSConn) readWebsocketMessage() ([]byte, *websocketMessage, error) {
-	_, mbytes, err := c.Wsconn.ReadMessage()
+func (c *WSConn) readWebsocketMessage() (bytes []byte, msg websocketMessage, err error) {
```
Comment (qdm12) [inline dot/rpc/subscription/websocket.go:55]: should we keep the raw bytes inside the `websocketMessage` struct? 🤔

**Review by qdm12 — APPROVED** [review]

File: dot/rpc/subscription/websocket.go (hunk 3 above)
Comment (EclesioMeloJunior) [reply dot/rpc/subscription/websocket.go:55]: I don't think so, the raw bytes don't belong to the `websocketMessage` struct as it is used to create one IMO

File: dot/rpc/subscription/websocket.go [hunk 4]
```diff
@@ -22,6 +22,12 @@ import (
 	"github.com/gorilla/websocket"
 )
 
+type websocketMessage struct {
+	ID     float64 `json:"id"`
+	Method string  `json:"method"`
+	Params any
```
Comment (qdm12) [inline dot/rpc/subscription/websocket.go:28]: 🤯

File: dot/rpc/subscription/websocket.go [hunk 5]
```diff
@@ -46,87 +52,82 @@ type WSConn struct {
...
-	logger.Tracef("websocket message received: %s", string(mbytes))
-
-	// determine if request is for subscribe method type
-	var msg map[string]interface{}
-	err = json.Unmarshal(mbytes, &msg)
-
-	if err != nil {
-		logger.Debugf("websocket failed to unmarshal request message: %s", err)
-		return nil, nil, errCannotUnmarshalMessage
+		return bytes, errCannotReadFromWebsocket
```
Comment (qdm12) [inline dot/rpc/subscription/websocket.go:59]: nit just to be clear / explicit to the maxxx

```suggestion
		return nil, errCannotReadFromWebsocket
```

File: dot/rpc/subscription/websocket.go [hunk 6]
```diff
@@ -46,87 +52,82 @@ type WSConn struct {
...
+			c.safeSendError(0, big.NewInt(InvalidRequestCode), InvalidRequestMessage)
+			continue
 		}
 
-		if errors.Is(err, errCannotUnmarshalMessage) {
-			c.safeSendError(0, big.NewInt(InvalidRequestCode), InvalidRequestMessage)
+		msg := new(websocketMessage)
+		err = json.Unmarshal(mbytes, &msg)
+		if err != nil {
+			logger.Debugf("websocket failed to unmarshal request message: %s", err)
```
Comment (qdm12) [inline dot/rpc/subscription/websocket.go:80]: nit

```suggestion
			logger.Debugf("failed to unmarshal websocket request message: %s", err)
```

**Review by qdm12 — APPROVED** [review]

File: dot/rpc/subscription/websocket.go [hunk 7]
```diff
@@ -46,87 +51,81 @@ type WSConn struct {
...
 				continue
 			}
 		}
 
 		err = listener.Stop()
 		if err != nil {
-			logger.Warnf("failed to stop listener goroutine (method=%s): %s", method, err)
-			c.safeSend(newBooleanResponseJSON(false, reqid))
+			logger.Warnf("failed to stop listener goroutine (method=%s): %s", msg.Method, err)
+			c.safeSend(newBooleanResponseJSON(false, msg.ID))
```
Comment (qdm12) [inline dot/rpc/subscription/websocket.go:125]: This is not covered by tests, do you think you can add a test case for this one?

File: dot/rpc/subscription/websocket.go [hunk 8]
```diff
@@ -46,87 +51,81 @@ type WSConn struct {
...
 			if setupListener == nil {
 				c.executeRPCCall(mbytes)
 				continue
 			}
 
-			listener, err := setupListener(reqid, params)
+			listener, err := setupListener(msg.ID, msg.Params)
 			if err != nil {
-				logger.Warnf("failed to create listener (method=%s): %s", method, err)
+				logger.Warnf("failed to create listener (method=%s): %s", msg.Method, err)
```
Comment (qdm12) [inline dot/rpc/subscription/websocket.go:99]: This is not covered by tests, do you think you can add a test case for this one?

File: dot/rpc/subscription/websocket.go [hunk 9]
```diff
@@ -46,87 +51,81 @@ type WSConn struct {
...
-func (c *WSConn) HandleComm() {
+// HandleConn handles messages received on websocket connections
+func (c *WSConn) HandleConn() {
 	for {
-		mbytes, msg, err := c.readWebsocketMessage()
+		mbytes, err := c.readWebsocketMessage()
 		if errors.Is(err, errCannotReadFromWebsocket) {
 			return
+		} else if err != nil {
+			c.safeSendError(0, big.NewInt(InvalidRequestCode), InvalidRequestMessage)
```
Comment (qdm12) [inline dot/rpc/subscription/websocket.go:72]: This is not covered by tests, do you think you can add a test case for this one?

File: dot/rpc/subscription/websocket.go (hunk 8 above)
Comment (EclesioMeloJunior) [reply dot/rpc/subscription/websocket.go:99]: This is being covered by the `TestWSConn_HandleConn` test, we try to connect to the `StorageChangeListener` without the `Storage State` then it will not set up the listener and return an error through the WebSocket connection that we assert.

File: dot/rpc/subscription/websocket.go (hunk 7 above)
Comment (EclesioMeloJunior) [reply dot/rpc/subscription/websocket.go:125]: We have tests that cover `*_unsubcribe` actions, I'm not sure if it is needed to implement more tests in this PR.

File: dot/rpc/subscription/websocket.go (hunk 9 above)
Comment (EclesioMeloJunior) [reply dot/rpc/subscription/websocket.go:72]: Actually, this branch condition is not needed as the `readWebsocketMessage` function will never return other error than `errCannotReadFromWebsocket`

File: dot/rpc/subscription/websocket.go (hunk 7 above)
Comment (qdm12) [reply dot/rpc/subscription/websocket.go:123]: Yes please add them / refactor existing tests 😉
We should especially pay attention to test cover new code added.

File: dot/rpc/subscription/websocket.go [hunk 10]
```diff
@@ -22,12 +22,17 @@ import (
 	"github.com/gorilla/websocket"
 )
 
+type websocketMessage struct {
+	ID     float64 `json:"id"`
+	Method string  `json:"method"`
+	Params any
```
Comment (kishansagathiya) [inline dot/rpc/subscription/websocket.go:28]: why not `json:"params"` here?

File: dot/rpc/subscription/websocket.go [hunk 11]
```diff
@@ -46,87 +51,79 @@ type WSConn struct {
...
 			continue
 		}
 
-		params := msg["params"]
-		reqid := msg["id"].(float64)
-		method := msg["method"].(string)
+		if msg.Method == "" {
+			c.safeSendError(0, big.NewInt(InvalidRequestCode), InvalidRequestMessage)
+			continue
+		}
```
Comment (kishansagathiya) [inline dot/rpc/subscription/websocket.go:83]: This is still reading websocket message. The selected piece of code could be moved inside `readWebsocketMessage` and then `readWebsocketMessage` could return `websocketMessage, err`

File: dot/rpc/subscription/websocket_test.go [hunk 12]
```diff
@@ -21,12 +21,59 @@ import (
 	"github.com/stretchr/testify/require"
 )
 
-func TestWSConn_HandleComm(t *testing.T) {
+func TestWSConn_CheckWebsocketInvalidData(t *testing.T) {
```
Comment (kishansagathiya) [inline dot/rpc/subscription/websocket_test.go:24]: I am not super sure, but I think if you move this test after `TestWSConn_HandleConn`, git would understand the differ better.

**Review by kishansagathiya — CHANGES_REQUESTED** [review]
Apart from a few small comments, looks pretty good!!

File: dot/rpc/subscription/websocket.go [hunk 13]
```diff
@@ -46,87 +51,84 @@ type WSConn struct {
...
 
-		params := msg["params"]
-		reqid := msg["id"].(float64)
-		method := msg["method"].(string)
+		logger.Tracef("websocket message received: %s", string(rawBytes))
+
+		if wsMessage.Method == "" {
+			c.safeSendError(0, big.NewInt(InvalidRequestCode), InvalidRequestMessage)
+			continue
+		}
```
Comment (kishansagathiya) [inline dot/rpc/subscription/websocket.go:88]: Could move this inside `readWebsocketMessage`? 

No need to return rawBytes as well
```
func (c *WSConn) readWebsocketMessage() ( wsMessage *websocketMessage, err error)
```

Comment (EclesioMeloJunior) [reply dot/rpc/subscription/websocket.go:88]: @kishansagathiya actually, we need to return the `rawBytes` because if we don't find a listener we execute an RPC call with `rawBytes`, on line 96

Comment (EclesioMeloJunior) [reply dot/rpc/subscription/websocket.go]: @kishansagathiya I've moved the condition to `readWebsocketMessage()`

Comment (kishansagathiya) [reply dot/rpc/subscription/websocket.go]: > we need to return the rawBytes because if we don't find a listener we execute an RPC call with rawBytes, on line 96

Ah, did not notice that, my bad!

**Review by kishansagathiya — APPROVED** [review]
:tada:

File: dot/rpc/subscription/websocket.go (hunk 7 above)
Comment (EclesioMeloJunior) [reply dot/rpc/subscription/websocket.go]: @qdm12 the tests assert the full WebSocket response and the changes I introduced are being testes by `TestWSConn_CheckWebsocketInvalidData`, so I will keep the `TestWSConn_HandleConn` as it is since I've opened an issue to improve/refactor it -> https://github.com/ChainSafe/gossamer/issues/2555
