### PR TITLE
fix(peerset): check for incoming slot error

### LINKED ISSUE #2914: [peerset]: cannot accept incomming peer: not enough incoming slots
## Describe the bug

- Investigation purpose issue
- ERROR cannot accept incomming peer 12D3KooWL3WgKWRhCMaxSCbyGVzYNa7DxF1SuBk9cRvffCBidR5y: not enough incoming slots peerset.go:L644 pkg=peerset

### PR DESCRIPTION
**Pull request by edwardmack**
## Changes

- Added check for error `ErrIncomingSlotsUnavailable` and logging condition to Info logs, since this happens when the peer set has filled it's incoming slot allowance.
- Fix spelling of `incomming` to `incoming` in log message.

## Tests

```sh
go test github.com/ChainSafe/gossamer/dot/peerset
```

## Issues
closes #2914 

## Primary Reviewer

@timwu20

### CODE REVIEW

File: dot/peerset/peerset.go [hunk 1]
```diff
@@ -641,8 +641,13 @@ func (ps *PeerSet) incoming(setID int, peers ...peer.ID) error {
 		} else {
 			err := state.tryAcceptIncoming(setID, pid)
 			if err != nil {
-				logger.Errorf("cannot accept incomming peer %s: %s", pid, err)
-				message.Status = Reject
+				if err == ErrIncomingSlotsUnavailable {
```
Comment (qdm12) [inline dot/peerset/peerset.go:644]:
```suggestion
				if errors.Is(err, ErrIncomingSlotsUnavailable) {
```

File: dot/peerset/peerset.go [hunk 2]
```diff
@@ -641,8 +641,13 @@ func (ps *PeerSet) incoming(setID int, peers ...peer.ID) error {
...
+					logger.Infof("cannot accept incoming peer %s: %s", pid, err)
+					message.Status = Reject
+				} else {
+					logger.Errorf("cannot accept incoming peer %s: %s", pid, err)
+					message.Status = Reject
```
Comment (qdm12) [inline dot/peerset/peerset.go:649]: take the `message.Status = Reject` outside the `if`/`else` (before or after it)

**Comment by jimjbrettj** [comment]
Even though it is no longer an error-level log, these logs still happen often and pollute the logs. Maybe this is okay, but maybe its worth discussing if there is another way to handle this that doesn't spam as many logs?

**Comment by qdm12** [comment]
> Even though it is no longer an error-level log, these logs still happen often and pollute the logs. Maybe this is okay, but maybe its worth discussing if there is another way to handle this that doesn't spam as many logs?

Yeah good point, should these be at the debug level? :thinking:

**Comment by edwardmack** [comment]
> > Even though it is no longer an error-level log, these logs still happen often and pollute the logs. Maybe this is okay, but maybe its worth discussing if there is another way to handle this that doesn't spam as many logs?
> 
> Yeah good point, should these be at the debug level? thinking

Yes, I agree, I've updated to report this message as log level Debug.

**Review by qdm12 — APPROVED** [review]

**Review by timwu20 — APPROVED** [review]
