### PR TITLE
Fixed Linter and Linted Project Files

### LINKED ISSUE #148: go fmt in CI not working
## Expected Behavior

all code should be go fmt'd. 

## Current Behavior 
it is not all formatted (run go fmt on development to check). this means the CI is not correctly checking that the code is formatted

## Possible Solution

fix the CI config

## Steps to Reproduce (for bugs)

1. clone repo
2. git checkout development
3. go fmt
4. see files get fmt'd

### PR DESCRIPTION
**Pull request by dutterbutter**
## Changes
- Enabled `gofmt` and `goimports`
- Fixed make lint command
- 

## Tests:
```
make lint
```

### Fixes:

Closes #148

### CODE REVIEW

File: trie/node.go [hunk 1]
```diff
@@ -127,8 +127,8 @@ func (b *branch) Encode() ([]byte, error) {
 
 	for _, child := range b.children {
 		if child != nil {
-			encChild, err := Encode(child)
-			if err != nil {
+			encChild, e := Encode(child)
```
Comment (noot) [inline trie/node.go]: idk why this is changed to e? not a big deal tho

File: config/config.go [hunk 2]
```diff
@@ -22,37 +22,32 @@ import (
...
+		RandSeed:       defaultP2PRandSeed,
 	},
 	DbConfig: polkadb.DbConfig{
 		Datadir: "chaindata",
 	},
 }
 
-
-
 //[ServiceConfig]
```
Comment (noot) [inline config/config.go]: delete this pls

File: trie/node.go (hunk 1 above)
Comment (dutterbutter) [reply trie/node.go]: The linter complained that `err` was overshadowed by the previous declaration
