### PR TITLE
dot/core, dot/rpc, dot/state, lib/grandpa: store finalized hash w/ round number, add chain_getFinalizedHeadByRound 

### LINKED ISSUE #960: dot/rpc: retrieve finalized block in specific round
## Expected Behavior

- integration tests require that all nodes finalized the same block in a specific round
- however chain_getFinalizedHead returns the most recent finalized head
- if the nodes are slightly out of sync in terms of grandpa round then they will return different blocks, this causes the tests to fail when they are actually ok.

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [x] I am planning to submit a pull request to fix this issue myself

### PR DESCRIPTION
**Pull request by noot**
## Changes

- update BlockState `GetFinalizedHash` and `SetFinalizedHash` to also accept a round number to store the hash, use 0 as latest for now since round 0 isn't used in grandpa
- add chain_getFinalizedHeadByRound rpc call to fetch hash finalized at a given round

## Tests

```
go test ./... -short
```

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [x] I have reviewed my own pull request before requesting a review
- [ ] All integration tests and required coverage checks are passing

## Issues

- closes #960

### CODE REVIEW

File: dot/core/finality.go [hunk 1]
```diff
@@ -56,24 +56,27 @@ func (s *Service) sendVoteMessages() {
...
-		// update state.finalizedHead
+		log.Info("[core] finalized block!!!", "msg", v)
+		msg, err := v.ToConsensusMessage()
+		if err != nil {
+			log.Error("[core] failed to convert FinalizationMessage to ConsensusMessage", "msg", msg)
+			continue
+		}
+
+		// update finalized hash for this round in database
+		// TODO: this also happens in grandpa.finalize(); decide which is preferred
```
Comment (edwardmack) [inline dot/core/finality.go:67]: my thought is it belongs in grandpa.finalize, no strong opinion just thinking it makes most sense there.

Comment (noot) [reply dot/core/finality.go:67]: I'll leave it as is for now, I'm leaning towards just doing it in core since that's where the block state updating should be done
