### PR TITLE
p2p: IPFS Bootstrap Purge and Cleanup

### LINKED ISSUE #221: Bootstrapping p2p nodes to each other
- Currently nodes bootstrap to an IPFS node
- Boot 2 p2p nodes up
- Have 1 p2p node bootstrap to the other
- Should add peer to DHT

### LINKED ISSUE #225: Parsing of Peer Addrs Unsafe
## Expected Behavior
Error should get propagated, de-referencing of `p` should not take place if there is an error.

## Current Behavior

If `peer.AddrInfoFromP2pAddr(maddr)` fails `p` is still cast, panic ensues
```
	p, err := peer.AddrInfoFromP2pAddr(maddr)
	return *p, err
```

## Possible Solution
```
	p, err := peer.AddrInfoFromP2pAddr(maddr)
	if err != nil {
		return peer.AddrInfo{}, err
	}
	return *p, err
```

### PR DESCRIPTION
**Pull request by ansermino**
These changes aim to deprecate old code and begin a transition to a more sensible organization for this package. 

## Changes
- Removes IPFS bootstrap test
- Purges any usage of IPFS as bootnode
- Reorganizes netsim command (in need of TLC, there is task on the board for this)
- Introduces `Service.FullAddrs()` to provide complete addresses

## Tests:
```
go test -v ./p2p/
```

### Fixes: Closes #221 Closes #225

### CODE REVIEW

File: cmd/netsim/main.go [hunk 1]
```diff
@@ -50,6 +50,8 @@ func getRandomInt(m int) int {
 	return r
 }
 
+
```
Comment (golangcibot) [inline cmd/netsim/main.go]: File is not `goimports`-ed (from `goimports`)

File: cmd/netsim/sim.go [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+		}
+		sim.Nodes[i] = new(p2p.Service)
+		sim.Nodes[i], err = p2p.NewService(conf)
+		if err != nil {
+			return nil, err
+		}
+	}
+
+	return sim, nil
+}
```
Comment (golangcibot) [inline cmd/netsim/sim.go]: File is not `goimports`-ed (from `goimports`)
```suggestion
}
```

File: p2p/address_utils.go [hunk 3]
```diff
@@ -0,0 +1,28 @@
+package p2p
+
+import (
+	"github.com/libp2p/go-libp2p-core/peer"
+	ma "github.com/multiformats/go-multiaddr"
+
```
Comment (golangcibot) [inline p2p/address_utils.go]: File is not `goimports`-ed (from `goimports`)
```suggestion

```

File: p2p/p2p.go [hunk 4]
```diff
@@ -230,6 +230,17 @@ func (s *Service) Host() host.Host {
 	return s.host
 }
 
+// FullAddrs returns all the hosts addresses with their ID append as multiaddrs
+func (s *Service) FullAddrs() (maddrs []ma.Multiaddr) {
+	addrs := s.host.Addrs()
+	for _, a := range addrs {
+		maddr, err := ma.NewMultiaddr(fmt.Sprintf("%s/p2p/%s", a, s.host.ID().Pretty()))
+		if err != nil { continue }
```
Comment (golangcibot) [inline p2p/p2p.go]: File is not `goimports`-ed (from `goimports`)
```suggestion
		if err != nil {
			continue
		}
```

File: p2p/p2p_test.go [hunk 5]
```diff
@@ -26,6 +26,21 @@ import (
 	ma "github.com/multiformats/go-multiaddr"
 )
 
+func startNewService(t *testing.T, cfg *Config) *Service{
```
Comment (golangcibot) [inline p2p/p2p_test.go]: File is not `goimports`-ed (from `goimports`)
```suggestion
func startNewService(t *testing.T, cfg *Config) *Service {
```

File: cmd/netsim/sim.go (hunk 2 above)
Comment (golangcibot) [inline cmd/netsim/sim.go]: File is not `goimports`-ed (from `goimports`)
```suggestion
}
```

File: p2p/address_utils.go (hunk 3 above)
Comment (golangcibot) [inline p2p/address_utils.go]: File is not `goimports`-ed (from `goimports`)
```suggestion

```

File: p2p/p2p.go (hunk 4 above)
Comment (golangcibot) [inline p2p/p2p.go]: File is not `goimports`-ed (from `goimports`)
```suggestion
		if err != nil {
			continue
		}
```

File: p2p/p2p_test.go (hunk 5 above)
Comment (golangcibot) [inline p2p/p2p_test.go]: File is not `goimports`-ed (from `goimports`)
```suggestion
func startNewService(t *testing.T, cfg *Config) *Service {
```

File: cmd/netsim/main.go [hunk 6]
```diff
@@ -61,17 +61,18 @@ func main() {
...
 		log.Crit("NewSimulator", "error", err)
 	}
 
-	defer func() {
-		err = sim.IpfsNode.Close()
-		if err != nil {
-			log.Warn("main", "warn", err.Error())
-		}
-	}()
+	// TODO: Since we removed IPFS this needs to handle error channel from sim.Bootnode.Stop()
```
Comment (noot) [inline cmd/netsim/main.go]: do you wanna add this? or do it another time?

Comment (ansermino) [reply cmd/netsim/main.go]: The whole simulator needs love, so I think its fine to leave for now

Comment (noot) [reply cmd/netsim/main.go]: sure

**Comment by noot** [comment]
does this also close #225 ?
