### PR TITLE
Parse unstructured array in JSON struct for RPC request.

### LINKED ISSUE #1216: Unmarshaling arrays items to struct for RPC
## Expected Behavior

1. API's like `QueryStorage` uses `StateStorageQueryRangeRequest` as request params but it should parse unstructured JSON to RPC request struct. The issue is with the [Gorilla RPC library](https://github.com/gorilla/rpc/issues/84).
2. `commmon.Hash` should have custom marshaling and unmarshalling. 

## Current Behavior

- For 1: It fails to parse unstructured JSON RPC request params struct and an unmarshalling error is returned.
- For 2: Any RPC returning `commmon.Hash` would convert the byte to string and return the underlying bytes instead of expected hash value. 
Example: It should format hash like this `0xe99c87d6efab57a98706c10fa4bc4d39feaf51ca62ac3bae7a67bf17c8c305ec ` but it returns the bytes directly(`e99c87d6efab57a98706c10fa4bc4d39feaf51ca62ac3bae7a67bf17c8c305ec` in bytes).

## Possible Solution

- Fix the `CodecRequest` implementation for JSON RPC v2 in the RPC gorilla library.
- Add custom marshaling and unmarshalling for `commmon.Hash`.

## Steps to Reproduce

1. Make RPC call to `QueryStorage`.
```
curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "state_queryStorage", "params":[["0xf2794c22e353e9a839f12faab03a911bf68967d635641a7087e53f2bff1ecad3c6756fee45ec79ead60347fffb770bcdf0ec74da701ab3d6495986fe1ecc3027"], "0xa32c60dee8647b07435ae7583eb35cee606209a595718562dd4a486a07b6de15", null]}' http://localhost:9933
```
2. Make RPC call to any RPC returning `common.Hash`

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [x] I am planning to submit a pull request to fix this issue myself

### PR DESCRIPTION
**Pull request by arijitAD**
## Changes

- Parse unstructured array in JSON struct for RPC request.
- Add custom marshaling and unmarshalling for `commmon.Hash`

## Tests

```
TestRPCStructParamUnmarshal
make it-rpc
```

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [x] I have reviewed my own pull request before requesting a review
- [x] All integration tests and required coverage checks are passing

## Issues

- closes #1216

### CODE REVIEW

File: lib/common/hash.go [hunk 1]
```diff
@@ -87,6 +88,22 @@ func BytesToHash(b []byte) Hash {
...
+	if *h, err = HexToHash(trimmedData); err != nil {
+		return err
+	}
+	return nil
+}
+
+// MarshalJSON converts hash to hex data
+func (h *Hash) MarshalJSON() ([]byte, error) {
+	return json.Marshal(h.String())
+}
```
Comment (noot) [inline lib/common/hash.go:105]: could you add a test for this?

File: packages/rpc/json2/server.go [hunk 2]
```diff
@@ -0,0 +1,259 @@
...
+//
+// The gossamer library is distributed in the hope that it will be useful,
+// but WITHOUT ANY WARRANTY; without even the implied warranty of
+// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
+// GNU Lesser General Public License for more details.
+//
+// You should have received a copy of the GNU Lesser General Public License
+// along with the gossamer library. If not, see <http://www.gnu.org/licenses/>.
+
+package json2
```
Comment (noot) [inline packages/rpc/json2/server.go:17]: what is the file used for?

**Comment by RyRy79261** [comment]
Encountered an error with the RPC test

```HOSTNAME=0.0.0.0 MODE=rpc go test ./tests/rpc/... -timeout=5m -v
Going to start RPC suite test
=== RUN   TestSystemRPC
    rpc_01-system_test.go:110: starting gossamer...
t=2020-12-04T15:11:37+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestSystemRPC/charlie --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
t=2020-12-04T15:11:37+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestSystemRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
t=2020-12-04T15:11:37+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestSystemRPC/bob --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
t=2020-12-04T15:11:38+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
t=2020-12-04T15:11:38+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestSystemRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
t=2020-12-04T15:11:38+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=1
t=2020-12-04T15:11:38+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7001 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestSystemRPC/bob --rpchost 0.0.0.0 --rpcport 8541 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key bob"
t=2020-12-04T15:11:39+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=2
t=2020-12-04T15:11:39+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7002 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestSystemRPC/charlie --rpchost 0.0.0.0 --rpcport 8542 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key charlie"
t=2020-12-04T15:11:40+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=169629
t=2020-12-04T15:11:40+0200 lvl=info msg="node started" pkg=test/utils key=bob cmd.Process.Pid=169639
t=2020-12-04T15:11:41+0200 lvl=info msg="node started" pkg=test/utils key=charlie cmd.Process.Pid=169653
=== RUN   TestSystemRPC/test_system_name
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestSystemRPC/test_system_version
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestSystemRPC/test_system_chain
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestSystemRPC/test_system_properties
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestSystemRPC/test_system_health
    rpc_01-system_test.go:124: Will assert SystemHealthResponse target &{{2 false true}}
=== RUN   TestSystemRPC/test_system_peers
    request_utils.go:97: 
                Error Trace:    request_utils.go:97
                                                        rpc_00_test.go:62
                                                        rpc_01-system_test.go:120
                Error:          Expected nil, but got: &errors.errorString{s:"could not byteify non 0x prefixed string"}
                Test:           TestSystemRPC/test_system_peers
                Messages:       {"jsonrpc":"2.0","result":{"peers":[{"PeerID":"12D3KooWAQGJtCfDoyPHjhpGDCoUmiPFiq9UmCKpuMQ773CK8Nzp","Roles":4,"ProtocolVersion":0,"BestHash":[143,166,222,68,206,241,81,78,194,160,94,35,152,27,210,110,134,151,132,66,170,167,23,250,213,185,30,8,14,129,103,6],"BestNumber":0},{"PeerID":"12D3KooWEn548sgWU775USfnD3rsUAKBMcAjMauMRgqcc61GEcWq","Roles":4,"ProtocolVersion":0,"BestHash":[143,166,222,68,206,241,81,78,194,160,94,35,152,27,210,110,134,151,132,66,170,167,23,250,213,185,30,8,14,129,103,6],"BestNumber":0}]},"id":1}
=== RUN   TestSystemRPC/test_system_network_state
    rpc_01-system_test.go:131: Will assert SystemNetworkStateResponse target &{{12D3KooWDmqA5WP22F6hGxaCFLq3d473RshHFdsKqtJbGuP4P6Za [/ip4/192.168.0.148/tcp/7000/p2p/12D3KooWDmqA5WP22F6hGxaCFLq3d473RshHFdsKqtJbGuP4P6Za /ip4/127.0.0.1/tcp/7000/p2p/12D3KooWDmqA5WP22F6hGxaCFLq3d473RshHFdsKqtJbGuP4P6Za]}}
=== RUN   TestSystemRPC/test_system_addReservedPeer
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestSystemRPC/test_system_removeReservedPeer
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestSystemRPC/test_system_nodeRoles
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestSystemRPC/test_system_accountNextIndex
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== CONT  TestSystemRPC
    rpc_01-system_test.go:158: going to tear down gossamer...
--- FAIL: TestSystemRPC (7.61s)
    --- SKIP: TestSystemRPC/test_system_name (0.00s)
    --- SKIP: TestSystemRPC/test_system_version (0.00s)
    --- SKIP: TestSystemRPC/test_system_chain (0.00s)
    --- SKIP: TestSystemRPC/test_system_properties (0.00s)
    --- PASS: TestSystemRPC/test_system_health (0.00s)
    --- FAIL: TestSystemRPC/test_system_peers (0.00s)
    --- PASS: TestSystemRPC/test_system_network_state (0.00s)
    --- SKIP: TestSystemRPC/test_system_addReservedPeer (0.00s)
    --- SKIP: TestSystemRPC/test_system_removeReservedPeer (0.00s)
    --- SKIP: TestSystemRPC/test_system_nodeRoles (0.00s)
    --- SKIP: TestSystemRPC/test_system_accountNextIndex (0.00s)
=== RUN   TestAuthorRPC
    rpc_02-author_test.go:73: starting gossamer...
t=2020-12-04T15:11:45+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestAuthorRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
t=2020-12-04T15:11:45+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
t=2020-12-04T15:11:45+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestAuthorRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
t=2020-12-04T15:11:46+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=169755
=== RUN   TestAuthorRPC/test_author_submitExtrinsic
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestAuthorRPC/test_author_pendingExtrinsics
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestAuthorRPC/test_author_removeExtrinsic
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestAuthorRPC/test_author_insertKey
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestAuthorRPC/test_author_rotateKeys
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestAuthorRPC/test_author_hasSessionKeys
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestAuthorRPC/test_author_hasKey
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== CONT  TestAuthorRPC
    rpc_02-author_test.go:85: going to tear down gossamer...
--- PASS: TestAuthorRPC (3.70s)
    --- SKIP: TestAuthorRPC/test_author_submitExtrinsic (0.00s)
    --- SKIP: TestAuthorRPC/test_author_pendingExtrinsics (0.00s)
    --- SKIP: TestAuthorRPC/test_author_removeExtrinsic (0.00s)
    --- SKIP: TestAuthorRPC/test_author_insertKey (0.00s)
    --- SKIP: TestAuthorRPC/test_author_rotateKeys (0.00s)
    --- SKIP: TestAuthorRPC/test_author_hasSessionKeys (0.00s)
    --- SKIP: TestAuthorRPC/test_author_hasKey (0.00s)
=== RUN   TestChainRPC
    rpc_03-chain_test.go:77: starting gossamer...
t=2020-12-04T15:11:48+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/tests/utils/config_babe_max_threshold.toml --basepath /tmp/TestChainRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
t=2020-12-04T15:11:49+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
t=2020-12-04T15:11:49+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/tests/utils/config_babe_max_threshold.toml --basepath /tmp/TestChainRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
t=2020-12-04T15:11:50+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=169820
=== RUN   TestChainRPC/test_chain_getHeader
    rpc_03-chain_test.go:97: Will assert ChainBlockHeaderResponse value &{0x1981f308be537f247e73551bd9cabda88a44aad3d176cde867defb7d262a2386 0x03 0x93c45176c38047e0f05cd298c01c7a1c1d4164918c872cd261afad1a8db2ce00 0x371c8568a2e757e5aeda742ffd451ae58628e2dbca52e7250c4f1258970f78ad {[0x0642414245c101843f35349150af9ddc125391e0f6017b4c3647274e616aa78b9d57dd7c76bb719f1ee92885161278d445aa639f1f30d7c32915ce53e4d2b5d4d48e71176d1c0d362aa7f52e779be9a90fe031a5d04ca6d180901911ccd61f96348e5230838b0f00000000000000000300000000000000 0x05424142450101ce792cce1f23b473654284aa9d89e29a0bedbce199a8f799249070647162315f43ad5ad7684b9e8ea015c9bfe7eaf9f86e485cd751f62eea55ebf612bbe9c48a]}}
=== RUN   TestChainRPC/test_chain_getBlock
    rpc_03-chain_test.go:109: Will assert ChainBlockResponse value {{0x11de252d68b23518ea2046899f13bf4411804fac16650e089268b5e4037afe4e 0x02 0x006d6fbe6c6c58781e47a9aa76d6b1c0cfa269414d17060a3b5cbf126a25f640 0xe1f26ecacc34b32f8a91ddf7ad573368b30070e02bb49dfecd445345e8fc73a5 {[0x0642414245c1014efb25f397653eae08aac973ff8f4610cb530822db106480c3c4fad4acd6c02f2207c8d99dfc033fc3cca69c02d4c3d73f605bd31c09bcdc1c5cf1b29e54db06b653dff0d1ef131933b72807289a55750238c7187d92faa947d0882c8c1af40c00000000000000000200000000000000 0x054241424501010c76be88a188cfe0f61d9f1849149f51dee255ed918b6102a199811cd49cc654d3b0b33dfd221ca51cd088afafb1a3021d64095fbe1c96f561f954dcfc143681]}} []}
=== RUN   TestChainRPC/test_chain_getBlockHash
    rpc_03-chain_test.go:127: Will assert ChainBlockNumberRequest value 0x4f5d7017a47e8d7b293f600bb52c0a546f9532f364615b3319c910b1ce64d38f
=== RUN   TestChainRPC/test_chain_getFinalizedHead
    rpc_03-chain_test.go:127: Will assert ChainBlockNumberRequest value 0x8fa6de44cef1514ec2a05e23981bd26e86978442aaa717fad5b91e080e816706
=== CONT  TestChainRPC
    rpc_03-chain_test.go:136: going to tear down gossamer...
--- PASS: TestChainRPC (3.69s)
    --- PASS: TestChainRPC/test_chain_getHeader (0.00s)
    --- PASS: TestChainRPC/test_chain_getBlock (0.00s)
    --- PASS: TestChainRPC/test_chain_getBlockHash (0.00s)
    --- PASS: TestChainRPC/test_chain_getFinalizedHead (0.00s)
=== RUN   TestChainSubscriptionRPC
    rpc_03-chain_test.go:196: starting gossamer...
t=2020-12-04T15:11:52+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/tests/utils/config_babe_max_threshold.toml --basepath /tmp/TestChainSubscriptionRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/tests/utils/genesis_oneauth.json --force"
t=2020-12-04T15:11:53+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
t=2020-12-04T15:11:53+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/tests/utils/config_babe_max_threshold.toml --basepath /tmp/TestChainSubscriptionRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice --ws --wsport 8546"
t=2020-12-04T15:11:54+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=169939
=== RUN   TestChainSubscriptionRPC/test_chain_subscribeNewHeads
2020/12/04 15:11:55 recv: 1: {"jsonrpc":"2.0","result":1,"id":1}

2020/12/04 15:11:55 recv: 2: {"jsonrpc":"2.0","method":"chain_newHead","params":{"result":{"parentHash":"0xb91d6611627d773b5435d4d5b86eeca01f2cc7ec67e71b8a7d66573e2361b87b","number":"0x04","stateRoot":"0xdc1171682013068506e1db83edf5024c30188a39fbcf9933b5cb1acb376381eb","extrinsicsRoot":"0x3742e7be17df62680aab00ac978d44a4b616372da5877789565c17148382cf27","digest":{"logs":["0x0642414245c1011e1fa96e41ae0e84751c574e4198c7969c2f9b242107d82c7732ecd7dd69f67ee13bcbdf1f113a67a64ef836edf7911959263eedde55825eeb8331521593ff011718bfe9da291aeaeac3c2f65be00d650e6b78ad5d3ca9dafaff2be761e3680400000000000000000400000000000000","0x054241424501012062a9383da112f2401949e80579c0fb8d0130b9b0d9ab80bba20f2024f4141ecb200d54124591ef8f2597c4fba7930708f6a1a24716b46af50f53d09f8a4885"]}},"subscription":1}}

=== RUN   TestChainSubscriptionRPC/test_state_subscribeStorage
    rpc_03-chain_test.go:217: Websocket endpoint not yet implemented
=== RUN   TestChainSubscriptionRPC/test_chain_finalizedHeads
2020/12/04 15:11:55 recv: 1: {"jsonrpc":"2.0","result":1,"id":1}

2020/12/04 15:11:57 recv: 2: {"jsonrpc":"2.0","method":"chain_finalizedHead","params":{"result":{"parentHash":"0xb91d6611627d773b5435d4d5b86eeca01f2cc7ec67e71b8a7d66573e2361b87b","number":"0x04","stateRoot":"0xdc1171682013068506e1db83edf5024c30188a39fbcf9933b5cb1acb376381eb","extrinsicsRoot":"0x3742e7be17df62680aab00ac978d44a4b616372da5877789565c17148382cf27","digest":{"logs":["0x0642414245c1011e1fa96e41ae0e84751c574e4198c7969c2f9b242107d82c7732ecd7dd69f67ee13bcbdf1f113a67a64ef836edf7911959263eedde55825eeb8331521593ff011718bfe9da291aeaeac3c2f65be00d650e6b78ad5d3ca9dafaff2be761e3680400000000000000000400000000000000","0x054241424501012062a9383da112f2401949e80579c0fb8d0130b9b0d9ab80bba20f2024f4141ecb200d54124591ef8f2597c4fba7930708f6a1a24716b46af50f53d09f8a4885"]}},"subscription":1}}

=== CONT  TestChainSubscriptionRPC
    rpc_03-chain_test.go:210: going to tear down gossamer...
--- PASS: TestChainSubscriptionRPC (8.46s)
    --- PASS: TestChainSubscriptionRPC/test_chain_subscribeNewHeads (0.25s)
    --- SKIP: TestChainSubscriptionRPC/test_state_subscribeStorage (0.00s)
    --- PASS: TestChainSubscriptionRPC/test_chain_finalizedHeads (2.50s)
=== RUN   TestOffchainRPC
    rpc_04-offchain_test.go:53: starting gossamer...
t=2020-12-04T15:12:00+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestOffchainRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
t=2020-12-04T15:12:01+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
t=2020-12-04T15:12:01+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestOffchainRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
t=2020-12-04T15:12:02+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=170053
=== RUN   TestOffchainRPC/test_offchain_localStorageSet
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestOffchainRPC/test_offchain_localStorageGet
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestOffchainRPC/test_offchain_localStorageGet#01
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== CONT  TestOffchainRPC
    rpc_04-offchain_test.go:65: going to tear down gossamer...
--- PASS: TestOffchainRPC (3.68s)
    --- SKIP: TestOffchainRPC/test_offchain_localStorageSet (0.00s)
    --- SKIP: TestOffchainRPC/test_offchain_localStorageGet (0.00s)
    --- SKIP: TestOffchainRPC/test_offchain_localStorageGet#01 (0.00s)
=== RUN   TestStateRPC
    rpc_05-state_test.go:99: starting gossamer...
t=2020-12-04T15:12:04+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestStateRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
t=2020-12-04T15:12:05+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
t=2020-12-04T15:12:05+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestStateRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
t=2020-12-04T15:12:06+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=170111
=== RUN   TestStateRPC/test_state_call
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestStateRPC/test_state_getPairs
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestStateRPC/test_state_getKeysPaged
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestStateRPC/test_state_getStorage
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestStateRPC/test_state_getStorageHash
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestStateRPC/test_state_getStorageSize
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestStateRPC/test_state_getChildKeys
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestStateRPC/test_state_getChildStorage
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestStateRPC/test_state_getChildStorageHash
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestStateRPC/test_state_getChildStorageSize
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestStateRPC/test_state_getRuntimeVersion
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestStateRPC/test_state_queryStorage
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== CONT  TestStateRPC
    rpc_05-state_test.go:111: going to tear down gossamer...
--- PASS: TestStateRPC (3.66s)
    --- SKIP: TestStateRPC/test_state_call (0.00s)
    --- SKIP: TestStateRPC/test_state_getPairs (0.00s)
    --- SKIP: TestStateRPC/test_state_getKeysPaged (0.00s)
    --- SKIP: TestStateRPC/test_state_getStorage (0.00s)
    --- SKIP: TestStateRPC/test_state_getStorageHash (0.00s)
    --- SKIP: TestStateRPC/test_state_getStorageSize (0.00s)
    --- SKIP: TestStateRPC/test_state_getChildKeys (0.00s)
    --- SKIP: TestStateRPC/test_state_getChildStorage (0.00s)
    --- SKIP: TestStateRPC/test_state_getChildStorageHash (0.00s)
    --- SKIP: TestStateRPC/test_state_getChildStorageSize (0.00s)
    --- SKIP: TestStateRPC/test_state_getRuntimeVersion (0.00s)
    --- SKIP: TestStateRPC/test_state_queryStorage (0.00s)
=== RUN   TestStateRPCAPI
    rpc_05-state_test.go:122: starting gossamer...
t=2020-12-04T15:12:08+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/tests/utils/config_babe_max_threshold.toml --basepath /tmp/TestStateRPCAPI/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
t=2020-12-04T15:12:08+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
t=2020-12-04T15:12:08+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/tests/utils/config_babe_max_threshold.toml --basepath /tmp/TestStateRPCAPI/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
t=2020-12-04T15:12:09+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=170176
=== RUN   TestStateRPCAPI/Test_valid_block_hash_state_getRuntimeVersion
=== RUN   TestStateRPCAPI/Test_valid_block_hash_state_getPairs
=== RUN   TestStateRPCAPI/Test_valid_block_hash_state_getMetadata
=== RUN   TestStateRPCAPI/Test_empty_value_state_getRuntimeVersion
=== RUN   TestStateRPCAPI/Test_empty_value_hash_state_getPairs
=== RUN   TestStateRPCAPI/Test_empty_value_hash_state_getMetadata
=== RUN   TestStateRPCAPI/Test_optional_params_state_getRuntimeVersion
=== RUN   TestStateRPCAPI/Test_optional_params_hash_state_getPairs
=== RUN   TestStateRPCAPI/Test_optional_params_hash_state_getMetadata
=== RUN   TestStateRPCAPI/Test_invalid_block_hash_state_getRuntimeVersion
    rpc_05-state_test.go:228: 
                Error Trace:    rpc_05-state_test.go:228
                Error:          "{\"jsonrpc\":\"2.0\",\"result\":{\"specName\":\"node\",\"implName\":\"substrate-node\",\"authoringVersion\":10,\"specVersion\":193,\"implVersion\":193,\"apis\":[[\"0xdf6acb689907609b\",2],[\"0x37e397fc7c91f5e4\",1],[\"0x40fe3ad401f8959a\",3],[\"0xd2bc9897eed08f15\",1],[\"0xf78b278be53f454c\",1],[\"0xed99c5acb25eedf5\",2],[\"0xcbca25e39f142387\",1],[\"0xbc9d89904f5b923f\",1],[\"0x68b66ba122c93fa7\",1],[\"0x37c8bb1350a9a2a8\",1],[\"0xab3c0572291feb8b\",1]]},\"id\":1}\n" does not contain "Key not found"
                Test:           TestStateRPCAPI/Test_invalid_block_hash_state_getRuntimeVersion
=== RUN   TestStateRPCAPI/Test_invalid_block_hash_state_getPairs
    rpc_05-state_test.go:228: 
                Error Trace:    rpc_05-state_test.go:228
                Error:      
                Test:           TestStateRPCAPI/Test_invalid_block_hash_state_getPairs
=== RUN   TestStateRPCAPI/Test_invalid_block_hash_state_getMetadata
    rpc_05-state_test.go:228: 
                Error Trace:    rpc_05-state_test.go:228
                Error:          "{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32600,\"message\":\"json: cannot unmarshal string into Go value of type modules.StateRuntimeMetadataQuery\",\"data\":[\"0x580d77a9136035a0bc3c3cd86286172f7f81291164c5914266073a30466fba21\"]},\"id\":1}\n" does not contain "Key not found"
                Test:           TestStateRPCAPI/Test_invalid_block_hash_state_getMetadata
=== RUN   TestStateRPCAPI/Test_required_params_missing_hash_state_getPairs
    rpc_05-state_test.go:225: 
                Error Trace:    rpc_05-state_test.go:225
                Error:          Expected nil, but got: &url.Error{Op:"Post", URL:"http://0.0.0.0:8540", Err:(*errors.errorString)(0xc000118030)}
                Test:           TestStateRPCAPI/Test_required_params_missing_hash_state_getPairs
=== CONT  TestStateRPCAPI
    rpc_05-state_test.go:131: going to tear down gossamer...
--- FAIL: TestStateRPCAPI (8.84s)
    --- PASS: TestStateRPCAPI/Test_valid_block_hash_state_getRuntimeVersion (0.12s)
    --- PASS: TestStateRPCAPI/Test_valid_block_hash_state_getPairs (0.13s)
    --- PASS: TestStateRPCAPI/Test_valid_block_hash_state_getMetadata (0.10s)
    --- PASS: TestStateRPCAPI/Test_empty_value_state_getRuntimeVersion (0.11s)
    --- PASS: TestStateRPCAPI/Test_empty_value_hash_state_getPairs (0.13s)
    --- PASS: TestStateRPCAPI/Test_empty_value_hash_state_getMetadata (0.10s)
    --- PASS: TestStateRPCAPI/Test_optional_params_state_getRuntimeVersion (0.12s)
    --- PASS: TestStateRPCAPI/Test_optional_params_hash_state_getPairs (0.11s)
    --- PASS: TestStateRPCAPI/Test_optional_params_hash_state_getMetadata (0.11s)
    --- FAIL: TestStateRPCAPI/Test_invalid_block_hash_state_getRuntimeVersion (0.02s)
    --- FAIL: TestStateRPCAPI/Test_invalid_block_hash_state_getPairs (0.06s)
    --- FAIL: TestStateRPCAPI/Test_invalid_block_hash_state_getMetadata (0.00s)
    --- FAIL: TestStateRPCAPI/Test_required_params_missing_hash_state_getPairs (0.00s)
=== RUN   TestRPCStructParamUnmarshal
    rpc_05-state_test.go:243: starting gossamer...
t=2020-12-04T15:12:17+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/tests/utils/config_babe_max_threshold.toml --basepath /tmp/TestRPCStructParamUnmarshal/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
t=2020-12-04T15:12:17+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
t=2020-12-04T15:12:17+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/tests/utils/config_babe_max_threshold.toml --basepath /tmp/TestRPCStructParamUnmarshal/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
t=2020-12-04T15:12:18+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=170303
=== RUN   TestRPCStructParamUnmarshal/Test_valid_read_request_in_local_json2
{"jsonrpc":"2.0","error":{"code":-32000,"message":"rpc: can't find method \"state.QueryStorage\"","data":null},"id":1}

=== CONT  TestRPCStructParamUnmarshal
    rpc_05-state_test.go:252: going to tear down gossamer...
--- PASS: TestRPCStructParamUnmarshal (4.81s)
    --- PASS: TestRPCStructParamUnmarshal/Test_valid_read_request_in_local_json2 (0.00s)
=== RUN   TestEngineRPC
    rpc_06-engine_test.go:48: starting gossamer...
t=2020-12-04T15:12:21+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestEngineRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
t=2020-12-04T15:12:22+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
t=2020-12-04T15:12:22+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestEngineRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
t=2020-12-04T15:12:23+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=170376
=== RUN   TestEngineRPC/test_engine_createBlock
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestEngineRPC/test_engine_finalizeBlock
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== CONT  TestEngineRPC
    rpc_06-engine_test.go:60: going to tear down gossamer...
--- PASS: TestEngineRPC (3.75s)
    --- SKIP: TestEngineRPC/test_engine_createBlock (0.00s)
    --- SKIP: TestEngineRPC/test_engine_finalizeBlock (0.00s)
=== RUN   TestPaymentRPC
    rpc_07-payment_test.go:43: starting gossamer...
t=2020-12-04T15:12:25+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestPaymentRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
t=2020-12-04T15:12:26+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
t=2020-12-04T15:12:26+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestPaymentRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
t=2020-12-04T15:12:27+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=170438
=== RUN   TestPaymentRPC/test_payment_queryInfo
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== CONT  TestPaymentRPC
    rpc_07-payment_test.go:55: going to tear down gossamer...
--- PASS: TestPaymentRPC (3.76s)
    --- SKIP: TestPaymentRPC/test_payment_queryInfo (0.00s)
=== RUN   TestContractsRPC
    rpc_08-contracts_test.go:48: starting gossamer...
t=2020-12-04T15:12:29+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestContractsRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
t=2020-12-04T15:12:30+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
t=2020-12-04T15:12:30+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestContractsRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
t=2020-12-04T15:12:31+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=170494
=== RUN   TestContractsRPC/test_contracts_getStorage
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== RUN   TestContractsRPC/test_contracts_getStorage#01
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== CONT  TestContractsRPC
    rpc_08-contracts_test.go:60: going to tear down gossamer...
--- PASS: TestContractsRPC (3.73s)
    --- SKIP: TestContractsRPC/test_contracts_getStorage (0.00s)
    --- SKIP: TestContractsRPC/test_contracts_getStorage#01 (0.00s)
=== RUN   TestBabeRPC
    rpc_09-babe_test.go:43: starting gossamer...
t=2020-12-04T15:12:33+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestBabeRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
t=2020-12-04T15:12:33+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
t=2020-12-04T15:12:33+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestBabeRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
t=2020-12-04T15:12:34+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=170565
=== RUN   TestBabeRPC/test_babe_epochAuthorship
    rpc_00_test.go:54: RPC endpoint not yet implemented
=== CONT  TestBabeRPC
    rpc_09-babe_test.go:55: going to tear down gossamer...
--- PASS: TestBabeRPC (3.70s)
    --- SKIP: TestBabeRPC/test_babe_epochAuthorship (0.00s)
=== RUN   TestStableNetworkRPC
    system_integration_test.go:34: Integration tests are disabled, going to skip.
--- SKIP: TestStableNetworkRPC (0.00s)
FAIL
FAIL    github.com/ChainSafe/gossamer/tests/rpc 59.421s
FAIL```

File: packages/rpc/json2/server.go (hunk 2 above)
Comment (arijitAD) [reply packages/rpc/json2/server.go:17]: This is the custom JSON to struct decoder we are using to parse unstructured JSON params. 
I have taken the code for `CodecRequest` from this https://github.com/gorilla/rpc/blob/master/v2/json2/server.go and fixed it to work.

**Comment by arijitAD** [comment]
> Encountered an error with the RPC test
> 
> ```
> Going to start RPC suite test
> === RUN   TestSystemRPC
>     rpc_01-system_test.go:110: starting gossamer...
> t=2020-12-04T15:11:37+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestSystemRPC/charlie --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
> t=2020-12-04T15:11:37+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestSystemRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
> t=2020-12-04T15:11:37+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestSystemRPC/bob --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
> t=2020-12-04T15:11:38+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
> t=2020-12-04T15:11:38+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestSystemRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
> t=2020-12-04T15:11:38+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=1
> t=2020-12-04T15:11:38+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7001 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestSystemRPC/bob --rpchost 0.0.0.0 --rpcport 8541 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key bob"
> t=2020-12-04T15:11:39+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=2
> t=2020-12-04T15:11:39+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7002 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestSystemRPC/charlie --rpchost 0.0.0.0 --rpcport 8542 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key charlie"
> t=2020-12-04T15:11:40+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=169629
> t=2020-12-04T15:11:40+0200 lvl=info msg="node started" pkg=test/utils key=bob cmd.Process.Pid=169639
> t=2020-12-04T15:11:41+0200 lvl=info msg="node started" pkg=test/utils key=charlie cmd.Process.Pid=169653
> === RUN   TestSystemRPC/test_system_name
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestSystemRPC/test_system_version
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestSystemRPC/test_system_chain
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestSystemRPC/test_system_properties
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestSystemRPC/test_system_health
>     rpc_01-system_test.go:124: Will assert SystemHealthResponse target &{{2 false true}}
> === RUN   TestSystemRPC/test_system_peers
>     request_utils.go:97: 
>                 Error Trace:    request_utils.go:97
>                                                         rpc_00_test.go:62
>                                                         rpc_01-system_test.go:120
>                 Error:          Expected nil, but got: &errors.errorString{s:"could not byteify non 0x prefixed string"}
>                 Test:           TestSystemRPC/test_system_peers
>                 Messages:       {"jsonrpc":"2.0","result":{"peers":[{"PeerID":"12D3KooWAQGJtCfDoyPHjhpGDCoUmiPFiq9UmCKpuMQ773CK8Nzp","Roles":4,"ProtocolVersion":0,"BestHash":[143,166,222,68,206,241,81,78,194,160,94,35,152,27,210,110,134,151,132,66,170,167,23,250,213,185,30,8,14,129,103,6],"BestNumber":0},{"PeerID":"12D3KooWEn548sgWU775USfnD3rsUAKBMcAjMauMRgqcc61GEcWq","Roles":4,"ProtocolVersion":0,"BestHash":[143,166,222,68,206,241,81,78,194,160,94,35,152,27,210,110,134,151,132,66,170,167,23,250,213,185,30,8,14,129,103,6],"BestNumber":0}]},"id":1}
> === RUN   TestSystemRPC/test_system_network_state
>     rpc_01-system_test.go:131: Will assert SystemNetworkStateResponse target &{{12D3KooWDmqA5WP22F6hGxaCFLq3d473RshHFdsKqtJbGuP4P6Za [/ip4/192.168.0.148/tcp/7000/p2p/12D3KooWDmqA5WP22F6hGxaCFLq3d473RshHFdsKqtJbGuP4P6Za /ip4/127.0.0.1/tcp/7000/p2p/12D3KooWDmqA5WP22F6hGxaCFLq3d473RshHFdsKqtJbGuP4P6Za]}}
> === RUN   TestSystemRPC/test_system_addReservedPeer
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestSystemRPC/test_system_removeReservedPeer
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestSystemRPC/test_system_nodeRoles
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestSystemRPC/test_system_accountNextIndex
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === CONT  TestSystemRPC
>     rpc_01-system_test.go:158: going to tear down gossamer...
> --- FAIL: TestSystemRPC (7.61s)
>     --- SKIP: TestSystemRPC/test_system_name (0.00s)
>     --- SKIP: TestSystemRPC/test_system_version (0.00s)
>     --- SKIP: TestSystemRPC/test_system_chain (0.00s)
>     --- SKIP: TestSystemRPC/test_system_properties (0.00s)
>     --- PASS: TestSystemRPC/test_system_health (0.00s)
>     --- FAIL: TestSystemRPC/test_system_peers (0.00s)
>     --- PASS: TestSystemRPC/test_system_network_state (0.00s)
>     --- SKIP: TestSystemRPC/test_system_addReservedPeer (0.00s)
>     --- SKIP: TestSystemRPC/test_system_removeReservedPeer (0.00s)
>     --- SKIP: TestSystemRPC/test_system_nodeRoles (0.00s)
>     --- SKIP: TestSystemRPC/test_system_accountNextIndex (0.00s)
> === RUN   TestAuthorRPC
>     rpc_02-author_test.go:73: starting gossamer...
> t=2020-12-04T15:11:45+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestAuthorRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
> t=2020-12-04T15:11:45+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
> t=2020-12-04T15:11:45+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestAuthorRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
> t=2020-12-04T15:11:46+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=169755
> === RUN   TestAuthorRPC/test_author_submitExtrinsic
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestAuthorRPC/test_author_pendingExtrinsics
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestAuthorRPC/test_author_removeExtrinsic
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestAuthorRPC/test_author_insertKey
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestAuthorRPC/test_author_rotateKeys
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestAuthorRPC/test_author_hasSessionKeys
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestAuthorRPC/test_author_hasKey
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === CONT  TestAuthorRPC
>     rpc_02-author_test.go:85: going to tear down gossamer...
> --- PASS: TestAuthorRPC (3.70s)
>     --- SKIP: TestAuthorRPC/test_author_submitExtrinsic (0.00s)
>     --- SKIP: TestAuthorRPC/test_author_pendingExtrinsics (0.00s)
>     --- SKIP: TestAuthorRPC/test_author_removeExtrinsic (0.00s)
>     --- SKIP: TestAuthorRPC/test_author_insertKey (0.00s)
>     --- SKIP: TestAuthorRPC/test_author_rotateKeys (0.00s)
>     --- SKIP: TestAuthorRPC/test_author_hasSessionKeys (0.00s)
>     --- SKIP: TestAuthorRPC/test_author_hasKey (0.00s)
> === RUN   TestChainRPC
>     rpc_03-chain_test.go:77: starting gossamer...
> t=2020-12-04T15:11:48+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/tests/utils/config_babe_max_threshold.toml --basepath /tmp/TestChainRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
> t=2020-12-04T15:11:49+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
> t=2020-12-04T15:11:49+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/tests/utils/config_babe_max_threshold.toml --basepath /tmp/TestChainRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
> t=2020-12-04T15:11:50+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=169820
> === RUN   TestChainRPC/test_chain_getHeader
>     rpc_03-chain_test.go:97: Will assert ChainBlockHeaderResponse value &{0x1981f308be537f247e73551bd9cabda88a44aad3d176cde867defb7d262a2386 0x03 0x93c45176c38047e0f05cd298c01c7a1c1d4164918c872cd261afad1a8db2ce00 0x371c8568a2e757e5aeda742ffd451ae58628e2dbca52e7250c4f1258970f78ad {[0x0642414245c101843f35349150af9ddc125391e0f6017b4c3647274e616aa78b9d57dd7c76bb719f1ee92885161278d445aa639f1f30d7c32915ce53e4d2b5d4d48e71176d1c0d362aa7f52e779be9a90fe031a5d04ca6d180901911ccd61f96348e5230838b0f00000000000000000300000000000000 0x05424142450101ce792cce1f23b473654284aa9d89e29a0bedbce199a8f799249070647162315f43ad5ad7684b9e8ea015c9bfe7eaf9f86e485cd751f62eea55ebf612bbe9c48a]}}
> === RUN   TestChainRPC/test_chain_getBlock
>     rpc_03-chain_test.go:109: Will assert ChainBlockResponse value {{0x11de252d68b23518ea2046899f13bf4411804fac16650e089268b5e4037afe4e 0x02 0x006d6fbe6c6c58781e47a9aa76d6b1c0cfa269414d17060a3b5cbf126a25f640 0xe1f26ecacc34b32f8a91ddf7ad573368b30070e02bb49dfecd445345e8fc73a5 {[0x0642414245c1014efb25f397653eae08aac973ff8f4610cb530822db106480c3c4fad4acd6c02f2207c8d99dfc033fc3cca69c02d4c3d73f605bd31c09bcdc1c5cf1b29e54db06b653dff0d1ef131933b72807289a55750238c7187d92faa947d0882c8c1af40c00000000000000000200000000000000 0x054241424501010c76be88a188cfe0f61d9f1849149f51dee255ed918b6102a199811cd49cc654d3b0b33dfd221ca51cd088afafb1a3021d64095fbe1c96f561f954dcfc143681]}} []}
> === RUN   TestChainRPC/test_chain_getBlockHash
>     rpc_03-chain_test.go:127: Will assert ChainBlockNumberRequest value 0x4f5d7017a47e8d7b293f600bb52c0a546f9532f364615b3319c910b1ce64d38f
> === RUN   TestChainRPC/test_chain_getFinalizedHead
>     rpc_03-chain_test.go:127: Will assert ChainBlockNumberRequest value 0x8fa6de44cef1514ec2a05e23981bd26e86978442aaa717fad5b91e080e816706
> === CONT  TestChainRPC
>     rpc_03-chain_test.go:136: going to tear down gossamer...
> --- PASS: TestChainRPC (3.69s)
>     --- PASS: TestChainRPC/test_chain_getHeader (0.00s)
>     --- PASS: TestChainRPC/test_chain_getBlock (0.00s)
>     --- PASS: TestChainRPC/test_chain_getBlockHash (0.00s)
>     --- PASS: TestChainRPC/test_chain_getFinalizedHead (0.00s)
> === RUN   TestChainSubscriptionRPC
>     rpc_03-chain_test.go:196: starting gossamer...
> t=2020-12-04T15:11:52+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/tests/utils/config_babe_max_threshold.toml --basepath /tmp/TestChainSubscriptionRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/tests/utils/genesis_oneauth.json --force"
> t=2020-12-04T15:11:53+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
> t=2020-12-04T15:11:53+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/tests/utils/config_babe_max_threshold.toml --basepath /tmp/TestChainSubscriptionRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice --ws --wsport 8546"
> t=2020-12-04T15:11:54+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=169939
> === RUN   TestChainSubscriptionRPC/test_chain_subscribeNewHeads
> 2020/12/04 15:11:55 recv: 1: {"jsonrpc":"2.0","result":1,"id":1}
> 
> 2020/12/04 15:11:55 recv: 2: {"jsonrpc":"2.0","method":"chain_newHead","params":{"result":{"parentHash":"0xb91d6611627d773b5435d4d5b86eeca01f2cc7ec67e71b8a7d66573e2361b87b","number":"0x04","stateRoot":"0xdc1171682013068506e1db83edf5024c30188a39fbcf9933b5cb1acb376381eb","extrinsicsRoot":"0x3742e7be17df62680aab00ac978d44a4b616372da5877789565c17148382cf27","digest":{"logs":["0x0642414245c1011e1fa96e41ae0e84751c574e4198c7969c2f9b242107d82c7732ecd7dd69f67ee13bcbdf1f113a67a64ef836edf7911959263eedde55825eeb8331521593ff011718bfe9da291aeaeac3c2f65be00d650e6b78ad5d3ca9dafaff2be761e3680400000000000000000400000000000000","0x054241424501012062a9383da112f2401949e80579c0fb8d0130b9b0d9ab80bba20f2024f4141ecb200d54124591ef8f2597c4fba7930708f6a1a24716b46af50f53d09f8a4885"]}},"subscription":1}}
> 
> === RUN   TestChainSubscriptionRPC/test_state_subscribeStorage
>     rpc_03-chain_test.go:217: Websocket endpoint not yet implemented
> === RUN   TestChainSubscriptionRPC/test_chain_finalizedHeads
> 2020/12/04 15:11:55 recv: 1: {"jsonrpc":"2.0","result":1,"id":1}
> 
> 2020/12/04 15:11:57 recv: 2: {"jsonrpc":"2.0","method":"chain_finalizedHead","params":{"result":{"parentHash":"0xb91d6611627d773b5435d4d5b86eeca01f2cc7ec67e71b8a7d66573e2361b87b","number":"0x04","stateRoot":"0xdc1171682013068506e1db83edf5024c30188a39fbcf9933b5cb1acb376381eb","extrinsicsRoot":"0x3742e7be17df62680aab00ac978d44a4b616372da5877789565c17148382cf27","digest":{"logs":["0x0642414245c1011e1fa96e41ae0e84751c574e4198c7969c2f9b242107d82c7732ecd7dd69f67ee13bcbdf1f113a67a64ef836edf7911959263eedde55825eeb8331521593ff011718bfe9da291aeaeac3c2f65be00d650e6b78ad5d3ca9dafaff2be761e3680400000000000000000400000000000000","0x054241424501012062a9383da112f2401949e80579c0fb8d0130b9b0d9ab80bba20f2024f4141ecb200d54124591ef8f2597c4fba7930708f6a1a24716b46af50f53d09f8a4885"]}},"subscription":1}}
> 
> === CONT  TestChainSubscriptionRPC
>     rpc_03-chain_test.go:210: going to tear down gossamer...
> --- PASS: TestChainSubscriptionRPC (8.46s)
>     --- PASS: TestChainSubscriptionRPC/test_chain_subscribeNewHeads (0.25s)
>     --- SKIP: TestChainSubscriptionRPC/test_state_subscribeStorage (0.00s)
>     --- PASS: TestChainSubscriptionRPC/test_chain_finalizedHeads (2.50s)
> === RUN   TestOffchainRPC
>     rpc_04-offchain_test.go:53: starting gossamer...
> t=2020-12-04T15:12:00+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestOffchainRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
> t=2020-12-04T15:12:01+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
> t=2020-12-04T15:12:01+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestOffchainRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
> t=2020-12-04T15:12:02+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=170053
> === RUN   TestOffchainRPC/test_offchain_localStorageSet
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestOffchainRPC/test_offchain_localStorageGet
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestOffchainRPC/test_offchain_localStorageGet#01
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === CONT  TestOffchainRPC
>     rpc_04-offchain_test.go:65: going to tear down gossamer...
> --- PASS: TestOffchainRPC (3.68s)
>     --- SKIP: TestOffchainRPC/test_offchain_localStorageSet (0.00s)
>     --- SKIP: TestOffchainRPC/test_offchain_localStorageGet (0.00s)
>     --- SKIP: TestOffchainRPC/test_offchain_localStorageGet#01 (0.00s)
> === RUN   TestStateRPC
>     rpc_05-state_test.go:99: starting gossamer...
> t=2020-12-04T15:12:04+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestStateRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
> t=2020-12-04T15:12:05+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
> t=2020-12-04T15:12:05+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestStateRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
> t=2020-12-04T15:12:06+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=170111
> === RUN   TestStateRPC/test_state_call
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestStateRPC/test_state_getPairs
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestStateRPC/test_state_getKeysPaged
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestStateRPC/test_state_getStorage
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestStateRPC/test_state_getStorageHash
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestStateRPC/test_state_getStorageSize
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestStateRPC/test_state_getChildKeys
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestStateRPC/test_state_getChildStorage
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestStateRPC/test_state_getChildStorageHash
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestStateRPC/test_state_getChildStorageSize
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestStateRPC/test_state_getRuntimeVersion
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestStateRPC/test_state_queryStorage
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === CONT  TestStateRPC
>     rpc_05-state_test.go:111: going to tear down gossamer...
> --- PASS: TestStateRPC (3.66s)
>     --- SKIP: TestStateRPC/test_state_call (0.00s)
>     --- SKIP: TestStateRPC/test_state_getPairs (0.00s)
>     --- SKIP: TestStateRPC/test_state_getKeysPaged (0.00s)
>     --- SKIP: TestStateRPC/test_state_getStorage (0.00s)
>     --- SKIP: TestStateRPC/test_state_getStorageHash (0.00s)
>     --- SKIP: TestStateRPC/test_state_getStorageSize (0.00s)
>     --- SKIP: TestStateRPC/test_state_getChildKeys (0.00s)
>     --- SKIP: TestStateRPC/test_state_getChildStorage (0.00s)
>     --- SKIP: TestStateRPC/test_state_getChildStorageHash (0.00s)
>     --- SKIP: TestStateRPC/test_state_getChildStorageSize (0.00s)
>     --- SKIP: TestStateRPC/test_state_getRuntimeVersion (0.00s)
>     --- SKIP: TestStateRPC/test_state_queryStorage (0.00s)
> === RUN   TestStateRPCAPI
>     rpc_05-state_test.go:122: starting gossamer...
> t=2020-12-04T15:12:08+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/tests/utils/config_babe_max_threshold.toml --basepath /tmp/TestStateRPCAPI/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
> t=2020-12-04T15:12:08+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
> t=2020-12-04T15:12:08+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/tests/utils/config_babe_max_threshold.toml --basepath /tmp/TestStateRPCAPI/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
> t=2020-12-04T15:12:09+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=170176
> === RUN   TestStateRPCAPI/Test_valid_block_hash_state_getRuntimeVersion
> === RUN   TestStateRPCAPI/Test_valid_block_hash_state_getPairs
> === RUN   TestStateRPCAPI/Test_valid_block_hash_state_getMetadata
> === RUN   TestStateRPCAPI/Test_empty_value_state_getRuntimeVersion
> === RUN   TestStateRPCAPI/Test_empty_value_hash_state_getPairs
> === RUN   TestStateRPCAPI/Test_empty_value_hash_state_getMetadata
> === RUN   TestStateRPCAPI/Test_optional_params_state_getRuntimeVersion
> === RUN   TestStateRPCAPI/Test_optional_params_hash_state_getPairs
> === RUN   TestStateRPCAPI/Test_optional_params_hash_state_getMetadata
> === RUN   TestStateRPCAPI/Test_invalid_block_hash_state_getRuntimeVersion
>     rpc_05-state_test.go:228: 
>                 Error Trace:    rpc_05-state_test.go:228
>                 Error:          "{\"jsonrpc\":\"2.0\",\"result\":{\"specName\":\"node\",\"implName\":\"substrate-node\",\"authoringVersion\":10,\"specVersion\":193,\"implVersion\":193,\"apis\":[[\"0xdf6acb689907609b\",2],[\"0x37e397fc7c91f5e4\",1],[\"0x40fe3ad401f8959a\",3],[\"0xd2bc9897eed08f15\",1],[\"0xf78b278be53f454c\",1],[\"0xed99c5acb25eedf5\",2],[\"0xcbca25e39f142387\",1],[\"0xbc9d89904f5b923f\",1],[\"0x68b66ba122c93fa7\",1],[\"0x37c8bb1350a9a2a8\",1],[\"0xab3c0572291feb8b\",1]]},\"id\":1}\n" does not contain "Key not found"
>                 Test:           TestStateRPCAPI/Test_invalid_block_hash_state_getRuntimeVersion
> === RUN   TestStateRPCAPI/Test_invalid_block_hash_state_getPairs
>     rpc_05-state_test.go:228: 
>                 Error Trace:    rpc_05-state_test.go:228
>                 Error:      
>                 Test:           TestStateRPCAPI/Test_invalid_block_hash_state_getPairs
> === RUN   TestStateRPCAPI/Test_invalid_block_hash_state_getMetadata
>     rpc_05-state_test.go:228: 
>                 Error Trace:    rpc_05-state_test.go:228
>                 Error:          "{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32600,\"message\":\"json: cannot unmarshal string into Go value of type modules.StateRuntimeMetadataQuery\",\"data\":[\"0x580d77a9136035a0bc3c3cd86286172f7f81291164c5914266073a30466fba21\"]},\"id\":1}\n" does not contain "Key not found"
>                 Test:           TestStateRPCAPI/Test_invalid_block_hash_state_getMetadata
> === RUN   TestStateRPCAPI/Test_required_params_missing_hash_state_getPairs
>     rpc_05-state_test.go:225: 
>                 Error Trace:    rpc_05-state_test.go:225
>                 Error:          Expected nil, but got: &url.Error{Op:"Post", URL:"http://0.0.0.0:8540", Err:(*errors.errorString)(0xc000118030)}
>                 Test:           TestStateRPCAPI/Test_required_params_missing_hash_state_getPairs
> === CONT  TestStateRPCAPI
>     rpc_05-state_test.go:131: going to tear down gossamer...
> --- FAIL: TestStateRPCAPI (8.84s)
>     --- PASS: TestStateRPCAPI/Test_valid_block_hash_state_getRuntimeVersion (0.12s)
>     --- PASS: TestStateRPCAPI/Test_valid_block_hash_state_getPairs (0.13s)
>     --- PASS: TestStateRPCAPI/Test_valid_block_hash_state_getMetadata (0.10s)
>     --- PASS: TestStateRPCAPI/Test_empty_value_state_getRuntimeVersion (0.11s)
>     --- PASS: TestStateRPCAPI/Test_empty_value_hash_state_getPairs (0.13s)
>     --- PASS: TestStateRPCAPI/Test_empty_value_hash_state_getMetadata (0.10s)
>     --- PASS: TestStateRPCAPI/Test_optional_params_state_getRuntimeVersion (0.12s)
>     --- PASS: TestStateRPCAPI/Test_optional_params_hash_state_getPairs (0.11s)
>     --- PASS: TestStateRPCAPI/Test_optional_params_hash_state_getMetadata (0.11s)
>     --- FAIL: TestStateRPCAPI/Test_invalid_block_hash_state_getRuntimeVersion (0.02s)
>     --- FAIL: TestStateRPCAPI/Test_invalid_block_hash_state_getPairs (0.06s)
>     --- FAIL: TestStateRPCAPI/Test_invalid_block_hash_state_getMetadata (0.00s)
>     --- FAIL: TestStateRPCAPI/Test_required_params_missing_hash_state_getPairs (0.00s)
> === RUN   TestRPCStructParamUnmarshal
>     rpc_05-state_test.go:243: starting gossamer...
> t=2020-12-04T15:12:17+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/tests/utils/config_babe_max_threshold.toml --basepath /tmp/TestRPCStructParamUnmarshal/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
> t=2020-12-04T15:12:17+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
> t=2020-12-04T15:12:17+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/tests/utils/config_babe_max_threshold.toml --basepath /tmp/TestRPCStructParamUnmarshal/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
> t=2020-12-04T15:12:18+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=170303
> === RUN   TestRPCStructParamUnmarshal/Test_valid_read_request_in_local_json2
> {"jsonrpc":"2.0","error":{"code":-32000,"message":"rpc: can't find method \"state.QueryStorage\"","data":null},"id":1}
> 
> === CONT  TestRPCStructParamUnmarshal
>     rpc_05-state_test.go:252: going to tear down gossamer...
> --- PASS: TestRPCStructParamUnmarshal (4.81s)
>     --- PASS: TestRPCStructParamUnmarshal/Test_valid_read_request_in_local_json2 (0.00s)
> === RUN   TestEngineRPC
>     rpc_06-engine_test.go:48: starting gossamer...
> t=2020-12-04T15:12:21+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestEngineRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
> t=2020-12-04T15:12:22+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
> t=2020-12-04T15:12:22+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestEngineRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
> t=2020-12-04T15:12:23+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=170376
> === RUN   TestEngineRPC/test_engine_createBlock
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestEngineRPC/test_engine_finalizeBlock
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === CONT  TestEngineRPC
>     rpc_06-engine_test.go:60: going to tear down gossamer...
> --- PASS: TestEngineRPC (3.75s)
>     --- SKIP: TestEngineRPC/test_engine_createBlock (0.00s)
>     --- SKIP: TestEngineRPC/test_engine_finalizeBlock (0.00s)
> === RUN   TestPaymentRPC
>     rpc_07-payment_test.go:43: starting gossamer...
> t=2020-12-04T15:12:25+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestPaymentRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
> t=2020-12-04T15:12:26+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
> t=2020-12-04T15:12:26+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestPaymentRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
> t=2020-12-04T15:12:27+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=170438
> === RUN   TestPaymentRPC/test_payment_queryInfo
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === CONT  TestPaymentRPC
>     rpc_07-payment_test.go:55: going to tear down gossamer...
> --- PASS: TestPaymentRPC (3.76s)
>     --- SKIP: TestPaymentRPC/test_payment_queryInfo (0.00s)
> === RUN   TestContractsRPC
>     rpc_08-contracts_test.go:48: starting gossamer...
> t=2020-12-04T15:12:29+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestContractsRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
> t=2020-12-04T15:12:30+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
> t=2020-12-04T15:12:30+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestContractsRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
> t=2020-12-04T15:12:31+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=170494
> === RUN   TestContractsRPC/test_contracts_getStorage
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === RUN   TestContractsRPC/test_contracts_getStorage#01
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === CONT  TestContractsRPC
>     rpc_08-contracts_test.go:60: going to tear down gossamer...
> --- PASS: TestContractsRPC (3.73s)
>     --- SKIP: TestContractsRPC/test_contracts_getStorage (0.00s)
>     --- SKIP: TestContractsRPC/test_contracts_getStorage#01 (0.00s)
> === RUN   TestBabeRPC
>     rpc_09-babe_test.go:43: starting gossamer...
> t=2020-12-04T15:12:33+0200 lvl=info msg="initializing gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer init --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestBabeRPC/alice --genesis-raw /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/genesis-raw.json --force"
> t=2020-12-04T15:12:33+0200 lvl=info msg="initialized gossamer!" pkg=test/utils node=0
> t=2020-12-04T15:12:33+0200 lvl=info msg="starting gossamer..." pkg=test/utils cmd="/home/ryann/Documents/Repos/ChainSafe/gossamer/bin/gossamer --port 7000 --config /home/ryann/Documents/Repos/ChainSafe/gossamer/chain/gssmr/config.toml --basepath /tmp/TestBabeRPC/alice --rpchost 0.0.0.0 --rpcport 8540 --rpcmods system,author,chain,state,dev --rpc --log info --roles 4 --key alice"
> t=2020-12-04T15:12:34+0200 lvl=info msg="node started" pkg=test/utils key=alice cmd.Process.Pid=170565
> === RUN   TestBabeRPC/test_babe_epochAuthorship
>     rpc_00_test.go:54: RPC endpoint not yet implemented
> === CONT  TestBabeRPC
>     rpc_09-babe_test.go:55: going to tear down gossamer...
> --- PASS: TestBabeRPC (3.70s)
>     --- SKIP: TestBabeRPC/test_babe_epochAuthorship (0.00s)
> === RUN   TestStableNetworkRPC
>     system_integration_test.go:34: Integration tests are disabled, going to skip.
> --- SKIP: TestStableNetworkRPC (0.00s)
> FAIL
> FAIL    github.com/ChainSafe/gossamer/tests/rpc 59.421s
> FAIL```
> ```

Fixed this.

File: tests/rpc/rpc_05-state_test.go [hunk 3]
```diff
@@ -209,13 +209,14 @@ func TestStateRPCAPI(t *testing.T) {
...
-			isErr:       true,
-		},
+		// TODO: Add validation for this RPC and enable the test.
+		//{
+		//	description: "Test required params missing hash state_getPairs",
+		//	method:      "state_getPairs",
+		//	params:      `[]`,
+		//	expected:    "required field missing in params",
+		//	isErr:       true,
+		//},
```
Comment (noot) [inline tests/rpc/rpc_05-state_test.go:219]: is this related to #1199?

File: dot/rpc/modules/state.go [hunk 4]
```diff
@@ -47,13 +46,44 @@ type StateStorageKeyRequest struct {
 }
 
 // StateRuntimeMetadataQuery is a hash value
-type StateRuntimeMetadataQuery common.Hash
+type StateRuntimeMetadataQuery struct {
+	Bhash common.Hash
```
Comment (noot) [inline dot/rpc/modules/state.go:50]: is this able to accept `nil` or only `""` ? I think it needs to be able to accept nil

Comment (noot) [reply dot/rpc/modules/state.go:50]: same for other request types

**Review by noot — COMMENTED** [review]
overall looks good, could you update the state request types to accept nil block hash instead of `""`? it's an optional value as specified here https://github.com/w3f/PSPs/diffs?base_sha=85e05b228a8053a162604e56c368842ece22015a&bytes=120&commentable=true&lines=8&pull_number=6&responsive=true&sha1=85e05b228a8053a162604e56c368842ece22015a&sha2=4a6df794e0616e44194c9c12dd51f8ac291e2daf&short_path=dcd448e&start_entry=2&sticky=true&unchanged=expanded#1119-state_getmetadata so it should be able to take nil

File: tests/rpc/rpc_05-state_test.go (hunk 3 above)
Comment (arijitAD) [reply tests/rpc/rpc_05-state_test.go:219]: Yes.

**Comment by noot** [comment]
could you also update the description to say `closes #1216`? gotta put the `closes` in front of the issue :p

File: dot/rpc/modules/state.go (hunk 4 above)
Comment (arijitAD) [reply dot/rpc/modules/state.go:50]: I have updated the PR. Now `common.Hash` accepts nil and `""` value both.

**Review by noot — APPROVED** [review]
great work! when adding more state RPC integration tests, could you add cases for nil and non-nil block hash?

**Comment by arijitAD** [comment]
> great work! when adding more state RPC integration tests, could you add cases for nil and non-nil block hash?

Yes. I am planning to cover three cases(valid request, empty/nil request, and invalid request) for all RPCs.

File: packages/rpc/json2/server.go [hunk 5]
```diff
@@ -0,0 +1,259 @@
...
+			//	Unstructured JSON: ["Hello world", 10, false]
+			//	After parsing to Notification Struct: main.Notification{Message:"Hello world", Priority:0xa, Critical:false}
+			if argsVal.Kind() == reflect.Struct && argsVal.NumField() > 0 {
+				for i := 0; i < argsVal.NumField(); i++ {
+					params = append(params, argsVal.Field(i).Addr().Interface())
+				}
+			} else {
+				params = []interface{}{args}
+			}
+
```
Comment (edwardmack) [inline packages/rpc/json2/server.go:194]: This is great, nice to parse these into structs here so the rpc methods can deal with structs instead of generic interfaces.  I like it!

**Review by edwardmack — APPROVED** [review]
