### PR TITLE
refactor(client/consensus/grandpa): revise generic params, fix justification signing and verification

### LINKED ISSUE #3892: Refactor generic params on existing work

### PR DESCRIPTION
**Pull request by timwu20**
## Changes

- Revised and reduced number of generic parameters used
- Introduces runtime primitives for `Hash`, `Hasher`, and `Number`.
- Introduces generic header used in tests, and corresponds to the same generic header in substrate.  
- Introduces keyring and key pair functionality similar to substrate
- Fixes signing and verification for justifications

## Tests

```sh
go test -tags integration github.com/ChainSafe/gossamer
```

## Issues

closes #3892 and #3893

## Primary Reviewer

@jimjbrettj

### CODE REVIEW

File: internal/client/consensus/grandpa/authorities.go [hunk 1]
```diff
@@ -46,46 +49,64 @@ type hashNumber[H, N any] struct {
...
 // appliedChanges represents the median and new set when a forced change has occurred
-type appliedChanges[H comparable, N constraints.Unsigned, ID AuthorityID] struct {
+type appliedChanges[H comparable, N constraints.Unsigned] struct {
 	median N
-	set    AuthoritySet[H, N, ID]
+	set    AuthoritySet[H, N]
+}
+
+// Get the current authorities and their weights (for the current set ID).
+func (sas *SharedAuthoritySet[H, N]) CurrentAuthorities() grandpa.VoterSet[string] {
```
Comment (jimjbrettj) [inline internal/client/consensus/grandpa/authorities.go:58]: Since this is using currentAuthorities, perhaps rename it to something like `currentVoterSet` or `voterSetFromAuthorities`

File: internal/client/consensus/grandpa/authorities.go [hunk 2]
```diff
@@ -8,6 +8,9 @@ import (
 	"fmt"
 	"sync"
 
+	"github.com/ChainSafe/gossamer/internal/client/telemetry"
+	pgrandpa "github.com/ChainSafe/gossamer/internal/primitives/consensus/grandpa"
```
Comment (jimjbrettj) [inline internal/client/consensus/grandpa/authorities.go]: nit/maybe rename to grandpa and finality-grandpa, pgrandpa feels unintuitive to me

File: internal/client/consensus/grandpa/aux_schema.go [hunk 3]
```diff
@@ -48,23 +51,24 @@ func loadDecoded(store AuxStore, key []byte, destination any) error {
...
+	authSet := &AuthoritySet[H, N]{}
 	err := loadDecoded(store, authoritySetKey, authSet)
 	if err != nil && !errors.Is(err, errValueNotFound) {
 		return nil, err
 	}
 
 	if !errors.Is(err, errValueNotFound) {
-		setStateOld := voterSetState[H, N, ID, Sig]{}
-		setState := setStateOld.New()
+		// setStateOld := voterSetState[H, N]{}
```
Comment (jimjbrettj) [inline internal/client/consensus/grandpa/aux_schema.go]: do we not need this anymore? else re-add

File: internal/client/consensus/grandpa/aux_schema_test.go [hunk 4]
```diff
@@ -0,0 +1,376 @@
+// Copyright 2023 ChainSafe Systems (ON)
+// SPDX-License-Identifier: LGPL-3.0-only
+
+package grandpa
```
Comment (jimjbrettj) [inline internal/client/consensus/grandpa/aux_schema_test.go:4]: This file already existed right? Why doesnt it just show up as a moved file?

File: internal/client/consensus/grandpa/finality_proof.go [hunk 5]
```diff
@@ -42,16 +44,12 @@ const maxUnknownHeaders = 100_000
...
-	ID AuthorityID,
-	H Header[Hash, N],
-	B BlockchainBackend[Hash, N, H],
+	Hash runtime.Hash,
+	N runtime.Number,
+	Hasher runtime.Hasher[Hash],
 ] struct {
-	backend            BE
-	sharedAuthoritySet *SharedAuthoritySet[Hash, N, ID]
+	backend            api.Backend[Hash, N, Hasher]
```
Comment (jimjbrettj) [inline internal/client/consensus/grandpa/finality_proof.go:51]: Does this not need to be a constraint for encoding/decoding purposes?

File: internal/client/consensus/grandpa/finality_proof_test.go [hunk 6]
```diff
@@ -0,0 +1,400 @@
+// Copyright 2023 ChainSafe Systems (ON)
+// SPDX-License-Identifier: LGPL-3.0-only
+
+package grandpa
```
Comment (jimjbrettj) [inline internal/client/consensus/grandpa/finality_proof_test.go:4]: Same for these files, not sure why they are showing up as new files vs moved files

File: internal/client/consensus/grandpa/justification.go [hunk 7]
```diff
@@ -20,53 +23,46 @@ var (
...
-type GrandpaJustification[
-	Hash constraints.Ordered,
-	N constraints.Unsigned,
-	S comparable,
-	ID AuthorityID,
-] struct {
-	Round           uint64
-	Commit          finalityGrandpa.Commit[Hash, N, S, ID]
-	VotesAncestries []Header[Hash, N]
+// #[derive(Clone, Encode, Decode, PartialEq, Eq, Debug)]
```
Comment (jimjbrettj) [inline internal/client/consensus/grandpa/justification.go]: nit/remove

File: internal/client/consensus/grandpa/justification.go [hunk 8]
```diff
@@ -20,53 +23,46 @@ var (
 	errBlockNotDescendentOfBase = errors.New("block not descendent of base")
 )
 
-// GrandpaJustification is a GRANDPA justification for block finality, it includes a commit message and
+// A GRANDPA justification for block finality, it includes a commit message and
```
Comment (jimjbrettj) [inline internal/client/consensus/grandpa/justification.go:26]: I think `GrandpaJustification` part is needed for linting

File: internal/client/consensus/grandpa/lib.go [hunk 9]
```diff
@@ -0,0 +1,19 @@
+// Copyright 2023 ChainSafe Systems (ON)
```
Comment (jimjbrettj) [inline internal/client/consensus/grandpa/lib.go:1]:
```suggestion
// Copyright 2024 ChainSafe Systems (ON)
```

File: internal/client/telemetry/telemetry.go [hunk 10]
```diff
@@ -0,0 +1,6 @@
+package telemetry
```
Comment (jimjbrettj) [inline internal/client/telemetry/telemetry.go:4]:
```suggestion
// Copyright 2024 ChainSafe Systems (ON)
// SPDX-License-Identifier: LGPL-3.0-only

package telemetry
```

File: internal/hash-db/hash_db.go [hunk 11]
```diff
@@ -0,0 +1,11 @@
+package hashdb
```
Comment (jimjbrettj) [inline internal/hash-db/hash_db.go:4]:
```suggestion
// Copyright 2024 ChainSafe Systems (ON)
// SPDX-License-Identifier: LGPL-3.0-only

package hashdb
```

File: internal/primitives/blockchain/backend.go [hunk 12]
```diff
@@ -0,0 +1,121 @@
+package blockchain
```
Comment (jimjbrettj) [inline internal/primitives/blockchain/backend.go:4]:
```suggestion
// Copyright 2024 ChainSafe Systems (ON)
// SPDX-License-Identifier: LGPL-3.0-only

package blockchain
```

File: internal/primitives/blockchain/backend.go [hunk 13]
```diff
@@ -0,0 +1,121 @@
...
+
+import (
+	"sync"
+
+	"github.com/ChainSafe/gossamer/internal/primitives/runtime"
+	"github.com/ChainSafe/gossamer/internal/primitives/runtime/generic"
+)
+
+// Blockchain database header backend. Does not perform any validation.
```
Comment (jimjbrettj) [inline internal/primitives/blockchain/backend.go:13]:
```suggestion
// HeaderBackend Blockchain database header backend. Does not perform any validation.
```

File: internal/primitives/blockchain/backend.go [hunk 14]
```diff
@@ -0,0 +1,121 @@
...
+type HeaderBackend[Hash runtime.Hash, N runtime.Number] interface {
+	// Get block header. Returns `None` if block is not found.
+	Header(hash Hash) (*runtime.Header[N, Hash], error)
+
+	// Get blockchain info.
+	Info() Info[Hash, N]
```
Comment (jimjbrettj) [inline internal/primitives/blockchain/backend.go:19]: really like all the comments here for these interfaces

File: internal/primitives/blockchain/backend.go [hunk 15]
```diff
@@ -0,0 +1,121 @@
...
+
+	// Get block status.
+	Status(hash Hash) (BlockStatus, error)
+
+	// Get block number by hash. Returns `None` if the header is not in the chain.
```
Comment (jimjbrettj) [inline internal/primitives/blockchain/backend.go:24]: nit/perhaps update comments to use go types for description

File: internal/primitives/consensus/grandpa/app/app.go [hunk 16]
```diff
@@ -0,0 +1,25 @@
+package app
```
Comment (jimjbrettj) [inline internal/primitives/consensus/grandpa/app/app.go:4]:
```suggestion
// Copyright 2024 ChainSafe Systems (ON)
// SPDX-License-Identifier: LGPL-3.0-only

package app
```

File: internal/primitives/consensus/grandpa/app/app.go [hunk 17]
```diff
@@ -0,0 +1,25 @@
...
+func NewPublicFromSlice(data []byte) (Public, error) {
+	if len(data) != 32 {
+		return Public{}, fmt.Errorf("invalid public key from data: %v", data)
+	}
+	pub := Public{}
+	copy(pub[:], data)
+	return pub, nil
+}
+
+type Signature = ed25519.Signature
```
Comment (jimjbrettj) [inline internal/primitives/consensus/grandpa/app/app.go:28]: nit/put this at top with other type declaration

File: internal/primitives/consensus/grandpa/grandpa.go [hunk 18]
```diff
@@ -0,0 +1,93 @@
...
+
+	if !valid {
+		logger.Debugf("Bad signature on message from %v", id)
+	}
+	return valid
+}
+
+// Encode round message localized to a given round and set id using the given
+// buffer.
+func LocalizedPayload(round RoundNumber, setID SetID, message any) []byte {
```
Comment (jimjbrettj) [inline internal/primitives/consensus/grandpa/grandpa.go:90]: I think we can remove/rename this function. Since it just marshals, I think the naming makes this more confusing

File: internal/primitives/core/core.go [hunk 19]
```diff
@@ -0,0 +1,5 @@
+package core
```
Comment (jimjbrettj) [inline internal/primitives/core/core.go:4]:
```suggestion
// Copyright 2024 ChainSafe Systems (ON)
// SPDX-License-Identifier: LGPL-3.0-only

package core
```

File: internal/primitives/core/crypto/crypto.go [hunk 20]
```diff
@@ -0,0 +1,246 @@
...
+
+func (dj DeriveJunction) Value() any {
+	if dj.inner == nil {
+		panic("nil inner for DeriveJunction")
+	}
+	return dj.inner
+}
+
+// Soft (vanilla) derivation. Public keys have a correspondent derivation.
+type DeriveJunctionSoft [32]byte
```
Comment (jimjbrettj) [inline internal/primitives/core/crypto/crypto.go:37]: Is the difference between Soft and Hard here that one has a corresponding derivation and the other doesn't?

File: internal/primitives/core/crypto/crypto.go [hunk 21]
```diff
@@ -0,0 +1,246 @@
...
+	"github.com/ChainSafe/gossamer/pkg/scale"
+)
+
+// The root phrase for our publicly known keys.
+const DevPhrase = "bottom drive obey lake curtain smoke basket hold race lonely fit walk"
+
+// A since derivation junction description. It is the single parameter used when creating
+// a new secret key from an existing secret key and, in the case of `SoftRaw` and `SoftIndex`
+// a new public key from an existing public key.
+type DeriveJunction struct {
```
Comment (jimjbrettj) [inline internal/primitives/core/crypto/crypto.go:22]: forgive me if this is a naive question, but what is a function in this sense?

File: internal/primitives/core/crypto/crypto.go [hunk 22]
```diff
@@ -0,0 +1,246 @@
...
+		Phrase:    phrase,
+		Password:  password,
+		Junctions: junctions,
+	}, nil
+}
+
+// Trait suitable for typical cryptographic PKI key pair type.
+//
+// For now it just specifies how to create a key from a phrase and derivation path.
+type Pair[Seed, Signature any] interface {
```
Comment (jimjbrettj) [inline internal/primitives/core/crypto/crypto.go:241]: Im a little confused what this file is actually for. We have implementations of the different crypto protocols that we need already, so is this meant to just wrap them/replace them? I see that this is used by the crypto protocols below, but what is different between these impls and the ones we already have? Why did we need new impls? With the regexes and such it looks quite different to me from our existing impls and I'm curious why that is

File: internal/primitives/core/ed25519/ed25519.go [hunk 23]
```diff
@@ -0,0 +1,272 @@
...
+// See [`from_string_with_seed`](Pair::from_string_with_seed) for more extensive documentation.
+func NewPairFromString(s string, passwordOverride *string) (crypto.Pair[[32]byte, Signature], error) {
+	pair, _, err := NewPairFromStringWithSeed(s, passwordOverride)
+	return pair, err
+}
+
+var _ crypto.Pair[[32]byte, Signature] = Pair{}
+
+// A signature (a 512-bit value).
+type Signature [64]byte
```
Comment (jimjbrettj) [inline internal/primitives/core/ed25519/ed25519.go:269]: nit/types at top

File: internal/primitives/core/hash/hash.go [hunk 24]
```diff
@@ -0,0 +1,54 @@
...
+import (
+	"crypto/rand"
+	"encoding/binary"
+	"fmt"
+	"io"
+
+	"github.com/ChainSafe/gossamer/pkg/scale"
+)
+
+// Fixed-size uninterpreted hash type with 32 bytes (256 bits) size.
```
Comment (jimjbrettj) [inline internal/primitives/core/hash/hash.go:15]: Why not just use out existing hash impl here? Does it just not have the needed receivers?

**Review by jimjbrettj — COMMENTED** [review]
Nice work! Have some questions into the context of some of the crypto things, but really liking the cleanup to the generics

File: internal/client/consensus/grandpa/authorities.go (hunk 1 above)
Comment (timwu20) [reply internal/client/consensus/grandpa/authorities.go:58]: I used the same naming as substrate. I don't think I changed this in the move.

File: internal/client/consensus/grandpa/finality_proof.go (hunk 5 above)
Comment (timwu20) [reply internal/client/consensus/grandpa/finality_proof.go:51]: `FinalityProofProvider` never gets encoded or decoded.  FYI: scale encoding is fine, the difficulty is when trying to decode into an interface.

File: internal/client/consensus/grandpa/justification.go (hunk 8 above)
Comment (timwu20) [reply internal/client/consensus/grandpa/justification.go:26]: yea I still need to fix the lint issues.

File: internal/primitives/blockchain/backend.go (hunk 15 above)
Comment (timwu20) [reply internal/primitives/blockchain/backend.go:24]: I think I may do this retroactively after I complete the rest of the tasks for this epic.  It kinda helps to be able to search entire lines to see where they are in substrate.

File: internal/primitives/consensus/grandpa/app/app.go (hunk 17 above)
Comment (timwu20) [reply internal/primitives/consensus/grandpa/app/app.go:28]: it's the next type though? I usually put the receiver methods and constructors after the type declaration.

File: internal/primitives/consensus/grandpa/grandpa.go (hunk 18 above)
Comment (timwu20) [reply internal/primitives/consensus/grandpa/grandpa.go:90]: I agree but I think I'm going to wait until I implement the rest of the `voterWork` logic and communication modules before refactoring to conform to go best practices.  This is a public method in substrate and is referenced a number of times within the client grandpa and communication modules.  I'll make this change in #3868.

File: internal/primitives/core/crypto/crypto.go (hunk 21 above)
Comment (timwu20) [reply internal/primitives/core/crypto/crypto.go:22]: you mean junction?

File: internal/primitives/core/crypto/crypto.go (hunk 20 above)
Comment (timwu20) [reply internal/primitives/core/crypto/crypto.go:37]: From what I gather, the separate types are merely descriptive.  You should be able to harden a derive junction essentially saying that this is no longer derived from another junction.  A slice of `DeriveJunction` with length of one would imply that the single junction is hard. We harden the junction in `NewDeriveJunctionFromString` when passing in the syntax `\\Alice` for example.

File: internal/primitives/core/crypto/crypto.go (hunk 22 above)
Comment (timwu20) [reply internal/primitives/core/crypto/crypto.go:241]: When trying to debug the tests after trying to fix signing, I found it difficult to know if the encodings were correct based on our existing keyring when comparing it the bytes substrate generated.  I discovered they used `SecretUri` to derive the keys using specific syntax.  Given that this syntax is synonymous in substrate, I thought it prudent to recreate how the keys were derived rather than change our existing keyring impl.  This would be useful to support the substrate like syntax when they declare authorities like `\\Alice` from the command line or chain spec.

File: internal/primitives/core/hash/hash.go (hunk 24 above)
Comment (timwu20) [reply internal/primitives/core/hash/hash.go:15]: Yea it doesn't have our existing receivers.  Also note the type of `string` here.  I need this cause I want it to satisfy `constraints.Ordered`.

File: internal/client/consensus/grandpa/aux_schema_test.go (hunk 4 above)
Comment (timwu20) [reply internal/client/consensus/grandpa/aux_schema_test.go:4]: I think cause I renamed this file.

File: internal/client/consensus/grandpa/finality_proof_test.go (hunk 6 above)
Comment (timwu20) [reply internal/client/consensus/grandpa/finality_proof_test.go:4]: I think cause I renamed this file.

File: internal/primitives/core/crypto/crypto.go (hunk 21 above)
Comment (jimjbrettj) [reply internal/primitives/core/crypto/crypto.go:22]: oops, yeah sorry I meant junction, not function

File: internal/client/consensus/grandpa/authorities.go [hunk 25]
```diff
@@ -46,46 +49,66 @@ type hashNumber[H, N any] struct {
...
+		idWeights[i] = grandpa.IDWeight[string]{
+			ID:     string(auth.AuthorityID.ToRawVec()),
+			Weight: uint64(auth.AuthorityWeight),
+		}
+	}
+	voterSet := grandpa.NewVoterSet[string](idWeights)
+	if voterSet == nil {
+		panic(fmt.Errorf(
+			"current_authorities is non-empty and weights are non-zero; constructor and all mutating operations on `AuthoritySet` ensure this; qed", //nolint: lll
+		))
```
Comment (EclesioMeloJunior) [inline internal/client/consensus/grandpa/authorities.go]:
```suggestion
		panic("current_authorities is non-empty and weights are non-zero; constructor and all mutating operations on `AuthoritySet` ensure this; qed") //nolint: lll
```

File: internal/client/consensus/grandpa/change_tree.go [hunk 26]
```diff
@@ -182,59 +182,80 @@ func (ct *ChangeTree[H, N, ID]) FinalizesAnyWithDescendentIf(
...
+func (mvdt *FinalizationResult[H, N]) SetValue(value any) (err error) {
+	switch value := value.(type) {
+	case changed[H, N]:
+		setFinalizationResult[H, N](mvdt, value)
 		return
+	case unchanged:
+		setFinalizationResult[H, N](mvdt, value)
+		return
+	default:
+		return fmt.Errorf("unsupported type")
```
Comment (EclesioMeloJunior) [inline internal/client/consensus/grandpa/change_tree.go:208]: I would to suggest panicking here. That is the tradeoff of using `any + constraint types`. The type is evaluated on runtime, which is something we can avoid using normal interfaces to achieve a VDT like style with comptime evaluation

**Review by EclesioMeloJunior — APPROVED** [review]
LGTM, just small nit

File: internal/client/consensus/grandpa/change_tree.go (hunk 26 above)
Comment (timwu20) [reply internal/client/consensus/grandpa/change_tree.go:208]: This is to satisfy the `VaryingDataType` interface, where the method `SetValue` can return an error.  This is used in the scale codec to decode into.  I'd consider revising the `VaryingDataType` interface if we were able to do this without returning an error using your suggestion.

File: internal/primitives/core/crypto/crypto.go (hunk 21 above)
Comment (timwu20) [reply internal/primitives/core/crypto/crypto.go:22]: Yea, it's just the steps on how this key was derived.

**Review by jimjbrettj — APPROVED** [review]
lgtm
