### PR TITLE
cmd, config, p2p: multiple bootnodes from genesis

### LINKED ISSUE #521: Error loading genesis file with multiple bootnodes
## Expected Behavior

Gossamer should be able to load a genesis file with multiple bootnodes listed.

## Current Behavior

Gossamer panics while loading a genesis file with multiple bootnodes listed.

```
panic: reflect: slice index out of range

goroutine 1 [running]:
reflect.Value.Index(0xd169c0, 0xc00027f940, 0x97, 0x1, 0xcf9c40, 0xc00027f8c0, 0x197)
	/usr/local/go/src/reflect/value.go:949 +0x1fe
github.com/ChainSafe/gossamer/codec.(*Decoder).DecodeArray(0xc03aa0b8d0, 0xd169c0, 0xc00027f940, 0xc03aa0b630, 0xc03aa0b630, 0x4232ff, 0xd169c0)
	/home/admin/go/src/github.com/ChainSafe/gossamer/codec/decode.go:333 +0x1ea
github.com/ChainSafe/gossamer/codec.(*Decoder).DecodeInterface(0xc03aa0b8d0, 0xd169c0, 0xc00027f940, 0xc000133340, 0x197, 0xd169c0, 0xc00027f940)
	/home/admin/go/src/github.com/ChainSafe/gossamer/codec/decode.go:299 +0xc5
github.com/ChainSafe/gossamer/codec.(*Decoder).Decode(0xc03aa0b8d0, 0xd169c0, 0xc00027f940, 0x1, 0xd169c0, 0xc00027f940, 0x197)
	/home/admin/go/src/github.com/ChainSafe/gossamer/codec/decode.go:70 +0x1ac
github.com/ChainSafe/gossamer/codec.(*Decoder).DecodeTuple(0xc03aa0b8d0, 0xd68380, 0xc000133320, 0xe0e7a0, 0xc000133320, 0x199, 0x506f54)
	/home/admin/go/src/github.com/ChainSafe/gossamer/codec/decode.go:510 +0x5a9
github.com/ChainSafe/gossamer/codec.(*Decoder).DecodeInterface(0xc03aa0b8d0, 0xd68380, 0xc000133320, 0xc0000ea540, 0xc03aa0b888, 0x506ba8, 0xc0000ea540)
	/home/admin/go/src/github.com/ChainSafe/gossamer/codec/decode.go:296 +0x22e
github.com/ChainSafe/gossamer/codec.(*Decoder).Decode(0xc03aa0b8d0, 0xd68380, 0xc000133320, 0xb8, 0xb8, 0x0, 0x0)
	/home/admin/go/src/github.com/ChainSafe/gossamer/codec/decode.go:70 +0x1ac
github.com/ChainSafe/gossamer/codec.Decode(0xc0000ea480, 0xb8, 0xb8, 0xd68380, 0xc000133320, 0xb8, 0xb8, 0x0, 0x0)
	/home/admin/go/src/github.com/ChainSafe/gossamer/codec/decode.go:44 +0xcc
github.com/ChainSafe/gossamer/trie.(*Database).LoadGenesisData(0xc000148150, 0xc00027e7c0, 0xc0000ee6e0, 0x0)
	/home/admin/go/src/github.com/ChainSafe/gossamer/trie/database.go:87 +0x11e
github.com/ChainSafe/gossamer/state.(*StorageState).LoadGenesisData(...)
	/home/admin/go/src/github.com/ChainSafe/gossamer/state/storage.go:71
main.makeNode(0xc0000d0b00, 0x0, 0x0, 0x1, 0xe840a0)
	/home/admin/go/src/github.com/ChainSafe/gossamer/cmd/gossamer/configcmd.go:82 +0x35e
main.gossamer(0xc0000d0b00, 0xc0000d0b00, 0xc00025fbbf)
	/home/admin/go/src/github.com/ChainSafe/gossamer/cmd/gossamer/main.go:168 +0x64
github.com/urfave/cli.HandleAction(0xd41d20, 0xfecf88, 0xc0000d0b00, 0xc000049200, 0x0)
	/home/admin/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8
github.com/urfave/cli.(*App).Run(0xc0003001a0, 0xc0000321d0, 0x1, 0x1, 0x0, 0x0)
	/home/admin/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:264 +0x58c
main.main()
	/home/admin/go/src/github.com/ChainSafe/gossamer/cmd/gossamer/main.go:124 +0x51
```

## Steps to Reproduce

Add a second bootnode address to the default genesis file and attempt to initialize node.

### PR DESCRIPTION
**Pull request by ryanchristo**
## Changes

This pull request adds test for multiple bootnodes and cleans up the loading of bootnodes from genesis following #587, which resolved #521 (panic when multiple bootnodes in genesis file).

## Tests:

```
make gossamer
./build/bin/gossamer init
./build/bin/gossamer
```

### Issues:

closes #521

### CODE REVIEW

File: trie/database.go [hunk 1]
```diff
@@ -85,7 +85,7 @@ func (db *Database) LoadGenesisData() (*genesis.GenesisData, error) {
 	}
 
 	data, err := scale.Decode(enc, &genesis.GenesisData{
-		Bootnodes: [][]byte{{}},
+		Bootnodes: [][]byte{{}}, // TODO: read slice length from SCALE encoding
```
Comment (ryanchristo) [inline trie/database.go]: This was the root cause of the gossamer command not being able to support multiple bootnodes listed in the genesis file. We were attempting to load bootnodes from the db where we are using SCALE encoding but with a defined number of bootnodes in the interface provided here, otherwise encoding panics on `reflect.value.Index()` using this interface.

Comment (ryanchristo) [reply trie/database.go]: addressed in #539

File: cmd/gossamer/configcmd.go [hunk 2]
```diff
@@ -72,29 +70,29 @@ func makeNode(ctx *cli.Context) (*dot.Dot, *cfg.Config, error) {
...
-	r, err := loadStateAndRuntime(stateSrv.Storage, ks)
+	rt, err := loadStateAndRuntime(stateSrv.Storage, ks)
 	if err != nil {
 		return nil, nil, fmt.Errorf("error loading state and runtime: %s", err)
 	}
 
-	// load extra genesis data from DB
-	gendata, err := stateSrv.Storage.LoadGenesisData()
+	// load genesis from JSON file
+	gen, err := genesis.LoadGenesisFromJSON(getGenesisPath(ctx))
```
Comment (noot) [inline cmd/gossamer/configcmd.go]: we shouldn't be loading anything from the genesis file here, it should all happen when `gossamer init` is done

File: cmd/gossamer/configcmd.go [hunk 3]
```diff
@@ -108,7 +106,8 @@ func makeNode(ctx *cli.Context) (*dot.Dot, *cfg.Config, error) {
 	// RPC
 	rpcSrvr := startRpc(ctx, fig.Rpc, apiSrvc)
 
-	return dot.NewDot(string(gendata.Name), srvcs, rpcSrvr), fig, nil
+	// gendata
```
Comment (noot) [inline cmd/gossamer/configcmd.go]: ?

Comment (ryanchristo) [reply cmd/gossamer/configcmd.go]: a straggler, will remove

File: cmd/gossamer/configcmd.go (hunk 2 above)
Comment (ryanchristo) [reply cmd/gossamer/configcmd.go]: Hmm... I did this because the bootnodes are string slice type when using `Genesis` and we are currently unable to use SCALE encoding with a byte slice. All we need for p2p service here is `Name` and `Bootnodes`. Why should we not be using the genesis file here? Can we combine `init` with action?

Comment (noot) [reply cmd/gossamer/configcmd.go]: I believe the SCALE issue has been fixed, unless you are talking about something else? 
yes we need Name and Bootnodes, which should already have been stored in the DB from doing init. the idea is that we don't need to pass in the genesis file when running just `gossamer`.

**Comment by ryanchristo** [comment]
@noot I am not currently working on #539 but this issue is blocked if we do not want to load from the genesis file here. I will likely pick it up unless you want to tackle it.

**Comment by noot** [comment]
@ryanchristo feel free to take #539 if it's blocking this!

File: cmd/gossamer/configcmd.go (hunk 2 above)
Comment (ryanchristo) [reply cmd/gossamer/configcmd.go]: If we do not want to load from genesis file here, we can solve #539 first. I thought using `Genesis` here was an improvement but either way works for me.

Comment (noot) [reply cmd/gossamer/configcmd.go]: okay yeah I'm gonna say do #539 first, is there a reason you can't retrieve it from the DB? I guess because decoding only decodes 1 bootnode?

Comment (ryanchristo) [reply cmd/gossamer/configcmd.go]: correct, the length is currently fixed with a length of `1`
