### PR TITLE
Elizabeth/trie fix

### LINKED ISSUE #151: Trie root hash does not match the result from rust implementation
```
$ ./run_tests.sh
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/polkadot-re-tests/build
[100%] running cargo
    Finished dev [unoptimized + debuginfo] target(s) in 0.77s
[100%] Built target rust_tester_target
[100%] Built target go_tester
[100%] Built target go_tester_all
[100%] running cargo
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
[100%] Built target rust_tester_target
[100%] Built target go_tester
[100%] Built target go_tester_all
Install the project...
-- Install configuration: ""
-- Up-to-date: bin/usr/local/bin/rust_tester
-- Installing: bin/usr/local/bin/go_tester
Test Summary:     | Pass  Total
Scale Codec Tests |    6      6
  2.552807 seconds (4.40 M allocations: 226.640 MiB, 4.80% gc time)
WARNING: replacing module CommonFixtures.
WARNING: replacing module ScaleCodecFixtures.
WARNING: replacing module StateTrieFixtures.
state trie root: 0xa10270d88debdb7005451775b908c2d575a37bfed94daaa0b6fa14045372e45c

state root hash: 0x4213043100000000000000000000000000000000000000000000000000000000
State Trie Tests: Test Failed at /home/user/polkadot-re-tests/test/state_trie_tests.jl:18
  Expression: test_result_array[end] == test_result_array[CommonFixtures.reference_implementation]
   Evaluated: "state root hash: 0x4213043100000000000000000000000000000000000000000000000000000000" == "state trie root: 0xa10270d88debdb7005451775b908c2d575a37bfed94daaa0b6fa14045372e45c\n"
Stacktrace:
 [1] top-level scope at /home/user/polkadot-re-tests/test/state_trie_tests.jl:18
 [2] top-level scope at /build/julia/src/julia-1.1.0/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083
 [3] top-level scope at /home/user/polkadot-re-tests/test/state_trie_tests.jl:5
state trie root: 0x7cdd17212f13b5943c04cc48c59a4e2307f4b4f6370a4f10db2195b5ae90589c

state root hash: 0xb804236613fdec5bec79e990892cb84c7941af6cdd9879917221ca0655970f15
State Trie Tests: Test Failed at /home/user/polkadot-re-tests/test/state_trie_tests.jl:18
  Expression: test_result_array[end] == test_result_array[CommonFixtures.reference_implementation]
   Evaluated: "state root hash: 0xb804236613fdec5bec79e990892cb84c7941af6cdd9879917221ca0655970f15" == "state trie root: 0x7cdd17212f13b5943c04cc48c59a4e2307f4b4f6370a4f10db2195b5ae90589c\n"
Stacktrace:
 [1] top-level scope at /home/user/polkadot-re-tests/test/state_trie_tests.jl:18
 [2] top-level scope at /build/julia/src/julia-1.1.0/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083
 [3] top-level scope at /home/user/polkadot-re-tests/test/state_trie_tests.jl:5
Test Summary:      | Fail  Total
State Trie Tests   |    2      2
  State Trie Tests |    2      2
ERROR: LoadError: Some tests did not pass: 0 passed, 2 failed, 0 errored, 0 broken.
in expression starting at /home/user/polkadot-re-tests/test/runtests.jl:3

```

### PR DESCRIPTION
**Pull request by noot**
## Changes
- fixed trie bugs to get root encoding/hash to conform to parity's
- branch encoding bug where hasher wasn't cleared, as well as ordering of values

## Tests:
```
go test ./trie/
```

### Fixes:
closes #151

### CODE REVIEW

File: trie/node_test.go [hunk 1]
```diff
@@ -173,11 +162,25 @@ func TestBranchEncode(t *testing.T) {
 
 		expected = append(expected, buf.Bytes()...)
 
+		for _, child := range b.children {
+			if child != nil {
+				hasher, err := NewHasher()
```
Comment (golangcibot) [inline trie/node_test.go]: shadow: declaration of "err" shadows declaration at line 147 (from `govet`)

File: trie/iterator.go [hunk 2]
```diff
@@ -17,25 +17,65 @@
...
+		fmt.Printf("leaf hash ")
+		printHexBytes(hash)
 	default:
 		// do nothing
 	}
 }
+
+func printHexBytes(in []byte) {
+	fmt.Print("[")
+    for i, b := range in {
```
Comment (golangcibot) [inline trie/iterator.go]: File is not `gofmt`-ed with `-s` (from `gofmt`)

File: trie/trie_test.go [hunk 3]
```diff
@@ -515,4 +515,4 @@ func TestDelete(t *testing.T) {
 			}
 		}
 	}
-}
+}
```
Comment (golangcibot) [inline trie/trie_test.go]: File is not `gofmt`-ed with `-s` (from `gofmt`)
```suggestion
}
```

File: trie/iterator.go [hunk 4]
```diff
@@ -17,25 +17,65 @@
...
+		fmt.Printf("new hasher err %s\n", err)
+	}
+	var encoding []byte
+	var hash []byte
+	if withEncoding && current != nil {
+		encoding, err = current.Encode()
+		if err != nil {
+			fmt.Printf("encoding err %s\n", err)
+		}
+		hash, err = h.Hash(current)
```
Comment (golangcibot) [inline trie/iterator.go]: ineffectual assignment to `err` (from `ineffassign`)

**Comment by noot** [comment]
@ansermino can we ignore the code climate issue, i think the function is fine

File: trie/iterator.go [hunk 5]
```diff
@@ -17,25 +17,72 @@
 package trie
 
 import (
-	log "github.com/inconshreveable/log15"
+	"fmt"
+	//log "github.com/inconshreveable/log15"
```
Comment (dutterbutter) [inline trie/iterator.go]: Why not use log15?

File: trie/iterator.go [hunk 6]
```diff
@@ -17,25 +17,72 @@
...
+			fmt.Printf("hashing err %s\n", err)
+		}
+	}
+
 	switch c := current.(type) {
 	case *branch:
-		log.Info("branch key %x children %b value %s\n", nibblesToKeyLE(append(prefix, c.key...)), c.childrenBitmap(), c.value)
+		fmt.Printf("branch key %x children %b value %x\n", nibblesToKeyLE(append(prefix, c.key...)), c.childrenBitmap(), c.value)
+		if withEncoding {
+			fmt.Printf("branch encoding ")
```
Comment (dutterbutter) [inline trie/iterator.go]: is there a particular reason we are printing messages to the terminal this often? Makes for messy logs

File: trie/iterator.go (hunk 5 above)
Comment (noot) [reply trie/iterator.go]: i'm not sure how to format things properly with log15.. i need stuff to be printed in hex and binary formats

File: trie/iterator.go (hunk 6 above)
Comment (noot) [reply trie/iterator.go]: this function is for printing/debugging, i can try to change it to log15

Comment (noot) [reply trie/iterator.go]: also idk how to throw the `printHexBytes` function into log15, can we just leave it for now? i feel like fmt looks more readable for trie debugging than a logger

Comment (dutterbutter) [reply trie/iterator.go]: Okay but make a task in zube we need to be consistent throughout each package how we are logging and setting up debugging logs. We will have to go back and change the logs to reflect the rest of the package files.

File: trie/test_trie.yaml [hunk 7]
```diff
@@ -0,0 +1,13 @@
+keys:
```
Comment (ansermino) [inline trie/test_trie.yaml]: What is this file?

File: trie/trie.go [hunk 8]
```diff
@@ -57,6 +58,15 @@ func (t *Trie) Encode() ([]byte, error) {
 	return Encode(t.root)
 }
 
+func (t *Trie) Hash() (common.Hash, error) {
```
Comment (ansermino) [inline trie/trie.go]: Exported, please document

File: trie/test_trie.yaml (hunk 7 above)
Comment (noot) [reply trie/test_trie.yaml]: deleted

File: trie/trie.go (hunk 8 above)
Comment (noot) [reply trie/trie.go]: added a comment

File: trie/iterator.go (hunk 6 above)
Comment (noot) [reply trie/iterator.go]: ok done. David pointed out this should probably be made into an actual iterator so I'm going to work on that

**Comment by noot** [comment]
@ansermino any updates?

**Comment by GregTheGreek** [comment]
fixed codecov

**Comment by noot** [comment]
@ansermino a new build error on travis?
