### PR TITLE
fix(utils): create a specific folder for database

### LINKED ISSUE #1588: Create a seperate folder for db.
## Issue summary

- Currently, DB is stored in the base path. It will be nice if we store it in a separate folder.
Screenshot 2021-05-14 at 6 48 39 PM

## Other information and links

-

### PR DESCRIPTION
**Pull request by EclesioMeloJunior**
## Changes

- Create function `utils.SetupDatabase` to centralize the code to create a database instance. (maybe could we have an package just for database)
- Update all the code pieces that calls `chaindb.NewBadgerDB` to calls `utils.SetupDatabase`

## Tests

```
```

## Issues

- closes #1588 

## Screenshots
- Storage folder inside the basepath folder
image

### CODE REVIEW

File: lib/utils/utils.go [hunk 1]
```diff
@@ -25,8 +25,21 @@ import (
 	"path/filepath"
 	"runtime"
 	"strings"
+
+	"github.com/ChainSafe/chaindb"
 )
 
+// DefaultDatabaseDir directory inside baspath where database contents are stored
+const DefaultDatabaseDir = "storage"
```
Comment (noot) [inline lib/utils/utils.go:33]: maybe change to `db`?

**Review by noot — APPROVED** [review]
looks good! please put `closes` before the issue number in your PR description

File: lib/utils/utils.go [hunk 2]
```diff
@@ -25,8 +25,21 @@ import (
 	"path/filepath"
 	"runtime"
 	"strings"
+
+	"github.com/ChainSafe/chaindb"
 )
 
+// DefaultDatabaseDir directory inside baspath where database contents are stored
```
Comment (arijitAD) [inline lib/utils/utils.go:32]: typo `baspath` -> `basepath`

**Review by arijitAD — APPROVED** [review]
