### PR TITLE
Cli Fix

### LINKED ISSUE #124: `--config` panic on invalid path
## Expected Behavior
Using `--config` with any file/path results in a clean exit if file/path is invalid.

## Current Behavior

Panic :

https://github.com/ChainSafe/gossamer/blob/0f431ae99efb172dc1e835584a91d40ce20f93d8/cmd/gossamer/configcmd.go#L95

## Possible Solution

This likely qualifies as a fatal error, so we should report the error and exit. 

Note: Error returned is of type `*PathError` (https://golang.org/pkg/os/#Open)

## Steps to Reproduce (for bugs)

1. `make gossamer`
2. `gossamer --config laksjdf.toml` (any non-existant name would do)

## Context
N/A

## Your Environment
* Version used: 
* Commit hash: 0f431ae
* Go Version: 1.12
* Operating System and version (include distro if Linux): Ubuntu 18.04
* Link to your project or reproducible gist:
* I intend to submit a pull request to fix this issue: [x]

### PR DESCRIPTION
**Pull request by dutterbutter**
Adds some validation for passing in `config.toml`

## Changes
- Checks to see if the file path passed in is a directory if so serves a `Fatal` error
- Checks to see if the file path passed in exists if not servers a `Fatal` error 
- 

## Tests:
```

```

### Fixes:
closes #124 #125

### CODE REVIEW

File: cmd/gossamer/configcmd.go [hunk 1]
```diff
@@ -89,10 +89,20 @@ func loadConfig(file string) (*cfg.Config, error) {
 		log.Warn("error finding working directory", "err", err)
 	}
 	filep := filepath.Join(filepath.Clean(fp))
+	info, err := os.Lstat(filep)
+	if err != nil {
+		log.Crit("config file err ","err", err)
+		os.Exit(1)
+	}
+	if info.IsDir() {
+		log.Crit("cannot pass in a directory as config.toml ")
```
Comment (ansermino) [inline cmd/gossamer/configcmd.go]: probably shouldn't reference an actual filename
