### PR TITLE
fix: cmd/gossamer: Generate random name if --name flag not set

### LINKED ISSUE #1496: Generate random name when --name flag is not used
## Describe the bug

- Currently when starting the gossamer node, the node's name defaults to "Polkadot" if the `--name` flag is not used.  

## Expected Behavior

- When the `--name` flag is not used the node should generate a random name (so that the node can be uniquely identified).  The ParityTech Polkadot nodes generate a name by compining two random words followed by a 4 digit number. For example: `cuddly-rake-4006`

## Current Behavior

- Currently Gossamer node uses default name 'Polkadot' if the '--name' flag is not used.

## Possible Solution

- Add function to generate random name when `--name` flag is not used.

## To Reproduce

1. Start gossamer node without name flag.
2. Observe name defaults to "Polkadot"

## Log output

<details>
  <summary>Log Output</summary>
  
  ```
INFO[03-30|14:15:44] 🕸️ initializing node services...    pkg=dot name=Polkadot id=polkadot basepath=/home/emack/.gossamer/polkadot caller=node.go:180
  ```
</details> 
</br>

## Specification

- go version:
- gossamer version: 0.3.2
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

### PR DESCRIPTION
**Pull request by edwardmack**
## Changes

- Implement code to generate random name if `--name` flag not set.  Names in form of [word]-[word]-[number]

## Tests

start gossamer node without `--name` flag, for example
```
 ./bin/gossamer --chain polkadot
```
review logs to determine name assigned to node:
```
INFO[04-05|18:05:20] 🕸️ initializing node services...    pkg=dot name=ankle-shallow-2360 id=polkadot basepath=/home/emack/.gossamer/polkadot caller=node.go:186
```

## Issues

- closes #1496

### CODE REVIEW

File: cmd/gossamer/config.go [hunk 1]
```diff
@@ -408,6 +410,13 @@ func setDotGlobalConfig(ctx *cli.Context, tomlCfg *ctoml.Config, cfg *dot.Global
 	// check --name flag and update node configuration
 	if name := ctx.GlobalString(NameFlag.Name); name != "" {
 		cfg.Name = name
+	} else {
+		// generate random name
+		entropy, _ := bip39.NewEntropy(128)
+		randomNamesString, _ := bip39.NewMnemonic(entropy)
+		randomNames := strings.Split(randomNamesString, " ")
```
Comment (arijitAD) [inline cmd/gossamer/config.go:417]: Is `len(randomNames) > 1` always?

**Review by arijitAD — APPROVED** [review]

**Review by noot — APPROVED** [review]
looks good! nitpick, but I think substrate generates adjective-noun-number format, but this isn't necessarily the same. but we'd have to add a dictionary or something for that so no big deal

File: cmd/gossamer/config.go (hunk 1 above)
Comment (edwardmack) [reply cmd/gossamer/config.go:417]: Yes, bip39.NewMnemonic always returns 12 words when provided with a 128 bit entropy.
