### PR TITLE
dot/state: Fix node storing head data

### LINKED ISSUE #1142: node not storing head data for blocks 1-64
## Expected Behavior

- calling RPC chain_getHeader with hash for block 1 - 64 should return header data.
- 

## Current Behavior

- calling RPC chain_getHeader with hash for block 1 - 64 should returns "Key not found" error.
- works as it should for blocks higher than 64

## Possible Solution

-

## Steps to Reproduce
found testing #790 

1. RPC call `chain_getBlockHash` with parameter any block number less than 65.
2. use resulting hash to call `chain_getHeader`

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

### PR DESCRIPTION
**Pull request by edwardmack**
## Changes

- The code updates the check BlockState.IsDescendantOf so that it doesn't prune blocks that are on the current chain.
-
-

## Tests

```
go test ./dot/state/...
```

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [x] I have reviewed my own pull request before requesting a review
- [ ] All integration tests and required coverage checks are passing

## Issues

- closes #1142

### CODE REVIEW

File: lib/blocktree/blocktree.go [hunk 1]
```diff
@@ -157,10 +157,6 @@ func (bt *BlockTree) Prune(newRoot Hash) (pruned []Hash) {
 	// get pruned nodes
 	pruned = bt.head.getAllDescendantsExcluding(nil, newRoot)
 
-	// set blocktree with new root node
-	next := newBlockTreeFromNode(n, bt.db)
-	*bt = *next
-
```
Comment (noot) [inline lib/blocktree/blocktree.go:163]: we actually still need to prune the blocktree at the end of `SetFinalizedHash`, so we'll have to re-add this. I think this could be done by first copying the original blocktree (will need to implement a `Copy` func) and using that to check `IsDescendantOf`

File: dot/state/block.go [hunk 2]
```diff
@@ -444,6 +444,13 @@ func (bs *BlockState) SetFinalizedHash(hash common.Hash, round, setID uint64) er
 			return err
 		}
 
+		if des, err1 := bs.IsDescendantOf(rem, hash); des {
+			if err1 != nil {
+				logger.Error("pruning block error", "error", err)
+			}
+			continue
+		}
```
Comment (noot) [inline dot/state/block.go:452]: I think you can ignore the error here, the only times an error would be returned are if `rem` or `hash` don't exist which should never be the case

**Review by noot — COMMENTED** [review]
could you add a `Copy` function for the blocktree that deep copies it and use that to check `IsDescendantOf`? also, could you update the tests as well?

**Review by RyRy79261 — APPROVED** [review]

**Comment by RyRy79261** [comment]
Ran the tests locally, looks good to me

File: lib/blocktree/blocktree.go (hunk 1 above)
Comment (edwardmack) [reply lib/blocktree/blocktree.go]: I've implemented DeepCopy for BlockTree and for node, but I don't understand where/how it should be used. Please let me know how these should be used.

Comment (noot) [reply lib/blocktree/blocktree.go]: the current code is this, the issue is that `bt.prune` deletes the previous nodes, causing `IsDescendantOf` to fail
```
	pruned := bs.bt.Prune(hash)
	for _, rem := range pruned {
		header, err := bs.GetHeader(rem)
		if err != nil {
			return err
		}

		if des, _ := bs.IsDescendantOf(rem, hash); des {
			continue
		}

		err = bs.DeleteBlock(rem)
		if err != nil {
			return err
		}

		bs.pruneKeyCh <- header
	}
```

instead you could copy the blocktree before pruning, then use the copy to check `IsDescendantOf`
```
        copy := bs.bt.DeepCopy()
	pruned := bs.bt.Prune(hash)
	for _, rem := range pruned {
		header, err := bs.GetHeader(rem)
		if err != nil {
			return err
		}

		if des, _ := copy.IsDescendantOf(rem, hash); des {
			continue
		}

		err = bs.DeleteBlock(rem)
		if err != nil {
			return err
		}

		bs.pruneKeyCh <- header
	}
```

**Review by noot — APPROVED** [review]
