### PR TITLE
fix(storage): Improve get nextkey performance when we have txs

### LINKED ISSUE #3958: fix(lib/runtime/storage): improve `NextKeys` time complexity
### Description

- When the runtime requests the next key under an ongoing transaction we should not use `t.state.Entries()`, this method will go through the entire in-memory trie inserting each key and value in a map to be used to search the next key in lexicographic order. This is not optimal because the trie tends to grow so `t.state.Entries()` is O(n).

- Outside of ongoing transaction the same method searches in the in-memory trie directly which is more efficient since you don't need to search the entire trie but just the path for the next key in lex order

The motivation is explained here: https://github.com/ChainSafe/gossamer/issues/3950#issuecomment-2115938281.

### PR DESCRIPTION
**Pull request by dimartiro**
## Changes

Improve `TrieState` `NextKey` performance by keeping the keys sorted in memory

## Tests

```sh
make test
```

## Issues

closes: https://github.com/ChainSafe/gossamer/issues/3958

## Benchmarks

| Case | time / op | bytes / op | allocs / op |
|--------|--------:|--------:|--------:|
| old implementation | 920289771 ns/op | 993969728 B/op | 11610410 allocs/op |
| new implementation | 1270280 ns/op | 208029 B/op | 12002 allocs/op | 

## Primary Reviewer

@jimjbrettj

### CODE REVIEW

**Review by jimjbrettj — APPROVED** [review]
super nice work here!

File: lib/runtime/storage/storagediff.go [hunk 1]
```diff
@@ -290,3 +296,27 @@ func (cs *storageDiff) applyToTrie(t trie.Trie) {
 
 	}
 }
+
+func (cs *storageDiff) insertSortedKey(key string) {
+	pos := sort.Search(len(cs.sortedKeys), func(i int) bool {
+		return cs.sortedKeys[i] >= key
+	})
```
Comment (EclesioMeloJunior) [inline lib/runtime/storage/storagediff.go]: Given that the list is sorted can we use `slice.BinarySearch` https://pkg.go.dev/slices#BinarySearch

File: lib/runtime/storage/storagediff.go [hunk 2]
```diff
@@ -290,3 +296,27 @@ func (cs *storageDiff) applyToTrie(t trie.Trie) {
...
+
+	cs.sortedKeys = append(cs.sortedKeys, "")
+	copy(cs.sortedKeys[pos+1:], cs.sortedKeys[pos:])
+	cs.sortedKeys[pos] = key
+}
+
+func (cs *storageDiff) removeSortedKey(key string) {
+	pos := sort.Search(len(cs.sortedKeys), func(i int) bool {
+		return cs.sortedKeys[i] >= key
+	})
```
Comment (EclesioMeloJunior) [inline lib/runtime/storage/storagediff.go]: Given that the list is sorted can we use slice.BinarySearch https://pkg.go.dev/slices#BinarySearch

File: lib/runtime/storage/trie.go [hunk 3]
```diff
@@ -176,34 +191,40 @@ func (t *TrieState) NextKey(key []byte) []byte {
...
-
-		for _, k := range keys {
-			if k > string(key) && !currentTx.deletes[k] {
-				return []byte(k)
-			}
+		allSortedKeys := append(t.sortedKeys, currentTx.sortedKeys...)
+		// Find key position
+		pos := sort.Search(len(allSortedKeys), func(i int) bool {
+			return bytes.Compare([]byte(allSortedKeys[i]), key) > 0
+		})
```
Comment (EclesioMeloJunior) [inline lib/runtime/storage/trie.go]: can we use https://pkg.go.dev/slices#BinarySearch?

File: lib/runtime/storage/trie.go [hunk 4]
```diff
@@ -176,34 +191,40 @@ func (t *TrieState) NextKey(key []byte) []byte {
...
-
-		keys := maps.Keys(allEntries)
-		sort.Strings(keys)
-
-		for _, k := range keys {
-			if k > string(key) && !currentTx.deletes[k] {
-				return []byte(k)
-			}
+		allSortedKeys := append(t.sortedKeys, currentTx.sortedKeys...)
+		// Find key position
```
Comment (EclesioMeloJunior) [inline lib/runtime/storage/trie.go:196]: How do you check if the key is not in the `delete` set?

File: lib/runtime/storage/trie.go [hunk 5]
```diff
@@ -447,32 +504,23 @@ func (t *TrieState) GetChildNextKey(keyToChild, key []byte) ([]byte, error) {
...
-			if err != nil {
-				// Child trie does not exists and won't exists in the future
-				if len(allEntries) == 0 {
-					return nil, err
-				}
-			} else {
-				allEntries = child.Entries()
+			allSortedKeys := append(t.childSortedKeys[string(keyToChild)], childChanges.sortedKeys...)
+			// Find key position
+			pos := sort.Search(len(allSortedKeys), func(i int) bool {
```
Comment (EclesioMeloJunior) [inline lib/runtime/storage/trie.go]: can we use `slices.BinarySearch`?

**Review by EclesioMeloJunior — CHANGES_REQUESTED** [review]

File: lib/runtime/storage/storagediff.go (hunk 1 above)
Comment (dimartiro) [reply lib/runtime/storage/storagediff.go]: Yeah I thought that `sort.Search` and `slice.BinarySearch` were equivalent. But I'll change it! thks

File: lib/runtime/storage/trie.go (hunk 4 above)
Comment (dimartiro) [reply lib/runtime/storage/trie.go:196]: We don't need to do that since we are removing them from the `sortedKeys` list when we remove keys from the trie.

**Review by edwardmack — APPROVED** [review]
Nice work.

**Review by EclesioMeloJunior — APPROVED** [review]

File: lib/runtime/storage/trie.go [hunk 6]
```diff
@@ -176,34 +192,41 @@ func (t *TrieState) NextKey(key []byte) []byte {
...
+		}
 
-		for _, k := range keys {
-			if k > string(key) && !currentTx.deletes[k] {
-				return []byte(k)
-			}
+		// Get next key based on that position
+		if pos < len(allSortedKeys) {
+			k := allSortedKeys[pos]
+			return []byte(k)
```
Comment (P1sar) [inline lib/runtime/storage/trie.go:205]: I saw that we are sever times doing string(k) when adding to keys and []byte(k)when returning, maybe can jsut make sortedKeys to by array of byte arrays

Comment (dimartiro) [reply lib/runtime/storage/trie.go:205]: Yes we have a "problem" with the keys because they are `[]bytes` but slices in golang doesn't implement `cmp.Ordered` so we need to use `string` for that.
For example, if I change `sortedKeys` to a `[][]byte` we wont be able to use `slices.BinarySearch` since it expects a `cmp.Ordered` https://pkg.go.dev/slices#BinarySearch
Something similar happens when we need to add the keys to a map, the map keys should be comparable and we need to define the map as `map[string]T` for that 😞

**Review by P1sar — APPROVED** [review]
