### PR TITLE
fix/cli: use default log values from config

### LINKED ISSUE #3403: logs are not being set in the generated `config.toml`
## Describe the bug

- In the `chain/westend/defaults.go` in the `DefaultConfig()` function I set the log levels to be `trace` for some packages

```
func DefaultConfig() *cfg.Config {
  config := cfg.DefaultConfig()
  ...
  config.Log.Sync = "trace"
  config.Log.Digest = "trace"
  config.Log.State = "trace"
  ...
  return config
}
```

But in the generated `config.toml` those packages log levels appears with info level:

```
#######################################################
###              Log Configuration Options          ###
#######################################################
[log]

# One of: crit, error, warn, info, debug, trace
# Defaults to "info"

# Core module log level
core = "info"

# Digest module log level
digest = "info"

# Sync module log level
sync = "info"

# Network module log level
network = "info"

# RPC module log level
rpc = "info"

# State module log level
state = "info"

# Runtime module log level
runtime = "info"

# BABE module log level
babe = "info"

# GRANDPA module log level
grandpa = "info"

# WASM module log level
wasmer = "info"
```

But it works fine if I use the `--log` flag, for example:

```
gossamer --chain westend --log sync=trace,state=trace
```

Then the `config.toml` reflects the flag log level values

## Expected Behavior

- The generated `config.toml` should reflect the values from the `defaults.go` if there is no flag

## Specification

- go version: go 1.20.1
- gossamer version: development branch
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

### PR DESCRIPTION
**Pull request by kanishkatn**
## Changes

Fixes `parseLogLevel` method in the CLI.

## Issues

closes #3403 

## Primary Reviewer

@EclesioMeloJunior

### CODE REVIEW

File: chain/westend/defaults.go [hunk 1]
```diff
@@ -29,6 +29,7 @@ func DefaultConfig() *cfg.Config {
 	config.Core.GrandpaAuthority = false
 	config.Core.Role = 1
 	config.Network.NoMDNS = false
+	config.Log.Babe = "error"
```
Comment (EclesioMeloJunior) [inline chain/westend/defaults.go:32]:
```suggestion
```

**Review by EclesioMeloJunior — CHANGES_REQUESTED** [review]

File: chain/westend/defaults.go (hunk 1 above)
Comment (kanishkatn) [reply chain/westend/defaults.go:32]: Yeah, I thought I did. Thank you!

**Review by EclesioMeloJunior — APPROVED** [review]

**Review by dimartiro — APPROVED** [review]

**Review by edwardmack — APPROVED** [review]
