### PR TITLE
dot/rpc implement state_subscribeStorage RPC WebSocket method

### LINKED ISSUE #969: Implement State Subscribe Storage Websocket
## Expected Behavior

- Implement State Subscribe Storage Websocket

## Current Behavior

-

## Possible Solution

-

## Steps to Reproduce

1.
2.
3.
4.

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

### PR DESCRIPTION
**Pull request by edwardmack**
## Changes

- Implement state_subscribeStorage RPC WebSocket method: Storage subscription. If storage keys are specified, it creates a message for each block which changes the specified storage keys. If none are specified, then it creates a message for every block. see https://github.com/w3f/PSPs/blob/psp-rpc-api/psp-002.md#state_subscribestorage-pubsub 

## Tests

```
go test ./dot/rpc/...
``` 
OR connect a websocket client to node and send request:
```
{
    "jsonrpc": "2.0",
    "method": "state_subscribeStorage",
    "params": [],
    "id": 1
}
```

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [x] I have reviewed my own pull request before requesting a review
- [x] All integration tests and required coverage checks are passing

## Issues

- closes #969

### CODE REVIEW

**Comment by edwardmack** [comment]
I see that code climate is complaining, let me know if you want me to refactor.

File: dot/rpc/modules/state.go [hunk 1]
```diff
@@ -285,9 +285,11 @@ func (sm *StateModule) SubscribeRuntimeVersion(r *http.Request, req *StateStorag
 	return sm.GetRuntimeVersion(r, nil, res)
 }
 
-// SubscribeStorage isn't implemented properly yet.
-func (sm *StateModule) SubscribeStorage(r *http.Request, req *StateStorageQueryRangeRequest, res *StorageChangeSetResponse) {
-	// TODO implement change storage trie so that block hash parameter works (See issue #834)
+// SubscribeStorage Storage subscription. If storage keys are specified, it creates a message for each block which
+//  changes the specified storage keys. If none are specified, then it creates a message for every block.
+//  This endpoint communicates over the Websockt protocol, but this func should remain here so it's added to rpc_methods list
```
Comment (noot) [inline dot/rpc/modules/state.go:290]: *websocket

File: dot/rpc/modules/state.go [hunk 2]
```diff
@@ -285,9 +285,11 @@ func (sm *StateModule) SubscribeRuntimeVersion(r *http.Request, req *StateStorag
...
+func (sm *StateModule) SubscribeStorage(r *http.Request, req *StateStorageQueryRangeRequest, res *StorageChangeSetResponse) error {
```
Comment (noot) [inline dot/rpc/modules/state.go:291]: I'm also wondering, is there an unsubscribe method corresponding to the subscribe methods?

File: dot/rpc/websocket.go [hunk 3]
```diff
@@ -191,12 +192,18 @@ func (h *HTTPServer) ServeHTTP(w http.ResponseWriter, r *http.Request) {
...
+	for _, param := range pA {
+		filter[param.(string)] = true
+	}
 	wss := &WebSocketSubscription{
 		WSConnection:     conn,
 		SubscriptionType: subscriptionType,
+		Filter:           filter,
 	}
 	wssub[sub] = wss
 	h.serverConfig.WSSubscriptions = wssub
```
Comment (noot) [inline dot/rpc/websocket.go:209]: the WSSubscriptions should be stored in the HTTPServer struct (or in a separate wsServer struct) not in the config

File: dot/rpc/websocket.go [hunk 4]
```diff
@@ -233,3 +240,36 @@ func (h *HTTPServer) blockReceivedListener() {
...
+	if h.serverConfig.StorageAPI == nil {
+		return
+	}
+
+	for change := range h.storageChan {
+
+		if change != nil {
+			for i, sub := range h.serverConfig.WSSubscriptions {
+				if sub.SubscriptionType == SUB_STORAGE {
+					// check it change key is in subscription filter
```
Comment (noot) [inline dot/rpc/websocket.go:254]: check if*

File: dot/state/storage.go [hunk 5]
```diff
@@ -120,7 +125,18 @@ func (s *StorageState) EnumeratedTrieRoot(values [][]byte) {
 func (s *StorageState) SetStorage(key []byte, value []byte) error {
 	s.lock.Lock()
 	defer s.lock.Unlock()
-	return s.trie.Put(key, value)
+	kv := &KeyValue{
+		Key:   key,
+		Value: value,
+	}
+	//fmt.Printf("SetStorage Key: %x Value: %x\n", key, value)
```
Comment (noot) [inline dot/state/storage.go:132]: remove?

File: dot/state/storage.go [hunk 6]
```diff
@@ -120,7 +125,18 @@ func (s *StorageState) EnumeratedTrieRoot(values [][]byte) {
...
+	// TODO ed add channel notify here
```
Comment (noot) [inline dot/state/storage.go:133]: is this done?

Comment (noot) [reply dot/state/storage.go:133]: should also be added to `ClearStorage`

File: dot/rpc/websocket.go [hunk 7]
```diff
@@ -233,3 +240,36 @@ func (h *HTTPServer) blockReceivedListener() {
...
+
+func (h *HTTPServer) storageChangeListener() {
+	if h.serverConfig.StorageAPI == nil {
+		return
+	}
+
+	for change := range h.storageChan {
+
+		if change != nil {
+			for i, sub := range h.serverConfig.WSSubscriptions {
```
Comment (noot) [inline dot/rpc/websocket.go:252]: I'm wondering if it would be simpler to start a goroutine for each subscription, what do you think?

File: dot/state/storage.go (hunk 6 above)
Comment (edwardmack) [reply dot/state/storage.go:133]: Yes

File: dot/rpc/websocket.go (hunk 7 above)
Comment (edwardmack) [reply dot/rpc/websocket.go]: Yes, I've refactor websockets to better handle this.

**Comment by edwardmack** [comment]
I've updated this, it's ready for another look.  Let me know your thoughts.

File: dot/rpc/http.go [hunk 8]
```diff
@@ -56,13 +54,18 @@ type HTTPServerConfig struct {
...
 
-// WebSocketSubscription holds subscription details
-type WebSocketSubscription struct {
-	WSConnection     *websocket.Conn
-	SubscriptionType int
+// WSConn struct to hold WebSocket Connection references
+type WSConn struct {
+	wsconn             *websocket.Conn
+	mu                 sync.Mutex
+	serverConfig       *HTTPServerConfig
```
Comment (noot) [inline dot/rpc/http.go:63]: does this need the whole server config? or just the state interfaces?

File: dot/rpc/http.go [hunk 9]
```diff
@@ -56,13 +54,18 @@ type HTTPServerConfig struct {
...
+	logger             log.Logger
```
Comment (noot) [inline dot/rpc/http.go:64]: might be nice to make the logger global to the rpc package

File: dot/rpc/websocket.go [hunk 10]
```diff
@@ -83,152 +80,281 @@ type ErrorMessageJSON struct {
...
+	return scl.subID, nil
 }
 
-func (h *HTTPServer) blockReceivedListener() {
-	if h.serverConfig.BlockAPI == nil {
-		return
+// Listen implementation of Listen interface to listen for channel changes
+func (l *StorageChangeListener) Listen() {
+	for change := range l.channel {
+		if change != nil {
```
Comment (noot) [inline dot/rpc/websocket.go:287]: nitpick but it might be nice to do
```
if change == nil {
    continue
}

// check if change key .... 
```

same for below

File: dot/rpc/http.go (hunk 8 above)
Comment (edwardmack) [reply dot/rpc/http.go:63]: No just BlockAPI and StorageAPI, I've updated.

File: dot/rpc/http.go (hunk 9 above)
Comment (edwardmack) [reply dot/rpc/http.go:64]: good idea.
