### PR TITLE
fix(lib/grandpa): avoid spamming round messages

### LINKED ISSUE #2700: avoid sending messages in wrong sub-rounds
### Description

1. Split `sendVoteMessage` into two related functions, `sendPrevoteMessage` which will gossip prevote messages to peers until gossamer receive enough prevotes messages and `sendPrecommitMessage` which will waits for sendPrevoteMessage finish to start sending the precommit messages
2. The function `determinePrecommit` should wait for enough prevotes before determine a precommit vote
3. Split the function `sendNeighbourMessage` into `notifyNeighbor` and `sendNeighborMessage`, we should send a neighbor message to other peers every time we move to the next round or at least every 5 minutes (following the host spec), so every time we finalize a block we call the `sendNeighborMessage` and then reset the timer in the `notifyNeighbor`\

- Related to #2505

### PR DESCRIPTION
**Pull request by EclesioMeloJunior**
## Changes

1. Introduces the service pattern `lib/grandpa/engine.go`:
- GRANDPA counts with 2 mains services (`finalizationEngine`, `handleVotingRound`) and 1 orchestrator service (`finalizationHandler`)
- `finalizationEngine`: is responsible for deciding when the node does the voting, it owns the `determinePrevoteTimer`, `determinePrecommitTimer` and once the node does a pre-commit it starts attempting to finalize checking the vote thresholds, this engine ends once a valid commit message arrives.

- `handleVotingRound`: holds a channel from the finalization engine and is responsible for executes actions (`determinePrevote`, `determinePrecommit`, `finalize`, `alreadyFinalized`) based on messages sent through the finalization engine channel

- `finalizationHandler`: holds both previous services and is responsible for initiating the current round, bootstrapping both services, and waiting for them to finish to proceed to the next round. This service exposes an `observableErrs`, which is a fanout channel that aggregates errors from `finalizationEngine` and `handleVotingRound`, the caller can listen and handle those errors.

## Tests

```
go test github.com/ChainSafe/gossamer/lib/grandpa
```

Currently, the GRANDPA test suite at the development branch takes `234.980s` while in this branch the GRANDPA test suite takes `154.471s` a reduction of `80,5s` and in a branch called `eclesio/add/grandpa-paralell-tests` where I included `t.Parallel()` to all GRANDPA tests, it takes `115.824s` a reduction of `119,15s` from the development branch.

## Issues

- Closes #2700

## Primary Reviewer

@timwu20

### CODE REVIEW

File: lib/grandpa/network.go [hunk 1]
```diff
@@ -174,39 +174,43 @@ func (s *Service) sendMessage(msg GrandpaMessage) error {
 	return nil
 }
 
-func (s *Service) sendNeighbourMessage(interval time.Duration) {
+// notifyNeighbor will gossip a NeighbourMessage every 5 minutes, however we reset the ticker
+// whenever a finalisation occur meaning that a neighbour message already was sent by s.initiateRound()
+func (s *Service) notifyNeighbor(interval time.Duration) {
```
Comment (timwu20) [inline lib/grandpa/network.go:179]: can you move `interval` as an attribute of the `Service`. You can set it as `neighbourMessageInterval` in the constructor for `Service`.

File: lib/grandpa/network.go [hunk 2]
```diff
@@ -174,39 +174,43 @@ func (s *Service) sendMessage(msg GrandpaMessage) error {
...
 			}
-		}
+			s.roundLock.Unlock()
 
-		cm, err := s.neighbourMessage.ToConsensusMessage()
-		if err != nil {
-			logger.Warnf("failed to convert NeighbourMessage to network message: %s", err)
-			continue
+			s.sendNeighborMessage(nm)
+		case <-s.finalisedCh:
```
Comment (timwu20) [inline lib/grandpa/network.go:198]: Maybe we can end this goroutine and spawn a new one every time with supplied `round`, `setID` and `head` parameters when we receive something on `finalisedCh`.  That's the more event driven way.  There may be some overlap of messages, but I would assume that's expected.  Or we could explicitly cancel any existing goroutines running `notifyNeighbour`.

File: lib/grandpa/grandpa.go [hunk 3]
```diff
@@ -501,25 +506,15 @@ func (s *Service) playGrandpaRound() error {
...
-
-	logger.Debug("receiving pre-commit messages...")
-	// through goroutine s.receiveVoteMessages(ctx)
-	time.Sleep(s.interval)
+	prevoteRoundComplete := make(chan struct{})
+	go s.sendPrevoteMessage(vm, prevoteRoundComplete)
 
 	if s.paused.Load().(bool) {
 		return ErrServicePaused
 	}
```
Comment (timwu20) [inline lib/grandpa/grandpa.go:514]: what is this? this function could return early if what is returned by `s.paused.Load()` is a bool that `== true`? Shouldn't we cancel any running goroutines for this round?

File: lib/grandpa/grandpa.go [hunk 4]
```diff
@@ -501,25 +506,15 @@ func (s *Service) playGrandpaRound() error {
...
 
-	// broadcast pre-commit
+	// determine and broadcast pre-commit only after seen prevote messages
+	<-prevoteRoundComplete
```
Comment (timwu20) [inline lib/grandpa/grandpa.go:517]: not sure why line 510 needs to be run in a goroutine if we are immediately waiting for it.

File: lib/grandpa/grandpa.go [hunk 5]
```diff
@@ -501,25 +506,15 @@ func (s *Service) playGrandpaRound() error {
...
-	// explicitly send a value.
-	defer close(roundComplete)
-
-	// continue to send prevote messages until round is done
-	go s.sendVoteMessage(prevote, vm, roundComplete)
-
-	logger.Debug("receiving pre-commit messages...")
-	// through goroutine s.receiveVoteMessages(ctx)
-	time.Sleep(s.interval)
+	prevoteRoundComplete := make(chan struct{})
```
Comment (timwu20) [inline lib/grandpa/grandpa.go:509]: ideally the `done` chan should be instantiated and returned by the writing function to the channel.

**Review by timwu20 — CHANGES_REQUESTED** [review]

File: lib/grandpa/network.go (hunk 1 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/network.go:179]: This `interval` is different, the `interval` in the `Service` is the amount of time we wait to send messages in the stages of the round (around 1 sec) and the interval in the `notifyNeighbor` is around 5 min and we should send a neighbor message every round change or at least 5 min following the docs

File: lib/grandpa/grandpa.go [hunk 6]
```diff
@@ -478,7 +484,6 @@ func (s *Service) playGrandpaRound() error {
 		return err
 	}
 
-	logger.Debug("receiving pre-vote messages...")
 	go s.receiveVoteMessages(ctx)
```
[the remark this answers is not in the document]
Comment (qdm12) [reply lib/grandpa/grandpa.go:487]: Also that context is just `s.ctx` really, we misused context wrapping in that function.
And yeah a `stopCh <-chan struct{}` would most likely achieve the same thing (unless libraries take in a context, but not the case here)

**Comment by EclesioMeloJunior** [comment]
I've removed most of the channels and now we rely on the votes collected through `receiveVoteMessages`, so basically, we do:

- Start listening to votes from other peers
- Determine the prevote and start sending it
- Once we reach the prevote threshold we release the `determinePrecommitCh` which will 
  - allow the node to produce the `pre-commit` vote
  - stop the `sendPrevoteMessage` goroutine 
  - start the `sendPrecommitMessage` goroutine
- Once we reach the finalization threshold we will
  - stop the `sendPrecommitMessage` goroutine
  - send the `commitMessage` and notify the telemetry
  - start next round

@timwu20 what do you think of this workflow?

**Comment by EclesioMeloJunior** [comment]
Currently, `attemptToFinalize` method runs until we got enough pre-commit messages in the following way:

```go
func (s *Service) attemptToFinalize() error {
  ticker := time.NewTicker(s.interval / 100)
  var (
    bestFinalCandidate *types.GrandpaVote
    precommitCount     uint64
  )
  for {
    select {
      case <-s.ctx.Done():
        return errors.New("context cancelled")
      case <-ticker.C:
    }
    ... code to check if we got enough precommits
  }

```

I believe we can transform it into a more reactive relying on the `receiveVoteMessages` rather than pulling the number of votes every `time.NewTicker(s.interval / 100)`. So every time we receive a vote message we check if we reached the pre-commit threshold and then finalize the block and jump into the next round, check `vote_message.go`

File: lib/grandpa/grandpa.go [hunk 7]
```diff
@@ -529,124 +518,59 @@ func (s *Service) playGrandpaRound() error {
...
 
 	// Though this looks like we are sending messages multiple times,
 	// caching would make sure that they are being sent only once.
 	for {
-		if s.paused.Load().(bool) {
+		select {
+		case <-ticker.C:
+		case <-isFinalizable:
 			return
 		}
```
Comment (noot) [inline lib/grandpa/grandpa.go:545]: do we need the for loop here still? comment is a bit sus too (i know it works but still lol)

File: lib/grandpa/grandpa.go [hunk 8]
```diff
@@ -529,124 +518,59 @@ func (s *Service) playGrandpaRound() error {
...
+func (s *Service) sendPrevoteMessage(vm *VoteMessage, determinePrecommitCh <-chan struct{}) {
+	logger.Debugf("sending pre-vote message %s...", vm)
+
+	ticker := time.NewTicker(s.interval * 4)
+	defer ticker.Stop()
 
+	// Though this looks like we are sending messages multiple times,
+	// caching would make sure that they are being sent only once.
 	for {
 		select {
```
Comment (noot) [inline lib/grandpa/grandpa.go:563]: same here

File: lib/grandpa/grandpa.go [hunk 9]
```diff
@@ -962,7 +886,8 @@ func (s *Service) getPreVotedBlock() (Vote, error) {
 
 	// if there are multiple, find the one with the highest number and return it
 	highest := Vote{
-		Number: uint32(0),
+		Hash:   s.head.Hash(),
+		Number: uint32(s.head.Number),
 	}
```
Comment (noot) [inline lib/grandpa/grandpa.go:891]: we don't need to set this because `blocks > 0` so the `highest` will definitely be set in the next for loop

File: lib/grandpa/grandpa.go [hunk 10]
```diff
@@ -1006,7 +931,8 @@ func (s *Service) getGrandpaGHOST() (Vote, error) {
...
```
Comment (noot) [inline lib/grandpa/grandpa.go:936]: same here

File: lib/grandpa/vote_message.go [hunk 11]
```diff
@@ -70,13 +61,129 @@ func (s *Service) receiveVoteMessages(ctx context.Context) {
...
+				fmt.Sprint(vm.Message.Number),
+				vm.Message.AuthorityID.String(),
+			),
+		)
+	default:
+		logger.Warnf("unsupported stage %s", vm.Message.Stage.String())
+	}
+}
+
+// attemptToFinalize loops until the round is finalisable
```
Comment (noot) [inline lib/grandpa/vote_message.go:116]: change comment, this doesn't loop

File: lib/grandpa/vote_message.go [hunk 12]
```diff
@@ -70,13 +61,129 @@ func (s *Service) receiveVoteMessages(ctx context.Context) {
 					"prevote count %d, precommit count %d, votes needed %d",
 				v, vm.Message.AuthorityID, vm.Round, vm.Message.Stage,
 				s.lenVotes(prevote), s.lenVotes(precommit), s.state.threshold()+1)
+
+			// when a given vote is validated we should check
+			// if we have reached the prevotes threshold
+			prevotesThreshold := s.lenVotes(prevote) - 1
+			if !prevotesThresholdReached && prevotesThreshold >= int(threshold) {
+				prevotesThresholdReached = true
+				determinePrecommitCh <- struct{}{}
```
Comment (noot) [inline lib/grandpa/vote_message.go:70]: why not just close the channel?

**Review by noot — COMMENTED** [review]
overall the flow looks reasonable, just some smaller comments!

File: lib/grandpa/vote_message.go (hunk 12 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/vote_message.go:70]: It is possible to close the channel here but I believe is not the right choice because moving the `close(ch)` here we should remove the `defer close(ch)` and in a case where we should exit the `receiveVoteMessages` method without the condition was reached then the channel will keep open.

File: lib/grandpa/grandpa.go (hunk 9 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/grandpa.go:891]: I would like to remove the `waitForFirstBlock` method as it is normal to gossip votes for the genesis block, that being said if we do not set the infos so when we call the method `getGrandpaGHOST` and the `len(blocks) > 0` the following problem happens:

```go
// blocks -> map[hash]uint32
blocks := { 0xABC: 0 }

// Without setting
// -------

highest := Vote {Number: uint32(0)}
for h, n := range blocks {
  // this condition will never happens as 0 > 0 is false 
  // and then the highest will have an empty hash
  if n > highest.Number {...}
}

// Setting latest finalized info
// -------

highest := Vote {Hash: s.head.Hash(), Number: uint32(s.head.Number)}
for h, n := range blocks {
  // this condition will never happens as 0 > 0 is false 
  // but we still have informations in the highest in a case where there is no highest blocks
  if n > highest.Number {...}
}
```

I think that we should set the highest as the latest finalized block (aka `s.head.Hash()` and `s.head.Number`) and then compare it with the incoming possible selected blocks, that way we avoid choosing a block that is before the latest finalized block as well. what do you think?

File: lib/grandpa/grandpa.go (hunk 10 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/grandpa.go:936]: See https://github.com/ChainSafe/gossamer/pull/2688#discussion_r949215646

**Review by timwu20 — COMMENTED** [review]
Took a stab at trying clear up `playGrandpaRound` in another [PR](https://github.com/ChainSafe/gossamer/pull/2761)

Let me know if you wanna sync up about it.

File: lib/grandpa/grandpa.go [hunk 13]
```diff
@@ -466,8 +466,13 @@ func (s *Service) primaryBroadcastCommitMessage() {
 // playGrandpaRound executes a round of GRANDPA
 // at the end of this round, a block will be finalised.
 func (s *Service) playGrandpaRound() error {
+	if s.paused.Load().(bool) {
```
[the remark this answers is not in the document]
Comment (qdm12) [reply lib/grandpa/grandpa.go:442]: Counter-intuitively, `bool` isn't atomic. They even added an `atomic.Bool` in Go 1.19 https://tip.golang.org/doc/go1.19#atomic_types

File: lib/grandpa/vote_message.go [hunk 14]
```diff
@@ -23,58 +22,169 @@ type networkVoteMessage struct {
...
+						"prevote count %d, precommit count %d, votes needed %d",
+					v, vm.Message.AuthorityID, vm.Round, vm.Message.Stage,
+					s.lenVotes(prevote), s.lenVotes(precommit), s.state.threshold()+1)
+
+				// when a given vote is validated we should check
+				// if we have reached the prevotes threshold
+				prevotesThreshold := s.lenVotes(prevote) - 1
+				if !prevotesThresholdReached && prevotesThreshold >= int(threshold) {
+					prevotesThresholdReached = true
+					determinePrecommitCh <- struct{}{}
```
Comment (EclesioMeloJunior) [inline lib/grandpa/vote_message.go:87]: Explaining why I don't close the round here:

In the `playGrandpaRound` we have this blocking loop where we wait for one of 3 channels:
1. context closure then we exit the function
2. Enough pre-votes then we should determine and send our precommit
3. Round is finalizable means we reach enough amount or pre-commits or we received a valid commit message that finalizes a block for the current round

```go
for {
  select {
    case <-s.ctx.Done():
      return nil
    case <-determinePrecommit:
      ...
      go s.sendPrecommitMessage(pcm, cancel)
    case <-finalizable:
      // send the commit message and jump into the next round		
  }
}
```

Specifically, the second case is controlled here where we check if we reach the amount of pre-votes needed to determine our pre-commit, and the point is: if we close the channel instead of just passing and empty `struct{}` then in our loop we will always trigger the second channel since closed channels are always good to read unless you check `_, ok := <-channel` the closed property

```go
prevotesThreshold := s.lenVotes(prevote) - 1
if !prevotesThresholdReached && prevotesThreshold >= int(threshold) {
  prevotesThresholdReached = true
  // determinePrecommitCh <- struct{}
  close(determinePrecommitCh)
}
```

File: lib/grandpa/grandpa.go [hunk 15]
```diff
@@ -1297,3 +1209,192 @@ func (s *Service) lenVotes(stage Subround) int {
...
+	}
+
+	highestFinalizedHeader, err := blockState.GetHighestFinalisedHeader()
+	if err != nil {
+		return fmt.Errorf("getting highest finalised header: %w", err)
+	}
+
+	isDescendant, err := blockState.IsDescendantOf(highestFinalizedHeader.Hash(), fm.Vote.Hash)
+	if err != nil {
+		return fmt.Errorf("cannot verify ancestry of highest finalised block: %w", err)
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1296]: nit

```suggestion
		return fmt.Errorf("verifying ancestry of highest finalised block: %w", err)
```

File: lib/grandpa/grandpa.go [hunk 16]
```diff
@@ -1297,3 +1209,192 @@ func (s *Service) lenVotes(stage Subround) int {
...
+	}
+
+	if !isDescendant {
+		return errVoteBlockMismatch
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1300]: nit

```suggestion
		return fmt.Errorf("%w: vote hash %s and highest finalised header %s",
			errVoteBlockMismatch, fm.Vote.Hash, highestFinalizedHeader.Hash())
```

File: lib/grandpa/grandpa.go [hunk 17]
```diff
@@ -1297,3 +1209,192 @@ func (s *Service) lenVotes(stage Subround) int {
...
+	}
+
+	eqvVoters := getEquivocatoryVoters(fm.AuthData)
+	var count int
+	for i, pc := range fm.Precommits {
+		just := &SignedVote{
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1306]: nit `justification` would be nicer

File: lib/grandpa/grandpa.go [hunk 18]
```diff
@@ -1297,3 +1209,192 @@ func (s *Service) lenVotes(stage Subround) int {
...
+			Vote:        pc,
+			Signature:   fm.AuthData[i].Signature,
+			AuthorityID: fm.AuthData[i].AuthorityID,
+		}
+
+		err := verifyJustification(just, fm.Round, setID, precommit, authorities)
+		if err != nil {
+			logger.Errorf("failed to verify justification for vote from authority id %s, for block hash %s: %s",
+				just.AuthorityID.String(), just.Vote.Hash, err)
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1315]: nit ideally `err` should contain the justification authorityID and vote hash already?

File: lib/grandpa/grandpa.go [hunk 19]
```diff
@@ -1297,3 +1209,192 @@ func (s *Service) lenVotes(stage Subround) int {
...
+	// ensure the persistence of informations
+	// and then notify the grandpa service about
+	// a received commit message
+	s.receivedCommit <- msg
+
+	// TODO: re-add catch-up logic (#1531)
+	return nil
+}
+
+func verifyCommitMessageJustification(fm *CommitMessage, setID uint64, threshold uint64,
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1278]: nit what does the `f` stand in `fm`? Shouldn't it be `commitMessage` instead?

File: lib/grandpa/grandpa.go [hunk 20]
```diff
@@ -1297,3 +1209,192 @@ func (s *Service) lenVotes(stage Subround) int {
...
+
+		isDescendant, err := blockState.IsDescendantOf(fm.Vote.Hash, just.Vote.Hash)
+		if err != nil {
+			logger.Warnf("could not check for descendant: %s", err)
+			continue
+		}
+
+		precommitedHeader, err := blockState.GetHeader(pc.Hash)
+		if err != nil {
+			return fmt.Errorf("getting header of %s: %w", pc.Hash.Short(), err)
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1327]: the `pc.Hash` information should be wrapped inside `GetHeader`, not here

```suggestion
			return fmt.Errorf("getting header: %w", err)
```

File: lib/grandpa/grandpa.go [hunk 21]
```diff
@@ -1297,3 +1209,192 @@ func (s *Service) lenVotes(stage Subround) int {
...
+		}
+
+		if precommitedHeader.Number != uint(pc.Number) {
+			return fmt.Errorf("%w: expected number %d from header but got number %d",
+				ErrBlockHashMismatch, precommitedHeader.Number, pc.Number)
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1332]: Isn't it `ErrBlockNumberMismatch` instead here?

File: lib/grandpa/grandpa.go [hunk 22]
```diff
@@ -1297,3 +1209,192 @@ func (s *Service) lenVotes(stage Subround) int {
...
+			count++
+		}
+	}
+
+	// confirm total # signatures >= grandpa threshold
+	if uint64(count)+uint64(len(eqvVoters)) < threshold {
+		logger.Debugf(
+			"minimum votes not met for finalisation message. Need %d votes and received %d votes.",
+			threshold, count)
+		return ErrMinVotesNotMet
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1349]: just return an error with the context instead of debug logging it.

```suggestion
		return fmt.Errorf("%w: for finalisation message; need %d votes but received only %d votes",
			ErrMinVotesNotMet, threshold, uint64(count)+uint64(len(eqvVoters)))
```

File: lib/grandpa/grandpa.go [hunk 23]
```diff
@@ -1297,3 +1209,192 @@ func (s *Service) lenVotes(stage Subround) int {
...
+	stage Subround, authorities []*types.Authority) error {
+	// verify signature
+	msg, err := scale.Marshal(FullVote{
+		Stage: stage,
+		Vote:  just.Vote,
+		Round: round,
+		SetID: setID,
+	})
+	if err != nil {
+		return err
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1366]:
```suggestion
		return fmt.Errorf("scale encoding full vote: %w", err)
```

File: lib/grandpa/grandpa.go [hunk 24]
```diff
@@ -1297,3 +1209,192 @@ func (s *Service) lenVotes(stage Subround) int {
...
+	}
+
+	pk, err := ed25519.NewPublicKey(just.AuthorityID[:])
+	if err != nil {
+		return err
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1371]:
```suggestion
		return fmt.Errorf("creating ed25519 public key: %w", err)
```

File: lib/grandpa/grandpa.go [hunk 25]
```diff
@@ -1297,3 +1209,192 @@ func (s *Service) lenVotes(stage Subround) int {
...
+	}
+
+	ok, err := pk.Verify(msg, just.Signature[:])
+	if err != nil {
+		return err
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1376]:
```suggestion
		return fmt.Errorf("verifying signature: %w", err)
```

File: lib/grandpa/grandpa.go [hunk 26]
```diff
@@ -1297,3 +1209,192 @@ func (s *Service) lenVotes(stage Subround) int {
...
+	}
+
+	if !ok {
+		return ErrInvalidSignature
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1380]:
```suggestion
		return fmt.Errorf("%w: %v for message %v", ErrInvalidSignature, just.Signature, msg)
```

File: lib/grandpa/grandpa.go [hunk 27]
```diff
@@ -1297,3 +1209,192 @@ func (s *Service) lenVotes(stage Subround) int {
...
+
+	// verify authority in justification set
+	authFound := false
+
+	for _, auth := range authorities {
+		justKey, err := just.AuthorityID.Encode()
+		if err != nil {
+			return err
+		}
+		if reflect.DeepEqual(auth.Key.Encode(), justKey) {
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1391]:
```suggestion
		if bytes.Equal(auth.Key.Encode(), justKey) {
```

File: lib/grandpa/grandpa.go [hunk 28]
```diff
@@ -1297,3 +1209,192 @@ func (s *Service) lenVotes(stage Subround) int {
...
+	}
+
+	// verify authority in justification set
+	authFound := false
+
+	for _, auth := range authorities {
+		justKey, err := just.AuthorityID.Encode()
+		if err != nil {
+			return err
+		}
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1390]: Move this outside the for loop, no point re-encoding the same thing multiple times.

File: lib/grandpa/grandpa.go [hunk 29]
```diff
@@ -1297,3 +1209,192 @@ func (s *Service) lenVotes(stage Subround) int {
...
+		if reflect.DeepEqual(auth.Key.Encode(), justKey) {
+			authFound = true
+			break
+		}
+	}
+	if !authFound {
+		return fmt.Errorf("%w", ErrVoterNotFound)
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1397]:
```suggestion
		return fmt.Errorf("%w: for justification key %v", ErrVoterNotFound, justKey)
```

File: lib/grandpa/message.go [hunk 30]
```diff
@@ -56,6 +56,10 @@ type VoteMessage struct {
 	Message SignedMessage
 }
 
+func (v VoteMessage) String() string {
+	return fmt.Sprintf("round=%d, setID=%d, message=%s", v.Round, v.SetID, v.Message)
```
Comment (qdm12) [inline lib/grandpa/message.go:60]: nit since message is itself a struct, maybe wrap it with braces:

```suggestion
	return fmt.Sprintf("round=%d, setID=%d, message={%s}", v.Round, v.SetID, v.Message)
```

File: lib/grandpa/round_test.go [hunk 31]
```diff
@@ -216,388 +218,775 @@ func TestGrandpa_DifferentChains(t *testing.T) {
...
+				branches := map[uint]int{2: 1}
+				const baseLenght = 4
+				state.AddBlocksToStateWithFixedBranches(t, blockState.(*state.BlockState), baseLenght, branches)
+			},
+		},
+	}
+
+	for tname, tt := range tests {
+		tt := tt
+		t.Run(tname, func(t *testing.T) {
```
Comment (qdm12) [inline lib/grandpa/round_test.go:302]: nit can we run subtests in parallel? 🤔 

```suggestion
		t.Run(tname, func(t *testing.T) {
			t.Parallel()
```

File: lib/grandpa/round_test.go [hunk 32]
```diff
@@ -216,388 +218,775 @@ func TestGrandpa_DifferentChains(t *testing.T) {
...
+				defer cancel()
+
+				st := newTestState(t)
+				grandpaServices[idx] = &Service{
+					ctx:          ctx,
+					cancel:       cancel,
+					paused:       atomic.Value{},
+					blockState:   st.Block,
+					grandpaState: st.Grandpa,
+					//defined as in the grandpa service
```
Comment (qdm12) [inline lib/grandpa/round_test.go:327]: supermeganit 
```suggestion
					// defined as in the grandpa service
```

File: lib/grandpa/round_test.go [hunk 33]
```diff
@@ -216,388 +218,775 @@ func TestGrandpa_DifferentChains(t *testing.T) {
...
+				// to issue another prevote/precommit message
+				const subroundInterval = 100 * time.Millisecond
+				ctx, cancel := context.WithCancel(context.Background())
+				defer cancel()
+
+				st := newTestState(t)
+				grandpaServices[idx] = &Service{
+					ctx:          ctx,
+					cancel:       cancel,
+					paused:       atomic.Value{},
```
Comment (qdm12) [inline lib/grandpa/round_test.go:324]: I don't think that's needed

```suggestion
```

**Review by qdm12 — COMMENTED** [review]
Nice 👍

I'm half way more or less, I need to review all these new tests as well, looking good.

I might have left many nit-comments on code moved, but we might as well improve it a bit since it shows as delta anyway / will show in the git blame.

File: lib/grandpa/grandpa.go [hunk 34]
```diff
@@ -500,152 +471,96 @@ func (s *Service) playGrandpaRound() error {
...
-			return
-		case <-ticker.C:
-		}
-	}
-}
-
-// attemptToFinalize loops until the round is finalisable
-func (s *Service) attemptToFinalize() error {
-	ticker := time.NewTicker(s.interval / 100)
+	performCh := s.receiveVoteMessages(cancel)
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/grandpa.go:477]: `performCh` sounds reasonable since we should perform some action accordingly to the vote messages we receive from the network

File: lib/grandpa/grandpa.go [hunk 35]
```diff
@@ -1297,3 +1209,192 @@ func (s *Service) lenVotes(stage Subround) int {
...
+		return nil
+	}
+
+	// check justification here
+	err = verifyCommitMessageJustification(msg, s.state.setID,
+		s.state.threshold(), s.authorities(), s.blockState)
+	if err != nil {
+		if errors.Is(err, blocktree.ErrStartNodeNotFound) {
+			// we haven't synced the committed block yet, add this to the tracker for later processing
+			s.tracker.addCommit(msg)
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/grandpa.go:1249]: This code was moved from `vote_message.go` to `grandpa.go` and I didn't touch this part, but I believe we should return the error but track the message

File: lib/grandpa/round_test.go (hunk 33 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/round_test.go:324]: This is important otherwise we will face a panic exception as we load the value stored in it and if we don't create or store a value (see the line right after the creation of the service) in it then it will panic

**Comment by timwu20** [comment]
@EclesioMeloJunior can you ensure the tests work? I'd rather not review multiple times if there are more changes required to fix the tests.

File: lib/grandpa/grandpa.go [hunk 36]
```diff
@@ -74,8 +76,9 @@ type Service struct {
 	bestFinalCandidate map[uint64]*Vote // map of round number -> best final candidate
 
 	// channels for communication with other services
-	in          chan *networkVoteMessage // only used to receive *VoteMessage
+	//in             chan *networkVoteMessage // only used to receive *VoteMessage
 	finalisedCh chan *types.FinalisationInfo
+	//receivedCommit chan *CommitMessage
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:81]:
```suggestion
	finalisedCh chan *types.FinalisationInfo
```

File: lib/grandpa/grandpa.go [hunk 37]
```diff
@@ -449,188 +424,300 @@ func (s *Service) primaryBroadcastCommitMessage() {
...
 
-	// broadcast pre-vote
-	pv, err := s.determinePreVote()
-	if err != nil {
-		return err
+			switch action {
+			case determinePrevote:
+				isPrimary, err := s.handleIsPrimary()
+				if err != nil {
+					return err
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:451]:
```suggestion
					return fmt.Errorf("handling primary: %w", err)
```

File: lib/grandpa/grandpa.go [hunk 38]
```diff
@@ -449,188 +424,300 @@ func (s *Service) primaryBroadcastCommitMessage() {
...
+				}
+
+				// broadcast pre-vote
+				preVote, err := s.determinePreVote()
+				if err != nil {
+					return err
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:457]:
```suggestion
					return fmt.Errorf("determining prevote: %w", err)
```

File: lib/grandpa/grandpa.go [hunk 39]
```diff
@@ -449,188 +424,300 @@ func (s *Service) primaryBroadcastCommitMessage() {
...
+				}
+
+				signedpreVote, prevoteMessage, err :=
+					s.createSignedVoteAndVoteMessage(preVote, prevote)
+				if err != nil {
+					return err
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:463]:
```suggestion
					return fmt.Errorf("creating signed vote and vote message: %w", err)
```

File: lib/grandpa/grandpa.go [hunk 40]
```diff
@@ -449,188 +424,300 @@ func (s *Service) primaryBroadcastCommitMessage() {
...
+				}
+
+				s.precommits.Store(s.publicKeyBytes(), signedpreComit)
+
+				s.sendPrecommitMessage(precommitMessage)
+
+			case finalize:
+				commitMessage, err := s.newCommitMessage(s.head, s.state.round, s.state.setID)
+				if err != nil {
+					return fmt.Errorf("generating commit message: %w", err)
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:491]: nit creating feels more appropriate than `generating` (no randomness etc. if you see what I mean)

```suggestion
					return fmt.Errorf("creating commit message: %w", err)
```

File: lib/grandpa/grandpa.go [hunk 41]
```diff
@@ -449,188 +424,300 @@ func (s *Service) primaryBroadcastCommitMessage() {
...
+				}
+
+				commitConsensusMessage, err := commitMessage.ToConsensusMessage()
+				if err != nil {
+					return fmt.Errorf("transforming commit into consensus message: %w", err)
+				}
+
+				logger.Debugf("sending CommitMessage: %v", commitMessage)
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:499]: nit let's use human friendly words instead of Go CamelCase struct names, in your  logs

```suggestion
				logger.Debugf("sending commit message: %v", commitMessage)
```

File: lib/grandpa/grandpa.go [hunk 42]
```diff
@@ -449,188 +424,300 @@ func (s *Service) primaryBroadcastCommitMessage() {
...
-	defer cancel()
+	logger.Debugf("starting round %d with set id %d",
+		currentRound, currentSetID)
 
-	isPrimary, err := s.handleIsPrimary()
-	if err != nil {
-		return err
-	}
+	cancel := make(chan struct{})
+	defer close(cancel)
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:436]: This should be closed if the service context is canceled. If we use a context inside the Service, we might want to just pass in `s.ctx` to `s.finalizationEngine`.

Transforming the context to a signal channel would require an extra goroutine which is meh.

Alternatively you could change `s.ctx` to be a stop signal channel, but I'm not sure about the implications.

File: lib/grandpa/message_handler.go [hunk 43]
```diff
@@ -49,15 +48,10 @@ func (h *MessageHandler) handleMessage(from peer.ID, m GrandpaMessage) (network.
 
 	switch msg := m.(type) {
 	case *VoteMessage:
-		// send vote message to grandpa service
-		h.grandpa.in <- &networkVoteMessage{
-			from: from,
-			msg:  msg,
-		}
-
+		h.grandpa.handleVoteMessage(from, msg)
```
Comment (qdm12) [inline lib/grandpa/message_handler.go:51]: handleVoteMessage should return errors and the parent here should wrap and return

File: lib/grandpa/message_handler.go [hunk 44]
```diff
@@ -49,15 +48,10 @@ func (h *MessageHandler) handleMessage(from peer.ID, m GrandpaMessage) (network.
...
 		return nil, nil
 	case *CommitMessage:
-		return nil, h.handleCommitMessage(msg)
+		return nil, h.grandpa.handleCommitMessage(msg)
```
Comment (qdm12) [inline lib/grandpa/message_handler.go:54]: nit a bit out of scope, but let's wrap the error since we are touching this here

```suggestion
		err = h.grandpa.handleCommitMessage(msg)
		if err != nil {
			return nil, fmt.Errorf("handling commit message: %w", err)
		}
		return nil, nil
```

File: lib/grandpa/grandpa.go [hunk 45]
```diff
@@ -1281,3 +1372,208 @@ func (s *Service) lenVotes(stage Subround) int {
...
+			ErrMinVotesNotMet, threshold, validAndEqv)
+	}
+
+	logger.Debugf("validated commit message: %v", commitMessage)
+	return nil
+}
+
+func verifyJustification(just *SignedVote, round, setID uint64,
+	stage Subround, authorities []*types.Authority) error {
+	// verify signature
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1540]: nit feels unneeded

```suggestion
```

File: lib/grandpa/grandpa.go [hunk 46]
```diff
@@ -1281,3 +1372,208 @@ func (s *Service) lenVotes(stage Subround) int {
...
+	}
+
+	// TODO: re-add catch-up logic (#1531)
+	return nil
+}
+
+func verifyCommitMessageJustification(commitMessage *CommitMessage, setID uint64, threshold uint64,
+	authorities []*types.Authority, blockState BlockState) error {
+	if len(commitMessage.Precommits) != len(commitMessage.AuthData) {
+		return fmt.Errorf("%w", ErrPrecommitSignatureMismatch)
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1464]: nit add both lengths to the context? 🤔

File: lib/grandpa/grandpa.go [hunk 47]
```diff
@@ -1281,3 +1372,208 @@ func (s *Service) lenVotes(stage Subround) int {
...
+		return nil
+	}
+
+	// check justification here
+	err = verifyCommitMessageJustification(commitMessage, s.state.setID,
+		s.state.threshold(), s.authorities(), s.blockState)
+	if err != nil {
+		if errors.Is(err, blocktree.ErrStartNodeNotFound) {
+			// we haven't synced the committed block yet, add this to the tracker for later processing
+			s.tracker.addCommit(commitMessage)
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1437]: we should `return nil` in this if block

File: lib/grandpa/grandpa.go [hunk 48]
```diff
@@ -1281,3 +1372,208 @@ func (s *Service) lenVotes(stage Subround) int {
...
+		telemetry.NewAfgReceivedCommit(
+			commitMessage.Vote.Hash,
+			fmt.Sprint(commitMessage.Vote.Number),
+			containsPrecommitsSignedBy,
+		),
+	)
+
+	has, err := s.blockState.HasFinalisedBlock(commitMessage.Round, s.state.setID)
+	if err != nil {
+		return fmt.Errorf("checking if there is finalized block: %w", err)
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1424]: nit

```suggestion
		return fmt.Errorf("checking for a finalized block in the block state: %w", err)
```

File: lib/grandpa/grandpa.go [hunk 49]
```diff
@@ -1281,3 +1372,208 @@ func (s *Service) lenVotes(stage Subround) int {
...
 }
+
+func (s *Service) handleVoteMessage(from peer.ID, vote *VoteMessage) {
+	logger.Debugf("received vote message, (peer: %s, msg: %+v)", from, vote)
+	s.sendTelemetryVoteMessage(vote)
+
+	v, err := s.validateVoteMessage(from, vote)
+	if err != nil {
+		logger.Debugf("failed to validate vote message {%v}: %s", vote, err)
+		return
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1383]: this should be an error returned and handled by the caller, not a debug log

**Review by qdm12 — COMMENTED** [review]
Substantial work 👍 I'll continue reviewing tomorrow though.

One note to remember for future PRs (note to everyone as well), is it's nice to modify functions in place, get reviews, and then have a last commit moving them around. For example here `handleCommitMessage` got moved and so it's quite troublesome for reviewers to see the diffs between the two (if any)

File: lib/grandpa/grandpa.go [hunk 50]
```diff
@@ -449,188 +424,300 @@ func (s *Service) primaryBroadcastCommitMessage() {
...
-	if err != nil {
-		return err
-	}
+	cancel := make(chan struct{})
+	defer close(cancel)
 
-	logger.Debug("receiving pre-vote messages...")
-	go s.receiveVoteMessages(ctx)
-	time.Sleep(s.interval)
+	roundActions := s.finalizationEngine(cancel)
```
Comment (timwu20) [inline lib/grandpa/grandpa.go:438]: I think we need to know that all `finalizationEngine` goroutines have actually exited if we actually close `cancel`.  It may make sense to create a `finalizationEngine` type that implements the service interface that I suggested:
```
// Service is a generalized interface for a long running asynchronous service
type Service interface {
	// Start returns an error channel that is only written to if err == nil.  It is implied that
	// the service is ready if the returned err == nil.
	Start() (errChan chan error, err error)
	// Stop will shutdown the service.  The errChan returned in Start() is expected to be closed.
	// Packages that implement the Service interface should implement a timeout to ensure Stop()
	// does not block indefinitely.
	Stop() (err error)
}```

That way we can ensure that no goroutine is left dangling before proceeding to the next grandpa round.

File: lib/grandpa/grandpa.go [hunk 51]
```diff
@@ -449,188 +424,300 @@ func (s *Service) primaryBroadcastCommitMessage() {
...
+		var precommited bool = false
 
-	// broadcast pre-commit
-	pc, err := s.determinePreCommit()
-	if err != nil {
-		return err
-	}
+		for !precommited {
+			select {
+			case <-cancel:
```
Comment (timwu20) [inline lib/grandpa/grandpa.go:537]: this case is not tested in the unit tests.

File: lib/grandpa/grandpa.go [hunk 52]
```diff
@@ -449,188 +424,300 @@ func (s *Service) primaryBroadcastCommitMessage() {
...
-	// continue to send prevote messages until round is done
-	go s.sendVoteMessage(prevote, vm, roundComplete)
+	go func() {
+		defer close(performAction)
 
-	logger.Debug("receiving pre-commit messages...")
-	// through goroutine s.receiveVoteMessages(ctx)
-	time.Sleep(s.interval)
+		determinePrevoteTimer := time.NewTimer(s.interval * 2)
+		determinePrecommitTimer := time.NewTimer(s.interval * 4)
```
Comment (timwu20) [inline lib/grandpa/grandpa.go:531]: we don't need to make these explicitly configurable?

File: lib/grandpa/grandpa.go [hunk 53]
```diff
@@ -449,188 +424,300 @@ func (s *Service) primaryBroadcastCommitMessage() {
...
 
-	logger.Debug("receiving pre-vote messages...")
-	go s.receiveVoteMessages(ctx)
-	time.Sleep(s.interval)
+	roundActions := s.finalizationEngine(cancel)
 
-	if s.paused.Load().(bool) {
-		return ErrServicePaused
-	}
+	for { //nolint:gosimple
```
Comment (timwu20) [inline lib/grandpa/grandpa.go:440]: I don't see how we exit this function if `Service.cancel` gets called.

**Review by timwu20 — CHANGES_REQUESTED** [review]

File: lib/grandpa/message_handler.go (hunk 43 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/message_handler.go:51]: Yes, but this code is called by the network layer and it does not expect an error from a vote message we just log it, but messages like catchup should return an error to the net layer

File: lib/grandpa/grandpa.go (hunk 52 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/grandpa.go:531]: those timers are similar to what substrate has here -> https://github.com/paritytech/substrate/blob/c24431eb6a95197550b30715a4c124be1aea79de/client/finality-grandpa/src/environment.rs#L700

File: lib/grandpa/grandpa.go [hunk 54]
```diff
@@ -321,25 +323,15 @@ func (s *Service) initiateRound() error {
...
-	if err != nil {
-		return err
-	}
 
-	if best.Number > 0 {
-		return nil
-	}
-
-	// don't begin grandpa until we are at block 1
-	s.waitForFirstBlock()
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/grandpa.go:342]: it is not necessary to wait until the first block since the genesis block can be chosen in the next rounds if there are no new blocks, so hanging here until we receive/produce a new block is not needed

File: lib/grandpa/grandpa_test.go [hunk 55]
```diff
@@ -98,13 +98,20 @@ func newTestService(t *testing.T) (*Service, *state.Service) {
...
 		Authority:    true,
 		Network:      net,
 		Interval:     time.Second,
 		Telemetry:    telemetryMock,
 	}
 
+	if len(kp) == 0 {
+		cfg.Keypair = kr.Alice().(*ed25519.Keypair)
+	} else if len(kp) > 1 {
+		t.Fatalf("expecting only one *ed25519.Keypair, got: %d", len(kp))
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/grandpa_test.go:109]: Changed to a single `kp *ed25519.Keypair` argument, I agree that a config struct is a better option but will require a larger refactor, created issue https://github.com/ChainSafe/gossamer/issues/2872 to track this suggestion!

File: lib/grandpa/grandpa.go (hunk 47 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/grandpa.go:1247]: Not really, an error occurs in the function `verifyCommitMessageJustification` and if the error is `blocktree.ErrStartNodeNotFound` then we track the commit message to a future retry (managed by `commit_tracker`) and we should return an error to the caller the commit message could not be verified correctly otherwise we are telling to the caller the commit message is ok which is not correct.

**Review by timwu20 — COMMENTED** [review]
still reviewing the functionality of this, but I'll add my comments regarding function signatures and small fixes.

File: lib/grandpa/engine.go [hunk 56]
```diff
@@ -0,0 +1,474 @@
...
+			}
+			return
+		}
+	}
+}
+
+func (fh *finalizationHandler) Start() (errsCh <-chan error, err error) {
+	go fh.runFinalization()
+	return fh.observableErrs, nil
+}
```
Comment (timwu20) [inline lib/grandpa/engine.go:146]: I took a stab at figuring out how to handle two sub services that should be instantiated per round, and should gracefully shut down if any of the services throws an error in [this service-example PR](https://github.com/timwu20/service-example/pull/1/files).

File: lib/grandpa/engine.go [hunk 57]
```diff
@@ -0,0 +1,474 @@
...
+
+		select {
+		case <-waitServicesCh:
+			err := fh.stopServices(finalizationEngine, votingRound)
+			if err != nil {
+				fh.observableErrs <- err
+				return
+			}
+
+		case <-fh.grandpaService.ctx.Done():
```
Comment (timwu20) [inline lib/grandpa/engine.go:122]: this should be handled outside the `finalizationHandler`.  Once we receive the `Done` signal from the context, it should be calling `finalizationHandler.Stop()`.

**Review by timwu20 — CHANGES_REQUESTED** [review]

File: dot/network/inbound.go [hunk 58]
```diff
@@ -45,6 +45,7 @@ func (s *Service) readStream(stream libp2pnetwork.Stream, decoder messageDecoder
 			s.host.id(), peer, msg)
 
 		if err = handler(stream, msg); err != nil {
+			// TODO: should we response on certain kinds of messages?
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply dot/network/inbound.go:48]: I am not sure about this part of the code, I think I placed the comment in the wrong place, I believe that this is one of the parts that should be in the network refactor in the future. I removed the comment

File: lib/grandpa/network_test.go [hunk 59]
```diff
@@ -78,65 +76,65 @@ func TestHandleNetworkMessage(t *testing.T) {
...
-			Round:  round,
-			Number: 1,
-		}
-
-		nm, ok := msg.(*NeighbourPacketV1)
-		require.True(t, ok)
-		require.Equal(t, expected, nm)
-	}
-}
+// func TestSendNeighbourMessage(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/network_test.go:79]: Oh, since I changed the way we send neighbor messages this test will be changed, working on it!

File: lib/grandpa/engine.go [hunk 60]
```diff
@@ -0,0 +1,475 @@
+// Copyright 2022 ChainSafe Systems (ON)
```
Comment (timwu20) [inline lib/grandpa/engine.go:1]: can we change the name of this file to `finalization.go`?

File: lib/grandpa/engine.go [hunk 61]
```diff
@@ -0,0 +1,475 @@
...
+	Start() error
+	Stop() error
+}
+
+type finalizationHandler struct {
+	servicesLock       sync.Mutex
+	finalizationEngine ephemeralService
+	votingRound        ephemeralService
+
+	servicesBuilder func() (engine, voting ephemeralService)
```
Comment (timwu20) [inline lib/grandpa/engine.go:25]:
```suggestion
	newServices func() (engine, voting ephemeralService)
```

File: lib/grandpa/engine.go [hunk 62]
```diff
@@ -0,0 +1,475 @@
...
+	defer close(errorsCh)
+
+	go func() {
+		defer stopWg.Done()
+		errorsCh <- fh.finalizationEngine.Stop()
+	}()
+	go func() {
+		defer stopWg.Done()
+		errorsCh <- fh.votingRound.Stop()
+	}()
```
Comment (timwu20) [inline lib/grandpa/engine.go:76]: How do you know which service returned which error?

File: lib/grandpa/engine.go [hunk 63]
```diff
@@ -0,0 +1,475 @@
...
+	case <-fh.handlerDone:
+	case <-time.After(fh.timeoutStop):
+		return fmt.Errorf("%w", errTimeoutWhileStoping)
+	}
+
+	close(fh.observableErrs)
+	return err
+}
+
+func (fh *finalizationHandler) runFinalization() {
```
Comment (timwu20) [inline lib/grandpa/engine.go:105]:
```suggestion
func (fh *finalizationHandler) run() {
```
or even `start()`

File: lib/grandpa/engine.go [hunk 64]
```diff
@@ -0,0 +1,475 @@
...
+		select {
+		case <-fh.stopCh:
+			return nil
+
+		case err, ok := <-votingRoundErr:
+			if !ok {
+				votingRoundErr = nil
+			}
+
+			_ = fh.stop()
```
Comment (timwu20) [inline lib/grandpa/engine.go:163]: we should probably log at level INFO for any error.

File: lib/grandpa/engine.go [hunk 65]
```diff
@@ -0,0 +1,475 @@
...
+// playGrandpaRound executes a round of GRANDPA
+// at the end of this round, a block will be finalised.
+// TODO(test): stopping handleVotingRound first and then stopping
+// finalizationEngine might cause a write in a non-reading unbuff channel
+// blocking the finalizationEngine to stop and triggering the stop timeout timer
+func (h *handleVotingRound) Start() (err error) {
+	defer func() {
+		close(h.engineDone)
+		fmt.Println("RETURNING VOTING ROUND")
+	}()
```
Comment (timwu20) [inline lib/grandpa/engine.go:228]:
```suggestion
	defer close(h.engineDone)
```

File: lib/grandpa/engine.go [hunk 66]
```diff
@@ -0,0 +1,475 @@
...
+	f.stopCh = nil
+	close(f.actionCh)
+	return nil
+}
+
+func (f *finalizationEngine) Start() (err error) {
+	defer func() {
+		close(f.engineDone)
+		fmt.Println("RETURNING FINALIZATION ENGINE")
+	}()
```
Comment (timwu20) [inline lib/grandpa/engine.go:369]:
```suggestion
	defer close(f.engineDone)
```

File: lib/grandpa/engine.go [hunk 67]
```diff
@@ -0,0 +1,475 @@
...
+			}
+
+			if !determinePrecommitTimer.Stop() {
+				<-determinePrecommitTimer.C
+			}
+
+			return nil
+
+		case <-determinePrevoteTimer.C:
+			alreadyCompletable, err := f.grandpaService.checkRoundAlreadyCompletable()
```
Comment (timwu20) [inline lib/grandpa/engine.go:391]:
```suggestion
			completable, err := f.grandpaService.checkRoundCompletable()
```

File: lib/grandpa/engine.go [hunk 68]
```diff
@@ -0,0 +1,475 @@
...
+			if err != nil {
+				return fmt.Errorf("checking grandpa ghost ancestry: %w", err)
+			}
+
+			if !isDescendant {
+				panic("block with supermajority does not belong to the latest finalized block chain")
+			}
+
+			f.actionCh <- determinePrecommit
+			precommited = true
```
Comment (timwu20) [inline lib/grandpa/engine.go:441]: I kinda like using the loop labels here and breaking out of this explicitly.  It's easier to read, since it's not obvious this breaks out of the loop on line 377.

File: lib/grandpa/engine.go [hunk 69]
```diff
@@ -0,0 +1,475 @@
...
+			f.actionCh <- finalize
+			return nil
+		}
+
+		select {
+		case <-f.stopCh:
+			return nil
+		case <-attemptFinalizationTicker.C:
+		}
+	}
```
Comment (timwu20) [inline lib/grandpa/engine.go:474]: I feel like this function can be broken into two separate functions.

**Review by timwu20 — CHANGES_REQUESTED** [review]

File: lib/grandpa/engine.go (hunk 62 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/engine.go:76]: Changing to an `errs := [2]error{}` and now we can check index 0 for first service, index 1 for the other service, similar to here -> https://github.com/timwu20/service-example/blob/510df34a7051daf9f88023b81ec99c1e827d0955/service/sub_service_round.go#L102

File: lib/grandpa/engine.go (hunk 68 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/engine.go:441]: I have a different point of view. When I call break inside a select it jump out the select block, and in this case is the same as going to the next loop iteration, and there is only one `break` in this entire select block, I don't see this code as convoluted/not obvious

File: lib/grandpa/message_handler.go [hunk 70]
```diff
@@ -78,7 +77,31 @@ func (h *MessageHandler) handleMessage(from peer.ID, m GrandpaMessage) (network.
 	}
 }
 
+func (h *MessageHandler) notifyNeighbors(neighbourMessage *NeighbourPacketV1) {
```
Comment (timwu20) [inline lib/grandpa/message_handler.go:80]: I think this should return an error.  and the calling function can just decide to `log.Warnf` any error that comes back.

File: lib/grandpa/vote_message.go [hunk 71]
```diff
@@ -156,54 +126,57 @@ func (s *Service) validateVoteMessage(from peer.ID, m *VoteMessage) (*Vote, erro
...
+		return nil, fmt.Errorf("transforming public key into a voter: %w", err)
 	}
 
 	vote := NewVote(m.Message.BlockHash, m.Message.Number)
 
 	// if the vote is from ourselves, return an error
 	kb := [32]byte(s.publicKeyBytes())
 	if bytes.Equal(m.Message.AuthorityID[:], kb[:]) {
-		return nil, errVoteFromSelf
+		return nil, fmt.Errorf("%w", errVoteFromSelf)
```
Comment (timwu20) [inline lib/grandpa/vote_message.go:179]: why are we wrapping the error here?

File: lib/grandpa/vote_message.go [hunk 72]
```diff
@@ -225,7 +198,7 @@ func (s *Service) validateVoteMessage(from peer.ID, m *VoteMessage) (*Vote, erro
 
 	equivocated := s.checkForEquivocation(voter, just, m.Message.Stage)
 	if equivocated {
-		return nil, ErrEquivocation
+		return nil, fmt.Errorf("%w", ErrEquivocation)
```
Comment (timwu20) [inline lib/grandpa/vote_message.go:201]: why are we wrapping the error here?

File: lib/grandpa/finalization.go [hunk 73]
```diff
@@ -0,0 +1,493 @@
...
+}
+
+func (fh *finalizationHandler) Stop() (err error) {
+	close(fh.stopCh)
+
+	err = fh.stop()
+	select {
+	case <-fh.handlerDone:
+	case <-time.After(fh.timeoutStop):
+		return fmt.Errorf("%w", errTimeoutWhileStoping)
```
Comment (timwu20) [inline lib/grandpa/finalization.go:121]: why do we wrap the error here?

File: lib/grandpa/engine.go (hunk 68 above)
Comment (timwu20) [reply lib/grandpa/engine.go]: I mean using a loop label and explicit breaking.
```
main:
	for {
		select {
		case <-f.stopCh:
			...
		case <-determinePrevoteTimer.C:
			...
		case <-determinePrecommitTimer.C:
			...
			break main
		}
	}
```

Comment (timwu20) [reply lib/grandpa/engine.go]: The line 441 is `precommited = true` which means that you're trying to break out of the loop in on line 377.  Am I misunderstanding something?  I was just suggesting adding a loop label so you can use the `break <loop name>` explicitly.

File: lib/grandpa/message.go [hunk 74]
```diff
@@ -56,7 +56,11 @@ type VoteMessage struct {
 	Message SignedMessage
 }
 
-// Index returns VDT index
+func (v VoteMessage) String() string {
+	return fmt.Sprintf("round=%d, setID=%d, message={%s}", v.Round, v.SetID, v.Message)
+}
+
+// Index Returns VDT index
```
Comment (qdm12) [inline lib/grandpa/message.go:63]: nit to revert the not-so-needed delta

```suggestion
// Index returns VDT index
```

File: lib/grandpa/grandpa_test.go [hunk 75]
```diff
@@ -85,7 +86,7 @@ func newTestVoters() []Voter {
 	return vs
 }
 
-func newTestService(t *testing.T) (*Service, *state.Service) {
+func newTestService(t *testing.T, kp *ed25519.Keypair) (*Service, *state.Service) {
```
Comment (qdm12) [inline lib/grandpa/grandpa_test.go:89]: nit `keyPair` would be nicer than `kp`

File: lib/grandpa/grandpa.go [hunk 76]
```diff
@@ -1281,3 +1167,209 @@ func (s *Service) lenVotes(stage Subround) int {
...
+		Round: round,
+		SetID: setID,
+	}
+
+	msg, err := scale.Marshal(fullVote)
+	if err != nil {
+		return fmt.Errorf("scale encoding full vote: %w", err)
+	}
+
+	pk, err := ed25519.NewPublicKey(just.AuthorityID[:])
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1349]: nit rename `pk` to `publicKey`

File: lib/grandpa/grandpa.go [hunk 77]
```diff
@@ -1281,3 +1167,209 @@ func (s *Service) lenVotes(stage Subround) int {
...
+	if validAndEqv < threshold {
+		return fmt.Errorf("%w: for finalisation message; need %d votes but received only %d votes",
+			ErrMinVotesNotMet, threshold, validAndEqv)
+	}
+
+	logger.Debugf("validated commit message: %v", commitMessage)
+	return nil
+}
+
+func verifyJustification(just *SignedVote, round, setID uint64,
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1335]: nit rename `just` to `justification`

File: lib/grandpa/grandpa.go [hunk 78]
```diff
@@ -1281,3 +1167,209 @@ func (s *Service) lenVotes(stage Subround) int {
...
+	stage Subround, authorities []*types.Authority) error {
+	fullVote := FullVote{
+		Stage: stage,
+		Vote:  just.Vote,
+		Round: round,
+		SetID: setID,
+	}
+
+	msg, err := scale.Marshal(fullVote)
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1344]: nit rename `msg` to `encodedFullVote`

File: lib/grandpa/grandpa.go [hunk 79]
```diff
@@ -1281,3 +1167,209 @@ func (s *Service) lenVotes(stage Subround) int {
...
+	ok, err := pk.Verify(msg, just.Signature[:])
+	if err != nil {
+		return fmt.Errorf("verifying signature: %w", err)
+	}
+
+	if !ok {
+		return fmt.Errorf("%w: 0x%x for message {%v}", ErrInvalidSignature, just.Signature, fullVote)
+	}
+
+	justKey, err := just.AuthorityID.Encode()
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1363]: nit rename `justKey` to `justificationKey`

File: lib/grandpa/grandpa.go [hunk 80]
```diff
@@ -1281,3 +1167,209 @@ func (s *Service) lenVotes(stage Subround) int {
...
+		}
+
+		precommitedHeader, err := blockState.GetHeader(pc.Hash)
+		if err != nil {
+			return fmt.Errorf("getting header: %w", err)
+		}
+
+		if precommitedHeader.Number != uint(pc.Number) {
+			return fmt.Errorf("%w: expected block number %d, got block number %d",
+				ErrBlockNumberMismatch, precommitedHeader.Number, pc.Number)
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1312]: nit a bit easier to understand

```suggestion
			return fmt.Errorf("%w: pre commit corresponding header has block number %d " +
				"and pre commit has block number %d",
				ErrBlockNumberMismatch, precommitedHeader.Number, pc.Number)
```

File: lib/grandpa/grandpa.go [hunk 81]
```diff
@@ -1281,3 +1167,209 @@ func (s *Service) lenVotes(stage Subround) int {
...
+		justification := &SignedVote{
+			Vote:        pc,
+			Signature:   commitMessage.AuthData[i].Signature,
+			AuthorityID: commitMessage.AuthData[i].AuthorityID,
+		}
+
+		err := verifyJustification(justification, commitMessage.Round, setID, precommit, authorities)
+		if err != nil {
+			logger.Errorf("verifying justification: %", err)
+			continue
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1296]: Should'nt we return an error if verification fails for one of the precommit? :thinking:

File: lib/grandpa/grandpa.go [hunk 82]
```diff
@@ -1281,3 +1167,209 @@ func (s *Service) lenVotes(stage Subround) int {
...
+	}
+
+	if !isDescendant {
+		return fmt.Errorf("%w: vote hash %s and highest finalised header %s",
+			errVoteBlockMismatch, commitMessage.Vote.Hash.Short(), highestFinalizedHeader.Hash())
+	}
+
+	eqvVoters := getEquivocatoryVoters(commitMessage.AuthData)
+	var totalValidPrecommits int
+	for i, pc := range commitMessage.Precommits {
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1286]: nit rename `pc` to `preCommit`

File: lib/grandpa/grandpa.go [hunk 83]
```diff
@@ -1281,3 +1167,209 @@ func (s *Service) lenVotes(stage Subround) int {
...
+	err = s.grandpaState.SetPrecommits(commitMessage.Round, commitMessage.SetID, preCommitSigned)
+	if err != nil {
+		return fmt.Errorf("setting precommits: %w", err)
+	}
+
+	// TODO: re-add catch-up logic (#1531)
+	return nil
+}
+
+func verifyCommitMessageJustification(commitMessage *CommitMessage, setID uint64, threshold uint64,
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:1257]: nit pass commitMessage as `CommitMessage` without a pointer, I don't think there is a need :thinking:

File: lib/grandpa/grandpa.go [hunk 84]
```diff
@@ -1068,6 +952,8 @@ func (s *Service) getPossibleSelectedAncestors(votes []Vote, curr common.Hash,
 			return nil, err
 		}
 
+		// if the common ancestor is the same as
+		// the current  block, should we just continue?
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:956]: Question reminder... :wink:

File: lib/grandpa/grandpa.go [hunk 85]
```diff
@@ -1047,6 +928,9 @@ func (s *Service) getPossibleSelectedBlocks(stage Subround, threshold uint64) (m
 		}
 	}
 
+	// we should check if the blocks map contains only
+	// one element, meaning that one common ancestor
+	// was found otherwise return an error
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:933]: TODO reminder I think?

File: lib/grandpa/grandpa.go [hunk 86]
```diff
@@ -1025,6 +904,8 @@ func (s *Service) getPossibleSelectedBlocks(stage Subround, threshold uint64) (m
 			return nil, err
 		}
 
+		// TODO: if a block reaches enough threshold then should we
+		// return from here since the others didn't reach the same amount of votes
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:908]: TODO / question reminder

File: lib/grandpa/grandpa.go [hunk 87]
```diff
@@ -321,69 +319,32 @@ func (s *Service) initiateRound() error {
...
-	// loop until block 1
 	for {
 		select {
-		case block := <-ch:
-			if block != nil && block.Header.Number > 0 {
-				return
-			}
 		case <-s.ctx.Done():
-			return
+			return finalizationHandler.Stop()
```
Comment (qdm12) [inline lib/grandpa/grandpa.go:345]: If the ctx gets canceled, shouldn't we also collect errors from `errsCh` (even if unchecked, to at least drain the channel and let the other goroutine exit)?

File: lib/grandpa/finalization_test.go [hunk 88]
```diff
@@ -0,0 +1,260 @@
...
+	go func() {
+		defer close(doneCh)
+		for err := range errsCh {
+			t.Errorf("expected no error, got %s", err)
+			return
+		}
+	}()
+
+	// wait enough time to start subservices
+	<-time.After(5 * time.Second)
```
Comment (qdm12) [inline lib/grandpa/finalization_test.go:255]:
```suggestion
	time.Sleep(5 * time.Second)
```

File: lib/grandpa/finalization_test.go [hunk 89]
```diff
@@ -0,0 +1,260 @@
...
+	doneCh := make(chan struct{})
+	errsCh, err := handler.Start()
+	require.NoError(t, err)
+
+	go func() {
+		defer close(doneCh)
+		for err := range errsCh {
+			t.Errorf("expected no error, got %s", err)
+			return
+		}
```
Comment (qdm12) [inline lib/grandpa/finalization_test.go:251]: this looks sketchy... I think this just quickly goes over the empty error channel and exits; shouldn't we check for errors later in a blocking manner with i.e. a `select+default`?

File: lib/grandpa/finalization_test.go [hunk 90]
```diff
@@ -0,0 +1,260 @@
...
+		"engine_fails_should_stop_voting_round_service": {
+			wantErr: errors.New("mocked finalisation engine fails"),
+			createFinalizationHandler: func(ctrl *gomock.Controller) *finalizationHandler {
+				builder := func() (engine ephemeralService, voting ephemeralService) {
+					failTime := 2 * time.Second
+
+					mockEngine := NewMockephemeralService(ctrl)
+					mockEngine.EXPECT().Start().DoAndReturn(func() error {
+						timeToFail := time.NewTimer(failTime)
+						<-timeToFail.C
```
Comment (qdm12) [inline lib/grandpa/finalization_test.go:145]: nit / applies to other `timeToFail` in this file

```suggestion
						time.Sleep(failTime)
```

File: lib/grandpa/finalization_test.go [hunk 91]
```diff
@@ -0,0 +1,260 @@
+// Copyright 2022 ChainSafe Systems (ON)
+// SPDX-License-Identifier: LGPL-3.0-only
+
+package grandpa
+
```
Comment (qdm12) [inline lib/grandpa/finalization_test.go:5]: Many of these tests sleep and take several seconds, please move these to an integration test file and add a lib/grandpa integ test line to the matrix in the github workflow

File: lib/grandpa/finalization.go [hunk 92]
```diff
@@ -0,0 +1,493 @@
...
+					return fmt.Errorf("determining pre-commit: %w", err)
+				}
+
+				signedpreComit, precommitMessage, err :=
+					h.grandpaService.createSignedVoteAndVoteMessage(preComit, precommit)
+				if err != nil {
+					return fmt.Errorf("creating signed vote: %w", err)
+				}
+
+				logger.Warnf("sending pre-commit message: {%v}", precommitMessage)
```
Comment (qdm12) [inline lib/grandpa/finalization.go:285]: nit why is this a warning?

File: lib/grandpa/finalization.go [hunk 93]
```diff
@@ -0,0 +1,493 @@
...
+	h.stopCh = nil
+	return nil
+}
+
+// playGrandpaRound executes a round of GRANDPA
+// at the end of this round, a block will be finalised.
+// TODO(test): stopping handleVotingRound first and then stopping
+// finalizationEngine might cause a write in a non-reading unbuff channel
+// blocking the finalizationEngine to stop and triggering the stop timeout timer
+func (h *handleVotingRound) Start() (err error) {
```
Comment (qdm12) [inline lib/grandpa/finalization.go:230]: This is not really a start function since it runs until stopped. Usually/imo/afaik, Start should launch a goroutine and return a start error promptly. The easiest fix here is to rename `Start` to `Run`

File: lib/grandpa/finalization.go [hunk 94]
```diff
@@ -0,0 +1,493 @@
...
+	case <-time.After(h.timeoutStop):
+		return errTimeoutWhileStoping
+	}
+
+	h.stopCh = nil
+	return nil
+}
+
+// playGrandpaRound executes a round of GRANDPA
+// at the end of this round, a block will be finalised.
```
Comment (qdm12) [inline lib/grandpa/finalization.go:226]: comment needs to be updated

File: lib/grandpa/finalization.go [hunk 95]
```diff
@@ -0,0 +1,493 @@
...
+
+	return nil
+}
+
+func (f *finalizationEngine) defineRoundVotes() error {
+	gossipInterval := f.grandpaService.interval
+	determinePrevoteTimer := time.NewTimer(gossipInterval * 2)
+	determinePrecommitTimer := time.NewTimer(gossipInterval * 4)
+
+	var precommited bool = false
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go:388]: Yeah, I know the default value for `bool` variables is always false, but I prefer to keep it explicitly to help the readability of the workflow above that line

File: lib/grandpa/finalization.go [hunk 96]
```diff
@@ -0,0 +1,493 @@
...
+
+	stopWg.Wait()
+
+	if errs[0] != nil {
+		return errs[0]
+	}
+
+	if errs[1] != nil {
+		return errs[1]
+	}
```
[the remark this answers is not in the document]
Comment (qdm12) [reply lib/grandpa/finalization.go:109]: Also we should *ideally* wrap one of the two since we cannot wrap 2 errors :cry: 

Something like `fmt.Errorf("both failed: %s; %w", errA, errB)`... or define a new sentinel error `ErrBothFailed` that you wrap with `fmt.Errorf("%w: %s; %s", ErrBothFailed, errA, errB)`... probably overthinking it a bit though :smile:

File: lib/grandpa/finalization.go [hunk 97]
```diff
@@ -0,0 +1,493 @@
...
+	"github.com/ChainSafe/gossamer/dot/telemetry"
+)
+
+type ephemeralService interface {
+	Start() error
+	Stop() error
+}
+
+type finalizationHandler struct {
+	servicesLock       sync.Mutex
```
[the remark this answers is not in the document]
Comment (qdm12) [reply lib/grandpa/finalization.go:21]: I disagree, otherwise it exposes the Lock and Unlock methods to the caller.

Also very niche complain, but it's annoying you cannot CTRL+Click on the embedded mutex when finding a `.Lock()` call.

File: lib/grandpa/finalization.go [hunk 98]
```diff
@@ -0,0 +1,493 @@
...
+}
+
+func (h *handleVotingRound) Stop() (err error) {
+	if h.stopCh == nil {
+		return nil
+	}
+
+	close(h.stopCh)
+	select {
+	case <-h.engineDone:
```
[the remark this answers is not in the document]
Comment (qdm12) [reply lib/grandpa/finalization.go:216]: From the top of my head and what I've read yesterday, when you close `stopCh`, it signals the goroutine to stop. However, the goroutine is not instantly closed, so we wait for it to terminate with `engineDone`. There probably is a `defer close(engineDone)` in the goroutine function.

File: lib/grandpa/finalization.go [hunk 99]
```diff
@@ -0,0 +1,493 @@
...
+		stopCh:               make(chan struct{}),
+		engineDone:           make(chan struct{}),
+		finalizationEngineCh: finalizationEngineCh,
+	}
+}
+
+func (h *handleVotingRound) Stop() (err error) {
+	if h.stopCh == nil {
+		return nil
+	}
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go:213]: it is not possible to check if a channel is closed by `_, ok := h.stopCh` we should use the arrow `<-` like: `_, ok := <-h.stopCh` but we cannot do that here since it will block until the `stopCh` is closed so we face the problem where in the first time we call the `Stop` method it will block forever, however setting it to `nil` once the channel is closed enable us to do the check without blocking.

File: lib/grandpa/finalization.go (hunk 97 above)
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go:21]: I think the named field makes explicit that the locking purpose is to lock the ephemeral services we create each round

File: lib/grandpa/finalization.go [hunk 100]
```diff
@@ -0,0 +1,493 @@
...
+
+func (fh *finalizationHandler) start() {
+	defer close(fh.handlerDone)
+
+	for {
+		select {
+		case <-fh.stopCh:
+			return
+		default:
+		}
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go:70]: `waitServices` already returns when `stopCh` is closed since it should shut down the inner services it manages.

`initiateRound` does not have to return when the `stopCh` is closed because it does not manage the inner services, it basically updates the authorities (if needed) and increases the round number, so once this is done this function returns.

File: lib/grandpa/finalization.go [hunk 101]
```diff
@@ -0,0 +1,493 @@
...
+			votingRoundErr <- err
+		}
+	}()
+
+	for {
+		select {
+		case <-fh.stopCh:
+			return nil
+
+		case err, ok := <-votingRoundErr:
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go]: yes, the only way to `fh.stopCh` is closed is by calling the `fh.Stop()` method, and this method closes the `fh.stopCh` and then call the `Stop()` method from each `votingRound` and `finalizationEngine`, see the `(fh *finalizationHandler) stop()` method

File: lib/grandpa/finalization.go [hunk 102]
```diff
@@ -0,0 +1,493 @@
...
+		stopCh:         make(chan struct{}),
+		engineDone:     make(chan struct{}),
+	}
+}
+
+func (f *finalizationEngine) Stop() (err error) {
+	if f.stopCh == nil {
+		return nil
+	}
+
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go:349]: yes, since the code is designed to call `stop` when a service fails it is possible that we call the `Stop()` method from a service that is already stopped

File: lib/grandpa/finalization.go (hunk 99 above)
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go]: See https://github.com/ChainSafe/gossamer/pull/2688#discussion_r1017054315

File: lib/grandpa/finalization.go [hunk 103]
```diff
@@ -0,0 +1,493 @@
...
+				f.actionCh <- alreadyFinalized
+				return nil
+			}
+
+			f.actionCh <- determinePrevote
+
+		case <-determinePrecommitTimer.C:
+			alreadyCompletable, err := f.grandpaService.checkRoundCompletable()
+			if err != nil {
+				return fmt.Errorf("checking round is completable: %w", err)
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go:417]: the `determinePrevoteTimer` is always triggered before the `determinePrecommitTimer` so it is not needed to call the stop method here since the prevote timer was already called and will not be called anymore

File: lib/grandpa/finalization.go [hunk 104]
```diff
@@ -0,0 +1,493 @@
...
+			}
+
+			if alreadyCompletable {
+				f.actionCh <- alreadyFinalized
+				return nil
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go:422]: See https://github.com/ChainSafe/gossamer/pull/2688#discussion_r1017061626

File: lib/grandpa/finalization.go [hunk 105]
```diff
@@ -0,0 +1,493 @@
...
+			}
+
+			prevoteGrandpaGhost, err := f.grandpaService.getPreVotedBlock()
+			if err != nil {
+				return fmt.Errorf("getting grandpa ghost: %w", err)
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go:427]: See https://github.com/ChainSafe/gossamer/pull/2688#discussion_r1017061626

File: lib/grandpa/finalization.go [hunk 106]
```diff
@@ -0,0 +1,493 @@
...
+			}
+
+			total, err := f.grandpaService.getTotalVotesForBlock(prevoteGrandpaGhost.Hash, prevote)
+			if err != nil {
+				return fmt.Errorf("getting grandpa ghost: %w", err)
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go:432]: See https://github.com/ChainSafe/gossamer/pull/2688#discussion_r1017061626

File: lib/grandpa/finalization.go [hunk 107]
```diff
@@ -0,0 +1,493 @@
...
+			if total <= f.grandpaService.state.threshold() {
+				determinePrecommitTimer.Reset(gossipInterval * 4)
+				continue
+			}
+
+			latestFinalizedHash := f.grandpaService.head.Hash()
+			isDescendant, err := f.grandpaService.blockState.IsDescendantOf(
+				latestFinalizedHash, prevoteGrandpaGhost.Hash)
+			if err != nil {
+				return fmt.Errorf("checking grandpa ghost ancestry: %w", err)
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go:444]: See https://github.com/ChainSafe/gossamer/pull/2688#discussion_r1017061626

File: lib/grandpa/grandpa.go [hunk 108]
```diff
@@ -173,18 +173,16 @@ func (s *Service) Start() error {
...
-			if err := s.initiate(); err != nil {
-				logger.Criticalf("failed to initiate: %s", err)
+		err := s.initiate()
+		if err != nil {
+			errStop := s.Stop()
+			if errStop != nil {
+				logger.Criticalf("%s", errStop)
 			}
-			time.Sleep(s.interval)
+			panic(fmt.Errorf("grandpa service: %s", err))
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/grandpa.go:182]: We are assuming that any error caming out from the grandpa finalization handler is a critical error that should shut down the node. In fact we don't need to call `stop` so removed the lines which calls `Stop`

File: tests/rpc/rpc_03-chain_test.go [hunk 109]
```diff
@@ -249,7 +258,8 @@ func TestChainSubscriptionRPC(t *testing.T) { //nolint:tparallel
 		// Check block numbers grow by zero or one in order of responses.
 		for i, blockNumber := range blockNumbers {
 			if i == 0 {
-				assert.Equal(t, uint(1), blockNumber)
+				// the first finalized block could be block 0 as well
+				assert.GreaterOrEqual(t, uint(0), blockNumber)
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply tests/rpc/rpc_03-chain_test.go:262]: You're right! Should be reversed!

File: lib/grandpa/types.go [hunk 110]
```diff
@@ -59,24 +59,13 @@ func NewState(voters []Voter, setID, round uint64) *State {
...
 
-	if id == max {
-		return nil, ErrVoterNotFound
-	}
-
-	return &Voter{
-		Key: *pk,
-		ID:  id,
-	}, nil
+	return nil, ErrVoterNotFound
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/types.go:68]: I will keep it as it is since this is not a problem we should address in the PR 😄

File: lib/grandpa/message_tracker.go [hunk 111]
```diff
@@ -128,10 +129,13 @@ func (t *tracker) handleBlock(b *types.Block) {
...
 
 func (t *tracker) handleTick() {
-	t.mapLock.Lock()
-	defer t.mapLock.Unlock()
+	t.mapLock.RLock()
+	networkVoteMessages := t.votes.networkVoteMessages()
+	t.mapLock.RUnlock()
 
-	for _, networkVoteMessage := range t.votes.networkVoteMessages() {
+	blocksToRemoveFromTracker := make([]common.Hash, 0, len(networkVoteMessages))
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/message_tracker.go]: Removed since it is out of the scope of the PR

File: lib/grandpa/message_tracker.go [hunk 112]
```diff
@@ -141,10 +145,17 @@ func (t *tracker) handleTick() {
 		}
 
 		if message.Round < t.handler.grandpa.state.round && message.SetID == t.handler.grandpa.state.setID {
-			t.votes.delete(message.Message.BlockHash)
+			blocksToRemoveFromTracker = append(blocksToRemoveFromTracker, message.Message.BlockHash)
 		}
 	}
 
+	t.mapLock.Lock()
+	defer t.mapLock.Unlock()
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/message_tracker.go]: Removed since it is out of the scope of the PR

File: lib/grandpa/message_tracker.go [hunk 113]
```diff
@@ -38,7 +39,7 @@ func newTracker(bs BlockState, handler *MessageHandler) *tracker {
 		handler:                 handler,
 		votes:                   newVotesTracker(votesCapacity),
 		commits:                 newCommitsTracker(commitsCapacity),
-		mapLock:                 sync.Mutex{},
+		mapLock:                 sync.RWMutex{},
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/message_tracker.go]: Removed since it is out of the scope of the PR

File: lib/grandpa/message_handler.go [hunk 114]
```diff
@@ -79,6 +78,27 @@ func (h *MessageHandler) handleMessage(from peer.ID, m GrandpaMessage) (network.
 }
 
 func (h *MessageHandler) handleNeighbourMessage(msg *NeighbourPacketV1) error {
+	if h.grandpa.authority {
+		// TODO: this is a simple hack to ensure that the neighbour messages
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/message_handler.go:82]: Because we should fix it to don't rely on messages received from other nodes, we should be able to send messages whenever the connection is in a proper state, so I've created the issue and I will link with this TODO

File: lib/grandpa/grandpa.go (hunk 81 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/grandpa.go:1292]: Not really, if we fail to verify some pre-commit we don't count it in the `totalValidPrecommits`, so since we can validate  > 2/3 pre-commits we don't need to return an error

File: lib/grandpa/grandpa.go (hunk 83 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/grandpa.go:1253]: It will require more deltas that are not in the scope of this PR (this PR is quite large), we could open a new issue if you think we should really address it otherwise I think there is no problem to keep it as it is

File: lib/grandpa/vote_message.go (hunk 72 above)
Comment (qdm12) [reply lib/grandpa/vote_message.go]: [From https://engineering-handbook-pr-62.onrender.com/development/tech-stack/go#wrap-or-wrapped](https://engineering-handbook-pr-62.onrender.com/development/tech-stack/go#wrapping-the-sentinel-error)

> There are also cases where it is not necessary to add error context. For example if the database is 'closed', there is no need to add context really. In this case, use the format return fmt.Errorf("%w", ErrSentinel) and NOT return ErrSentinel. The reason is to prevent callers from using err == ErrDatabaseClosed, and force them to use errors.Is(err, ErrSentinel), so context can be added later on if needed.

File: lib/grandpa/finalization.go (hunk 100 above)
[the remark this answers is not in the document]
Comment (qdm12) [reply lib/grandpa/finalization.go:73]: `initiateRound` does look it doesn't do IO/infinite looping, my bad. Although it does lock mutexes and stuff, so let's just assume/hope it doesn't deadlock on exit.

Regarding `waitServices`, maybe we could inject the stop channel as an argument `waitServices(fh.stopCh)` from the caller? That way we can also restrict it as read only channel. I guess I'm used to passing contexts as arguments and not as field, and this feels like a context-ish.

File: lib/grandpa/finalization.go (hunk 98 above)
[the remark this answers is not in the document]
Comment (qdm12) [reply lib/grandpa/finalization.go]: Yeah we should probably document this in the eng handbook, this is rather critical (to avoid 'fire and forget' goroutines which are untestable, unpredictable, and may lead to a build up of goroutines). And in my experience so far, not many devs know or think about it (also shame on contexts carrying a mechanism system but not a waiting for canceled mechanism) :confused:

File: lib/grandpa/finalization.go (hunk 92 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go:283]: Changed to be a DEBUG level warning

File: lib/grandpa/finalization.go (hunk 93 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go]: I agree with you, I changed the `ephemeralService` interface to be `Run(), Stop()` and now makes more sense to understand that we **run** an ephemeral service but we allow the caller to **stop** it

File: lib/grandpa/finalization.go [hunk 115]
```diff
@@ -0,0 +1,493 @@
...
+
+	if finalizationEngErr != nil {
+		return fmt.Errorf("%w: %s", errServicesStopFailed, finalizationEngErr)
+	}
+
+	if votingRoundErr != nil {
+		return fmt.Errorf("%w: %s", errServicesStopFailed, votingRoundErr)
+	}
+
+	return nil
```
Comment (timwu20) [inline lib/grandpa/finalization.go:118]:
```suggestion
	if finalizationEngErr != nil && votingRoundErr != nil {
		return fmt.Errorf("%w: %s; %s", errServicesStopFailed, finalizationEngErr, votingRoundErr)
	} else if finalizationEngErr != nil {
		return fmt.Errorf("%w: %s", errServicesStopFailed, finalizationEngErr)
	} else if votingRoundErr != nil {
		return fmt.Errorf("%w: %s", errServicesStopFailed, votingRoundErr)
	} else {
	        return nil
	}
```

File: lib/grandpa/grandpa.go [hunk 116]
```diff
@@ -446,191 +423,114 @@ func (s *Service) primaryBroadcastCommitMessage() {
...
-			"Head hash is %s, %d direct votes for bfc and %d total votes for bfc",
-			s.state.round, s.state.setID, s.head.Hash(), votes[*bfc], pc)
+	return true, nil
+}
 
-		cm, err := s.newCommitMessage(s.head, s.state.round)
-		if err != nil {
-			return err
-		}
+func (s *Service) sendPrecommitMessage(vm *VoteMessage) {
```
[the remark this answers is not in the document]
Comment (timwu20) [reply lib/grandpa/grandpa.go:488]: bump on this @EclesioMeloJunior

File: lib/grandpa/grandpa.go [hunk 117]
```diff
@@ -446,191 +423,114 @@ func (s *Service) primaryBroadcastCommitMessage() {
...
-		s.network.GossipMessage(msg)
+	s.network.GossipMessage(consensusMessage)
+	logger.Tracef("sent pre-commit message: %v", consensusMessage)
+}
 
-		s.telemetry.SendMessage(telemetry.NewAfgFinalizedBlocksUpTo(
-			s.head.Hash(),
-			fmt.Sprint(s.head.Number),
-		))
+func (s *Service) sendPrevoteMessage(vm *VoteMessage) {
```
[the remark this answers is not in the document]
Comment (timwu20) [reply lib/grandpa/grandpa.go:501]: bump on this as well

File: lib/grandpa/grandpa.go (hunk 49 above)
Comment (timwu20) [reply lib/grandpa/grandpa.go:1168]: bump on this @EclesioMeloJunior

File: lib/grandpa/finalization.go (hunk 115 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go:118]: Both ways achieve the same result is there any specific reason for changing from the current way to use the `if {} else if {}` other than the style?

File: lib/grandpa/finalization.go [hunk 118]
```diff
@@ -0,0 +1,493 @@
...
+}
+
+func (fh *finalizationHandler) Stop() (err error) {
+	// even though we close the `stopCh` we might
+	// we drain the `errorCh` since an ephemeral service
+	// could failed in the mean time the caller calls the
+	// Stop method hanging here as it will blocks to write
+	// into the channel since there is no channel reader
+	close(fh.stopCh)
+	<-fh.errorCh
```
Comment (qdm12) [inline lib/grandpa/finalization.go:125]: I don't think we should drain the error channel, we should just let the close send a `nil, false` to the reader channel of `Start()` :thinking: Or am I missing something?

File: lib/grandpa/finalization.go [hunk 119]
```diff
@@ -0,0 +1,493 @@
...
+	<-fh.handlerDone
+
+	err = fh.stop()
+	return err
```
Comment (qdm12) [inline lib/grandpa/finalization.go:129]: nit

```suggestion
	return fh.stop()
```

File: lib/grandpa/finalization.go [hunk 120]
```diff
@@ -0,0 +1,493 @@
...
+		case err := <-finalizationEngineErr:
+			if err == nil {
+				finalizationEngineErr = nil
+				// go out from the select case
+				break
+			}
+
+			stopErr := fh.stop()
+			if stopErr != nil {
+				logger.Warnf("stopping finalisation handler: %s", stopErr)
```
Comment (qdm12) [inline lib/grandpa/finalization.go:180]:
```suggestion
				logger.Warnf("stopping voting round handler: %s", stopErr)
```

File: lib/grandpa/finalization.go [hunk 121]
```diff
@@ -0,0 +1,493 @@
...
+	err = fh.stop()
+	return err
+}
+
+// waitServices will start the ephemeral services that handles the
+// votes for the current round and once those services finishes the
+// waitServices return without errors, if one ephemeral service face
+// a problem the waitServices will shut down all the running ephemeral
+// services and return an error, this function also returns if the
+// finalizationHandler.Stop() method is called
```
Comment (qdm12) [inline lib/grandpa/finalization.go:137]: Tried to simplify a tiny bit the comment

```suggestion
// waitServices starts the two ephemeral services that handle the
// votes for the current round, and returns with nil when the two
// service runs succeed.
// If any service run fails, the other service run is stopped and
// an error is returned. The function returns nil is the finalisation
// handler is stopped.
```

File: lib/grandpa/finalization.go [hunk 122]
```diff
@@ -0,0 +1,493 @@
...
+func (fh *finalizationHandler) waitServices() error {
```
Comment (qdm12) [inline lib/grandpa/finalization.go:138]: nit should we rename `waitServices` to `runEphemeralServices`? `wait` is not so appropriate since we also start the services.

File: lib/grandpa/finalization.go [hunk 123]
```diff
@@ -0,0 +1,493 @@
...
+
+func newFinalizationHandler(service *Service) *finalizationHandler {
+	// builder is a constructor function which takes care to instantiate
+	// and return the services needed to finalize a round, those services
+	// are ephemeral services with a lifetime of a round
+	builder := func() (engine, voting ephemeralService) {
+		finalizationEngine := newFinalizationEngine(service)
+		votingRound := newHandleVotingRound(service, finalizationEngine.actionCh)
+		return finalizationEngine, votingRound
+	}
```
Comment (qdm12) [inline lib/grandpa/finalization.go:43]: nit it would be cleaner imo to just have `*Service` as a field in the handler, and inline the content of that `builder` within `waitServices`

File: lib/grandpa/finalization.go [hunk 124]
```diff
@@ -0,0 +1,493 @@
...
+		finish := votingRoundErr == nil && finalizationEngineErr == nil
+		if finish {
+			return nil
+		}
+	}
+}
+
+// handleVotingRound interacts with finalizationEngine service
+// executing the actions based on what it receives throuhg channel
+type handleVotingRound struct {
```
Comment (qdm12) [inline lib/grandpa/finalization.go:194]: Dumb question, why do we have `handleVotingRound`? It looks like it reads only from `h.finalizationEngineCh` (which is unbuffered)... couldn't we just do this directly in the `finalizationEngine`?

File: lib/grandpa/finalization.go [hunk 125]
```diff
@@ -0,0 +1,493 @@
...
+		engineDone:           make(chan struct{}),
+		finalizationEngineCh: finalizationEngineCh,
+	}
+}
+
+func (h *handleVotingRound) Stop() (err error) {
+	if h.engineDone == nil {
+		return nil
+	}
+
```
Comment (qdm12) [inline lib/grandpa/finalization.go:214]: imo I think we should not check this and let it panic... we shouldn't stop that service twice anyway right?

File: lib/grandpa/errors.go [hunk 126]
```diff
@@ -93,4 +89,6 @@ var (
 	errVoteToSignatureMismatch = errors.New("votes and authority count mismatch")
 	errVoteBlockMismatch       = errors.New("block in vote is not descendant of previously finalised block")
 	errVoteFromSelf            = errors.New("got vote from ourselves")
+	errRoundOutOfBounds        = errors.New("round out of bounds")
```
Comment (qdm12) [inline lib/grandpa/errors.go:92]: You can remove `ErrServicePaused` in this file

File: lib/grandpa/finalization.go [hunk 127]
```diff
@@ -0,0 +1,493 @@
...
+				votingRoundErr = nil
+				// go out from the select case
+				break
+			}
+
+			stopErr := fh.stop()
+			if stopErr != nil {
+				logger.Warnf("stopping finalisation handler: %s", stopErr)
+			}
+			return err
```
Comment (qdm12) [inline lib/grandpa/finalization.go:169]: nit wrap the error stating it's the voting round eph. service that failed

File: lib/grandpa/finalization.go [hunk 128]
```diff
@@ -0,0 +1,493 @@
...
+				finalizationEngineErr = nil
+				// go out from the select case
+				break
+			}
+
+			stopErr := fh.stop()
+			if stopErr != nil {
+				logger.Warnf("stopping finalisation handler: %s", stopErr)
+			}
+			return err
```
Comment (qdm12) [inline lib/grandpa/finalization.go:182]: nit wrap the error stating it's the fin engine eph. service that failed

File: lib/grandpa/finalization.go [hunk 129]
```diff
@@ -0,0 +1,493 @@
...
+
+	for {
+		select {
+		case <-h.stopCh:
+			return nil
+
+		case action, ok := <-h.finalizationEngineCh:
+			if !ok {
+				return nil
+			}
```
Comment (qdm12) [inline lib/grandpa/finalization.go:240]: `h.finalizationEngineCh` can only be closed in the block:

```go
func (f *finalizationEngine) Stop() (err error) {
	if f.engineDone == nil {
		return nil
	}

	close(f.stopCh)
	<-f.engineDone

	close(f.actionCh)
	return nil
}
```

So the `stopCh` case should trigger first, let's just remove this otherwise it allows, if we're working on an action below, the function to exit from either of the 2 select cases (which is bad for future changes and predictability).

```suggestion
		case action := <-h.finalizationEngineCh:
```

File: lib/grandpa/finalization.go [hunk 130]
```diff
@@ -0,0 +1,493 @@
...
+
+			switch action {
+			case determinePrevote:
+				isPrimary, err := h.grandpaService.handleIsPrimary()
+				if err != nil {
+					return fmt.Errorf("handling primary: %w", err)
+				}
+
+				// broadcast pre-vote
+				preVote, err := h.grandpaService.determinePreVote()
```
Comment (qdm12) [inline lib/grandpa/finalization.go:250]: Is the comment still valid? If so, why is the method still named `determinePreVote`?

File: lib/grandpa/finalization.go [hunk 131]
```diff
@@ -0,0 +1,493 @@
...
+				}
+
+				if !isPrimary {
+					h.grandpaService.prevotes.Store(h.grandpaService.publicKeyBytes(), signedpreVote)
+				}
+
+				logger.Debugf("sending pre-vote message: {%v}", prevoteMessage)
+				err = h.grandpaService.sendPrevoteMessage(prevoteMessage)
+				if err != nil {
+					logger.Errorf("sending pre-vote message: %s", err)
```
Comment (qdm12) [inline lib/grandpa/finalization.go:268]: why not return an error instead?

File: lib/grandpa/finalization.go [hunk 132]
```diff
@@ -0,0 +1,493 @@
...
+				}
+
+			case determinePrecommit:
+				preComit, err := h.grandpaService.determinePreCommit()
```
Comment (qdm12) [inline lib/grandpa/finalization.go:272]: typo `preComit` -> `preCommit` :wink:

File: lib/grandpa/finalization.go [hunk 133]
```diff
@@ -0,0 +1,493 @@
...
+				if err != nil {
+					return fmt.Errorf("determining pre-commit: %w", err)
+				}
+
+				signedpreComit, precommitMessage, err :=
```
Comment (qdm12) [inline lib/grandpa/finalization.go:277]: `signedpreComit` -> signedpreCommit

**Comment by EclesioMeloJunior** [comment]
The test `TestMessageTracker_handleTick` is hanging due to the deadlock described at https://github.com/ChainSafe/gossamer/issues/2841. The PR https://github.com/ChainSafe/gossamer/pull/2923 is addressing it

File: lib/grandpa/finalization.go (hunk 124 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go:187]: The name `handleVotingRound` could be better but the idea is to separate the finalization engine (which count pre-votes, pre-commits, check the round is completable) from the part where we send pre-votes, pre-commits, primary proposals which we call `handleVotingRound`. 

You're right, right now it just performs actions based on what the finalization engine sends but the idea is to evolve to choose the peers to send messages for example. So the separation is intentional.

File: lib/grandpa/finalization.go (hunk 125 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go:207]: You're right, this check is not necessary!

File: lib/grandpa/engine.go (hunk 68 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/engine.go]: Oh, right, I set `precommited = true` then I go out the for loop. I choose this way using the variable because it looks very explicit and given the fact that Go enables loop conditionals, your way achieves the same result but uses labels which I don't think is a good fit for this case since Go enable this loop conditional

File: lib/grandpa/finalization.go (hunk 100 above)
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go:72]: Since the `stopCh` is a field and `waitServices ` is a method of the `finalizationHandler` I don't see why we should pass `stopCh` to `waitServices ` as an argument given that we could just use it from the instance

**Comment by qdm12** [comment]
> The test `TestMessageTracker_handleTick` is hanging due to the deadlock described at #2841. The PR #2923 is addressing it

You could `git rebase kishan/fix/grandpa-deadlock` and change the target branch to `kishan/fix/grandpa-deadlock` in this PR, that way CI would pass. Once `kishan/fix/grandpa-deadlock` gets merged, you can just `git rebase development` this branch and change the target branch of the PR to `development`

File: lib/grandpa/finalization.go (hunk 124 above)
Comment (qdm12) [reply lib/grandpa/finalization.go:187]: Let's make it without a channel then. Just have it as a method call and inject `handleVotingRound` to the finalization engine. Let's very much 100% avoid channels if unnecessary (for complexity, readability and performance)

File: lib/grandpa/finalization.go (hunk 123 above)
Comment (qdm12) [reply lib/grandpa/finalization.go]: I was suggesting to create the ephemeral services inline within `runEphemeralServices`, and without a functional field. However, I guess you use that functional field to mock it for tests right?

File: lib/grandpa/finalization.go [hunk 134]
```diff
@@ -0,0 +1,473 @@
...
+
+		err := fh.initiateRound()
+		if err != nil {
+			errorCh <- fmt.Errorf("initiating round: %w", err)
+			return
+		}
+
+		err = fh.runEphemeralServices()
+		if err != nil {
+			errorCh <- fmt.Errorf("waiting for services: %w", err)
```
Comment (qdm12) [inline lib/grandpa/finalization.go:82]:
```suggestion
			errorCh <- fmt.Errorf("running ephemeral services: %w", err)
```

**Review by qdm12 — CHANGES_REQUESTED** [review]

File: lib/grandpa/finalization.go (hunk 100 above)
[the remark this answers is not in the document]
Comment (timwu20) [reply lib/grandpa/finalization.go:72]: There's a lot to unpack here.  I don't understand what you mean by "we stop both ephemeral services kinda at the wrong place (might be causing one or more problems as well)".  If you're going to make a declaration like this you need to elaborate why your reasoning behind this.

> It really does help to inject all channels as arguments (stop channel, error channel, ready channel etc.), even if it's already present in the receiving struct. We really just need to have them in the receiving struct so both Start and Stop can share some of the channels, but then internally, we should inject them as arguments for our own sakes.

Again, what does this mean? How does it help? We need the stop chan to be in the state of the service because they need to be read by one receiver method and accessed by another.  How does passing it via parameters help this? We would need to introduce new methods that have different signatures than the methods that are publicly exposed.  

> I'm pausing my local suggestion rework since we should first throw out the service nature of votingRound (just make it a single global function handleVotingRound(service *Service, action engineAction) without even a votingRound struct).

@EclesioMeloJunior designed `handleVotingRound` to be asynchronous for a reason.  I think it mirrors more of how the `sc-grandpa-finality` interacts with `grandpa-finality` package in substrate.  I don't see why you wouldn't want to process more incoming votes or determine whether or not we can continue to a completable state if we're waiting on a synchronous call to said function.

File: lib/grandpa/finalization.go (hunk 124 above)
Comment (timwu20) [reply lib/grandpa/finalization.go:187]: > Let's make it without a channel then.
@EclesioMeloJunior said the separation is intentional. 🤔

**Review by timwu20 — APPROVED** [review]

File: lib/grandpa/finalization.go [hunk 135]
```diff
@@ -0,0 +1,473 @@
...
+		finish := votingRoundErr == nil && finalizationEngineErr == nil
+		if finish {
+			return nil
+		}
+	}
+}
+
+// handleVotingRound interacts with finalizationEngine service
+// executing the actions based on what it receives throuhg channel
+type handleVotingRound struct {
```
Comment (qdm12) [inline lib/grandpa/finalization.go:187]: nit Should this be called `votingRoundHandler` instead?

File: lib/grandpa/finalization.go (hunk 124 above)
Comment (qdm12) [reply lib/grandpa/finalization.go:187]: After some pairing with Eclesio, I think we should inject the voting round handler to the finalization engine, and have an `enqueueAction(action)` method on the voting round. That way the voting round can handle internally how to enqueue the action (without a channel, with an unbuffered or buffered channel or some other clever queuing system). We can keep the two voting round handler and finalization engine as two goroutines running in parallel.

File: lib/grandpa/finalization.go (hunk 100 above)
[the remark this answers is not in the document]
Comment (qdm12) [reply lib/grandpa/finalization.go:72]: > I don't understand what you mean by "we stop both ephemeral services kinda at the wrong place (might be causing one or more problems as well)". If you're going to make a declaration like this you need to elaborate your reasoning behind this.

If the finalization engine fails, the voting round handler is then stopped in `runEphemeralServices() error` (same the other way around). If the caller then calls `Stop()` on the finalization handler, it would close signal channels twice and panic. I think Eclesio and I went over this Friday afternoon. The solution would be to stop both services within `runEphemeralServices() error` (and nowhere else) in the `case <-fh.stopCh:`. It gets a bit more complicated though, we would have to write the error from stopping both services to an extra internal channel so it can be retrieved from the `Stop()` method.

> Again, what does this mean? How does it help?

It's easier to track what function gets what, especially since channels/parallel programming isn't particularly easy. Just my opinion/own experience though, take it as you wish. 

> We need the stop chan to be in the state of the service because they need to be read by one receiver method and accessed by another. How does passing it via parameters help this? We would need to introduce new methods that have different signatures than the methods that are publicly exposed.

That's what I said, and I didn't suggest to change the exported method signatures: *We really just need to have them in the receiving struct so both Start and Stop can share some of the channels but then internally, we should inject them as arguments for our own sakes.* I meant to pass down the channels in the call stack below `Start`/`Stop` in case that wasn't clear.

> @EclesioMeloJunior designed handleVotingRound to be asynchronous for a reason. I think it mirrors more of how the sc-grandpa-finality interacts with grandpa-finality package in substrate. I don't see why you wouldn't want to process more incoming votes or determine whether or not we can continue to a completable state if we're waiting on a synchronous call to said function.

I just saw the current state of it when reviewing the code, where two goroutines with non-cancelable runs (within their infinite for loops) were communicating through an unbuffered channel, and that's pretty much a function call with extra unneeded cpu locking. The channel would be buffered, then it would make sense. I then learnt Eclesio wants to have some sort of queuing between the two goroutines, so it makes sense to have it like that then (although hiding the queuing within the voting round handler).

File: lib/grandpa/finalization.go [hunk 136]
```diff
@@ -0,0 +1,473 @@
...
+
+	logger.Debugf("starting round %d with set id %d",
+		h.grandpaService.state.round, h.grandpaService.state.setID)
+
+	for {
+		select {
+		case <-h.stopCh:
+			return nil
+
+		case action := <-h.finalizationEngineCh:
```
Comment (qdm12) [inline lib/grandpa/finalization.go:226]: Question, how long can this case take at most (and why ideally)?

File: lib/grandpa/finalization_integration_test.go [hunk 137]
```diff
@@ -0,0 +1,308 @@
...
+import (
+	"errors"
+	"testing"
+	"time"
+
+	"github.com/golang/mock/gomock"
+	"github.com/stretchr/testify/require"
+)
+
+func Test_FinalizationHandler_waitServices(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization_integration_test.go]: We cover the bootstrap of both ephemeral services + stops + error assertion and we test the `case <- fh.stopCh` case in the `Test_FinalizationHandler_Stop_ShouldHalt_Services` so what cases should be covered?

File: lib/grandpa/grandpa.go [hunk 138]
```diff
@@ -1281,3 +1156,212 @@ func (s *Service) lenVotes(stage Subround) int {
...
+		if err != nil {
+			logger.Errorf("verifying justification: %", err)
+			continue
+		}
+
+		isDescendant, err := blockState.IsDescendantOf(commitMessage.Vote.Hash, justification.Vote.Hash)
+		if err != nil {
+			logger.Warnf("could not check for descendant: %s", err)
+			continue
+		}
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/grandpa.go:1292]: In this case we just `continue` which means this specific vote will not be considered a valid vote and we don't increase the `totalValidPrecommits`, so we don't need to return

File: lib/grandpa/message_tracker_test.go [hunk 139]
```diff
@@ -191,52 +210,143 @@ func TestMessageTracker_MapInsideMap(t *testing.T) {
...
+		serviceRound       uint64
+		voteRound          uint64
+		trackerKeepMessage bool
+	}{
+		"vote_round_greater_than_service_round": {
+			serviceRound:       1,
+			voteRound:          2,
+			trackerKeepMessage: true,
+		},
+		"vote_round_less_than_service_round": {
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/message_tracker_test.go:226]: Yeah, I believe we should use underscores because if we don't use the test runner will add them for us, for example if we have a inner test like:

```go
t.Run("Testing Example", func(t *testing.T) {})
```

in the test logs this will look like: `Testing_Example`, so I believe we should use underscores instead of spaces

File: lib/grandpa/message_tracker_test.go [hunk 140]
```diff
@@ -191,52 +210,143 @@ func TestMessageTracker_MapInsideMap(t *testing.T) {
...
+				grandpaState: grandpaStateMock,
+				blockState:   blockStateMock,
+				network:      networkMock,
+				prevotes:     new(sync.Map),
+			}
+
+			messageHandler := NewMessageHandler(grandpaService, blockStateMock, telemetryMock)
+			grandpaService.messageHandler = messageHandler
+			grandpaService.tracker = newTracker(blockStateMock, messageHandler)
+
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/message_tracker_test.go:446]: The `NewMessageHandler` expects the `grandpaService` which is why I put it right after the grandpa service instantiation

File: tests/rpc/rpc_03-chain_test.go [hunk 141]
```diff
@@ -79,12 +86,9 @@ func TestChainRPC(t *testing.T) {
...
 
-	// Assert remaining struct with predictable fields
-	expectedHeader := modules.ChainBlockHeaderResponse{
-		ParentHash: finalizedHead,
-		Number:     "0x02",
-	}
-	assert.Equal(t, expectedHeader, header)
+	blockNumber, err := common.HexToUint(header.Number)
+	require.NoError(t, err)
+	assert.GreaterOrEqual(t, blockNumber, uint(2))
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply tests/rpc/rpc_03-chain_test.go:91]: It can be 2, that is why I use `GreaterOrEqual`

File: tests/rpc/rpc_03-chain_test.go [hunk 142]
```diff
@@ -96,7 +100,7 @@ func TestChainRPC(t *testing.T) {
 	block.Block.Header.StateRoot = ""
 	assert.Regexp(t, regex32BytesHex, block.Block.Header.ExtrinsicsRoot)
 	block.Block.Header.ExtrinsicsRoot = ""
-	assert.Len(t, block.Block.Header.Digest.Logs, 3)
+	assert.NotEmpty(t, block.Block.Header.Digest.Logs)
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply tests/rpc/rpc_03-chain_test.go:103]: Not really, block number 0 has 3 logs but the other blocks produced/finalized just have 1 (we don't include anything in them), so asserting with `NotEmpty` ensure at least 1 log in the block

File: lib/grandpa/round_test.go [hunk 143]
```diff
@@ -216,388 +172,694 @@ func TestGrandpa_DifferentChains(t *testing.T) {
...
+		"varying_chain": {
+			voters: []*ed25519.Keypair{
+				ed25519Keyring.Alice().(*ed25519.Keypair),
+				ed25519Keyring.Bob().(*ed25519.Keypair),
+				ed25519Keyring.Charlie().(*ed25519.Keypair),
+				ed25519Keyring.Ian().(*ed25519.Keypair),
+			},
+			defineBlockTree: func(t *testing.T, blockState BlockState, neighbourServices []*Service) {
+				const diff uint = 5
+				rand := uint(rand.Intn(int(diff)))
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/round_test.go:212]: I believe the random behavior is not needed and could open an issue to investigate/remove this random behavior from this test, for now I will keep it as it is

File: lib/grandpa/round_test.go [hunk 144]
```diff
@@ -216,388 +172,694 @@ func TestGrandpa_DifferentChains(t *testing.T) {
...
-	fins := make([]chan GrandpaMessage, len(kr.Keys))
-	done := false
-
-	for i := range gss {
-		gs, in, out, fin := setupGrandpa(t, kr.Keys[i])
-		defer cleanup(gs, in, &done)
+	tests := map[string]struct {
+		voters          []*ed25519.Keypair
+		whoEquivocates  map[int]struct{}
+		defineBlockTree func(t *testing.T, blockState BlockState, neighbourServices []*Service)
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/round_test.go:184]: I would like to keep it as an interface to avoid relying on concrete implementations

File: lib/grandpa/round_test.go [hunk 145]
```diff
@@ -216,388 +172,694 @@ func TestGrandpa_DifferentChains(t *testing.T) {
...
-				return
-			}
-
-			tc <- &networkVoteMessage{
-				msg: v.(*VoteMessage),
-			}
-		}
-	}
-}
+func TestPlayGrandpaRound(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply lib/grandpa/round_test.go:175]: I will rename `round_test.go` to `round_integration_test.go` since all tests inside it do some lock or take longer to run

File: lib/grandpa/finalization.go (hunk 136 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go]: Ideally, a round should take seconds to complete.

I believe we should keep them as independent routines since inside a round we have many interactions (sending one pre-vote message, waiting for votes, defining the pre-commit block, sending the pre-commit message, waiting for a completable/finalized block, sending the commit message if needed, check if we have received a valid commit message then proceed to the next round) and for some of those actions we should rely on the peer tracking + networking layer and that's the responsibilities there is the voting handler.

Our next step should be to handle the background active voting round (proceed to the next round but the prior round is still available and running waiting for votes) and given the current state we can spin ephemeral services that take care of a specific round context.

File: lib/grandpa/finalisation.go [hunk 146]
```diff
@@ -0,0 +1,467 @@
...
+		err = fh.runEphemeralServices()
+		if err != nil {
+			errorCh <- fmt.Errorf("running ephemeral services: %w", err)
+			return
+		}
+	}
+}
+
+func (fh *finalisationHandler) stop() (err error) {
+	fh.servicesLock.Lock()
```
Comment (jimjbrettj) [inline lib/grandpa/finalisation.go:89]: What is actually being locked here? Would other processes be trying to read/write to the ephemeral services?

Comment (EclesioMeloJunior) [reply lib/grandpa/finalisation.go:89]: Since the services are writen in the `fh.run()` goroutine but we read those services at `fh.stop()` so we have this `servicesLock` to prevent rece conditions.

Comment (jimjbrettj) [reply lib/grandpa/finalisation.go:89]: ah okay I see, thank you!

File: lib/grandpa/finalisation.go [hunk 147]
```diff
@@ -0,0 +1,467 @@
...
+
+	stopCh      chan struct{}
+	handlerDone chan struct{}
+}
+
+func newFinalisationHandler(service *Service) *finalisationHandler {
+	return &finalisationHandler{
+		newServices: func() (engine, voting ephemeralService) {
+			finalisationEngine := newfinalisationEngine(service)
+			votingRound := newvotingRoundHandler(service, finalisationEngine.actionCh)
```
Comment (jimjbrettj) [inline lib/grandpa/finalisation.go:45]: Im still getting familiar with best practices for service orchestration, so had a question.

Why do message passing directly between two subchannels, rather than have the handlerService be in charge of message propagation?

My initial though its because its more efficient/easier to do it directly, but does it add complication to graceful shutdown if one of the sub services fails?

File: lib/grandpa/finalisation_integration_test.go [hunk 148]
```diff
@@ -0,0 +1,176 @@
...
+				}
+			},
+		},
+		"halt_fails_to_stop_one_ephemeral_service": {
+			wantErr:   errServicesStopFailed,
+			errString: "services stop failed: cannot stop finalisation engine test",
+			newHandler: func(ctrl *gomock.Controller) *finalisationHandler {
+				builder := func() (engine ephemeralService, voting ephemeralService) {
+					engineStopCh := make(chan struct{})
+					mockEngine := NewMockephemeralService(ctrl)
```
Comment (jimjbrettj) [inline lib/grandpa/finalisation_integration_test.go:73]: Are mocked tests part of integration tests just because they are long running?

File: lib/grandpa/grandpa.go [hunk 149]
```diff
@@ -446,191 +403,112 @@ func (s *Service) primaryBroadcastCommitMessage() {
...
-func (s *Service) playGrandpaRound() error {
-	logger.Debugf("starting round %d with set id %d",
-		s.state.round, s.state.setID)
-	start := time.Now()
-
-	ctx, cancel := context.WithCancel(s.ctx)
-	defer cancel()
-
-	isPrimary, err := s.handleIsPrimary()
+func (s *Service) checkRoundCompletable() (bool, error) {
```
Comment (jimjbrettj) [inline lib/grandpa/grandpa.go:406]: In future this will be extended to account for potential votes, yes?

File: lib/grandpa/finalisation.go (hunk 147 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/finalisation.go:45]: So the message exchange is between `finalization engine (ephemeral) -> voting round handler (ephemeral)`, it is not worth it for `finalization handler` to know about those messages because it does not care about them it just cares about keeping ephemeral services running for one entire round. So, given that `finalization handler` just manages the ephemeral services it is easy to manage the shutdown because whenever one ephemeral service fails (`finalization engine` or `voting round handler`) the manager just stops the other, but if the handler knows that both ephemeral services ended without error it proceeds to the next round.

File: lib/grandpa/grandpa.go (hunk 149 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/grandpa.go:406]: Right!

File: lib/grandpa/message_tracker_test.go [hunk 150]
```diff
@@ -191,63 +211,298 @@ func TestMessageTracker_MapInsideMap(t *testing.T) {
...
+				blockStateMock := NewMockBlockState(ctrl)
+				blockStateMock.EXPECT().
+					GetImportedBlockNotifierChannel().
+					Return(make(chan *types.Block))
+
+				blockStateMock.EXPECT().
+					GetHeader(testHash).
+					Return(nil, chaindb.ErrKeyNotFound)
+
+				// telemetryMock := NewMockClient(ctrl)
```
Comment (jimjbrettj) [inline lib/grandpa/message_tracker_test.go:239]: Nit uncomment or remove

File: lib/grandpa/finalisation.go (hunk 147 above)
Comment (jimjbrettj) [reply lib/grandpa/finalisation.go:45]: okay sweet, makes sense. Thank you!

File: lib/grandpa/finalization.go (hunk 100 above)
[the remark this answers is not in the document]
Comment (jimjbrettj) [reply lib/grandpa/finalization.go]: My question what is the expected behavior on the caller here? If one of the ephemeral services stops, you say then if caller calls Stop() it will panic, not good, but will this happen? It feels to me like its a binary thing, either this is the intended behavior or not. If it is, then we need to stop it from panicking, yes? But if its not then its not something we need to worry about (we shouldnt/wont just be arbitrarily calling stop on our finality service I wouldn't assume)

**Comment by jimjbrettj** [comment]
Referencing https://github.com/ChainSafe/gossamer/pull/2688#discussion_r1020956379 @EclesioMeloJunior @qdm12 @timwu20 

Giving the size of this PR already, and the fact that this code will likely be refactored as we integrate our standalone grandpa impl, is this worth doing rn? If it's super important okay, but if not I feel like we are better off finalizing this PR to get grandpa to a healthier place rn and then pick up this conversation again when the larger grandpa refactor happens. Just my opinion, I could be missing some context, but wanted to give my thoughts here

**Review by jimjbrettj — APPROVED** [review]
Tremendous work Eclesio!! Stoked to see this get merged in!

File: lib/grandpa/finalization.go (hunk 99 above)
[the remark this answers is not in the document]
Comment (qdm12) [reply lib/grandpa/finalization.go]: Actually you can use

```go
var ok bool
select {
case _, ok := <- h.stopCh
default:
}
```

File: lib/grandpa/finalization.go (hunk 136 above)
Comment (EclesioMeloJunior) [reply lib/grandpa/finalization.go]: Right, the fifo order

**Comment by EclesioMeloJunior** [comment]
> Not important of course, but a later refactor PR would be a bit without reason nor issue, so worth having good prod code from start imo. I would doubt the larger grandpa refactor would affect this new code right? 🤔

When we have the standalone package we should touch this code to integrate with, basically more refactors because the finalization engine will be part of the standalone project, and as I said earlier we have more features to add that will touch this code since the finalization is not 100% stable

File: lib/grandpa/finalization.go (hunk 103 above)
[the remark this answers is not in the document]
Comment (qdm12) [reply lib/grandpa/finalization.go]: Indeed my bad!

File: lib/grandpa/finalisation_integration_test.go (hunk 148 above)
Comment (qdm12) [reply lib/grandpa/finalisation_integration_test.go:73]: This is really a unit test, but we need to wait some time (here 2s) for:

- ephemeral services to be set (nil initially)
- goroutines to be launched so mock Run methods are called as expected

Now ephemeral services can be (and should be) set in the `Start` method before we call `run` in a goroutine; and for the goroutines Run method expectations, we can just add `.MaxTimes(1)` to the Run expectations. Then that test is instant and can be moved to a unit test.

Pushed changes to https://github.com/ChainSafe/gossamer/pull/2938/files

File: lib/grandpa/finalization.go (hunk 136 above)
Comment (qdm12) [reply lib/grandpa/finalization.go]: Ok then it makes sense, cool :+1:

File: lib/grandpa/grandpa.go [hunk 151]
```diff
@@ -1281,3 +1156,212 @@ func (s *Service) lenVotes(stage Subround) int {
...
+		return fmt.Errorf("%w: for finalisation message; need %d votes but received only %d votes",
+			ErrMinVotesNotMet, threshold, validAndEqv)
+	}
+
+	logger.Debugf("validated commit message: %v", commitMessage)
+	return nil
+}
+
+func verifyJustification(justification *SignedVote, round, setID uint64,
+	stage Subround, authorities []*types.Authority) error {
```
[the remark this answers is not in the document]
Comment (qdm12) [reply lib/grandpa/grandpa.go:1325]: Fair enough, created https://github.com/ChainSafe/gossamer/issues/2960 :wink:

File: lib/grandpa/helpers_test.go [hunk 152]
```diff
@@ -5,16 +5,114 @@ package grandpa
...
+		finalised: make(chan GrandpaMessage, 128),
+	}
+}
+
+func (n *testNetwork) GossipMessage(msg NotificationsMessage) {
+	cm, ok := msg.(*ConsensusMessage)
+	require.True(n.t, ok)
+
+	gmsg, err := decodeMessage(cm)
+	require.NoError(n.t, err)
```
Comment (qdm12) [inline lib/grandpa/helpers_test.go:50]: I'd recommend to use `assert` since `require` would `t.FailNow()` the test, and that cannot happen in another goroutine than the test goroutine. I would guess this could be handled in other goroutines than the test main goroutine right?

```suggestion
	assert.True(n.t, ok)

	gmsg, err := decodeMessage(cm)
	assert.NoError(n.t, err)
```

File: lib/grandpa/helpers_test.go [hunk 153]
```diff
@@ -5,16 +5,114 @@ package grandpa
...
+
+	switch gmsg.(type) {
+	case *CommitMessage:
+		n.finalised <- gmsg
+	default:
+		n.out <- gmsg
+	}
```
Comment (qdm12) [inline lib/grandpa/helpers_test.go:57]: nit a type check would do instead of a switch

```suggestion
	_, ok := gmsg.(*CommitMessage)
	if ok {
		n.finalised <- gmsg
		return
	}
	n.out <- gmsg
```

File: lib/grandpa/vote_message.go [hunk 154]
```diff
@@ -17,63 +16,33 @@ import (
...
+	case precommit:
+		s.telemetry.SendMessage(
+			telemetry.NewAfgReceivedPrecommit(
+				vm.Message.BlockHash,
+				fmt.Sprint(vm.Message.Number),
+				vm.Message.AuthorityID.String(),
+			),
+		)
+	default:
+		logger.Warnf("unsupported stage %s", vm.Message.Stage.String())
```
Comment (qdm12) [inline lib/grandpa/vote_message.go:45]: nit no need to call `String()`, `%s` should fish it out itself

```suggestion
		logger.Warnf("unsupported stage %s", vm.Message.Stage.String())
```
```suggestion
		logger.Warnf("unsupported stage %s", vm.Message.Stage)
```

File: lib/grandpa/vote_message.go [hunk 155]
```diff
@@ -93,18 +62,19 @@ func (s *Service) createSignedVoteAndVoteMessage(vote *Vote, stage Subround) (*S
 		return nil, nil, err
 	}
 
+	publicBytes := s.keypair.Public().(*ed25519.PublicKey).AsBytes()
```
Comment (qdm12) [inline lib/grandpa/vote_message.go:65]: nit maybe rename to `publicKeyBytes`?

File: tests/rpc/rpc_03-chain_test.go [hunk 156]
```diff
@@ -249,7 +251,8 @@ func TestChainSubscriptionRPC(t *testing.T) { //nolint:tparallel
 		// Check block numbers grow by zero or one in order of responses.
 		for i, blockNumber := range blockNumbers {
 			if i == 0 {
-				assert.Equal(t, uint(1), blockNumber)
+				// the first finalized block could be block 0 as well
+				assert.GreaterOrEqual(t, blockNumber, uint(0))
```
Comment (qdm12) [inline tests/rpc/rpc_03-chain_test.go:255]: this is unneeded since blockNumber is an uint

```suggestion
```

or could we change this to check it's `0` or `1` only?

File: lib/grandpa/message_tracker_test.go [hunk 157]
```diff
@@ -191,63 +211,292 @@ func TestMessageTracker_MapInsideMap(t *testing.T) {
...
+		Vote:  *vote,
+		Round: round,
+		SetID: setID,
+	})
+	require.NoError(t, err)
+
+	signature, err := kp.Sign(fullVoteEncoded)
+	require.NoError(t, err)
+
+	publicBytes := kp.Public().(*ed25519.PublicKey).AsBytes()
```
Comment (qdm12) [inline lib/grandpa/message_tracker_test.go:480]: nit rename to `publicKeyBytes`?

File: lib/grandpa/message_tracker_test.go [hunk 158]
```diff
@@ -84,38 +95,44 @@ func TestMessageTracker_SendMessage(t *testing.T) {
...
-	const testTimeout = time.Second
-	select {
-	case v := <-in:
-		require.Equal(t, msg, v.msg)
-	case <-time.After(testTimeout):
-		t.Errorf("did not receive vote message %v", msg)
-	}
+	// grandpa tracker check every second if the block
+	// was included in the block tree
+	time.Sleep(2 * time.Second)
```
Comment (qdm12) [inline lib/grandpa/message_tracker_test.go:119]: move to integration test?

File: lib/grandpa/finalisation_test.go [hunk 159]
```diff
@@ -0,0 +1,138 @@
...
+		},
+
+		"voting_round_fails_should_stop_engine_service": {
+			errString: "voting round ephemeral failed: mocked voting round failed",
+			wantErr:   errvotingRoundHandlerFailed,
+			createfinalisationHandler: func(ctrl *gomock.Controller) *finalisationHandler {
+				builder := func() (engine ephemeralService, voting ephemeralService) {
+					mockVoting := NewMockephemeralService(ctrl)
+					mockVoting.EXPECT().Run().DoAndReturn(func() error {
+						time.Sleep(time.Second)
```
Comment (qdm12) [inline lib/grandpa/finalisation_test.go:55]: Either remove that sleep and add `.MaxTimes(1)` to that expectation OR move that entire test to an integration test file.

File: lib/grandpa/finalisation_test.go [hunk 160]
```diff
@@ -0,0 +1,138 @@
...
+		},
+
+		"engine_fails_should_stop_voting_round_service": {
+			errString: "finalisation engine ephemeral failed: mocked finalisation engine failed",
+			wantErr:   errfinalisationEngineFailed,
+			createfinalisationHandler: func(ctrl *gomock.Controller) *finalisationHandler {
+				builder := func() (engine ephemeralService, voting ephemeralService) {
+					mockEngine := NewMockephemeralService(ctrl)
+					mockEngine.EXPECT().Run().DoAndReturn(func() error {
+						time.Sleep(time.Second)
```
Comment (qdm12) [inline lib/grandpa/finalisation_test.go:91]: Either remove that sleep and add `.MaxTimes(1)` to that expectation OR move that entire test to an integration test file.

File: lib/grandpa/finalisation.go [hunk 161]
```diff
@@ -0,0 +1,467 @@
...
+// runEphemeralServices starts the two ephemeral services that handle the
+// votes for the current round, and returns with nil when the two
+// service runs succeed.
+// If any service run fails, the other service run is stopped and
+// an error is returned. The function returns nil is the finalisation
+// handler is stopped.
+func (fh *finalisationHandler) runEphemeralServices() error {
+	fh.servicesLock.Lock()
+	fh.finalisationEngine, fh.votingRound = fh.newServices()
+	fh.servicesLock.Unlock()
```
Comment (qdm12) [inline lib/grandpa/finalisation.go:133]: Start() should not return until these are set to something non-nil, otherwise further calls like `.Stop()` would panic on nil pointers. See the related comment on finalisation_integration_test.go

**Review by qdm12 — APPROVED** [review]
Good work and good work on the tests being faster :medal_military: !

On the other hand, this `actionCh` still cringes me badly, I would still suggest to inject votingRoundHandler to the finalisationEngine, and hide the channel within votingRoundHandler (and not share it/expose it outside votingRoundHandler)

File: lib/grandpa/finalization.go (hunk 100 above)
[the remark this answers is not in the document]
Comment (qdm12) [reply lib/grandpa/finalization.go]: In our code this cannot happen. Right now we use this internally and it's not even exported (`finalisationHandler`). I'm thinking probably way too ahead to have a usable public Go API. BUT I believe :pray: :angel: in ourselves one day we'll expose all this stuff to the outside Go world :tada: And yes we should strike a balance between the two, and if this is to be further refactored there can be no point at all making it better as well.

Coming back to that particular problem and expected behavior: from an Go user perspective, I think it would easily make sense to call `.Stop` (even if it does nothing) if a runtime error is read from a returned channel. On the other hand, this doesn't extend to, in example, calling `.Stop` twice.

Anyway I guess we won't do anything further in this PR :smile: But it's good to discuss and exchange opinions :+1:
