### PR TITLE
fix(babe): Add support for versioned NextConfigData decoding

### LINKED ISSUE #3236: babe/digest: Gossamer could not verify slot claim VRF proof at `#5608874`
## Describe the bug

Gossamer fails to verify the VRF proof while requesting the range from block `#5608705` to `#5610241`

```
2023-04-21T13:26:27Z ERROR    block data processing for block with hash 0x711cca084131819539f7c85d0f362214aee947a897d43d4576bf123dec288813 failed: processing block data with header and body: babe verifying block: failed to verify pre-runtime digest: could not verify slot claim VRF proof	chain_sync.go:L741	pkg=sync
```

But before requesting the range Gossamer successfully imported the block `#5608275` which contains the BABE Next Epoch Data and BABE Config Data digests

- BABE Next Epoch Data
```
2023-04-21T13:25:53Z DEBUG    stored BABENextEpochData data: {{[{[102 85 132 42 246 238 38 228 88 181 254 162 211 181 190 178 221 140 249 107 36 180 72 56 145 158 26 226 150 72 223 12] 1} {[92 167 131 48 94 202 168 131 131 232 44 215 20 97 44 22 227 205 24 232 243 118 34 15 45 159 187 181 132 214 138 105] 1} {[212 81 34 24 150 248 208 236 69 62 90 78 252 0 125 32 86 208 73 44 151 210 88 169 187 105 170 28 165 137 126 3] 1} {[236 198 169 213 112 57 219 36 157 140 107 231 182 155 98 72 224 156 194 252 107 138 97 201 177 9 13 248 167 93 218 91] 1}] [237 156 197 246 97 87 56 66 224 116 137 55 52 103 165 76 225 1 189 69 137 154 109 221 47 204 220 167 79 77 161 61]} map[1:{[] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} 2:{0} 3:{0 0 0}]} for hash: 0x709238036170633c14ad9fc57e22d65601329a2d71e89f85c9204c094c0e76a8 to epoch: 9642	digest.go:L198	pkg=digest
```

- BABE Config Data
```
2023-04-21T13:25:53Z DEBUG    stored BABENextConfigData data: {{257 1024 0} map[1:{[] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} 2:{0} 3:{0 0 0}]} for hash: 0x709238036170633c14ad9fc57e22d65601329a2d71e89f85c9204c094c0e76a8 to epoch: 9642	digest.go:L213	pkg=digest
```

We can notice that the babe config data digest contains a map with 3 fields and they only contain zeroes, which made me suspect about Gossamer failed to decode the babe config digest properly

### PR DESCRIPTION
**Pull request by dimartiro**
## Changes

Adds support for NextConfigData versioning following the [substrate implementation](https://github.com/paritytech/substrate/blob/7d6084b5774ee13d0b33810c2830aa5a8506cbae/primitives/consensus/babe/src/digests.rs#L143C1-L152)

- Created `VersionedNextConfigData` to support different `NextConfigData` versions 
- Renamed the old `NextConfigData` as `NextConfigDataV1`

## Tests

```sh
make test
```
Since I modified a current structure used in different tests 

## Issues

Closes #3236 

## Primary Reviewer

@timwu20 @EclesioMeloJunior

### CODE REVIEW

File: dot/digest/digest.go [hunk 1]
```diff
@@ -201,17 +201,23 @@ func (h *Handler) handleBabeConsensusDigest(digest scale.VaryingDataType, header
...
-			return fmt.Errorf("cannot get epoch for block %d (%s): %w",
-				header.Number, headerHash, err)
+			return fmt.Errorf("getting digest value: %w", err)
 		}
 
-		nextEpoch := currEpoch + 1
-		h.epochState.StoreBABENextConfigData(nextEpoch, headerHash, val)
-		h.logger.Debugf("stored BABENextConfigData data: %v for hash: %s to epoch: %d", digest, headerHash, nextEpoch)
-		return nil
+		if nextConfigData, ok := nextConfigDataVersion.(types.NextConfigDataV1); ok {
```
Comment (EclesioMeloJunior) [inline dot/digest/digest.go:211]: would be nice to use a switch case with type assertion just as we are using + including an error if the version is not supported yet
```suggestion
		switch nextConfigData := nextConfigDataVersion.(type) {
		case types.NextConfigDataV1:
		   ...
		default:
		   return errors.New("next config data version not supported: %T", nextConfigDataVersion)
		}
```

**Review by EclesioMeloJunior — CHANGES_REQUESTED** [review]

File: dot/types/consensus_digest_test.go [hunk 2]
```diff
@@ -46,3 +46,25 @@ func TestBabeEncodeAndDecode(t *testing.T) {
 	require.NoError(t, err)
 	require.Equal(t, d, dec)
 }
+
+func TestBabeDecodeVersionedNextConfigData(t *testing.T) {
+	enc := common.MustHexToBytes("0x03010100000000000000040000000000000002")
```
Comment (EclesioMeloJunior) [inline dot/types/consensus_digest_test.go:51]: Could you point the block number from where this encoded digest was extracted?

File: dot/digest/digest.go (hunk 1 above)
Comment (dimartiro) [reply dot/digest/digest.go:211]: I did it but the `DeepSource: Go` complained. Seems to be a bad practice to use a switch with only one case 🤔

File: dot/types/consensus_digest_test.go (hunk 2 above)
Comment (dimartiro) [reply dot/types/consensus_digest_test.go:52]: Done

File: dot/digest/digest.go (hunk 1 above)
Comment (dimartiro) [reply dot/digest/digest.go]: Seems to be passing with the default case, thanks!

**Review by EclesioMeloJunior — APPROVED** [review]
LGTM! 🚀

File: dot/digest/digest.go [hunk 3]
```diff
@@ -201,17 +201,26 @@ func (h *Handler) handleBabeConsensusDigest(digest scale.VaryingDataType, header
...
 
-		nextEpoch := currEpoch + 1
-		h.epochState.StoreBABENextConfigData(nextEpoch, headerHash, val)
-		h.logger.Debugf("stored BABENextConfigData data: %v for hash: %s to epoch: %d", digest, headerHash, nextEpoch)
-		return nil
+		switch nextConfigData := nextConfigDataVersion.(type) {
+		case types.NextConfigDataV1:
+			currEpoch, err := h.epochState.GetEpochForBlock(header)
+			if err != nil {
+				return fmt.Errorf("cannot get epoch for block %d (%s): %w", header.Number, headerHash, err)
```
Comment (kanishkatn) [inline dot/digest/digest.go:215]: https://github.com/ChainSafe/gossamer/pull/3228#discussion_r1181505625
```suggestion
				return fmt.Errorf("get epoch for block %d (%s): %w", header.Number, headerHash, err)
```

File: dot/digest/digest_integration_test.go [hunk 4]
```diff
@@ -381,13 +381,16 @@ func TestHandler_HandleNextEpochData(t *testing.T) {
...
-	nextConfigData := types.NextConfigData{
+	nextConfigData := types.NextConfigDataV1{
 		C1:             1,
 		C2:             8,
 		SecondarySlots: 1,
 	}
 
-	err := digest.Set(nextConfigData)
+	VersionedNextConfigData := types.NewVersionedNextConfigData()
+	VersionedNextConfigData.Set(nextConfigData)
```
Comment (kanishkatn) [inline dot/digest/digest_integration_test.go:391]:
```suggestion
	versionedNextConfigData := types.NewVersionedNextConfigData()
	versionedNextConfigData.Set(nextConfigData)
```

**Review by kanishkatn — DISMISSED** [review]
Looks good, just 2 change requests

File: dot/digest/digest_integration_test.go (hunk 4 above)
Comment (dimartiro) [reply dot/digest/digest_integration_test.go:391]: Good catch!

File: dot/digest/digest.go (hunk 3 above)
Comment (dimartiro) [reply dot/digest/digest.go]: Done! thank you

File: dot/digest/digest.go [hunk 5]
```diff
@@ -201,17 +201,26 @@ func (h *Handler) handleBabeConsensusDigest(digest scale.VaryingDataType, header
 	case types.BABEOnDisabled:
 		return nil
 
-	case types.NextConfigData:
-		currEpoch, err := h.epochState.GetEpochForBlock(header)
+	case types.VersionedNextConfigData:
+		nextVersionedConfigData := digestValue.(types.VersionedNextConfigData)
```
Comment (timwu20) [inline dot/digest/digest.go:205]:
```suggestion
		nextVersionedConfigData := val
```

Comment (dimartiro) [reply dot/digest/digest.go:205]: Good one! Done!

**Review by jimjbrettj — APPROVED** [review]
great work, lgtm!

**Review by timwu20 — APPROVED** [review]
