### PR TITLE
end-to-end tests: refactor and fix flaky tests

### LINKED ISSUE #2161: Fix Flaky Tests in `TestSystemRPC`
[Logs](https://github.com/ChainSafe/gossamer/runs/4009896511?check_suite_focus=true)

### PR DESCRIPTION
**Pull request by qdm12**
:bulb: **Review commit by commit** by starting with the [first commit](https://github.com/ChainSafe/gossamer/pull/2470/commits/f6013846bfcd8be3de6d81c0d52829a8b041c6dd)

### TLDR

- Fix flakky tests and add testing depth
- More robust code
- Detect runtime errors
- Better concerns separation
- Can easily run a single test independently & locally (after `make gossamer`)

### Details

- Faster `TestAuthorSubmitExtrinsic`
- Fix `TestSync_SingleBlockProducer` (#2167)
- refactor `compareBlocksByNumber`
- refactor `TestSystemRPC` (#2161)
  - add empty skipped tests for missing cases
  - split each subtest individually
  - keep on retrying until main context is canceled
  - fix `networkState` test case
  - assert more fields
  - fix #2161 and #807
- `retry.UntilNoError` function
  - Use in `compareBlocksByNumber`
  - Use in `waitForNode`
  - change `GetBlockHash` to not retry RPC
  - remove `PostWithRetry`
- remove global variables `maxTries` and `testTimeout` in stress tests
- refactor `getResponse`
  - not test aware (#2389)
  - get passed target interface
  - push test assertion/skip to actual test
- rework start and stop of nodes (#2391)
  - Remove unneeded logs
  - Prefix writer with node string for multiple nodes
  - Test writer using t.Logf
  - Wait for nodes after starting all nodes
  - Log when node is ready only
  - Init nodes in parallel
- split `tests/utils` package
  - `tests/utils/rpc` package
  - `tests/utils/websocket` package
  - `tests/utils/config` package
- remove `DecodeRPC_NT`
- remove `HOSTNAME` variable
- inline RPC method strings
- remove global variable `GenesisTwoAuthsSecondaryVRF0_9_10`
- remove global configuration variables
  - write no auth config to temp dir per test
  - write no grandpa config to temp dir per test
  - write no babe config to temp dir per test
  - write grandpa config to temp dir per test
  - write default config to temp dir per test
- remove global framework variable
- remove global variables `GenesisDefault` and `GenesisDev`
- Add `GenerateGenesisAuths` function
- use `t.TempDir()` for base paths
- `waitForNode` context based function (#2390)
- make RPC helpers not test aware (#2389)
- make `DecodeRPC` not test aware (#2389)

## Tests

- RPC suite passing
- Stress tests passing

## Issues

See issues mentioned in changes above.

Indirectly fixed: #2165

### CODE REVIEW

File: tests/utils/config/config.go [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+func NoGrandpa() (cfg toml.Config) {
+	cfg = Default()
+	cfg.Core.GrandpaAuthority = false
+	cfg.Core.BABELead = true
+	cfg.Core.GrandpaInterval = 1
+	return cfg
+}
+
+// NotAuthority generates an non-authority config.
+func NotAuthority() (cfg toml.Config) {
```
Comment (timwu20) [inline tests/utils/config/config.go:45]: nit:
```suggestion
func NotAuthorities() (cfg toml.Config) {
```

File: tests/utils/node/nodes.go [hunk 2]
```diff
@@ -0,0 +1,205 @@
...
+
+		// Set defaults using index `i`
+		nodes[i].tomlConfig.Core.BABELead = i == 0
+
+		if nodes[i].index == nil {
+			nodes[i].index = intPtr(i)
+		}
+
+		// Set node defaults on the remaining unset fields
+		nodes[i].setDefaults(t)
```
Comment (timwu20) [inline tests/utils/node/nodes.go:42]: should this use `node.NewNode`

File: tests/utils/node/node.go [hunk 3]
```diff
@@ -0,0 +1,275 @@
...
+}
+
+// GetRPCPort returns the rpc port of the node.
+func (n Node) GetRPCPort() (port string) { return fmt.Sprint(n.tomlConfig.RPC.Port) }
+
+// GetWSPort returns the websocket port of the node.
+func (n Node) GetWSPort() (port string) { return fmt.Sprint(n.tomlConfig.RPC.WSPort) }
+
+// GetKey returns the key of the node.
+func (n Node) GetKey() (key string) { return n.tomlConfig.Account.Key }
```
Comment (timwu20) [inline tests/utils/node/node.go:58]: nit: remove the `Get`

File: tests/utils/node/node.go [hunk 4]
```diff
@@ -0,0 +1,275 @@
...
+	return nil
+}
+
+// StartAndWait starts a Gossamer node using the node configuration of
+// the receiving struct. It returns a start error if the node cannot
+// be started, and runs the node until the context gets canceled.
+// When the node crashes or is stopped, an error (nil or not) is sent
+// in the waitErrCh.
+// It waits for the node to respond to an RPC health call before returning.
+func (n *Node) StartAndWait(ctx context.Context, waitErrCh chan<- error) (startErr error) {
```
Comment (timwu20) [inline tests/utils/node/node.go:167]: Usually the function should return a `chan error`.  As a best practice, producers should return channels.

File: tests/utils/rpc/dev.go [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+
+	"github.com/ChainSafe/gossamer/lib/common"
+)
+
+// PauseBABE calls the endpoint dev_control with the params ["babe", "stop"]
+func PauseBABE(ctx context.Context, rpcPort string) error {
+	endpoint := NewEndpoint(rpcPort)
+	const method = "dev_control"
+	const params = `["babe", "stop"]`
+	_, err := Post(ctx, endpoint, method, params)
```
Comment (timwu20) [inline tests/utils/rpc/dev.go:20]: @EclesioMeloJunior babe can be controlled by RPC?

File: tests/utils/chain.go [hunk 6]
```diff
@@ -7,132 +7,123 @@ import (
...
+	if err != nil {
+		return nil, fmt.Errorf("cannot decode RPC response body: %w", err)
+	}
 
-	stateRoot, err := common.HexToHash(header.StateRoot)
-	require.NoError(t, err)
+	rpcHeader := rpcBlock.Block.Header
+	header, err := headerResponseToHeader(rpcHeader)
+	if err != nil {
+		return nil, fmt.Errorf("malformed RPC header: %w", err)
```
Comment (EclesioMeloJunior) [inline tests/utils/chain.go]: I think the variable `header` is not from the RPC but from the block returned by the RPC call, so the message error could be `malformed block header: %w`

File: tests/utils/chain.go [hunk 7]
```diff
@@ -7,132 +7,123 @@ import (
...
+	}
 
-	extrinsicsRoot, err := common.HexToHash(header.ExtrinsicsRoot)
-	require.NoError(t, err)
+	body, err := types.NewBodyFromExtrinsicStrings(rpcBlock.Block.Body)
+	if err != nil {
+		return nil, fmt.Errorf("cannot create body from RPC block blody: %w", err)
```
Comment (EclesioMeloJunior) [inline tests/utils/chain.go]: fmt.Errorf("cannot create body from RPC block <strike>blody</strike>: %w", err)
fmt.Errorf("cannot create body from RPC block **body**: %w", err)

**Review by EclesioMeloJunior — CHANGES_REQUESTED** [review]

File: tests/utils/rpc/dev.go (hunk 5 above)
Comment (EclesioMeloJunior) [reply tests/utils/rpc/dev.go:20]: @timwu20 yes! In the `./dot/rpc/modules/dev.go` we expose the method `Control` which calls the `blockProducerAPI.Pause()/Resume()`

File: tests/utils/websocket/decode.go [hunk 8]
```diff
@@ -0,0 +1,51 @@
+// Copyright 2022 ChainSafe Systems (ON)
+// SPDX-License-Identifier: LGPL-3.0-only
+
+package websocket
```
[the remark this answers is not in the document]
Comment (qdm12) [reply tests/utils/websocket/decode.go]: Well it did, and the decode function was also a bit different. But it might just work, I merged them and removed the `websocket` package. The CI seems to pass so let's just assume this is resolved :wink:

File: tests/stress/grandpa_test.go [hunk 9]
```diff
@@ -42,51 +43,47 @@ func TestStress_Grandpa_OneAuthority(t *testing.T) {
...
+		const retryWait = time.Second
+		fin, err := compareFinalizedHeadsWithRetry(ctx,
+			nodes, uint64(i), getFinalizedHeadByRoundTimeout, retryWait)
 		require.NoError(t, err)
 		t.Logf("finalised hash in round %d: %s", i, fin)
 	}
 }
 
 func TestStress_Grandpa_SixAuthorities(t *testing.T) {
 	t.Skip()
```
[the remark this answers is not in the document]
Comment (qdm12) [reply tests/stress/grandpa_test.go:72]: I tried to unskip it, but it hangs forever. I'll create an issue for it.

File: tests/utils/chain.go (hunk 7 above)
Comment (qdm12) [reply tests/utils/chain.go]: Bloody body! Fixed :+1:

File: tests/utils/node/node.go (hunk 4 above)
Comment (qdm12) [reply tests/utils/node/node.go]: I ended up making the changes, returning error channels instead of injecting them. It made things a bit more complicated, I had to add a 'errors fan in' object to handle stuff in `tests/utils/runtime/errors.go` but it did make responsibilities clearer, for example a consumer CANNOT close a channel (shame on my previous self!).

File: tests/utils/node/nodes.go (hunk 2 above)
Comment (qdm12) [reply tests/utils/node/nodes.go]: Done 👍 
Now it always sets each node to have their 'index' as the index of the nodes slice, so the `SetIndex` option is ignored. We don't use anywhere so all good as well.

File: tests/rpc/rpc_01-system_test.go [hunk 10]
```diff
@@ -9,137 +9,194 @@ import (
...
+
+	t.Run("system_nodeRoles", func(t *testing.T) {
+		t.Parallel()
+		t.Skip("test not implemented")
+	})
+
+	t.Run("system_accountNextIndex", func(t *testing.T) {
+		t.Parallel()
+		t.Skip("test not implemented")
+	})
```
[the remark this answers is not in the document]
Comment (qdm12) [reply tests/rpc/rpc_01-system_test.go:201]: Done in #2546 (Dan created sub-issues as well)

File: tests/stress/grandpa_test.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (qdm12) [reply tests/stress/grandpa_test.go:72]: Created #2545

File: tests/stress/stress_test.go [hunk 11]
```diff
@@ -61,127 +49,140 @@ func TestMain(m *testing.M) {
...
-	ctx := context.Background()
 	const getChainHeadTimeout = time.Second
 
-	err = compareChainHeadsWithRetry(ctx, t, nodes, getChainHeadTimeout)
+	err := compareChainHeadsWithRetry(ctx, nodes, getChainHeadTimeout)
 	require.NoError(t, err)
 }
 
 func TestSync_MultipleEpoch(t *testing.T) {
 	t.Skip("skipping TestSync_MultipleEpoch")
```
[the remark this answers is not in the document]
Comment (qdm12) [reply tests/stress/stress_test.go:150]: Created #2544

File: tests/stress/stress_test.go [hunk 12]
```diff
@@ -334,98 +340,138 @@ func TestSync_Restart(t *testing.T) {
...
 		time.Sleep(time.Second * 5)
 	}
-	close(done)
+
+	mainCancel()
+	<-onOffRoutineDone
 }
 
 func TestSync_SubmitExtrinsic(t *testing.T) {
 	t.Skip()
```
[the remark this answers is not in the document]
Comment (qdm12) [reply tests/stress/stress_test.go:440]: Created #2542

File: tests/utils/node/node.go (hunk 3 above)
Comment (qdm12) [reply tests/utils/node/node.go]: I'll add it to the engineering wiki Go page

File: tests/stress/stress_test.go [hunk 13]
```diff
@@ -61,127 +49,137 @@ func TestMain(m *testing.M) {
...
+	ctx, cancel := context.WithCancel(context.Background())
 
-	err = utils.StartNodes(t, nodes)
-	require.NoError(t, err)
+	runtimeErrors, startErr := nodes.Start(ctx)
+	if startErr != nil {
+		cancel()
+		for _, runtimeError := range runtimeErrors {
+			<-runtimeError
+		}
```
Comment (timwu20) [inline tests/stress/stress_test.go:72]: could you put this in a helper if you don't actually care?

File: tests/utils/runtime/errors.go [hunk 14]
```diff
@@ -0,0 +1,156 @@
...
+		nodeToRuntimeError: make(map[string]<-chan error),
+		nodeToFaninCancel:  make(map[string]context.CancelFunc),
+		nodeToFaninDone:    make(map[string]<-chan struct{}),
+		fifo:               make(chan nodeError),
+	}
+}
+
+// Add adds a runtime error receiving channel to the fan in mechanism
+// for the particular node string given. Note each node string must be
+// unique or the code willp panic.
```
Comment (timwu20) [inline tests/utils/runtime/errors.go:44]:
```suggestion
// unique or the code will panic.
```

File: tests/utils/node/nodes.go [hunk 15]
```diff
@@ -0,0 +1,177 @@
...
+		t.Helper()
+		// Disengage node watchdog goroutine
+		watchDogCancel()
+		<-watchDogDone
+		// Stop and wait for nodes to exit
+		stopNodes(t, nodesCancel, runtimeErrors)
+	})
+}
+
+func stopNodes(t *testing.T, nodesCancel context.CancelFunc,
```
Comment (timwu20) [inline tests/utils/node/nodes.go:165]: curious as to why this isn't just a receiver function on `Nodes`?

File: tests/utils/node/nodes.go [hunk 16]
```diff
@@ -0,0 +1,177 @@
...
+		err := waitForNode(ctx, node.RPCPort())
+		if err == nil {
+			t.Logf("Node %s is ready", node)
+			continue
+		}
+
+		t.Errorf("Node %s failed to be ready: %s", node, err)
+		stopNodes(t, nodesCancel, runtimeErrors)
+		t.FailNow()
+	}
```
Comment (timwu20) [inline tests/utils/node/nodes.go:134]: why not just for the nodes in parallel and use a waitgroup?

File: tests/utils/node/nodes.go (hunk 15 above)
Comment (timwu20) [inline tests/utils/node/nodes.go:165]: curious as to why this isn't a receiver function on `Nodes`?

File: tests/utils/retry/common.go [hunk 17]
```diff
@@ -0,0 +1,28 @@
...
+
+package retry
+
+import (
+	"context"
+	"fmt"
+	"time"
+)
+
+func waitAfterFail(ctx context.Context, retryWait time.Duration,
```
Comment (timwu20) [inline tests/utils/retry/common.go:12]: I find all this decorating of contexts very difficult to follow.

File: tests/utils/rpc/models.go [hunk 18]
```diff
@@ -0,0 +1,30 @@
+// Copyright 2022 ChainSafe Systems (ON)
+// SPDX-License-Identifier: LGPL-3.0-only
+
```
Comment (timwu20) [inline tests/utils/rpc/models.go:3]: I would name this file `types.go`.

File: tests/utils/runtime/errors.go [hunk 19]
```diff
@@ -0,0 +1,156 @@
...
+
+import (
+	"context"
+	"errors"
+	"fmt"
+	"sync"
+	"time"
+)
+
+// ErrorsFanIn takes care of fanning runtime errors from
```
Comment (timwu20) [inline tests/utils/runtime/errors.go:14]: Can you explain why this needs to be exported? I would have assumed the `Nodes` type just handles this internally.

File: Dockerfile [hunk 20]
```diff
@@ -17,11 +17,6 @@ RUN wget -qO- https://deb.nodesource.com/setup_14.x | bash - && \
 RUN wget -O /usr/local/bin/subkey https://chainbridge.ams3.digitaloceanspaces.com/subkey-v2.0.0 && \
     chmod +x /usr/local/bin/subkey
 
-# Polkadot JS dependencies
-WORKDIR /go/src/github.com/ChainSafe/gossamer/tests/polkadotjs_test
-COPY tests/polkadotjs_test/package.json tests/polkadotjs_test/package-lock.json ./
-RUN npm install
-
```
[the remark this answers is not in the document]
Comment (qdm12) [reply Dockerfile:24]: No it's done in Go code at

https://github.com/ChainSafe/gossamer/blob/qdm12/tests-refactor-tip/tests/polkadotjs_test/start_polkadotjs_test.go#L28-L41

when the (single) test needing it is run

File: tests/utils/node/nodes.go (hunk 16 above)
Comment (qdm12) [reply tests/utils/node/nodes.go:134]: See the comment

```go
	// this is run sequentially since all nodes start almost at the same time
	// so waiting for one node will also wait for all the others.
	// You can see this since the test logs out that all the nodes are ready
	// at the same time.
```

We could do it in parallel, but it adds quite a bit of complexity for no practical advantage.

File: tests/utils/node/nodes.go (hunk 15 above)
Comment (qdm12) [reply tests/utils/node/nodes.go:165]: Because:

- all the arguments for this function are not part of the `Nodes`
- the calling tests do not need to stop multiple nodes so far

So I don't think there is a need to have it as a method. If one day a test needs to stop multiple nodes, then yeah we should move it as a receiver.

File: tests/utils/retry/common.go (hunk 17 above)
Comment (qdm12) [reply tests/utils/retry/common.go:12]: I understand you're not a fan of contexts (yet hehe!), I also like to keep it simple with signal channels.

But in this case we have different triggers that would cancel the context (aka close the channel), which can be the `cancel` function or the timer(s). Having these with a signal channel, multiple nested timers and select blocks would make it unreadable and needlessly complex. Even if context would not be part of std lib, I might consider using them in those cases 😉

File: tests/utils/runtime/errors.go (hunk 19 above)
Comment (qdm12) [reply tests/utils/runtime/errors.go]: I moved it to `utils/nodes` as unexported.

It was the Nodes initially handling this internally but that got messy rather quickly, so I split it away in that struct.
I then moved it to its own package to avoid polluting the namespace in utils/nodes, but that might had been overkill indeed.

File: tests/stress/stress_test.go (hunk 13 above)
Comment (qdm12) [reply tests/stress/stress_test.go]: Done!

File: tests/utils/retry/common.go (hunk 17 above)
Comment (timwu20) [reply tests/utils/retry/common.go:12]: This function is called by `retry.UntilOk(ctx context.Context, poll time.Duration, func() (ok bool, err error)`.  If you made the signature of this function `retry.UntilOk(timeout time.Duration, poll time.Duration, func() (ok bool, err error)`, you could just handle the timeout and deadline internally without having to worry about passing in a context.   

In your tests you declare a global `ctx` before using this, and in the function you pass to `retry.UntilOK`, you add a timeout to that context using `context.WithTimeout`, and you do it again in `waitAfterFail`.  Not sure how this approach of decorating contexts from a parent to handle long running processes is easier to read.  I just want to reiterate, that contexts should be request scoped, and not for long running processes.  It would make sense to use a context to facilitate cancellation and deadline for an RPC call.  But cancellation shouldn't be confused with explicit stopping of long running services/goroutines.

Taken from Dave Cheney's blog: 
> However, context.Context‘s most important facility, broadcasting a cancellation signal, is incomplete as there is no way to wait for the signal to be acknowledged.
This is the problem when conflating cancellation and explicit stopping.  There's no way for us to know if services have actually stopped if you use contexts for stopping long running processes.

**Review by timwu20 — APPROVED** [review]

File: tests/utils/retry/common.go (hunk 17 above)
Comment (qdm12) [reply tests/utils/retry/common.go:12]: > you could just handle the timeout and deadline internally without having to worry about passing in a context.

No because the top level context is used for nodes and is canceled when one of them crashes. So it's a mix of timeout and event driven, which would be very tedious to implement with channels and timers only, especially considering the different timeouts values here and there, there would be a lot more select cases all over the place.

> But cancellation shouldn't be confused with explicit stopping of long running services/goroutines.

At the end of the day, you do need a signal channel (internally or not) to signal to stop a long running goroutine. Contexts are just here to ease mixing event driven and time driven cancellation, without having to create a bunch of sub-signal-channels and sub-timers.

> is incomplete as there is no way to wait for the signal to be acknowledged.

Yes, but this is a bit out of scope; it is the same when closing a channel to stop a goroutine, you need another signal channel to wait for the goroutine to exit (and I agree this sucks too).
Such signal channels are implemented (or it's registered in `t.Cleanup`) in those tests.
