### PR TITLE
lib/crypto: fix PubkeyToAddress to conform to ss58

### LINKED ISSUE #845: fix public key to ss58 address bug.
the function is  wrong that public key to ss58 address.
wrong code:
```
func PublicKeyToAddress(pub PublicKey) common.Address {
	enc := pub.Encode()
	hasher, err := blake2b.New(64, nil)
	if err != nil {
		return ""
	}

	_, err = hasher.Write(append(ss58Prefix, enc...))
	if err != nil {
		return ""
	}
	checksum := hasher.Sum(nil)
	return common.Address(base58.Encode(append(enc, checksum[:2]...)))
}
```
right code:
```
func PublicKeyToAddress(pub PublicKey) common.Address {
	enc := append([]byte{42},pub.Encode()...)  //should add 42 type
	hasher, err := blake2b.New(64, nil)
	if err != nil {
		return ""
	}

	_, err = hasher.Write(append(ss58Prefix, enc...))
	if err != nil {
		return ""
	}
	checksum := hasher.Sum(nil)
	return common.Address(base58.Encode(append(enc, checksum[:2]...)))
}

```

### PR DESCRIPTION
**Pull request by noot**
## Changes

- fix PubkeyToAddress to conform to ss58
- add test case
- https://github.com/paritytech/substrate/wiki/External-Address-Format-(SS58) 42 is substrate wildcard

## Tests:

```
go test ./lib/crypto
```

## Checklist:

- [x] I have read [CONTRIBUTING](CONTRIBUTING.md) and [CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)
- [x] I have provided as much information as possible and necessary
- [x] I have reviewed my own pull request before requesting a review
- [x] I have linked any relevant issues in my pull request comments
- [x] All integration tests and required coverage checks are passing

## Issues:

- closes #845

### CODE REVIEW

File: lib/crypto/keypair_test.go [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+func TestPubkeyToAddress(t *testing.T) {
+	// randomly generated from subkey
+	pub, _ := common.HexToBytes("0x6ec2950d29adda8d965d06fc78b7e05f8923b8de3e312c7b5957cdcfd8d4820c")
+	addr := "5EZvvkH5RUjigUNT7pabMzMnHtmrYamsSe7yW6vVACBzTHFe"
+
+	pk, err := sr25519.NewPublicKey(pub)
+	require.NoError(t, err)
+	a := pk.Address()
+	require.Equal(t, addr, string(a))
+}
```
Comment (ryanchristo) [inline lib/crypto/keypair_test.go:21]: should we add a test case for an invalid pubkey? not necessary but easy to add.

Comment (noot) [reply lib/crypto/keypair_test.go:21]: there should be tests for invalid pubkeys in the crypto libraries, I don't think it's relevant here since the `.Address()` function calls `PublicKeyToAddress` which assumes the pubkey is valid
