### PR TITLE
fix(dot/digest): verify if next epoch already contains some definition

### LINKED ISSUE #2471: check if the BABE next epoch is already persisted
## Describe the bug

In the `dot/digest` package we listen for finalized headers and when a new finalized header arrives we execute the function `persistBABEDigestsForNextEpoch(finalizedHeader *types.Header)`. This function retrieves the epoch for the finalized header add `1` and uses the result as the `nextEpoch` and then call the `h.epochState.FinalizeBABENextEpochData(nextEpoch)` and `h.epochState.FinalizeBABENextConfigData(nextEpoch)` in order to persist the next epoch BABE data and config and remove the in memory data.

The problem is that when another header is finalized in the same epoch we call the same functions again but this time they will fail as there is no data to persist in the database.

A possible solution is to check if the `nextEpoch` already has defined some data in the database and if so we skip the respective persistency step

### PR DESCRIPTION
**Pull request by EclesioMeloJunior**
## Changes

- Add `epochState.AlreadyDefined(epoch uint64)` method that verifies if the epoch already contains the epoch or config data
- Use the previous method in the `persistBABEDigestsForNextEpoch` to avoid persistence many times in the same epoch

## Tests

Test the `dot/digest` and `dot/state` pkgs
```sh
go test github.com/ChainSafe/gossamer/dot/digest
go test github.com/ChainSafe/gossamer/dot/state
```

## Issues

closes #2471

## Primary Reviewer

@timwu20

### CODE REVIEW

File: dot/state/epoch_test.go [hunk 1]
```diff
@@ -591,12 +597,24 @@ func TestStoreAndFinalizeBabeNextConfigData(t *testing.T) {
 			err := epochState.blockState.db.Put(headerKey(tt.finalizeHash), []byte{})
 			require.NoError(t, err)
 
+			// before finalize next config data this epoch should not be defined
```
Comment (qdm12) [inline dot/state/epoch_test.go:600]: nit maybe a word missing I think?

```suggestion
			// before finalize next config data for this epoch should not be defined
```

File: dot/state/epoch_test.go [hunk 2]
```diff
@@ -591,12 +597,24 @@ func TestStoreAndFinalizeBabeNextConfigData(t *testing.T) {
...
+			require.False(t, definedEpochData)
+			require.False(t, definedConfigData)
+
 			err = epochState.FinalizeBABENextConfigData(tt.finalizeEpoch)
 			if tt.expectErr != nil {
 				require.ErrorIs(t, err, tt.expectErr)
 			} else {
 				require.NoError(t, err)
 
+				// after finalize next config data this epoch should be defined
```
Comment (qdm12) [inline dot/state/epoch_test.go:612]: nit maybe a word missing I think?

```suggestion
				// after finalize next config data for this epoch should be defined
```

File: dot/state/epoch_test.go [hunk 3]
```diff
@@ -591,12 +597,24 @@ func TestStoreAndFinalizeBabeNextConfigData(t *testing.T) {
...
+				definedEpochData, definedConfigData, err = epochState.AlreadyDefined(tt.finalizeEpoch)
+				require.NoError(t, err)
+				require.False(t, definedEpochData)
```
Comment (qdm12) [inline dot/state/epoch_test.go:615]: This is meant to be false right? (after finalize)

File: dot/state/epoch_test.go [hunk 4]
```diff
@@ -401,12 +401,24 @@ func TestStoreAndFinalizeBabeNextEpochData(t *testing.T) {
...
+			require.False(t, definedEpochData)
+			require.False(t, definedConfigData)
+
 			err = epochState.FinalizeBABENextEpochData(tt.finalizeEpoch)
 			if tt.expectErr != nil {
 				require.ErrorIs(t, err, tt.expectErr)
 			} else {
 				require.NoError(t, err)
 
+				// after finalize next epoch data this epoch should not defined
```
Comment (qdm12) [inline dot/state/epoch_test.go:416]: nit I think `for` is missing here?

```suggestion
				// after finalize next epoch data for this epoch should not defined
```

File: dot/state/epoch_test.go [hunk 5]
```diff
@@ -401,12 +401,24 @@ func TestStoreAndFinalizeBabeNextEpochData(t *testing.T) {
 			err := epochState.blockState.db.Put(headerKey(tt.finalizeHash), []byte{})
 			require.NoError(t, err)
 
+			// before finalize next epoch data this epoch should not be defined
```
Comment (qdm12) [inline dot/state/epoch_test.go:404]: nit I think `for` is missing here?

```suggestion
			// before finalize next epoch data for this epoch should not be defined
```

File: dot/state/epoch_test.go [hunk 6]
```diff
@@ -226,10 +226,10 @@ func TestEpochState_GetEpochFromTime(t *testing.T) {
...
 }
 
-type inMemoryNextEpochData struct {
-	epoch          uint64
-	hashes         []common.Hash
-	nextEpochDatas []types.NextEpochData
+type inMemoryBABEData[T any] struct {
+	epoch  uint64
+	hashes []common.Hash
+	Data   []T
```
Comment (qdm12) [inline dot/state/epoch_test.go:232]: nit Can we have `Data` unexported as `data`?

Also generics are going wild :tiger: !!

File: dot/state/epoch.go [hunk 7]
```diff
@@ -512,6 +512,30 @@ func (s *EpochState) SkipVerify(header *types.Header) (bool, error) {
 	return false, nil
 }
 
+// AlreadyDefined will true for each returned value if it is already defined in the database for the given epoch
+func (s *EpochState) AlreadyDefined(epoch uint64) (epochData bool, configData bool, err error) {
+	keys := [...][]byte{epochDataKey(epoch), configDataKey(epoch)}
+	applied := [...]bool{false, false}
```
Comment (qdm12) [inline dot/state/epoch.go:518]: Why use arrays? Can't we use some `epochDataKeyByte` and `configDataKeyByte` variables instead, and update `epochData` and `configData` without a for loop?

That would be a bit longer code, but quite easier to follow/read I think.

Also I would think splitting this function in two, one for epochData and one for configData would be nice (without using generics lol).

File: dot/digest/interface.go [hunk 8]
```diff
@@ -18,6 +18,7 @@ type BlockState interface {
 	FreeFinalisedNotifierChannel(ch chan *types.FinalisationInfo)
 }
 
+//go:generate mockgen -destination=mock_epoch_state_test.go -package $GOPACKAGE . EpochState
```
Comment (qdm12) [inline dot/digest/interface.go:21]: add an empty line so it's not part of `EpochState`'s comment

```suggestion
//go:generate mockgen -destination=mock_epoch_state_test.go -package $GOPACKAGE . EpochState

```

File: dot/digest/digest_test.go [hunk 9]
```diff
@@ -515,3 +516,73 @@ func TestHandler_HandleNextConfigData(t *testing.T) {
 	require.NoError(t, err)
 	require.Equal(t, act.ToConfigData(), stored)
 }
+
+func Test_persistBABEDigestsForNextEpoch(t *testing.T) {
+	type testStruct struct {
+		defineNextEpochData          bool
+		defineNextConfigData         bool
+		expectedErr                  error
+		alreadyDefinedFuncThrowError bool
```
Comment (qdm12) [inline dot/digest/digest_test.go:525]: nit you could define your mocks using functional fields if you want. [example](https://gist.github.com/qdm12/99358e2529a5887ae13a936a7f1c8ae5#file-potato_test-go-L230)

File: dot/digest/digest.go [hunk 10]
```diff
@@ -267,23 +265,29 @@ func (h *Handler) persistBABEDigestsForNextEpoch(finalizedHeader *types.Header)
...
 	}
 
-	err = h.epochState.FinalizeBABENextConfigData(nextEpoch)
-	if err == nil {
-		return nil
-	} else if errors.Is(err, state.ErrEpochNotInMemory) {
-		return fmt.Errorf("%w: %s", ErrDefineNextEpoch, err)
+	if !appliedEpochData {
+		err = h.epochState.FinalizeBABENextEpochData(nextEpoch)
+		if err != nil && !errors.Is(err, state.ErrEpochNotInMemory) {
```
Comment (qdm12) [inline dot/digest/digest.go:276]: What do we do in the case where `errors.Is(err, state.ErrEpochNotInMemory)`? Should we just continue execution?

File: dot/digest/digest.go [hunk 11]
```diff
@@ -267,23 +265,29 @@ func (h *Handler) persistBABEDigestsForNextEpoch(finalizedHeader *types.Header)
...
+				finalizedHeader.Number, finalizedHeader.Hash(), err)
+		}
 	}
 
-	// the epoch state does not contains any information about the next epoch
-	return fmt.Errorf("cannot finalize babe next config data for block number %d (%s): %w",
-		finalizedHeader.Number, finalizedHeader.Hash(), err)
+	if !appliedConfigData {
+		err = h.epochState.FinalizeBABENextConfigData(nextEpoch)
+		if err != nil && !errors.Is(err, state.ErrEpochNotInMemory) {
```
Comment (qdm12) [inline dot/digest/digest.go:284]: What do we do in the case where `errors.Is(err, state.ErrEpochNotInMemory)`? Should we just continue execution?

File: dot/state/epoch_test.go (hunk 3 above)
Comment (EclesioMeloJunior) [reply dot/state/epoch_test.go:615]: Yeah, we finalize only the `NextConfigData` so `definedEpochData` should be false

File: dot/digest/digest_test.go (hunk 9 above)
Comment (EclesioMeloJunior) [reply dot/digest/digest_test.go:525]: Nice suggestion, shrink the test conditions

File: dot/digest/digest.go [hunk 12]
```diff
@@ -267,23 +265,29 @@ func (h *Handler) persistBABEDigestsForNextEpoch(finalizedHeader *types.Header)
...
+			return fmt.Errorf("cannot finalize babe next config data for block number %d (%s): %w",
+				finalizedHeader.Number, finalizedHeader.Hash(), err)
+		}
```
Comment (noot) [inline dot/digest/digest.go:287]: not every epoch will have `ConfigData`, if it doesn't, it should just use the last set config data. does this handle that case? it seems to me  like it doesn't

File: dot/digest/digest.go [hunk 13]
```diff
@@ -267,23 +265,29 @@ func (h *Handler) persistBABEDigestsForNextEpoch(finalizedHeader *types.Header)
...
 	nextEpoch := currEpoch + 1
-	err = h.epochState.FinalizeBABENextEpochData(nextEpoch)
-	if err != nil && !errors.Is(err, state.ErrEpochNotInMemory) {
-		return fmt.Errorf("cannot finalize babe next epoch data for block number %d (%s): %w",
-			finalizedHeader.Number, finalizedHeader.Hash(), err)
+
+	appliedEpochData, appliedConfigData, err := h.epochState.AlreadyDefined(nextEpoch)
+	if err != nil {
+		return fmt.Errorf("cannot check if next epoch is already defined: %w", err)
 	}
```
Comment (noot) [inline dot/digest/digest.go:272]: I'm kind of confused still as to why this is needed - a block won't be finalized twice, so what is the case where the digest data would already be set in the database? also, it would be cleaner to handle the digest check + writing to disk all the in `EpochState` instead of here.

File: dot/digest/digest.go (hunk 10 above)
Comment (noot) [reply dot/digest/digest.go:276]: I think this function should only be called if `finalizedHeader` is the first block in its epoch, as that's the only block that would contain `NextEpoch` or `NextConfig` digests. that would also prevent the spamming

Comment (EclesioMeloJunior) [reply dot/digest/digest.go:276]: But, what about the case of the epoch 1 started at block `N` but the finalized block is the block `N + 2`, we will not persist the next epoch data because the finalized block is not the first in its epoch.

File: dot/state/epoch.go [hunk 14]
```diff
@@ -573,24 +591,45 @@ func (s *EpochState) FinalizeBABENextEpochData(epoch uint64) error {
...
+		return fmt.Errorf("cannot check if next epoch config is already defined for epoch %d: %w", nextEpoch, err)
+	}
+
+	// config already defined we don't need to lookup in the map
+	if configInDatabase != nil {
+		return nil
+	}
+
+	// not every epoch will have `ConfigData`
+	finalizedNextConfigData, err := lookupForNextEpochPersistedHash(s.nextConfigData, s, nextEpoch)
```
Comment (noot) [inline dot/state/epoch.go:617]: can we rename this function `lookupForNextEpochPersistedHash` to something like `findNextInfoFromMemory`?

**Review by noot — APPROVED** [review]
looks good!

File: dot/state/epoch.go (hunk 14 above)
Comment (EclesioMeloJunior) [reply dot/state/epoch.go:617]: This function checks in the memory for the hash which is persisted in the database, what about `findFinalizedHeaderForEpoch`? meaning that we need to have in the epoch map one hash that is persisted in the database.

File: dot/state/epoch_test.go [hunk 15]
```diff
@@ -539,38 +557,11 @@ func TestStoreAndFinalizeBabeNextConfigData(t *testing.T) {
...
-							C1:             3,
-							C2:             4,
-							SecondarySlots: 0,
-						},
-					},
-				},
-			},
+		"in_memory_config_not_found_shouldnt_return_error": {
+			shouldRemainInMemory: 0,
+			finalizeEpoch:        1, // try to finalize a epoch that does not exists
```
Comment (qdm12) [inline dot/state/epoch_test.go:562]: supernit

```suggestion
			finalizeEpoch:        1, // try to finalize an epoch that does not exist
```

File: dot/state/epoch_test.go [hunk 16]
```diff
@@ -422,33 +423,50 @@ func TestStoreAndFinalizeBabeNextEpochData(t *testing.T) {
...
+		types.PreRuntimeDigest{}))
+
+	require.NoError(t, digest.Add(*preRuntimeDigest))
+
+	// a random finalized header for testing purposes
+	finalizedHeader := &types.Header{
+		ParentHash: common.Hash{},
+		Number:     1,
+		Digest:     digest,
+	}
```
Comment (qdm12) [inline dot/state/epoch_test.go:446]: nit it's not really random, is it? :thinking:

**Review by qdm12 — APPROVED** [review]
:+1:

File: dot/state/epoch.go [hunk 17]
```diff
@@ -573,35 +591,56 @@ func (s *EpochState) FinalizeBABENextEpochData(epoch uint64) error {
...
+	}
+
+	// config already defined we don't need to lookup in the map
+	if configInDatabase != nil {
+		return nil
+	}
+
+	// not every epoch will have `ConfigData`
+	finalizedNextConfigData, err := findFinalizedHeaderForEpoch(s.nextConfigData, s, nextEpoch)
+	if errors.Is(err, ErrEpochNotInMemory) {
```
Comment (kishansagathiya) [inline dot/state/epoch.go:618]: Are we likely to come across `ErrEpochNotInMemory` a lot?

File: dot/state/epoch_test.go (hunk 6 above)
Comment (kishansagathiya) [reply dot/state/epoch_test.go]: I am starting to see why go did not have generics. The code without them looks so much better!

File: dot/state/epoch.go [hunk 18]
```diff
@@ -540,11 +540,29 @@ func (s *EpochState) StoreBABENextConfigData(epoch uint64, hash common.Hash, nex
...
-	finalizedNextEpochData, err := lookupForNextEpochPersistedHash(s.nextEpochData, s, epoch)
+	finalizedBlockEpoch, err := s.GetEpochForBlock(finalizedHeader)
+	if err != nil {
+		return fmt.Errorf("cannot get epoch for block %d (%s): %w",
+			finalizedHeader.Number, finalizedHeader.Hash(), err)
+	}
+
+	nextEpoch := finalizedBlockEpoch + 1
+
+	epochInDatabase, err := s.getEpochDataInDatabase(nextEpoch)
```
Comment (kishansagathiya) [inline dot/state/epoch.go:555]: better to rename this as `getEpochDataFromDatabase`

File: dot/state/epoch.go [hunk 19]
```diff
@@ -540,11 +540,29 @@ func (s *EpochState) StoreBABENextConfigData(epoch uint64, hash common.Hash, nex
...
+	if err != nil && !errors.Is(err, chaindb.ErrKeyNotFound) {
+		return fmt.Errorf("cannot check if next epoch data is already defined for epoch %d: %w", nextEpoch, err)
+	}
+
+	// config already defined we don't need to lookup in the map
```
Comment (kishansagathiya) [inline dot/state/epoch.go:560]: do you mean epoch data already defined (and not config)?
because there is also a config data which also gets written to the db

File: dot/state/epoch.go [hunk 20]
```diff
@@ -573,35 +591,56 @@ func (s *EpochState) FinalizeBABENextEpochData(epoch uint64) error {
...
-	finalizedNextConfigData, err := lookupForNextEpochPersistedHash(s.nextConfigData, s, epoch)
+	finalizedBlockEpoch, err := s.GetEpochForBlock(finalizedHeader)
 	if err != nil {
+		return fmt.Errorf("cannot get epoch for block %d (%s): %w",
+			finalizedHeader.Number, finalizedHeader.Hash(), err)
+	}
+
+	nextEpoch := finalizedBlockEpoch + 1
+
+	configInDatabase, err := s.getConfigDataInDatabase(nextEpoch)
```
Comment (kishansagathiya) [inline dot/state/epoch.go:606]: getConfigDataInDatabase -> getConfigDataFromDatabase

**Review by kishansagathiya — CHANGES_REQUESTED** [review]

File: dot/state/epoch.go [hunk 21]
```diff
@@ -573,35 +591,56 @@ func (s *EpochState) FinalizeBABENextEpochData(epoch uint64) error {
...
+	if err != nil && !errors.Is(err, chaindb.ErrKeyNotFound) {
+		return fmt.Errorf("cannot check if next epoch config is already defined for epoch %d: %w", nextEpoch, err)
+	}
+
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply dot/state/epoch.go:610]: This is deliberate, I call the `getConfigDataInDatabase` and if I got the `chaindb.ErrKeyNotFound` error I don't need to return an error since this error tells me a key is not present in the database

File: dot/state/epoch.go (hunk 17 above)
Comment (EclesioMeloJunior) [reply dot/state/epoch.go:618]: I'm not sure but, in this case, we will always use the previous epoch config data.

File: dot/digest/digest.go (hunk 10 above)
Comment (noot) [reply dot/digest/digest.go]: right, yeah this should be fine then

File: dot/state/epoch.go (hunk 14 above)
Comment (noot) [reply dot/state/epoch.go]: the function doesn't return a header though so that's kind of confusing I think

**Review by kishansagathiya — APPROVED** [review]

File: dot/state/epoch.go (hunk 17 above)
Comment (EclesioMeloJunior) [reply dot/state/epoch.go:624]: Added a `logger.Debugf` inside this if condition

**Review by kishansagathiya — APPROVED** [review]

File: dot/state/epoch.go [hunk 22]
```diff
@@ -573,35 +594,60 @@ func (s *EpochState) FinalizeBABENextEpochData(epoch uint64) error {
...
 		}
 	}
 
 	return nil
 }
 
-// lookupForNextEpochPersistedHash given a specific epoch (the key) will go through the hashes looking
+// findFinalizedHeaderForEpoch given a specific epoch (the key) will go through the hashes looking
 // for a database persisted hash (belonging to the finalized chain)
 // which contains the right configuration to be persisted and safely used
```
Comment (qdm12) [inline dot/state/epoch.go:649]: Update comment

```suggestion
// which contains the right configuration or data to be persisted and safely used
```

File: dot/state/epoch_test.go [hunk 23]
```diff
@@ -580,24 +571,32 @@ func TestStoreAndFinalizeBabeNextConfigData(t *testing.T) {
...
 				for i, hash := range e.hashes {
-					epochState.StoreBABENextConfigData(e.epoch, hash, e.nextConfigDatas[i])
+					epochState.StoreBABENextConfigData(e.epoch, hash, e.nextData[i])
 				}
 			}
 
 			require.Len(t, epochState.nextConfigData, len(tt.inMemoryEpoch))
 
-			expectedConfigData := epochState.nextConfigData[tt.finalizeEpoch][tt.finalizeHash]
+			// if there is no data in memory we try to finalize the net config data
```
Comment (qdm12) [inline dot/state/epoch_test.go:580]:
```suggestion
			// if there is no data in memory we try to finalize the next config data
```

**Review by qdm12 — APPROVED** [review]
Just two small suggestions
