### PR TITLE
fix(lib/runtime/storage): `NextKeys` failed after a transaction commit

### LINKED ISSUE #4057: bug(lib/runtime/trie): transaction `sortedKeys` are lost after commit
## Describe the bug

- Westend is stale at block #11541504 with the problem `Storage root must match that calculated`.
- That block contains a failed extrinsic (`remove_recovery`)
image
- That Pallet call is implemented [here](https://github.com/paritytech/substrate/blob/3348e144f0a2b39ce08bd8e3b976c42fe0c990b9/frame/recovery/src/lib.rs#L646) and after an investigation the problem is that this line:

```
ensure!(active_recoveries.next().is_none(), Error::<T>::StillActive);
```

This check is not being activated which is causing the error.

After an investigation I could check that the `iter_prefix_values`, method used to get the `active_recoveries`, actually calls the `next keys` method, so I started doing some speculations and wrote few tests.

The problem happens when you insert few keys and values under a transaction

```go
ts := NewTrieState(inmemory_trie.NewEmptyTrie())

fstKey := []byte("acc:abc123:ddd")
sndKey := []byte("acc:abc123:eee")
thdKey := []byte("acc:abc123:fff")

ts.StartTransaction()
 require.NoError(t, ts.Put(fstKey, []byte("0x10")))
 require.NoError(t, ts.Put(sndKey, []byte("0x11")))
 require.NoError(t, ts.Put(thdKey, []byte("0x12")))
ts.CommitTransaction()
```

and if you try to get the next key it will return `nil` instead of a actual valid key

```go
prefix := []byte("acc:abc123")

ts.StartTransaction()
nxtKey := ts.NextKey(prefix)
require.NotNil(nxtKey)
ts.CommitTransaction()
```

### PR DESCRIPTION
**Pull request by EclesioMeloJunior**
## Changes

- Update main state `sortedKeys` after transaction commit
- When retrieving the next key under a transaction, remove the `tx.deletes` from the main state `sortedKeys` ensuring we don't retrieve deleted keys

## Tests

```sh
go test -timeout 10m -run ^TestNextKeys$ github.com/ChainSafe/gossamer/lib/runtime/storage
```

## Issues

- Closes https://github.com/ChainSafe/gossamer/issues/4057

### CODE REVIEW

File: lib/runtime/storage/trie.go [hunk 1]
```diff
@@ -192,18 +211,29 @@ func (t *TrieState) NextKey(key []byte) []byte {
...
+		mainStateSortedKeys := make([]string, len(t.sortedKeys))
+		copy(mainStateSortedKeys, t.sortedKeys)
+
+		mainStateSortedKeys = slices.DeleteFunc(mainStateSortedKeys, func(s string) bool {
+			_, ok := currentTx.deletes[s]
+			return ok
+		})
+
+		allSortedKeys := append(mainStateSortedKeys, currentTx.sortedKeys...)
+		sort.Strings(allSortedKeys)
```
Comment (dimartiro) [inline lib/runtime/storage/trie.go:223]: What if instead of creating the slice + copying + deleting + sorting, we just do inserts + sort? I think it could be better in terms of performance

```suggestion
		// Get current tx sorted keys
		allSortedKeys := currentTx.sortedKeys

		// Add main trie sorted keys
		for _, s := range t.sortedKeys {
			if _, ok := currentTx.deletes[s]; !ok {
				allSortedKeys = append(allSortedKeys, s)
			}
		}

		// Sort all
		sort.Strings(allSortedKeys)
```

**Review by dimartiro — APPROVED** [review]
Approved with suggestion

**Review by jimjbrettj — APPROVED** [review]
nice work! lgtm

File: lib/runtime/storage/trie.go (hunk 1 above)
Comment (dimartiro) [reply lib/runtime/storage/trie.go:223]: nvm, I benchmarked it and they are almost the same we can keep it as it
