### PR TITLE
fix(dot/core): check transaction Validity.Propagate field to determine whether to propagate tx

### LINKED ISSUE #1610: check transaction `Validity.Propagate` field to determine whether to propagate tx
## Task summary

- when a tx is validated and put in the pool it has a `Validity` field with contains a `Propagate` bool
- this should be checked by the `network.Service.handleTransactionMessage` function which should return whether to propagate the tx or not

### PR DESCRIPTION
**Pull request by edwardmack**
## Changes

- add check to HandleTransactionMessage  to check Validity.Propagate field and determine if tx should be propagated. 
-
-

## Tests

```

```

## Issues

- closes #1610

### CODE REVIEW

**Review by noot — CHANGES_REQUESTED** [review]
this doesn't implement the functionality of the issue which is to use the propagate field to check whether to propagate the tx to the rest of the network, you will need to update the `handleTransactionMessage` function in `dot/network/transaction.go` for this. the `bool` it returns is whether to propagate the message or not

File: dot/core/messages.go [hunk 1]
```diff
@@ -17,29 +17,31 @@
...
 
 // HandleTransactionMessage validates each transaction in the message and
 // adds valid transactions to the transaction queue of the BABE session
-func (s *Service) HandleTransactionMessage(msg *network.TransactionMessage) error {
+func (s *Service) HandleTransactionMessage(msg *network.TransactionMessage) (bool, error) {
 	logger.Debug("received TransactionMessage")
 	if !s.isBlockProducer {
-		return nil
+		return false, nil
 	}
```
Comment (noot) [inline dot/core/messages.go:33]: you can remove these lines, we should be validating + propagating tx messages even if we aren't block producers

File: dot/core/messages.go [hunk 2]
```diff
@@ -17,29 +17,31 @@
...
-
+	var toRemove []types.Extrinsic
 	for _, tx := range txs {
 		// validate each transaction
 		externalExt := types.Extrinsic(append([]byte{byte(types.TxnExternal)}, tx...))
 		val, err := s.rt.ValidateTransaction(externalExt)
 		if err != nil {
 			logger.Error("failed to validate transaction", "err", err)
-			return err
+			return false, err
```
Comment (noot) [inline dot/core/messages.go:44]: don't return here but continue, and mark this tx "do not propagate" instead

File: dot/core/messages.go [hunk 3]
```diff
@@ -48,7 +50,28 @@ func (s *Service) HandleTransactionMessage(msg *network.TransactionMessage) erro
 		// push to the transaction queue of BABE session
 		hash := s.transactionState.AddToPool(vtx)
 		logger.Trace("Added transaction to queue", "hash", hash)
+
+		// find tx(s) that should not propagate
+		if !val.Propagate {
+			toRemove = append(toRemove, tx)
+		}
```
Comment (noot) [inline dot/core/messages.go:57]: it might be more straightforward to have a list of extrinsics to propagate instead of `toRemove`, and add valid txs with `Propagate == true` to it, that way you don't need to use `findAndDelete`

**Review by noot — COMMENTED** [review]
logic on the network side looks good, just some code suggestions!

File: dot/core/messages.go (hunk 1 above)
Comment (edwardmack) [reply dot/core/messages.go]: removed.

File: dot/core/messages.go (hunk 2 above)
Comment (edwardmack) [reply dot/core/messages.go:41]: makes sense, updated.

File: dot/core/messages.go (hunk 3 above)
Comment (edwardmack) [reply dot/core/messages.go:54]: Yes, more straightforward and readable, updated.

**Comment by edwardmack** [comment]
Update code to address comments, ready for re-review.

File: dot/core/messages.go [hunk 4]
```diff
@@ -24,19 +24,20 @@ import (
 
 // HandleTransactionMessage validates each transaction in the message and
 // adds valid transactions to the transaction queue of the BABE session
```
Comment (EclesioMeloJunior) [inline dot/core/messages.go:26]: Would be nice to have a description that the bool return means there is extrinsic to propagate.

**Review by EclesioMeloJunior — APPROVED** [review]

File: dot/core/messages.go (hunk 4 above)
Comment (edwardmack) [reply dot/core/messages.go:26]: good point... Updated.

File: dot/core/messages.go [hunk 5]
```diff
@@ -24,19 +24,21 @@ import (
...
-
+	var toPropagate []types.Extrinsic
 	for _, tx := range txs {
 		// validate each transaction
 		externalExt := types.Extrinsic(append([]byte{byte(types.TxnExternal)}, tx...))
 		val, err := s.rt.ValidateTransaction(externalExt)
 		if err != nil {
 			logger.Error("failed to validate transaction", "err", err)
-			return err
+			val.Propagate = false
```
Comment (noot) [inline dot/core/messages.go:40]: I think `val` will be `nil` if there's an error returned? you can remove this anyways, as it will move to the next tx

File: dot/core/messages_test.go [hunk 6]
```diff
@@ -157,8 +157,9 @@ func TestService_HandleTransactionMessage(t *testing.T) {
 	extBytes := createExtrinsics(t, s.rt, genHash, 0)
 
 	msg := &network.TransactionMessage{Extrinsics: []types.Extrinsic{extBytes}}
-	err = s.HandleTransactionMessage(msg)
+	b, err := s.HandleTransactionMessage(msg)
```
Comment (noot) [inline dot/core/messages_test.go:160]: can you also add a test case for invalid extrinsics?

**Review by timwu20 — APPROVED** [review]

File: dot/core/messages.go [hunk 7]
```diff
@@ -24,19 +24,21 @@ import (
 
 // HandleTransactionMessage validates each transaction in the message and
 // adds valid transactions to the transaction queue of the BABE session
-func (s *Service) HandleTransactionMessage(msg *network.TransactionMessage) error {
+// returns boolean for transaction propagation, true - transactions should be propagoted
```
Comment (arijitAD) [inline dot/core/messages.go:27]: `propagoted` -> `propagated`

**Review by arijitAD — APPROVED** [review]

File: dot/core/messages.go (hunk 5 above)
Comment (edwardmack) [reply dot/core/messages.go:40]: updated.

File: dot/core/messages_test.go (hunk 6 above)
Comment (edwardmack) [reply dot/core/messages_test.go:159]: added.

File: dot/core/messages.go (hunk 7 above)
Comment (edwardmack) [reply dot/core/messages.go]: fixed.

File: dot/core/messages.go [hunk 8]
```diff
@@ -24,19 +24,20 @@ import (
...
 	// get transactions from message extrinsics
 	txs := msg.Extrinsics
-
+	var toPropagate []types.Extrinsic
 	for _, tx := range txs {
 		// validate each transaction
 		externalExt := types.Extrinsic(append([]byte{byte(types.TxnExternal)}, tx...))
 		val, err := s.rt.ValidateTransaction(externalExt)
 		if err != nil {
 			logger.Error("failed to validate transaction", "err", err)
```
Comment (noot) [inline dot/core/messages.go:39]: I'd change this to debug since it's not an error

**Review by noot — APPROVED** [review]
looks good!

File: dot/core/messages.go (hunk 8 above)
Comment (edwardmack) [reply dot/core/messages.go]: good point, updated.
