### PR TITLE
fix(cmd): avoid nil pointer dereference

### LINKED ISSUE #2246: nil pointer dereference on build-spec commmand
## Task summary
- Make sure that `./bin/gossamer build-spec` does not error like this

```
kishan@kishan-T480:~/code/gossamer$ ./bin/gossamer build-spec
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xedf993]

goroutine 1 [running]:
main.setDotGlobalConfigName(0xc0000da580, 0x0, 0xc00000c3c0)
	github.com/ChainSafe/gossamer/cmd/gossamer/config.go:531 +0x73
main.setDotGlobalConfig(0xee5120, 0x0, 0xc00000c3c0)
	github.com/ChainSafe/gossamer/cmd/gossamer/config.go:433 +0xb8
main.createBuildSpecConfig(0x118988e)
	github.com/ChainSafe/gossamer/cmd/gossamer/config.go:227 +0xec
main.buildSpecAction(0xc0000da580)
	github.com/ChainSafe/gossamer/cmd/gossamer/main.go:367 +0xfd
main.FixFlagOrder.func1(0xc0000da580)
	github.com/ChainSafe/gossamer/cmd/gossamer/flags.go:546 +0x48
github.com/urfave/cli.HandleAction({0xfb2fa0, 0xc000600940}, 0xa)
	github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0x1186a6a, 0xa}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x12945df, 0x40}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:173 +0x652
github.com/urfave/cli.(*App).Run(0xc00097aa80, {0xc000032040, 0x2, 0x2})
	github.com/urfave/cli@v1.22.5/app.go:277 +0x705
main.main()
	github.com/ChainSafe/gossamer/cmd/gossamer/main.go:148 +0x35
```

## Specification reference

- 

## Other information and links

-

### PR DESCRIPTION
**Pull request by EclesioMeloJunior**
## Changes

- Check if a pointer is `nil` before accessing its value
- Change the description of `build-spec` command to use `build-spec --output file.json` rather than `build-spec > file.json` to avoid inserting logs outputs in the file

## Tests

```sh
gossamer build-spec --raw --output ./genesis.json
```

## Issues

- Closes #2246

## Primary Reviewer

@kishansagathiya

### CODE REVIEW

**Review by timwu20 — APPROVED** [review]

File: cmd/gossamer/config.go [hunk 1]
```diff
@@ -215,15 +212,14 @@ func createImportStateConfig(ctx *cli.Context) (*dot.Config, error) {
 }
 
 func createBuildSpecConfig(ctx *cli.Context) (*dot.Config, error) {
-	var tomlCfg *ctoml.Config
-	cfg := &dot.Config{}
+	var tomlCfg *ctoml.Config = new(ctoml.Config)
```
Comment (qdm12) [inline cmd/gossamer/config.go:215]:
```suggestion
	tomlCfg := new(ctoml.Config)
```

File: cmd/gossamer/main.go [hunk 2]
```diff
@@ -397,13 +397,11 @@ func buildSpecAction(ctx *cli.Context) error {
 	}
 
 	if outputPath := ctx.String(OutputSpecFlag.Name); outputPath != "" {
-		if err = dot.WriteGenesisSpecFile(res, outputPath); err != nil {
-			return err
-		}
-	} else {
-		fmt.Printf("%s", res)
+		return dot.WriteGenesisSpecFile(res, outputPath)
```
Comment (qdm12) [inline cmd/gossamer/main.go:400]: nit it would be nice to wrap the error since the function is rather large

```suggestion
		err = dot.WriteGenesisSpecFile(res, outputPath)
		if err != nil {
			return fmt.Errorf("cannot write genesis spec file: %w", err)
		}
```

**Review by qdm12 — APPROVED** [review]

File: cmd/gossamer/main.go [hunk 3]
```diff
@@ -397,13 +397,11 @@ func buildSpecAction(ctx *cli.Context) error {
...
 	}
 
+	fmt.Printf("%s", res)
```
[the remark this answers is not in the document]
Comment (EclesioMeloJunior) [reply cmd/gossamer/main.go:403]: Because `res` is an array of bytes then we use the `Printf` to print it in a readable form
