### PR TITLE
Fix(dot/sync): panic in handleWorkersResults

### LINKED ISSUE #3850: (dot/sync): Fix out of bounds panic during tip sync
## Issue summary

- Occasionally when we are in tip sync mode the node will crash with an index out of bounds error
- To be a user friendly full node we need to alleviate these kinds of vocational bugs, so this falls into the efforts to fix tip sync and clean up UX when running the node

## Other information and links

image

### PR DESCRIPTION
**Pull request by jimjbrettj**
## Changes

- Sometimes in the handleWorkersResults function we would get an index out of bounds error that caused the node to panic
- By doing a simple bounds check (as well as adding a few more bounds checks in other places) the node is able to ignore blocks it shouldn't process while also still making sure every block we need gets processed thus allowing us to keep processing the chain as expected.

## Tests

```sh
go test -tags integration github.com/ChainSafe/gossamer
```

## Issues
Closes #3850

### CODE REVIEW

File: dot/sync/chain_sync.go [hunk 1]
```diff
@@ -1012,11 +1018,12 @@ func doResponseGrowsTheChain(response, ongoingChain []*types.BlockData, startAtB
 	firstBlockInResponse := response[0]
 	firstBlockExactIndex := firstBlockInResponse.Header.Number - startAtBlock
 	if firstBlockExactIndex != 0 {
-		leftElement := ongoingChain[firstBlockExactIndex-1]
-		if leftElement != nil && !compareParentHash(leftElement, firstBlockInResponse) {
-			return false
+		if firstBlockExactIndex < uint(expectedTotal) {
```
Comment (EclesioMeloJunior) [inline dot/sync/chain_sync.go]: You can leave the conditions in a single if 
```suggestion
		if firstBlockExactIndex != 0 && firstBlockExactIndex < uint(expectedTotal) {
```

File: dot/sync/chain_sync.go [hunk 2]
```diff
@@ -783,6 +785,10 @@ taskResultLoop:
 }
 
 func (cs *chainSync) handleReadyBlock(bd *types.BlockData, origin blockOrigin) error {
+	if bd == nil {
+		logger.Debugf("nil block data provided to handleReadyBlock")
+		return fmt.Errorf("nil block data provided to handleReadyBlock")
+	}
```
Comment (EclesioMeloJunior) [inline dot/sync/chain_sync.go]: instead of handling this bd nil here, can we detect it at `handleWorkersResults` at the loop  where we insert the block data in the `syncingChain` slice, and if the `blockInResponse` is `nil` we create and dispatch a request to acquire it?

Comment (EclesioMeloJunior) [reply dot/sync/chain_sync.go]: Maybe you can add in another PR

**Review by EclesioMeloJunior — CHANGES_REQUESTED** [review]
LGTM, just small comments

File: dot/sync/chain_sync.go (hunk 2 above)
Comment (jimjbrettj) [reply dot/sync/chain_sync.go]: good call, modifying to add in this PR. Let me know how it looks

File: dot/sync/chain_sync.go [hunk 3]
```diff
@@ -731,8 +731,18 @@ taskResultLoop:
 					continue taskResultLoop
 				}
 
-				blockExactIndex := blockInResponse.Header.Number - startAtBlock
-				syncingChain[blockExactIndex] = blockInResponse
+				if blockInResponse != nil {
```
Comment (timwu20) [inline dot/sync/chain_sync.go]: when would this ever be `nil`?

Comment (jimjbrettj) [reply dot/sync/chain_sync.go]: This information is retrieved via the network, so nothing is stopping another node from sending us data with a nil block in it (either on purpose or accident) and its a case we appear to hit sometimes when running the node.

I have modified this logic to exist in the decoding of the actual response, rather than here

File: dot/network/errors.go [hunk 4]
```diff
@@ -10,6 +10,7 @@ import (
 var (
 	ErrNoPeersConnected     = errors.New("no peers connected")
 	ErrReceivedEmptyMessage = errors.New("received empty message")
+	ErrNilBlock             = errors.New("nil block in response")
```
Comment (EclesioMeloJunior) [inline dot/network/errors.go]: `ErrNilBlockInResponse` is a better name would say

**Review by EclesioMeloJunior — APPROVED** [review]

**Review by timwu20 — APPROVED** [review]

File: dot/sync/chain_sync.go (hunk 3 above)
Comment (timwu20) [reply dot/sync/chain_sync.go]: I think this is a much better approach 👍
