### PR TITLE
consensus/babe, runtime: fix ext_get_allocated_storage, implement build-block for empty block

### LINKED ISSUE #337: Implement Build Block
Implement Build-Block function as described in 5.1.7 in the Polkadot Runtime Environment Protocol Specification.

## Expected Behavior

Passing in the head block of the chain, and the slot number, the Build-Block function creates a new block within that slot filled with Extrinsics.

### PR DESCRIPTION
**Pull request by noot**
## Changes
- fix ext_get_allocated_storage
- implement build block for empty blocks, no extrinsics or inherents yet
- add BlockHeader without hash type since it's needed (not sure where it went :/)

## Tests:
```
go test ./consensus/... ./runtime/
```

### Issues:
closes #337

### CODE REVIEW

File: consensus/babe/babe.go [hunk 1]
```diff
@@ -50,6 +52,8 @@ type SessionConfig struct {
 	NewBlocks chan<- types.Block
 }
 
+const MaxBlockSize uint = 4*1024*1024 + 512
```
Comment (ryanchristo) [inline consensus/babe/babe.go]: maybe a comment here to explain `4*1024*1024 + 512`

File: state/block.go [hunk 2]
```diff
@@ -84,7 +83,8 @@ func (bs *blockState) GetBlockByHash(hash common.Hash) (types.Block, error) {
 		return types.Block{}, nil
 	}
 	blockBody := blockData.Body
-	return types.Block{Header: header, Body: *blockBody}, nil
+	bheader := header.WithoutHash()
```
Comment (ryanchristo) [inline state/block.go]: should we name `blockHeader` to be consistent?

File: consensus/babe/babe.go [hunk 3]
```diff
@@ -78,6 +82,7 @@ func (b *Session) Start() error {
 		}
 	}
 
+	//TODO: finish implementation of build block
```
Comment (ryanchristo) [inline consensus/babe/babe.go]: finished with this pull request?

File: consensus/babe/babe.go [hunk 4]
```diff
@@ -97,15 +102,12 @@ func (b *Session) invokeBlockAuthoring() {
 	var currentSlot uint64 = 0
 
 	for ; currentSlot < b.config.EpochLength; currentSlot++ {
-		if b.isProducer[currentSlot] {
-			// TODO: implement build block
-			block, err := b.buildBlock(big.NewInt(int64(currentSlot)))
-			if err != nil {
-				return
-			}
-			b.newBlocks <- *block
```
Comment (ryanchristo) [inline consensus/babe/babe.go]: can we call `buildBlock` with placeholders and keep `b.newBlocks <- block`?

File: consensus/babe/babe_test.go [hunk 5]
```diff
@@ -435,12 +437,100 @@ func TestBabeAnnounceMessage(t *testing.T) {
...
+		Number:     big.NewInt(0),
+	}
+
+	slot := Slot{
+		start:    uint64(time.Now().Unix()),
+		duration: uint64(10),
+		number:   1,
+	}
+
+	block0, err := babesession.buildBlock(parentHeader, slot)
```
Comment (ryanchristo) [inline consensus/babe/babe_test.go]: typo?

File: consensus/babe/babe_test.go [hunk 6]
```diff
@@ -404,7 +406,7 @@ func TestStart(t *testing.T) {
 	if err != nil {
 		t.Fatal(err)
 	}
-	time.Sleep(time.Duration(conf.SlotDuration) * time.Duration(conf.EpochLength) * time.Millisecond)
+	//time.Sleep(time.Duration(conf.SlotDuration) * time.Duration(conf.EpochLength) * time.Millisecond)
```
Comment (ryanchristo) [inline consensus/babe/babe_test.go]: delete?

File: consensus/babe/babe.go [hunk 7]
```diff
@@ -201,11 +203,28 @@ func (b *Session) vrfSign(input []byte) ([]byte, error) {
...
+	encodedHeader, err := codec.Encode(parent)
+	if err != nil {
+		return nil, err
+	}
+	err = b.initializeBlock(encodedHeader)
+	if err != nil {
+		return nil, err
+	}
+
+	// TODO: inherents and extrinsics
```
Comment (ryanchristo) [inline consensus/babe/babe.go]: Is this what needs to be finished for build block?

File: consensus/babe/babe.go (hunk 1 above)
Comment (noot) [reply consensus/babe/babe.go]: @dziabko where did this come from?

File: consensus/babe/babe.go (hunk 3 above)
Comment (noot) [reply consensus/babe/babe.go]: not finished yet :)

File: consensus/babe/babe_test.go (hunk 5 above)
Comment (noot) [reply consensus/babe/babe_test.go]: no but I'll change it

File: consensus/babe/babe.go (hunk 4 above)
Comment (noot) [reply consensus/babe/babe.go]: we still have `b.newBlock <- block` but block is a placeholder block now

File: consensus/babe/babe.go (hunk 7 above)
Comment (noot) [reply consensus/babe/babe.go]: yeah I have issues open for them #500 #501 
I did #500 already in my other PR that I can merge into here if you'd like

File: consensus/babe/babe.go (hunk 4 above)
Comment (ryanchristo) [reply consensus/babe/babe.go]: ah, I see :+1:

File: consensus/babe/babe.go (hunk 7 above)
Comment (ryanchristo) [reply consensus/babe/babe.go]: how you merge is up to you, just wanted to make sure we had an issue open for it

File: consensus/babe/babe.go (hunk 1 above)
Comment (noot) [reply consensus/babe/babe.go]: gonna remove this for now since I think the algo is different.

File: consensus/babe/runtime.go [hunk 8]
```diff
@@ -39,3 +43,74 @@ func (b *Session) configurationFromRuntime() error {
...
+// calls runtime API function BlockBuilder_apply_extrinsic
+//nolint:typecheck
+func (b *Session) applyExtrinsic(e types.Extrinsic) ([]byte, error) { //nolint:unused
+	// TODO: use allocator to store extrinsic
+	var loc int32 = 1
+	b.rt.Store(e, loc)
+
+	return b.rt.Exec(runtime.BlockBuilderApplyExtrinsic, loc, e)
+}
+
```
Comment (ansermino) [inline consensus/babe/runtime.go]: Only `//nolint:unused` seems to be needed here

File: core/types/types.go [hunk 9]
```diff
@@ -27,21 +28,76 @@ type Extrinsic []byte
...
+
+func (bh *BlockHeaderWithHash) WithoutHash() *BlockHeader {
+	return &BlockHeader{
+		ParentHash:     bh.ParentHash,
+		Number:         bh.Number,
+		StateRoot:      bh.StateRoot,
+		ExtrinsicsRoot: bh.ExtrinsicsRoot,
+		Digest:         bh.Digest,
+	}
+}
```
Comment (ansermino) [inline core/types/types.go]: Really don't love this, let find a better solution (merge if you have to)

File: consensus/babe/babe.go (hunk 7 above)
Comment (noot) [reply consensus/babe/babe.go]: okay gonna leave that PR open for now, should have issues open covering what still needs to be done

File: core/types/types.go (hunk 9 above)
Comment (noot) [reply core/types/types.go]: I also really dislike it :/ I just didn't want to change a bunch of stuff in the block tree and such in this PR. I'll open an issue to deal with it

File: consensus/babe/runtime.go (hunk 8 above)
Comment (noot) [reply consensus/babe/runtime.go]: ok removed typecheck

File: core/types/types.go (hunk 9 above)
Comment (ryanchristo) [reply core/types/types.go]: Issue number?

File: consensus/babe/babe_test.go [hunk 10]
```diff
@@ -435,12 +436,100 @@ func TestBabeAnnounceMessage(t *testing.T) {
...
+	if err != nil {
+		t.Fatal(err)
+	}
+	err = babesession.configurationFromRuntime()
+	if err != nil {
+		t.Fatal(err)
+	}
+
+	// https://github.com/paritytech/substrate/blob/5420de3face1349a97eb954ae71c5b0b940c31de/core/transaction-pool/src/tests.rs#L95
+	txb := []byte{1, 212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125, 142, 175, 4, 21, 22, 135, 115, 99, 38, 201, 254, 161, 126, 37, 252, 82, 135, 97, 54, 147, 201, 18, 144, 156, 178, 38, 170, 71, 148, 242, 106, 72, 69, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 216, 5, 113, 87, 87, 40, 221, 120, 247, 252, 137, 201, 74, 231, 222, 101, 85, 108, 102, 39, 31, 190, 210, 14, 215, 124, 19, 160, 180, 203, 54, 110, 167, 163, 149, 45, 12, 108, 80, 221, 65, 238, 57, 237, 199, 16, 10, 33, 185, 8, 244, 184, 243, 139, 5, 87, 252, 245, 24, 225, 37, 154, 163, 142}
```
Comment (ryanchristo) [inline consensus/babe/babe_test.go]: Just a side thought here outside of scope. It might be nice to have these examples reusable by other packages, which would make it easy to update across all packages and tests. I think we already have some duplication and some outdated examples.

File: consensus/babe/runtime.go [hunk 11]
```diff
@@ -39,3 +43,72 @@ func (b *Session) configurationFromRuntime() error {
 
 	return err
 }
+
+// calls runtime API function Core_initialize_block
+func (b *Session) initializeBlock(blockHeader []byte) error {
+	// TODO: use allocator to store block header
```
Comment (ryanchristo) [inline consensus/babe/runtime.go]: issue number?

File: consensus/babe/babe_test.go (hunk 10 above)
Comment (ansermino) [reply consensus/babe/babe_test.go]: This is a fantastic idea, event within a single package this might be useful

File: consensus/babe/runtime.go (hunk 11 above)
Comment (noot) [reply consensus/babe/runtime.go]: https://github.com/ChainSafe/gossamer/issues/441

File: core/types/types.go (hunk 9 above)
Comment (noot) [reply core/types/types.go]: https://github.com/ChainSafe/gossamer/issues/506
