### PR TITLE
enhancement/table-driven

### LINKED ISSUE #130: Improvements on table driven tests
When running multiple tests in a single test function, [t.Run](https://golang.org/pkg/testing/#T.Run) should be used. This allows to clearly state which iteration of the test has failed. Which would be useful for tests like [these](https://github.com/ChainSafe/gossamer/blob/development/polkadb/database_test.go#L76).

Example usage is 
```golang
for _, v := range tests {
    t.Run(v, func(t) {
         // @todo run test
    })
}

```

For a longer guide check out [this](https://blog.golang.org/subtests).

### PR DESCRIPTION
**Pull request by decanus**
starts work on #130 for `trie` directory

### CODE REVIEW

File: trie/codec_test.go [hunk 1]
```diff
@@ -35,10 +36,12 @@ func TestKeyToNibbles(t *testing.T) {
 	}
 
 	for _, test := range tests {
-		res := keyToNibbles(test.input)
-		if !bytes.Equal(test.expected, res) {
-			t.Errorf("Output doesn't match expected. got=%v expected=%v\n", res, test.expected)
-		}
+		t.Run(fmt.Sprintf("%v", test.input), func(t *testing.T) {
+			res := keyToNibbles(test.input)
```
Comment (golangcibot) [inline trie/codec_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/codec_test.go [hunk 2]
```diff
@@ -35,10 +36,12 @@ func TestKeyToNibbles(t *testing.T) {
...
+			if !bytes.Equal(test.expected, res) {
```
Comment (golangcibot) [inline trie/codec_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/codec_test.go [hunk 3]
```diff
@@ -35,10 +36,12 @@ func TestKeyToNibbles(t *testing.T) {
...
+				t.Errorf("Output doesn't match expected. got=%v expected=%v\n", res, test.expected)
```
Comment (golangcibot) [inline trie/codec_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/codec_test.go [hunk 4]
```diff
@@ -55,10 +58,12 @@ func TestNibblesToKey(t *testing.T) {
 	}
 
 	for _, test := range tests {
-		res := nibblesToKey(test.input)
-		if !bytes.Equal(test.expected, res) {
-			t.Errorf("Output doesn't match expected. got=%x expected=%x\n", res, test.expected)
-		}
+		t.Run(fmt.Sprintf("%v", test.input), func(t *testing.T) {
+			res := nibblesToKey(test.input)
```
Comment (golangcibot) [inline trie/codec_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/codec_test.go [hunk 5]
```diff
@@ -55,10 +58,12 @@ func TestNibblesToKey(t *testing.T) {
...
+			if !bytes.Equal(test.expected, res) {
```
Comment (golangcibot) [inline trie/codec_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/codec_test.go [hunk 6]
```diff
@@ -55,10 +58,12 @@ func TestNibblesToKey(t *testing.T) {
...
+				t.Errorf("Output doesn't match expected. got=%x expected=%x\n", res, test.expected)
```
Comment (golangcibot) [inline trie/codec_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/codec_test.go [hunk 7]
```diff
@@ -75,9 +80,11 @@ func TestNibblesToKeyLE(t *testing.T) {
 	}
 
 	for _, test := range tests {
-		res := nibblesToKeyLE(test.input)
-		if !bytes.Equal(test.expected, res) {
-			t.Errorf("Output doesn't match expected. got=%x expected=%x\n", res, test.expected)
-		}
+		t.Run(fmt.Sprintf("%v", test.input), func(t *testing.T) {
+			res := nibblesToKeyLE(test.input)
```
Comment (golangcibot) [inline trie/codec_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/codec_test.go [hunk 8]
```diff
@@ -75,9 +80,11 @@ func TestNibblesToKeyLE(t *testing.T) {
...
+			if !bytes.Equal(test.expected, res) {
```
Comment (golangcibot) [inline trie/codec_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/codec_test.go [hunk 9]
```diff
@@ -75,9 +80,11 @@ func TestNibblesToKeyLE(t *testing.T) {
...
+				t.Errorf("Output doesn't match expected. got=%x expected=%x\n", res, test.expected)
```
Comment (golangcibot) [inline trie/codec_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/node_test.go [hunk 10]
```diff
@@ -126,13 +127,15 @@ func TestLeafHeader(t *testing.T) {
...
-	for _, test := range tests {
-		res, err := test.br.header()
-		if err != nil {
-			t.Fatalf("Error when encoding header: %s", err)
-		} else if !bytes.Equal(res, test.header) {
-			t.Errorf("Leaf header fail: got %x expected %x", res, test.header)
-		}
+	for i, test := range tests {
+		t.Run(strconv.Itoa(i), func(t *testing.T) {
+			res, err := test.br.header()
```
Comment (golangcibot) [inline trie/node_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/node_test.go [hunk 11]
```diff
@@ -126,13 +127,15 @@ func TestLeafHeader(t *testing.T) {
...
+			if err != nil {
+				t.Fatalf("Error when encoding header: %s", err)
+			} else if !bytes.Equal(res, test.header) {
```
Comment (golangcibot) [inline trie/node_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/node_test.go [hunk 12]
```diff
@@ -126,13 +127,15 @@ func TestLeafHeader(t *testing.T) {
...
+				t.Errorf("Leaf header fail: got %x expected %x", res, test.header)
```
Comment (golangcibot) [inline trie/node_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 13]
```diff
@@ -47,11 +48,13 @@ var commonPrefixTests = []commonPrefixTest{
...
 
 func TestCommonPrefix(t *testing.T) {
-	for _, test := range commonPrefixTests {
-		output := lenCommonPrefix(test.a, test.b)
-		if output != test.output {
-			t.Errorf("Fail: got %d expected %d", output, test.output)
-		}
+	for i, test := range commonPrefixTests {
+		t.Run(strconv.Itoa(i), func(t *testing.T) {
+			output := lenCommonPrefix(test.a, test.b)
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 14]
```diff
@@ -47,11 +48,13 @@ var commonPrefixTests = []commonPrefixTest{
...
+			if output != test.output {
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 15]
```diff
@@ -47,11 +48,13 @@ var commonPrefixTests = []commonPrefixTest{
...
+				t.Errorf("Fail: got %d expected %d", output, test.output)
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 16]
```diff
@@ -174,36 +177,38 @@ func buildSmallTrie() *Trie {
...
 
 func runTests(t *testing.T, trie *Trie, tests []trieTest) {
-	for _, test := range tests {
-		if test.op == PUT {
-			err := trie.Put(test.key, test.value)
-			if err != nil {
-				t.Errorf("Fail to put key %x with value %x: %s", test.key, test.value, err)
+	for i, test := range tests {
+		t.Run(strconv.Itoa(i), func(t *testing.T) {
+			if test.op == PUT {
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 17]
```diff
@@ -174,36 +177,38 @@ func buildSmallTrie() *Trie {
...
+				err := trie.Put(test.key, test.value)
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 18]
```diff
@@ -174,36 +177,38 @@ func buildSmallTrie() *Trie {
...
+				if err != nil {
+					t.Errorf("Fail to put key %x with value %x: %s", test.key, test.value, err)
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 19]
```diff
@@ -174,36 +177,38 @@ func buildSmallTrie() *Trie {
...
+				}
+			} else if test.op == GET {
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 20]
```diff
@@ -174,36 +177,38 @@ func buildSmallTrie() *Trie {
...
+				val, err := trie.Get(test.key)
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 21]
```diff
@@ -174,36 +177,38 @@ func buildSmallTrie() *Trie {
...
+				if err != nil {
+					t.Errorf("Error when attempting to get key %x: %s", test.key, err.Error())
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 22]
```diff
@@ -174,36 +177,38 @@ func buildSmallTrie() *Trie {
...
+				} else if !bytes.Equal(val, test.value) {
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 23]
```diff
@@ -174,36 +177,38 @@ func buildSmallTrie() *Trie {
...
+					t.Errorf("Fail to get key %x with value %x: got %x", test.key, test.value, val)
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 24]
```diff
@@ -174,36 +177,38 @@ func buildSmallTrie() *Trie {
...
+				}
+			} else if test.op == DEL {
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 25]
```diff
@@ -174,36 +177,38 @@ func buildSmallTrie() *Trie {
...
+				err := trie.Delete(test.key)
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 26]
```diff
@@ -174,36 +177,38 @@ func buildSmallTrie() *Trie {
...
+				if err != nil {
+					t.Errorf("Fail to delete key %x: %s", test.key, err.Error())
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 27]
```diff
@@ -174,36 +177,38 @@ func buildSmallTrie() *Trie {
...
+				}
+			} else if test.op == GETLEAF {
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 28]
```diff
@@ -174,36 +177,38 @@ func buildSmallTrie() *Trie {
...
+				leaf, err := trie.getLeaf(test.key)
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 29]
```diff
@@ -174,36 +177,38 @@ func buildSmallTrie() *Trie {
...
+				if leaf == nil {
+					t.Errorf("Fail to get key %x: nil leaf", test.key)
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 30]
```diff
@@ -174,36 +177,38 @@ func buildSmallTrie() *Trie {
...
+				} else if err != nil {
+					t.Errorf("Fail to get key %x: %s", test.key, err.Error())
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 31]
```diff
@@ -174,36 +177,38 @@ func buildSmallTrie() *Trie {
...
+				} else if !bytes.Equal(leaf.value, test.value) {
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 32]
```diff
@@ -174,36 +177,38 @@ func buildSmallTrie() *Trie {
...
+					t.Errorf("Fail to get key %x with value %x: got %x", test.key, test.value, leaf.value)
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 33]
```diff
@@ -174,36 +177,38 @@ func buildSmallTrie() *Trie {
...
+				} else if !bytes.Equal(leaf.key, test.pk) {
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 34]
```diff
@@ -174,36 +177,38 @@ func buildSmallTrie() *Trie {
...
+					t.Errorf("Fail to get correct partial key %x: got %x", test.pk, leaf.key)
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 35]
```diff
@@ -480,35 +485,39 @@ func TestDelete(t *testing.T) {
...
-	}
-
-	for _, test := range rt {
-		r := rand.Int() % 2
-		switch r {
-		case 0:
-			err := trie.Delete(test.key)
+	for i, test := range rt {
+		t.Run(strconv.Itoa(i), func(t *testing.T) {
+			err := trie.Put(test.key, test.value)
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 36]
```diff
@@ -480,35 +485,39 @@ func TestDelete(t *testing.T) {
...
 			if err != nil {
-				t.Errorf("Fail to delete key %x: %s", test.key, err.Error())
+				t.Errorf("Fail to put with key %x and value %x: %s", test.key, test.value, err.Error())
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 37]
```diff
@@ -480,35 +485,39 @@ func TestDelete(t *testing.T) {
...
-			if err != nil {
-				t.Errorf("Error when attempting to get key %x: %s", test.key, err.Error())
-			} else if !bytes.Equal(test.value, val) {
-				t.Errorf("Fail to get key %x with value %x: got %x", test.key, test.value, val)
+	for i, test := range rt {
+		t.Run(strconv.Itoa(i), func(t *testing.T) {
+			r := rand.Int() % 2
+			switch r {
+			case 0:
+				err := trie.Delete(test.key)
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 38]
```diff
@@ -480,35 +485,39 @@ func TestDelete(t *testing.T) {
...
+				if err != nil {
+					t.Errorf("Fail to delete key %x: %s", test.key, err.Error())
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 39]
```diff
@@ -480,35 +485,39 @@ func TestDelete(t *testing.T) {
...
+				}
+
+				val, err := trie.Get(test.key)
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 40]
```diff
@@ -480,35 +485,39 @@ func TestDelete(t *testing.T) {
...
+				if err != nil {
+					t.Errorf("Error when attempting to get deleted key %x: %s", test.key, err.Error())
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 41]
```diff
@@ -480,35 +485,39 @@ func TestDelete(t *testing.T) {
...
+				} else if val != nil {
+					t.Errorf("Fail to delete key %x with value %x: got %x", test.key, test.value, val)
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 42]
```diff
@@ -480,35 +485,39 @@ func TestDelete(t *testing.T) {
...
+				}
+			case 1:
+				val, err := trie.Get(test.key)
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 43]
```diff
@@ -480,35 +485,39 @@ func TestDelete(t *testing.T) {
...
+				if err != nil {
+					t.Errorf("Error when attempting to get key %x: %s", test.key, err.Error())
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 44]
```diff
@@ -480,35 +485,39 @@ func TestDelete(t *testing.T) {
...
+				} else if !bytes.Equal(test.value, val) {
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

File: trie/trie_test.go [hunk 45]
```diff
@@ -480,35 +485,39 @@ func TestDelete(t *testing.T) {
...
+					t.Errorf("Fail to get key %x with value %x: got %x", test.key, test.value, val)
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)

**Comment by noot** [comment]
@decanus please fix scoping issues

also I'm not sure how much of an improvement this is, we really only need to be logging when there is a failing test which is what we already do

**Comment by decanus** [comment]
@noot, no real idea what the scoping issue is. That scope stuff was the same as before?

**Comment by noot** [comment]
@decanus I think the issue is that the outer loop variable is being captured inside the anonymous function. eg. 
```
for _, test := range tests {
    t.Run(fmt.Sprintf("%v", test.input), func(t *testing.T) {
        // do stuff
    }
}
```
in this case the variable `test` is being used inside the function. the way to fix this is to redeclare the variable inside the loop
```
for _, test := range tests {
    test := test
    t.Run(fmt.Sprintf("%v", test.input), func(t *testing.T) {
        // do stuff
    }
}
```

**Comment by noot** [comment]
@ansermino this still breaks travis, what do you think

**Comment by decanus** [comment]
@noot do we know why it breaks travis, I never get the full logs

**Comment by dutterbutter** [comment]
> @noot do we know why it breaks travis, I never get the full logs

@decanus see #170

**Comment by decanus** [comment]
@dutterbutter makes sense.

**Comment by noot** [comment]
@ansermino there's a new build error from travis

**Comment by ansermino** [comment]
Bit of a problem for outside contributors, will get back to you with a solution or workaround

File: trie/trie_test.go [hunk 46]
```diff
@@ -491,28 +497,31 @@ func TestDelete(t *testing.T) {
...
-				t.Errorf("Error when attempting to get key %x: %s", test.key, err.Error())
-			} else if !bytes.Equal(test.value, val) {
-				t.Errorf("Fail to get key %x with value %x: got %x", test.key, test.value, val)
-			}
-		}
+	for i, test := range rt {
+		test := test
+		t.Run(strconv.Itoa(i), func(t *testing.T) {
+			r := rand.Int() % 2
+		    	switch r {
```
Comment (golangcibot) [inline trie/trie_test.go]: File is not `goimports`-ed (from `goimports`)

**Comment by ansermino** [comment]
#172 should fix that failed build

**Comment by noot** [comment]
@ansermino is golangcibot okay?

**Comment by ansermino** [comment]
Looks like it didn't get triggered, wonder if its part of the huge outage today. @decanus fix the above issues again, if that doesn't trigger it I can look deeper.

File: trie/trie_test.go [hunk 47]
```diff
@@ -178,36 +181,39 @@ func buildSmallTrie() *Trie {
...
-				t.Errorf("Fail to get correct partial key %x with key %x: got %x", test.pk, test.key, leaf.key)
+	for i, test := range tests {
+		test := test
+		t.Run(strconv.Itoa(i), func(t *testing.T) {
+			if test.op == PUT {
+				err := trie.Put(test.key, test.value)
+				if err != nil {
+					t.Errorf("Fail to put key %x with value %x: %s", test.key, test.value, err)
+				}
+		 	} else if test.op == GET {
```
Comment (golangcibot) [inline trie/trie_test.go]: File is not `gofmt`-ed with `-s` (from `gofmt`)

File: trie/trie_test.go [hunk 48]
```diff
@@ -48,11 +49,14 @@ var commonPrefixTests = []commonPrefixTest{
...
 
 func TestCommonPrefix(t *testing.T) {
-	for _, test := range commonPrefixTests {
-		output := lenCommonPrefix(test.a, test.b)
-		if output != test.output {
-			t.Errorf("Fail: got %d expected %d", output, test.output)
-		}
+	for i, test := range commonPrefixTests {
+		t.Run(strconv.Itoa(i), func(t *testing.T) {
+			test := test
```
Comment (golangcibot) [inline trie/trie_test.go]: Using the variable on range scope `test` in function literal (from `scopelint`)
