### PR TITLE
dot/state, lib/blocktree: set block number->hash mapping for current chain only

### LINKED ISSUE #717: state: set number->hash mapping for canonical chain only
right now, `AddBlock` in state updates the number->blockhash mapping every time it imports a block, however this is wrong and will mess up BlockResponses and other features that rely on getting a block on the canonical chain by number. can be done once #716 is merged

### PR DESCRIPTION
**Pull request by noot**
## Changes
- addisBlockOnCurrentChain function to block state to check if block we are adding is on our current chain, if so, update number->hash mapping in db, otherwise don't 
- fix blocktree deepestLeaf function, wasn't correct before

## Tests:
```
go test ./... -short
```

### Issues:
closes #717

### CODE REVIEW

File: dot/state/block_test.go [hunk 1]
```diff
@@ -214,3 +210,94 @@ func TestGetSlotForBlock(t *testing.T) {
...
+	genesisHeader := &types.Header{
+		Number:    big.NewInt(0),
+		StateRoot: trie.EmptyHash,
+	}
+
+	bs := newTestBlockState(genesisHeader)
+	currChain, branchChains := addBlocksToState(bs, 8)
+
+	for _, header := range currChain {
+		ok, err := bs.isBlockOnCurrentChain(header)
```
Comment (ryanchristo) [inline dot/state/block_test.go]: same as above

File: dot/state/block_test.go [hunk 2]
```diff
@@ -214,3 +210,94 @@ func TestGetSlotForBlock(t *testing.T) {
...
+		if err != nil {
+			t.Fatal(err)
+		}
+		if !ok {
+			t.Fatalf("Fail: expected block %s to be on current chain", header.Hash())
+		}
+	}
+
+	for _, header := range branchChains {
+		ok, err := bs.isBlockOnCurrentChain(header)
```
Comment (ryanchristo) [inline dot/state/block_test.go]: same as above

File: dot/state/block.go [hunk 3]
```diff
@@ -336,19 +336,20 @@ func (bs *BlockState) AddBlockWithArrivalTime(block *types.Block, arrivalTime ui
...
 		}
 	}
 
-	// TODO: only set number->hash mapping for our canonical chain, otherwise, this messes up BlockResponses
-	// store number to hash
-	err = bs.db.Put(headerHashKey(block.Header.Number.Uint64()), hash.ToBytes())
-	if err != nil {
-		return err
+	// only set number->hash mapping for our current chain
+	var ok bool
```
Comment (ryanchristo) [inline dot/state/block.go]: this can also be declared on the line below since it is not used outside the condition block whether you keep `ok` or change it to something more descriptive

File: dot/state/block.go [hunk 4]
```diff
@@ -336,19 +336,20 @@ func (bs *BlockState) AddBlockWithArrivalTime(block *types.Block, arrivalTime ui
...
+	if ok, err = bs.isBlockOnCurrentChain(block.Header); ok && err == nil {
```
[the remark this answers is not in the document]
Comment (noot) [reply dot/state/block.go]: yeah good point, will change

File: dot/state/block.go (hunk 3 above)
Comment (noot) [reply dot/state/block.go]: it's defined outside because otherwise there's a lint error saying definition of err is being shadowed
