### PR TITLE
scripts, Update golangci and linters #559

### LINKED ISSUE #559: Update golangci and linters
Update golangci and add varcheck, misspell, ineffassign, gosimple, unconvert and goconst to golangci enabled linters

Add lint and test tasks to ci.go

Other minor code refactor related.

## Expected Behavior

Should fail lint when var is named: protocolId instead of protocolID.

https://github.com/golang/go/wiki/CodeReviewComments#initialisms

## Current Behavior

Lint reports no errors

## Possible Solution

add carcheck to golangci and fix all issues reported

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
* Version used:
* Commit hash:
* Go Version:
* Operating System and version (include distro if Linux):
* Link to your project or reproducible gist:
* I intend to submit a pull request to fix this issue: [ ]

### PR DESCRIPTION
**Pull request by thomasmodeneis**
* update Travis lint task

* add test task to ci.go
* add lint task to ci.go

* add varcheck, misspell, ineffassign, gosimple, unconvert and goconst to golangci enabled linters

* add add errcheck, govet, staticcheck, megacheck, goimports, gosec, bodyclose, goprintffuncname, golint, depguard

* update Makefile lint and test tasks

* Fix all reported lint issues 

## Changes
- 
- 
- 

## Tests:
```
make lint
make test
```

### Issues:
closes #559

### CODE REVIEW

File: codec/decode.go [hunk 1]
```diff
@@ -45,6 +46,7 @@ func Decode(in []byte, t interface{}) (interface{}, error) {
 	return output, err
 }
 
+// DecodePtr pointer
```
Comment (noot) [inline codec/decode.go]: DecodePtr decodes the input into a pointer to an interface ?

File: common/optional/types.go [hunk 2]
```diff
@@ -22,59 +22,71 @@ import (
 	common "github.com/ChainSafe/gossamer/common"
 )
 
+// Uint32 struct
```
Comment (noot) [inline common/optional/types.go]: Uint32 represents an optional uint32 type

File: common/transaction/types.go [hunk 3]
```diff
@@ -21,14 +21,16 @@ import (
 	"github.com/ChainSafe/gossamer/core/types"
 )
 
+// Pool ValidTransaction
 type Pool map[common.Hash]*ValidTransaction
```
Comment (noot) [inline common/transaction/types.go]: Pool is a mapping of transaction hashes to ValidTransactions

File: crypto/ed25519/ed25519.go [hunk 4]
```diff
@@ -22,7 +29,10 @@ type Keypair struct {
 	private *PrivateKey
 }
 
+// PrivateKey is the ed25519 Private Key
 type PrivateKey ed25519.PrivateKey
+
+// PublicKey is the ed25519 Public Key
```
Comment (noot) [inline crypto/ed25519/ed25519.go]: I feel like comments like these aren't helpful, are they required for the linter to pass? or is it mostly for the godocs? if it's just the latter, I would prefer not having redundant/self explanatory comments. however, if everyone else prefers them, that's ok too

File: common/transaction/types.go (hunk 3 above)
Comment (thomasmodeneis) [reply common/transaction/types.go]: good description

File: crypto/ed25519/ed25519.go (hunk 4 above)
Comment (thomasmodeneis) [reply crypto/ed25519/ed25519.go]: The comments are required for the lint to pass, please check the .golangci.yaml lines: 269, 273. I have added it there because there was just too much exported methods and variables without comments and that is required by the linter. All exported fields and methods should be commented its the common practice for Go.

I also added the "error strings should not be capitalized or end with punctuation or a newline" to skip the error messages, we should update this also at a later PR.

the: "and that stutters; consider calling this" and "which can be annoying to use" are also a little tricky to update, there is some exported methods that are returning non exported struct, so we have to either export the struct or not have the method exported.

File: codec/decode.go (hunk 1 above)
Comment (thomasmodeneis) [reply codec/decode.go]: will update this and try to provide better description to others.

File: common/optional/types.go (hunk 2 above)
Comment (thomasmodeneis) [reply common/optional/types.go]: will update this and try to provide better description to others.

File: crypto/ed25519/ed25519.go (hunk 4 above)
Comment (noot) [reply crypto/ed25519/ed25519.go]: okay, that makes sense. sure, let's open an issue for the error messages.

File: .golangci.yml [hunk 5]
```diff
@@ -228,6 +244,38 @@ issues:
...
+      text: "should have comment or be unexported"
+
+    - linters:
+        - golint
+      text: "or a comment on this block"
+
+    - linters:
+        - golint
+      text: "error strings should not be capitalized or end with punctuation or a newline"
+
```
Comment (ryanchristo) [inline .golangci.yml]: Can you explain the `text` fields here? Some of them are unclear and confusing, for example, "or a comment on this block" or "which can be annoying to use". I am not see this in other projects or examples.

Comment (thomasmodeneis) [reply .golangci.yml]: Yes, that is what I explained yesterday in the call. This section is the linter special section to skip tests. Do something, comment out this section and run the linters, you will see what is it for right away on the linter error messages reported.

**Comment by thomasmodeneis** [comment]
> could you open an issue to update the comments?

I have raised #586 in order to allow us to address the remaining points.
