### PR TITLE
fix(dot/network): remove `defer cancel()` inside loop

### LINKED ISSUE #2247: remove `defer cancel()` calls inside a infinite `for` loop
## Issue summary

- At file [`dot/network/discovery.go`](https://github.com/ChainSafe/gossamer/blob/a90a6e0f518d398ec34c2e21187f2511121fa3ee/dot/network/discovery.go#L164) the function `checkPeerCount` starts a looping to discover new peers at a defined amount of time, however, a new context is created inside the looping followed by the statement `defer cancel()` which is only called once the function exits
- This context is used by the ` findPeers` as a timeout trigger, but this can be done inside the function using `time.NewTimer(...)` without the needed to use a context.

## Other information and links

-

### PR DESCRIPTION
**Pull request by EclesioMeloJunior**
## Changes

- Remove unnecessary context creation inside a infinity for loop

## Tests

```
go test ./dot/network/... -v -short -timeout 5m
```

## Issues

- Closes #2247

## Primary Reviewer

- @noot

### CODE REVIEW

File: dot/network/discovery.go [hunk 1]
```diff
@@ -60,34 +60,44 @@ func newDiscovery(ctx context.Context, h libp2phost.Host,
...
 		}
 
-		for _, p := range peers {
-			d.bootnodes = append(d.bootnodes, d.h.Peerstore().PeerInfo(p))
+		currentPeers = d.h.Network().Peers()
+	}
+
+	peers = make([]peer.AddrInfo, len(currentPeers))
+	for idx, p := range currentPeers {
+		peers[idx] = d.h.Peerstore().PeerInfo(p)
```
Comment (qdm12) [inline dot/network/discovery.go:86]: nit why not `peer` instead of `p` 😉

File: dot/network/discovery.go [hunk 2]
```diff
@@ -141,8 +151,15 @@ func (d *discovery) advertise() {
 	ttl := initialAdvertisementTimeout
 
 	for {
+		wait := time.NewTimer(ttl)
```
Comment (qdm12) [inline dot/network/discovery.go:154]: nit rename to timer?

File: dot/network/discovery.go [hunk 3]
```diff
@@ -173,35 +189,34 @@ func (d *discovery) checkPeerCount() {
...
-func (d *discovery) findPeers(ctx context.Context) {
+func (d *discovery) findPeers() {
 	logger.Debug("attempting to find DHT peers...")
 	peerCh, err := d.rd.FindPeers(d.ctx, string(d.pid))
 	if err != nil {
 		logger.Warnf("failed to begin finding peers via DHT: %s", err)
 		return
 	}
 
+	timeout := time.NewTimer(findPeersTimeout)
```
Comment (qdm12) [inline dot/network/discovery.go:205]: nit rename to timer. Usually timeout is the duration value passed to the timer.

File: dot/network/discovery.go [hunk 4]
```diff
@@ -173,35 +189,34 @@ func (d *discovery) checkPeerCount() {
...
+	defer timeout.Stop()
```
Comment (qdm12) [inline dot/network/discovery.go:206]: Stop and drain the channel in the `case peer := <-peerCh:` block in case you receive the peer at the same time as the timer triggers. You can use

```go
if !timer.Stop() {
    <-timer.C
}
```

**Review by qdm12 — APPROVED** [review]

**Review by noot — APPROVED** [review]
