### PR TITLE
Remove checks for equivocatory blocks

### LINKED ISSUE #2597: When checking for equivocatory blocks error only if both are created by primary author
## Describe the bug

- We have logic to find blocks that were authored by same node and have same block number. In such case we error. This could happen when one block is authored as secondary author and other as primary author. We reduce this check only to primary author. That is error only if both blocks we authored as primary author. 

https://github.com/ChainSafe/gossamer/blob/8582cb20a37d574e6397f980f919c6dd4dfb24a0/lib/babe/verify.go#L367-L369

### PR DESCRIPTION
**Pull request by kishansagathiya**
## Changes
We have logic to find different blocks with same block number and same author. If we find such blocks we throw and error.
Some of the discussion is here https://github.com/ChainSafe/gossamer/issues/2541#issuecomment-1152010241
https://github.com/ChainSafe/gossamer/issues/2541#issuecomment-1152395681

As discussed with @noot , it's probably authoring one as primary and one as secondary. If we don't error the fork should get resolved eventually.

## Tests

```sh
go test -tags integration github.com/ChainSafe/gossamer
```

## Issues

Fixes #2597
## Primary Reviewer

@timwu20

### CODE REVIEW

File: lib/babe/verify.go [hunk 1]
```diff
@@ -354,17 +354,40 @@ func (b *verifier) verifyAuthorshipRight(header *types.Header) error {
 			continue
 		}
 
+		currentPreDigestItem := currentHeader.Digest.Types[0]
+
+		currentPreDigest, ok := currentPreDigestItem.Value().(types.PreRuntimeDigest)
+		if !ok {
+			return fmt.Errorf("first digest item is not pre-digest")
```
Comment (EclesioMeloJunior) [inline lib/babe/verify.go:361]: I would suggest to create the error `ErrNoFirstPreDigest` and set in the error message the type of `currentPreDigestItem.Value()`
```suggestion
			return fmt.Errorf("%w: got %T", ErrNoFirstPreDigest, currentPreDigestItem.Value())
```

File: lib/babe/verify.go [hunk 2]
```diff
@@ -354,17 +354,40 @@ func (b *verifier) verifyAuthorshipRight(header *types.Header) error {
 			continue
 		}
 
+		currentPreDigestItem := currentHeader.Digest.Types[0]
```
Comment (EclesioMeloJunior) [inline lib/babe/verify.go:357]: should we check the `len()` of `Types` before getting the first index?

**Review by EclesioMeloJunior — CHANGES_REQUESTED** [review]

File: lib/babe/verify_test.go [hunk 3]
```diff
@@ -697,22 +665,134 @@ func Test_verifier_verifyAuthorshipRight(t *testing.T) {
...
+		name     string
+		verifier verifier
+		header   *types.Header
+		expErr   error
+	}{
 		{
 			name:     "equivocate - primary",
-			verifier: *babeVerifier7,
-			header:   header7,
+			verifier: *verifierEquivocatoryPrimary,
```
Comment (EclesioMeloJunior) [inline lib/babe/verify_test.go:782]: This verifier is using a mock that defines `mockBlockStateEquiv1.EXPECT().GetAllBlocksAtDepth(gomock.Any())` but it is possible to replace the `gomock.Any()` with the `headerEquivocatoryPrimary.ParentHash`, same for the others mocks using the `gomock.Any()`

**Review by EclesioMeloJunior — CHANGES_REQUESTED** [review]

**Review by edwardmack — APPROVED** [review]

File: lib/babe/verify_test.go (hunk 3 above)
Comment (kishansagathiya) [reply lib/babe/verify_test.go:785]: :+1:  addressed

File: lib/babe/verify.go [hunk 4]
```diff
@@ -347,26 +347,55 @@ func (b *verifier) verifyAuthorshipRight(header *types.Header) error {
...
 			existingBlockProducerIndex = d.AuthorityIndex
 		case types.BabeSecondaryPlainPreDigest:
 			existingBlockProducerIndex = d.AuthorityIndex
 		}
 
-		// same authority won't produce two different blocks at the same block number
-		if currentBlockProducerIndex == existingBlockProducerIndex && hash != header.Hash() {
+		// same authority won't produce two different blocks at the same block number as primary block producer
+		if currentBlockProducerIndex == existingBlockProducerIndex &&
+			hash != header.Hash() &&
```
[the remark this answers is not in the document]
Comment (kishansagathiya) [reply lib/babe/verify.go]: :+1: addressed

File: lib/babe/verify.go [hunk 5]
```diff
@@ -347,26 +347,55 @@ func (b *verifier) verifyAuthorshipRight(header *types.Header) error {
...
 		}
 
 		currentBlockProducerIndex, err := getAuthorityIndex(currentHeader)
 		if err != nil {
+			logger.Errorf("failed to get authority index %s", err)
 			continue
 		}
 
+		if len(currentHeader.Digest.Types) == 0 {
+			return fmt.Errorf("current header missing digest")
```
[the remark this answers is not in the document]
Comment (kishansagathiya) [reply lib/babe/verify.go]: :+1: addressed

File: dot/types/babe.go [hunk 6]
```diff
@@ -107,7 +110,7 @@ func GetSlotFromHeader(header *Header) (uint64, error) {
 
 	preDigest, ok := header.Digest.Types[0].Value().(PreRuntimeDigest)
 	if !ok {
-		return 0, fmt.Errorf("first digest item is not pre-digest")
+		return 0, ErrNoFirstPreDigest
```
Comment (EclesioMeloJunior) [inline dot/types/babe.go:113]: Would be nice to put in the message the type we got
```suggestion
		return 0, fmt.Errorf("%w: got %T", ErrNoFirstPreDigest, header.Digest.Types[0].Value())
```

File: lib/babe/verify.go [hunk 7]
```diff
@@ -277,12 +277,12 @@ func (b *verifier) verifyAuthorshipRight(header *types.Header) error {
...
 	preDigest, ok := preDigestItem.Value().(types.PreRuntimeDigest)
 	if !ok {
-		return fmt.Errorf("first digest item is not pre-digest")
+		return fmt.Errorf("%w: got %T", types.ErrNoFirstPreDigest, preDigestItem.Value())
 	}
 
 	seal, ok := sealItem.Value().(types.SealDigest)
 	if !ok {
-		return fmt.Errorf("last digest item is not seal")
+		return errLastDigestItemNotSeal
```
Comment (EclesioMeloJunior) [inline lib/babe/verify.go:285]:
```suggestion
		return fmt.Errorf("%w: got %T", errLastDigestItemNotSeal, sealItem.Value())
```

File: lib/babe/verify.go [hunk 8]
```diff
@@ -344,29 +344,58 @@ func (b *verifier) verifyAuthorshipRight(header *types.Header) error {
...
 		}
 
 		currentBlockProducerIndex, err := getAuthorityIndex(currentHeader)
 		if err != nil {
+			logger.Errorf("failed to get authority index %s", err)
 			continue
 		}
 
+		if len(currentHeader.Digest.Types) == 0 {
+			logger.Errorf("current header missing digest")
```
Comment (EclesioMeloJunior) [inline lib/babe/verify.go:361]: should we return or continue to the next iteration?

File: lib/babe/verify.go [hunk 9]
```diff
@@ -344,29 +344,58 @@ func (b *verifier) verifyAuthorshipRight(header *types.Header) error {
...
 			existingBlockProducerIndex = d.AuthorityIndex
 		case types.BabeSecondaryPlainPreDigest:
 			existingBlockProducerIndex = d.AuthorityIndex
 		}
 
-		// same authority won't produce two different blocks at the same block number
-		if currentBlockProducerIndex == existingBlockProducerIndex && hash != header.Hash() {
+		// same authority won't produce two different blocks at the same block number as primary block producer
+		if currentBlockProducerIndex == existingBlockProducerIndex &&
+			currentHash.Equal(header.Hash()) &&
```
Comment (EclesioMeloJunior) [inline lib/babe/verify.go:397]: should be not equal, right?
```suggestion
			!currentHash.Equal(header.Hash()) &&
```

**Review by EclesioMeloJunior — CHANGES_REQUESTED** [review]

File: dot/types/babe.go (hunk 6 above)
Comment (EclesioMeloJunior) [inline dot/types/babe.go:113]:
```suggestion
		return 0, fmt.Errorf("%w: type=%T", ErrNoFirstPreDigest, header.Digest.Types[0].Value())
```

File: lib/babe/verify.go [hunk 10]
```diff
@@ -277,12 +277,12 @@ func (b *verifier) verifyAuthorshipRight(header *types.Header) error {
 
 	preDigest, ok := preDigestItem.Value().(types.PreRuntimeDigest)
 	if !ok {
-		return fmt.Errorf("first digest item is not pre-digest")
+		return fmt.Errorf("%w: got %T", types.ErrNoFirstPreDigest, preDigestItem.Value())
```
Comment (EclesioMeloJunior) [inline lib/babe/verify.go:280]: in some places, you've used `fmt.Errorf("%w: type=%T")` and in others you've used `fmt.Errorf("%w: got %T")` so would be nice to choose a single one and keep it as the default. IMO I would choose `fmt.Errorf("%w: got %T")` as the error explain that we did not receive the predigest but we got another type -> `ErrNoFirstPreDigest: got %T`

**Review by EclesioMeloJunior — CHANGES_REQUESTED** [review]

File: lib/babe/verify.go [hunk 11]
```diff
@@ -344,29 +344,58 @@ func (b *verifier) verifyAuthorshipRight(header *types.Header) error {
...
+		if err != nil {
+			return fmt.Errorf("failed to verify pre-runtime digest: %w", err)
+		}
+
+		var isCurrentBlockProducerPrimary bool
+		switch currentBabePreDigest.(type) {
+		case types.BabePrimaryPreDigest:
+			isCurrentBlockProducerPrimary = true
+		default:
+		}
```
Comment (timwu20) [inline lib/babe/verify.go:381]:
```suggestion
		_, isCurrentBlockProducerPrimary := currentBabePreDigest.(types.BabePrimaryPreDigest)
```

File: lib/babe/verify.go [hunk 12]
```diff
@@ -344,29 +344,53 @@ func (b *verifier) verifyAuthorshipRight(header *types.Header) error {
...
 		}
 
 		currentBlockProducerIndex, err := getAuthorityIndex(currentHeader)
 		if err != nil {
+			logger.Errorf("failed to get authority index %s", err)
 			continue
 		}
 
+		if len(currentHeader.Digest.Types) == 0 {
+			logger.Errorf("current header missing digest")
```
Comment (EclesioMeloJunior) [inline lib/babe/verify.go:361]: I think we should jump to the next item otherwise this condition will let empty `currentHeader.Digest.Types` go further and panic the node when tried to `currentPreDigestItem := currentHeader.Digest.Types[0]`

**Review by EclesioMeloJunior — CHANGES_REQUESTED** [review]

File: lib/babe/verify.go (hunk 12 above)
Comment (kishansagathiya) [reply lib/babe/verify.go]: I have started returning things, it makes more sense since it's a verification function.

**Review by EclesioMeloJunior — APPROVED** [review]
