### PR TITLE
fixes for polkadot.js UI

### LINKED ISSUE #865: Load system properties/chain name from genesis
## Expected Behavior

Get system properties related to chain from genesis definition:
- For RPC call `system_chain` get the chain's type. Given as a string identifier.
- For RPC call `system_properties` Get a custom set of properties as a JSON object, defined in the chain spec.

## Current Behavior

- Currently gets `system_chain` from Global config value Name
- Currently treats `system_properties` as empty result.

## Possible Solution

- Implement these to get their value from genesis. 
See https://github.com/w3f/PSPs/blob/psp-rpc-api/psp-002.md#system_properties

## Checklist

- [x] I have read [CONTRIBUTING](CONTRIBUTING.md) and [CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

### LINKED ISSUE #1248: load genesis fields into database
## Expected Behavior

- These fields are loaded from the genesis-raw.json but are not stored in database:
- [ ] properties
- [ ] forkBlocks
- [ ] badBlocks
- [ ] consensusEngine

## Current Behavior

- These fields are loaded into Genesis object, but not stored in database. 

## Possible Solution

- Add fields to Data struct, which is used when initializing database.

## Steps to Reproduce

1.
2.
3.
4.

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [x] I am planning to submit a pull request to fix this issue myself

### PR DESCRIPTION
**Pull request by noot**
## Changes

- update chain type in ksmcc genesis
- fix getting version for kusama
- load/store genesis properties from db
- (all of these help polkadot.js ui to work)

## Tests

```
./bin/gossamer --key alice --config chain/gssmr/config.toml --basepath /tmp/goss_dev --rpc --ws 
```

open https://polkadot.js.org/apps/#/explorer , navigate to development -> custom endpoint -> `ws://localhost:8546` 

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [x] I have reviewed my own pull request before requesting a review
- [x] All integration tests and required coverage checks are passing

## Issues

- closes #1248 
- closes #865
- related to #1366

### CODE REVIEW

**Review by RyRy79261 — APPROVED** [review]

File: dot/state/db.go [hunk 1]
```diff
@@ -44,7 +44,7 @@ func LoadBestBlockHash(db database.Database) (common.Hash, error) {
 
 // StoreGenesisData stores the given genesis data at the known GenesisDataKey.
 func StoreGenesisData(db database.Database, gen *genesis.Data) error {
-	enc, err := scale.Encode(gen)
+	enc, err := json.Marshal(gen)
 	if err != nil {
```
Comment (edwardmack) [inline dot/state/db.go:48]: This is great, I was stuck here because I couldn't figure out how to scale encode/decode type make[string]interface{}, but of course it doesn't need to be scale encode, it can be JSON.  Nice!

**Review by edwardmack — APPROVED** [review]
Great work.
