### PR TITLE
Fix: check auth changes before processing block 

### LINKED ISSUE #4281: Westend sync stalls at block #2318338
## Describe the bug

When syncing Westend from genesis, the node does not progress past block <strike>#2322947</strike> #2318338. The issues seems to be related to verification of GRANDPA justifications.

## Log output

```
2024-10-28 03:00:09.839 | 2024-10-27T20:00:09Z CRITICAL current sync strategy failed with: while handling ready block: verifying justification: decoding and verifying justification: bad justification for header: invalid commit in grandpa justification	pkg=sync  
2024-10-28 03:00:09.839 | 2024-10-27T20:00:09Z ERROR    processing block #2318339 (0xa6836b1530280181eabce3ded01e62283c7d6a64c6edbc9c789a28b10dc14be4) failed: verifying justification: decoding and verifying justification: bad justification for header: invalid commit in grandpa justification	pkg=sync
```

### PR DESCRIPTION
**Pull request by dimartiro**
## Changes

- [x] Process block headers and data before importing the block
- [x] Implement vdt for `runtime.DigestItem`

This changes will fix 2 issues:
- When we have to apply forced changes for the current block right before processing it.
- Decoding header digests in grandpa justifications.  

## Tests

```sh
make test
```

## Issues

closes #4281

### CODE REVIEW

File: dot/sync/block_importer.go [hunk 1]
```diff
@@ -104,20 +104,7 @@ func (b *blockImporter) importBlock(bd *types.BlockData, origin BlockOrigin) (im
...
-			round, setID, err = b.finalityGadget.VerifyBlockJustification(
-				blockData.Header.Hash(), blockData.Header.Number, *blockData.Justification)
-			if err != nil {
-				return fmt.Errorf("verifying justification: %w", err)
-			}
-		}
+		header := blockData.Header
 
 		if blockData.Body != nil {
 			err := b.processBlockDataWithHeaderAndBody(blockData, origin)
```
Comment (EclesioMeloJunior) [inline dot/sync/block_importer.go:110]: just a obs: we want to ensure that the justification has valid signatures before importing the block

Comment (dimartiro) [reply dot/sync/block_importer.go:110]: mmm you mean we would have to split the `processBlockDataWithHeaderAndBody` function so one part will be executed here and the other one after verifying the justification? Or I'm missing something? 
My changes are based on a "revert" of [these changes](https://github.com/ChainSafe/gossamer/commit/1836e44e018d32da11e4b84f779418a83406f835#diff-fa462c9d158b0ade886d250e613472bb634287b6fb2025c0d818942b0ced5763)

Comment (EclesioMeloJunior) [reply dot/sync/block_importer.go:110]: yeah, like: check the sigs from the justification (maybe given that we need to apply a forced change we should consider the new auths before checking the sig) ensure they are valid and then import the block. Basically `processBlockDataWithHeaderAndBody` is where we import the block, and I saw that we do the justification check after calling `processBlockDataWithHeaderAndBody`.

File: internal/client/consensus/grandpa/justification_test.go [hunk 2]
```diff
@@ -81,6 +81,17 @@ func TestJustificationEncoding(t *testing.T) {
 	require.Equal(t, expected, justification.Justification)
 }
 
+func TestDecodeJustificationFromWestendBlock2323464(t *testing.T) {
```
Comment (haikoschol) [inline internal/client/consensus/grandpa/justification_test.go:84]: Is this the test that reproduces the issue? If yes, why is it testing block 2323464 instead of 2318338?

File: internal/primitives/runtime/digest.go [hunk 3]
```diff
@@ -11,12 +17,82 @@ type DigestItemTypes interface {
 
 // Digest item that is able to encode/decode 'system' digest items and
 // provide opaque access to other items.
-// TODO: implement this as scale.VaryingDataType
-type DigestItem any
+type DigestItem struct {
```
Comment (haikoschol) [inline internal/primitives/runtime/digest.go:20]: Why do we need to duplicate this type? Can't we use one of the two everywhere?

**Review by haikoschol — DISMISSED** [review]
@dimartiro I was too late to check on Grafana how far the node has synced and my local node hasn't gotten to the problematic block yet. But based on your screenshot on the issue and the code changes, I believe that the issue is fixed.

File: internal/primitives/runtime/digest.go (hunk 3 above)
Comment (haikoschol) [reply internal/primitives/runtime/digest.go:20]: Will be unified as part of a future refactoring.

File: internal/client/consensus/grandpa/justification_test.go (hunk 2 above)
Comment (dimartiro) [reply internal/client/consensus/grandpa/justification_test.go:84]: No, this one is meant to fix another issue that arose while I was reviewing the other one. I'll be adding tests for 2318338 once I finish addressing this [comment](https://github.com/ChainSafe/gossamer/pull/4336#discussion_r1863713207)

File: internal/primitives/runtime/digest.go (hunk 3 above)
Comment (dimartiro) [reply internal/primitives/runtime/digest.go:20]: Already discussed by DM in slack

File: dot/sync/block_importer.go (hunk 1 above)
Comment (dimartiro) [reply dot/sync/block_importer.go:110]: I think the most straightforward way to solve this is by applying the forced changes as a first step in `processBlockData`. So I changed that in my last commit and I'm testing it in our nodes now. Let me know what you think @EclesioMeloJunior

Comment (EclesioMeloJunior) [reply dot/sync/block_importer.go:110]: That will not solve the problem, because you're trying to apply the forced change before we know about it. What happens is: Forced changes are in the block digests, basically the infos inside it is the block number where this change will take place and the new auths (normaly the block number is the same as the block that contains the forced change) so when we import the block we extract the digest and get the forced change and we place it in a [`orderedPendingChanges`](https://github.com/ChainSafe/gossamer/blob/a46ad52411cb95dad9e706c8c725f00ff940f36d/dot/state/grandpa_changes.go#L38) that stores the changes in order so whenever we import a block we check if there is a change to do.

So, if you try to apply a forced change before adding it to the `orderedPendingChanges` it will never found it and will always return nil. 

Maybe you will need to open the block digest and check if there is a forced change that will take place in the current block, if so you apply it directly (following the same rules as `ApplyForcedChanges`), I believe that code should be under `dot/state/grandpa.go`

Comment (dimartiro) [reply dot/sync/block_importer.go:110]: What about [now](https://github.com/ChainSafe/gossamer/pull/4336/commits/2d8968e15aed387db0ba96eff7d302a987bb45b3)?

File: dot/sync/block_importer.go [hunk 4]
```diff
@@ -99,6 +108,39 @@ func (b *blockImporter) importBlock(bd *types.BlockData, origin BlockOrigin) (im
...
+			if _, ok := digestValue.(types.GrandpaForcedChange); ok {
+				err = b.grandpaState.HandleGRANDPADigest(header, data)
+				if err != nil {
+					return fmt.Errorf("handling grandpa digest: %w", err)
+				}
+			}
+		}
+	}
+
+	return b.grandpaState.ApplyForcedChanges(header)
```
Comment (EclesioMeloJunior) [inline dot/sync/block_importer.go]: We should not apply the forced changes here, we should let it to the import flow, here we should only check the sigs w/o changing the state.

**Comment by haikoschol** [comment]
The latest deployment stalled at block #1491033. Apart from lots of networking errors, I found this in the logs:
```
2024-12-10T04:52:45Z CRITICAL current sync strategy failed with: while handling ready block: applying forced changes: cannot find applicable forced change: failed while applying condition: cannot check ancestry: getting header: pebble: not found   pkg=sync
```

**Comment by dimartiro** [comment]
> The latest deployment stalled at block #1491033. Apart from lots of networking errors, I found this in the logs:
> 
> ```
> 2024-12-10T04:52:45Z CRITICAL current sync strategy failed with: while handling ready block: applying forced changes: cannot find applicable forced change: failed while applying condition: cannot check ancestry: getting header: pebble: not found   pkg=sync
> ```

Yeah, I'm changing the approach and trying with the latest [comment](https://github.com/ChainSafe/gossamer/pull/4336#discussion_r1876159227) from Eclesio

File: dot/sync/block_importer.go (hunk 4 above)
Comment (dimartiro) [reply dot/sync/block_importer.go]: But just to clarify, in some way we are gonna have to know new authorities from the forced changes before applying them, then check the justification against those authorities without finalizing anything (because we didn't import the block yet) and I think that will mess our code in some way 😞 

I've been checking substrate code and they are:

1. [Applying the authorities changes](https://github.com/paritytech/polkadot-sdk/blob/da2dd9b7737cb7c0dc9dc3dc74b384c719ea3306/substrate/client/consensus/grandpa/src/import.rs#L578C7-L578C22)
2. [Importing the block](https://github.com/paritytech/polkadot-sdk/blob/da2dd9b7737cb7c0dc9dc3dc74b384c719ea3306/substrate/client/consensus/grandpa/src/import.rs#L582)
3. [Processing the justification](https://github.com/paritytech/polkadot-sdk/blob/da2dd9b7737cb7c0dc9dc3dc74b384c719ea3306/substrate/client/consensus/grandpa/src/import.rs#L650)

That's what I wanted to reproduce that behavior

**Review by EclesioMeloJunior — APPROVED** [review]

**Review by timwu20 — APPROVED** [review]
