### PR TITLE
fix(dot/network): Fix notification handshake and reuse stream.

### LINKED ISSUE #1524: dot/network: update notifications protocol to track specific stream w/ established handshake
## Task summary

- currently, a stream is established via handshake, however when messages are sent out it doesn't necessarily send it over the established stream
- we should track established streams and use them for pushing notifications messages
- this can be done potentially by storing the stream inside a peer's `handshakeData` or by tagging the libp2p stream itself `https://pkg.go.dev/github.com/libp2p/go-libp2p-core/network#Stat` using `Stat.Extra`

### LINKED ISSUE #1538: Non authority node fails to handle block announce message.
## Issue summary

- Non-authority node fails to read block announce message.

## Other information and links

- Continuation of #1482

### PR DESCRIPTION
**Pull request by arijitAD**
## Changes

- Fix notification handshake
- Reuse stream created during the handshake.

## Tests

```
TestPendingExtrinsic
```

## Issues

- closes #1538
- closes #1524

### CODE REVIEW

File: dot/network/host.go [hunk 1]
```diff
@@ -262,32 +262,26 @@ func (h *host) bootstrap() {
 	}
 }
 
-// send writes the given message to the outbound message stream for the given
-// peer (gets the already opened outbound message stream or opens a new one).
-func (h *host) send(p peer.ID, pid protocol.ID, msg Message) (err error) {
-	// get outbound stream for given peer
-	s := h.getOutboundStream(p, pid)
```
Comment (noot) [inline dot/network/host.go:269]: why is this removed?

File: dot/network/notifications.go [hunk 2]
```diff
@@ -256,13 +291,38 @@ func (s *Service) broadcastExcluding(info *notificationsProtocol, excluding peer
 				}
 			}
 
+			hsData, has = info.getHandshakeData(peer)
+			if !has {
+				continue
+			}
```
Comment (noot) [inline dot/network/notifications.go:297]: shouldn't this be covered by the first case? `if hsData, has := info.getHandshakeData(peer); !has || !hsData.received`

File: dot/network/notifications.go [hunk 3]
```diff
@@ -256,13 +291,38 @@ func (s *Service) broadcastExcluding(info *notificationsProtocol, excluding peer
...
 			logger.Trace("sending message", "protocol", info.protocolID, "peer", peer, "message", msg)
-			err = s.host.send(peer, info.protocolID, msg)
-		}
 
-		if err != nil {
-			logger.Debug("failed to send message to peer", "peer", peer, "error", err)
+			err = s.host.writeToStream(hsData.stream, msg)
+			if err != nil {
+				logger.Trace("failed to send message to peer", "peer", peer, "error", err)
+			}
```
Comment (noot) [inline dot/network/notifications.go:305]: this can be moved outside the `if-else` case, since in the `if` block we exchange the handshake, we still want to send the message after exchanging the handshake

File: dot/network/notifications.go [hunk 4]
```diff
@@ -256,13 +291,38 @@ func (s *Service) broadcastExcluding(info *notificationsProtocol, excluding peer
...
 	}
 }
+
+func readHandshake(stream libp2pnetwork.Stream) (Handshake, error) {
+	msgBytes := make([]byte, maxBlockResponseSize)
+	tot, err := readStream(stream, msgBytes)
+	if err == io.EOF {
+		return nil, io.EOF
+	} else if err != nil {
+		logger.Trace("failed to read handshake from stream", "peer", stream.Conn().RemotePeer(), "protocol", stream.Protocol(), "error", err)
```
Comment (noot) [inline dot/network/notifications.go:316]: can remove the logs in this function and leave it to the caller of `readHandshake` to log

File: dot/network/notifications.go [hunk 5]
```diff
@@ -256,13 +291,38 @@ func (s *Service) broadcastExcluding(info *notificationsProtocol, excluding peer
...
+		_ = stream.Close()
+		return nil, err
+	}
+
+	// TODO: Implement this for other messages.
+	handShake, err := decodeBlockAnnounceHandshake(msgBytes[:tot])
+	if err != nil {
+		logger.Trace("failed to decode handshake message from peer", "protocol", stream.Protocol(), "err", err)
```
Comment (noot) [inline dot/network/notifications.go:324]: same here

File: dot/network/utils.go [hunk 6]
```diff
@@ -204,6 +204,7 @@ func readStream(stream libp2pnetwork.Stream, buf []byte) (int, error) {
 		return 0, fmt.Errorf("message size greater than maximum: got %d", length)
 	}
 
+	// TODO: Allocate buffer after reading length. Avoid pre allocation.
```
Comment (noot) [inline dot/network/utils.go:207]: can you remove this? the reason it pre-allocates is because:
1. allocation is expensive, if we allocate each time we receive a message it increases our CPU usage a lot
2. we don't want to allocate a byte array based on a length a peer gives us, because a malicious peer can then tell us to allocate some very large buffer causing the node to crash

**Review by noot — COMMENTED** [review]
looking good! just a few comments, but overall great work :D

File: dot/network/host.go (hunk 1 above)
Comment (arijitAD) [reply dot/network/host.go:269]: `send` is only called from `broadcastExcluding` when we don't have handshake data in which case we need to create a new stream.

File: dot/network/notifications.go (hunk 2 above)
Comment (arijitAD) [reply dot/network/notifications.go:297]: Done

File: dot/network/notifications.go (hunk 4 above)
Comment (arijitAD) [reply dot/network/notifications.go:316]: Done

File: dot/network/notifications.go (hunk 5 above)
Comment (arijitAD) [reply dot/network/notifications.go:324]: Done

File: dot/network/notifications.go [hunk 7]
```diff
@@ -209,6 +214,59 @@ func (s *Service) createNotificationsMessageHandler(info *notificationsProtocol,
 	}
 }
 
+func (s *Service) sendData(peer peer.ID, hs Handshake, info *notificationsProtocol, msg NotificationsMessage) {
+	var err error
+	hsData, has := info.getHandshakeData(peer)
+	if !has || !hsData.received || !hsData.validated {
```
Comment (noot) [inline dot/network/notifications.go:220]: if we've already received the data but it's not valid, then we should return (and probably close the stream with the peer, or disconnect from them)

File: dot/network/notifications.go [hunk 8]
```diff
@@ -209,6 +214,59 @@ func (s *Service) createNotificationsMessageHandler(info *notificationsProtocol,
...
+
+		if !added {
+			return
+		}
+	}
+
+	// we've already completed the handshake with the peer, send message directly
+	logger.Trace("sending message", "protocol", info.protocolID, "peer", peer, "message", msg)
+
+	err = s.host.writeToStream(hsData.stream, msg)
```
Comment (noot) [inline dot/network/notifications.go:264]: check `hsData.stream != nil`

File: dot/network/service.go [hunk 9]
```diff
@@ -398,6 +398,10 @@ func (s *Service) RegisterNotificationsProtocol(sub protocol.ID,
 
 	decoder := createDecoder(info, handshakeDecoder, messageDecoder)
 	handlerWithValidate := s.createNotificationsMessageHandler(info, handshakeValidator, messageHandler)
+	streamHandler := func(stream libp2pnetwork.Stream, peerID peer.ID) {
+		s.readStream(stream, peerID, decoder, handlerWithValidate)
+	}
+	np.streamHandler = streamHandler
```
Comment (noot) [inline dot/network/service.go:404]: nice :D

File: dot/network/notifications.go [hunk 10]
```diff
@@ -55,23 +55,25 @@ type notificationsProtocol struct {
 	protocolID    protocol.ID
 	getHandshake  HandshakeGetter
 	handshakeData *sync.Map //map[peer.ID]*handshakeData
+	streamHandler func(stream libp2pnetwork.Stream, peerID peer.ID)
```
Comment (noot) [inline dot/network/notifications.go:58]: maybe put `func(stream libp2pnetwork.Stream, peerID peer.ID)` as its own type?

**Review by noot — COMMENTED** [review]
great work!! only small comments

File: dot/network/notifications.go (hunk 7 above)
Comment (arijitAD) [reply dot/network/notifications.go:220]: This is already done in the notification handler.

Comment (noot) [reply dot/network/notifications.go:220]: in that case, can you remove the `|| !hsData.validated` case?

File: dot/network/notifications.go (hunk 10 above)
Comment (arijitAD) [reply dot/network/notifications.go:58]: Done

File: dot/network/notifications.go (hunk 8 above)
Comment (arijitAD) [reply dot/network/notifications.go:264]: Done

File: dot/network/notifications.go (hunk 7 above)
Comment (arijitAD) [reply dot/network/notifications.go]: Done

**Review by timwu20 — APPROVED** [review]

File: dot/network/notifications.go (hunk 3 above)
Comment (arijitAD) [reply dot/network/notifications.go]: Done

**Review by noot — APPROVED** [review]
amazing work! tested it out with polkadot and works as it should :)
