### PR TITLE
dot/rpc, dot/types: fix RPC json header digest logs response

### LINKED ISSUE #744: fix json output for digest from RPC calls
Results from RPC calls that contain header responses, the digest results are not formatted as a hex string, instead results are shown as raw bytes.  

## Expected Behavior
```
 "digest": {
            "logs": [
                "0x066175726120b33bc10f00000000",
                "0x05617572610101180b4de13f74e206324c2b168b72acec4ceb563d3788a51e9671170cd23d426a7d6c444e7e3aed5ad65ae9a07ce9d14317601dcce7a2660638ddfccc460a6882"
            ]
        },
```

## Current Behavior
```
 "digest": [
            "AUJBQkUqwA/Tab4jGXRT1DnPUe+OPAzd1XbAYggcfYJpd9LGcrWY+ixNWMq6aoICoTqxBau2Cz4RZpLkSIsmnbAAtJEPtNDynEtllnhb+vfnMlbdSWDXEo/Ipb9tUWJHiuEH6g8AAAAAAAAAAG4HAAAAAAAA",
            "BEJBQkVaX75EtA7tF/9Vz2bcVHRjc0EHLnOSFrIPP+7VGc8We2GbQoYqkp7as+1PLyvnM3+Mh4gt+h1hbZEz2Kq3U7OH"
        ]
```

## Steps to Reproduce (for bugs)

1. RPC call chain_getHeader or chain_getBlock
2.
3.
4.

## Your Environment
* Version used:
* Commit hash:
* Go Version:
* Operating System and version (include distro if Linux):
* Link to your project or reproducible gist:
* I intend to submit a pull request to fix this issue: [ ]

### PR DESCRIPTION
**Pull request by edwardmack**
## Changes

- Fix response for RPC methods contain json header digest logs so that response is now represented as an array of strings of hex values
- Update digest type IDs to conform to Polkadot Host Protocol Spec table 3.2.
-

## Tests:

```
go test ./dot/rpc/...
go test ./dot/types/...

```

## Checklist:

- [x] I have read [CONTRIBUTING](CONTRIBUTING.md) and [CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)
- [x] I have provided as much information as possible and necessary
- [x] I have reviewed my own pull request before requesting a review
- [x] I have linked any relevant issues in my pull request comments
- [x] All integration tests and required coverage checks are passing

## Issues:

- Closes #744

### CODE REVIEW

File: dot/rpc/modules/chain.go [hunk 1]
```diff
@@ -45,11 +46,16 @@ type ChainBlock struct {
...
-	ParentHash     string   `json:"parentHash"`
-	Number         *big.Int `json:"number"`
-	StateRoot      string   `json:"stateRoot"`
-	ExtrinsicsRoot string   `json:"extrinsicsRoot"`
-	Digest         [][]byte `json:"digest"`
+	ParentHash     string                 `json:"parentHash"`
+	Number         *big.Int               `json:"number"`
+	StateRoot      string                 `json:"stateRoot"`
+	ExtrinsicsRoot string                 `json:"extrinsicsRoot"`
+	Digest         ChainBlockHeaderDigest `json:"digest"`
```
Comment (noot) [inline dot/rpc/modules/chain.go:53]: is this in the spec? I couldn't find it anywhere

Comment (edwardmack) [reply dot/rpc/modules/chain.go:53]: I'm using this as spec for JSON result: https://github.com/w3f/PSPs/blob/psp-rpc-api/psp-002.md#chain_getHeader 

But I see now that I should be treating number as a hex string, so I'll update that.
