### PR TITLE
fix(runtime): add child prefix check

### LINKED ISSUE #4142: Ignore when `ext_storage_clear_prefix` is called with child trie prefix
## Issue summary

- There is a import method called `ext_default_child_storage_clear_prefix` that should be used to clear prefix inside child tries, so we should ignore when the runtime calls `ext_storage_clear_prefix` passing the child trie prefix.

In gossamer we only check for the `DEFAULT_CHILD_STORAGE_KEY_PREFIX`, now we should check for `CHILD_STORAGE_KEY_PREFIX` as well, below there is a rust snippet of how the child storage key prefix is defined.

```rs
/// Prefix of child storage keys.
pub const CHILD_STORAGE_KEY_PREFIX: &[u8] = b":child_storage:";

/// Prefix of the default child storage keys in the top trie.
pub const DEFAULT_CHILD_STORAGE_KEY_PREFIX: &[u8] = b":child_storage:default:";
```

## Other information and links

- https://github.com/paritytech/polkadot-sdk/blob/b2ec017c0e5e49f3cbf782a5255bb0f9e88bd6c1/substrate/primitives/state-machine/src/ext.rs#L452

### PR DESCRIPTION
**Pull request by jimjbrettj**
## Changes

- When clearing a prefix from storage, first do a check to make sure the prefix does not contain the child prefix

## Tests

```sh
go test -tags integration github.com/ChainSafe/gossamer
```

## Issues
closes #4142

### CODE REVIEW

File: lib/runtime/wazero/imports.go [hunk 1]
```diff
@@ -2117,25 +2124,30 @@ func ext_storage_clear_prefix_version_2(ctx context.Context, m api.Module, prefi
...
+			logger.Errorf("failed to allocate: %s", err)
+			panic(err)
+		}
 
-	return valueSpan
+		return valueSpan
+	} else {
+		logger.Warnf("cannot clear prefix that is part of or contains a child storage key")
+	}
+	return 0
```
Comment (jimjbrettj) [inline lib/runtime/wazero/imports.go]: Wanted to double-check that we want to ignore this case and not panic. Also here wanted to make sure 0 was the correct value to return

**Review by EclesioMeloJunior — COMMENTED** [review]
We should not panic but return none Afaik

File: lib/runtime/wazero/imports.go [hunk 2]
```diff
@@ -2065,10 +2067,15 @@ func ext_storage_clear_prefix_version_1(ctx context.Context, m api.Module, prefi
...
-	err := storage.ClearPrefix(prefix)
-	if err != nil {
-		panic(err)
+	if !bytes.HasPrefix(prefix, childStorageKeyPrefix) {
+		err := storage.ClearPrefix(prefix)
+		if err != nil {
+			panic(err)
+		}
+	} else {
+		logger.Warnf("cannot clear prefix that is part of or contains a child storage key")
```
Comment (EclesioMeloJunior) [inline lib/runtime/wazero/imports.go:2076]:
```suggestion
	if !bytes.HasPrefix(prefix, childStorageKeyPrefix) {
		storage.ClearPrefix(prefix)
	} else {
		logger.Warnf("cannot clear a child prefix key: 0x%x", prefix)
```

File: lib/runtime/wazero/imports.go [hunk 3]
```diff
@@ -2117,25 +2124,30 @@ func ext_storage_clear_prefix_version_2(ctx context.Context, m api.Module, prefi
 		limitPtr = &maxLimit
 	}
 
-	numRemoved, all, err := storage.ClearPrefixLimit(prefix, *limitPtr)
-	if err != nil {
-		logger.Errorf("failed to clear prefix limit: %s", err)
-		panic(err)
-	}
+	if !bytes.HasPrefix(prefix, childStorageKeyPrefix) {
```
Comment (EclesioMeloJunior) [inline lib/runtime/wazero/imports.go]: instead of making the logic nested, you can check the prefix before calling the storage function, you can place the check after reading the prefix from memory, like:

```go
prefix := read(m, prefixSpan)
logger.Debugf("prefix: 0x%x", prefix)

if bytes.HasPrefix(prefix, childStorageKeyPrefix) {
    logger.Warnf("cannot clear child prefix: 0x%x", prefix)
    // the value you must return is a storage result enum
    // that can be built by calling toKillStorageResultEnum func
    encBytes, err := toKillStorageResultEnum(false, 0)
    if err != nil { ... }
    
    valueSpan := mustWrite(m, rtCtx.Allocator, encBytes)
    return valueSpan
}

... rest of the logic here 
```

**Review by EclesioMeloJunior — CHANGES_REQUESTED** [review]

File: lib/runtime/wazero/imports.go (hunk 2 above)
Comment (jimjbrettj) [reply lib/runtime/wazero/imports.go:2076]: Before we panicked if there was an error clearing the prefix, is there a reason you want to modify this behavior?

Comment (EclesioMeloJunior) [reply lib/runtime/wazero/imports.go:2076]: oh, just saw, nevermind!

**Review by EclesioMeloJunior — APPROVED** [review]

**Review by P1sar — APPROVED** [review]
