### PR TITLE
tool(script): state retrieval script

### LINKED ISSUE #4109: Westend sync stopped at #20368319 with `Storage root must match that calculated`
## Describe the bug

The westend instance stopped syncing with the error: `Storage root must match that calculated`.

Before the error happens we have a runtime upgrade to version `1010000`

The logs:

````
2024-07-26T07:55:07Z INFO 🔨 finalised block #20367872 (0x80cb24a923ecf0826b5d0cf711fb25d9cb473938cdd287a9f1ee896a1196abc1), round 272, set id 7695 pkg=state

2024-07-26T07:58:20Z INFO 🔄 detected runtime code change, upgrading with block 0xec26e9d9fcc255c842e87cdee87f97947932deb449399764a4d2f09d1cdefe80 from previous code hash 0xfc05f1863c0050bac8cb117c094232576bf63b8315415e95c77d506ef656a960 to new code hash 0x67b635216cfd9d40548f3a0d0c963015fb2b9a5b2dcf5171e3933b964a6f3838... pkg=state

2024-07-26T07:58:22Z CRITICAL target=runtime message=panicked at /build/substrate/frame/executive/src/lib.rs:834:9: Storage root must match that calculated. ext_logging_log_version_1 pkg=runtime module=wazero

2024-07-26T07:58:22Z ERROR requesting max blocks from best block header: while handling workers results: while handling ready block: processing block data with header and body: handling block: failed to execute block 20368319: running runtime function: wasm error: unreachable
````

### LINKED ISSUE #4123: state trie retrieve script
## Task summary

- Using the `State Request` p2p we can receive a `State Response` that contains a set of keys and values for a specific block hash, that is useful to debug specific blocks.
- The short term goal is to debug/understand the `Storage root mismatch` error happening on block #20368319 https://github.com/ChainSafe/gossamer/issues/4109.

### PR DESCRIPTION
**Pull request by EclesioMeloJunior**
## Changes

This script was created to be used as a debugging tool, it was used in order to fix https://github.com/ChainSafe/gossamer/issues/4109

## Tests

```sh
N/A
```

## Issues

- Closes https://github.com/ChainSafe/gossamer/issues/4123
- Depends on https://github.com/ChainSafe/gossamer/pull/4089

### CODE REVIEW

File: scripts/p2p/common_p2p.go [hunk 1]
```diff
@@ -117,20 +118,24 @@ func parsePeerAddress(arg string) peer.AddrInfo {
 	return *p
 }
 
-func ReadStream(stream lip2pnetwork.Stream) []byte {
+var (
+	errZeroLength = errors.New("zero length")
+)
```
Comment (jimjbrettj) [inline scripts/p2p/common_p2p.go]:
```suggestion
var errZeroLength = errors.New("zero length")
```

**Review by jimjbrettj — APPROVED** [review]
Super helpful, thanks for this!

**Review by dimartiro — APPROVED** [review]
