### PR TITLE
fix(dot/node) Start websocket server only with `--ws` flag

### LINKED ISSUE #1654: websockets server doesn't start with only `--ws` flag
## Describe the bug

- the websockets server only starts if `--rpc --ws` are provided, but not only `--ws`
- specifying only `--ws` should start the websockets server

### PR DESCRIPTION
**Pull request by EclesioMeloJunior**
## Changes

- check the value of `cfg.RPC.WS` before start the server

## Tests

```
N/A
```

## Issues
- closes #1654

## Screenshots
image

### CODE REVIEW

**Review by noot — APPROVED** [review]

File: dot/node.go [hunk 1]
```diff
@@ -308,7 +308,7 @@ func NewNode(cfg *Config, ks *keystore.GlobalKeystore, stopFunc func()) (*Node,
 	nodeSrvcs = append(nodeSrvcs, sysSrvc)
 
 	// check if rpc service is enabled
-	if enabled := cfg.RPC.Enabled; enabled {
+	if enabled := (cfg.RPC.Enabled || cfg.RPC.WS); enabled {
```
Comment (arijitAD) [inline dot/node.go:311]: Parenthesis is not required.
Not idiomatic to use parenthesis in if-else in Go.

**Review by arijitAD — APPROVED** [review]

File: dot/node.go (hunk 1 above)
Comment (EclesioMeloJunior) [reply dot/node.go]: removed!

**Review by edwardmack — APPROVED** [review]
