### PR TITLE
If the direction in block request is descending, prune blocks from start.

### LINKED ISSUE #2595: Substrate drops gossamer nodes
## Describe the bug

- When we a run network with a substrate and a gossamer node in it. Substrate would eventually drop it. It does not happen always, but it happens rather frequently.

## Possible Solution

It looks like we are sending a block that was not requested. I believe that most likely is the reason, because right after that substrate drops gossamer.
```
2022-06-10 18:53:34.681 DEBUG tokio-runtime-worker sync: Received block that was not requested. Requested Hash(0xc22e325a230162748411c3aa7701a24d8e264a61a5662fc6b5c7e13034afe5bc), got Some(Header { parent_hash: 0xee87cc7ac5e87460094ec4ba29bbf8f28fb7741b69e7edb142233c3dd990b365, number: 1, state_root: 0x358d9a63263eeacf5a753316e2fa7e45405e5a152c32a2546961fdcb3c47d673, extrinsics_root: 0x97ed434301435ad255ef38db54a17a50b13f16985cdee32c49835a0faa405123, digest: Digest { logs: [DigestItem::PreRuntime([66, 65, 66, 69], [3, 0, 0, 0, 0, 116, 209, 168, 24, 0, 0, 0, 0, 48, 247, 238, 88, 232, 162, 220, 223, 135, 104, 230, 159, 199, 113, 199, 243, 60, 205, 76, 56, 4, 45, 39, 197, 106, 228, 110, 170, 128, 167, 42, 39, 235, 121, 30, 38, 236, 154, 127, 30, 100, 144, 31, 236, 246, 105, 47, 254, 120, 236, 178, 192, 70, 162, 110, 123, 117, 92, 237, 94, 82, 50, 179, 0, 61, 203, 4, 126, 246, 19, 158, 138, 198, 109, 196, 244, 84, 21, 213, 37, 43, 217, 125, 125, 78, 87, 197, 94, 87, 126, 4, 250, 86, 52, 13, 8]), DigestItem::Consensus([66, 65, 66, 69], [1, 12, 212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125, 1, 0, 0, 0, 0, 0, 0, 0, 142, 175, 4, 21, 22, 135, 115, 99, 38, 201, 254, 161, 126, 37, 252, 82, 135, 97, 54, 147, 201, 18, 144, 156, 178, 38, 170, 71, 148, 242, 106, 72, 1, 0, 0, 0, 0, 0, 0, 0, 144, 181, 171, 32, 92, 105, 116, 201, 234, 132, 27, 230, 136, 134, 70, 51, 220, 156, 168, 163, 87, 132, 62, 234, 207, 35, 20, 100, 153, 101, 254, 34, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), DigestItem::Seal([66, 65, 66, 69], [132, 221, 173, 106, 54, 91, 32, 133, 8, 188, 216, 164, 9, 83, 204, 149, 224, 200, 66, 194, 142, 221, 3, 15, 86, 88, 178, 6, 194, 68, 87, 73, 29, 64, 173, 25, 93, 248, 211, 112, 252, 186, 186, 249, 79, 93, 20, 105, 50, 99, 40, 160, 38, 230, 235, 177, 64, 107, 16, 43, 187, 199, 214, 135])] } }).    
2022-06-10 18:53:34.681 DEBUG tokio-runtime-worker sync: 12D3KooWN6W3yZYrd5FN8ysPGD5EMryvG4TS6EoNkkzAxmWr37wf disconnected    
```

-

## To Reproduce
Steps I took to reproduce the behaviour:

./bin/gossamer --key bob --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/12D3KooWShRJhQnccFh7aRXPKnjAnUG4x3Lrwfw4wLgTFyDVfqh7 --port 7010 --basepath /tmp/bob --genesis ../substrate-node-template/genesis.json --log trace > bob.log

./bin/gossamer --key charlie --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/12D3KooWShRJhQnccFh7aRXPKnjAnUG4x3Lrwfw4wLgTFyDVfqh7 -port 7011 --basepath /tmp/charlie --genesis ../substrate-node-template/genesis.json --log trace > charlie.log

1. Use  https://github.com/ChainSafe/substrate-node-template/pull/1  for substrate node
2. Create genesis file using substrate node template.
3. Run Substrate using`target/release/gssmr-test-node --alice --chain genesis.json --log=debug &> debug.log
`
4. Run two gossamer nodes 
5. Wait for blocks to get produced. Keep an eye on substrate logs. It should eventually drop from `(2 peers)` to `(1 peers)` to `(0 peers)`

## Log output
Logs of all three nodes in this gist https://gist.github.com/kishansagathiya/ec47bce650b926ff2a0c463d792080a6

### PR DESCRIPTION
**Pull request by kishansagathiya**
## Changes
A block request contain start block, end block, direction and max size.
It could be the case that block between start and end are less than max
size. In such cases, so far we were pruning block from the end while
preparing a block response.

The correct way however would be to prune from the start, if the direction
is descending and prune from the end if the direction is ascending.

Since, we were pruning blocks the wrong way, we were preparing a
response which substrate was not expecting. And that used to result in
substrate dropping us.

This commit fixes that issue.

## Tests

```sh
go test -tags integration github.com/ChainSafe/gossamer
```

## Issues

Fixes #2595

## Primary Reviewer

@timwu20

### CODE REVIEW

**Review by qdm12 — APPROVED** [review]
Awesome 💯 !

File: dot/sync/message.go [hunk 1]
```diff
@@ -338,8 +338,14 @@ func (s *Service) handleChainByHash(ancestor, descendant common.Hash,
...
 	}
 
+	// If the direction is descending, prune from the start.
+	// if the direction is ascending it should prune from the end.
 	if uint(len(subchain)) > max {
-		subchain = subchain[:max]
+		if direction == network.Ascending {
+			subchain = subchain[:max]
+		} else {
+			subchain = subchain[uint(len(subchain))-max:]
```
Comment (EclesioMeloJunior) [inline dot/sync/message.go:347]: nit: `len` will be always greater than or equal 0
```suggestion
			subchain = subchain[len(subchain)-max:]
```

**Review by EclesioMeloJunior — APPROVED** [review]
LGTM! Just a small nit

File: dot/sync/message.go (hunk 1 above)
Comment (qdm12) [reply dot/sync/message.go:347]: It's actually interesting the index can be an `uint`, I thought these would need to be `int`.
