### PR TITLE
cmd,trie,polkadb,p2p,config - Cannot handle home dir #496

### LINKED ISSUE #496: Cannot handle home dir
## Expected Behavior

Should expand `~` to home dir.

## Current Behavior

Creates directory `./~` when starting gossamer

## Steps to Reproduce (for bugs)

1. `./build/bin/gossamer init --genesis genesis.json`
2. `gossamer --config ./config.toml `
3. `ls -la `

config.toml:
```toml
[global]
data-dir = "~/.gossamer"
```

### PR DESCRIPTION
**Pull request by thomasmodeneis**
Fixes #496 

## Changes
- Update cli Actions to support reversed usage
- Update var names to be more legible
- Update from id to ID in multiple places
- Update touched testcases to require funcs
- Add err log on main func
- Update weird discrepancy on log for Close func on database.go and table.go
- Update config.toml to use tilde
- 
- 

## Tests:
```

```

### Issues: #496

### CODE REVIEW

File: cmd/utils/flags.go [hunk 1]
```diff
@@ -123,3 +123,15 @@ var (
 		Usage: "Specify account type as secp256k1",
 	}
 )
+
+// FixFlagsOder allow us to use various flag order formats, eg: (gossamer init --config config.toml and  gossamer --config config.toml init)
+func FixFlagsOder(f func(ctx *cli.Context) error) func(*cli.Context) error {
```
Comment (noot) [inline cmd/utils/flags.go]: should be `FixFlagOrder`?

File: cmd/gossamer/configcmd.go [hunk 2]
```diff
@@ -46,15 +48,17 @@ import (
 
 // makeNode sets up node; opening badgerDB instance and returning the Dot container
 func makeNode(ctx *cli.Context) (*dot.Dot, *cfg.Config, error) {
-	fig, err := getConfig(ctx)
+	defaultConfig, err := getConfig(ctx)
```
Comment (noot) [inline cmd/gossamer/configcmd.go]: is this the defaultConfig? I don't think it's always the default

File: cmd/utils/flags.go (hunk 1 above)
Comment (thomasmodeneis) [reply cmd/utils/flags.go]: Sure, I mean it fixes many flags, so that why the plural there, but can change.

File: cmd/gossamer/configcmd.go (hunk 2 above)
Comment (thomasmodeneis) [reply cmd/gossamer/configcmd.go]: cfg.DefaultConfig is the struct that is used to marshal the config into, so that is why I called it defaultConfig everywhere its used, its already better than fig IMHO.

File: cmd/utils/flags.go [hunk 3]
```diff
@@ -123,3 +123,17 @@ var (
...
+		for _, flagName := range ctx.FlagNames() {
+			if ctx.IsSet(flagName) {
+				if err := ctx.GlobalSet(flagName, ctx.String(flagName)); err != nil {
+					log.Error("Error when fixing flag", "flagName", flagName)
+				}
+			}
+		}
+		return f(ctx)
+	}
+}
```
Comment (ansermino) [inline cmd/utils/flags.go]: This is not how flags should be used. Global flags apply to `gossamer`, local flags should be applied to sub-commands (eg. `accounts`). This seems to be standard for most CLIs

File: cmd/gossamer/configcmd.go (hunk 2 above)
Comment (ansermino) [reply cmd/gossamer/configcmd.go]: `cfg.DefaultConfig()` returns a copy of the config with all defaults applied, we then apply all specified options, so at this point it is not a default config

File: cmd/gossamer/configcmd.go [hunk 4]
```diff
@@ -328,3 +338,24 @@ var tomlSettings = toml.Config{
...
+// home will return the HOME ENV DIR OR the current user dir
+func home() string {
+	if homeDir := os.Getenv("HOME"); homeDir != "" {
+		return homeDir
+	}
+	if usrDir, err := user.Current(); err == nil {
+		return usrDir.HomeDir
+	}
+	return ""
+}
```
Comment (ansermino) [inline cmd/gossamer/configcmd.go]: Same as `cfg.homeDir()`? Maybe it makes sense for this logic to live there, up to you

File: cmd/gossamer/configcmd.go [hunk 5]
```diff
@@ -131,21 +135,26 @@ func loadStateAndRuntime(ss *state.StorageState, ks *keystore.Keystore) (*runtim
...
+	} else {
+		log.Debug("Config File is not set")
 	}
 
 	// Parse CLI flags
-	setGlobalConfig(ctx, &fig.Global)
-	setP2pConfig(ctx, &fig.P2p)
-	setRpcConfig(ctx, &fig.Rpc)
-	return fig, nil
+	log.Debug("Parse CLI flags")
```
Comment (ansermino) [inline cmd/gossamer/configcmd.go]: Doesn't really add any context

File: cmd/gossamer/configcmd.go [hunk 6]
```diff
@@ -328,3 +338,24 @@ var tomlSettings = toml.Config{
 		return fmt.Errorf("field '%s' is not defined in %s%s", field, rt.String(), link)
 	},
 }
+
+// tilde will expand a tilde prefix path to full home path
+func tilde(targetPath string) string {
```
Comment (ansermino) [inline cmd/gossamer/configcmd.go]: I think something like `expandTilde` would be more descriptive

File: cmd/utils/flags.go (hunk 3 above)
Comment (thomasmodeneis) [reply cmd/utils/flags.go]: Well, the issue was reported as `./build/bin/gossamer init --genesis genesis.json` does not work.
Indeed, it does not work because its order is improper. It would work if used like: `./build/bin/gossamer --genesis genesis.json init`
So, the fix is needed to avoid issues like this.

File: cmd/gossamer/configcmd.go (hunk 4 above)
Comment (thomasmodeneis) [reply cmd/gossamer/configcmd.go]: `defaultConfig` maybe not the best name here, but its the name of the struct that is being marshaled into, but `fig` as a var name was also not good either. Do you have a better suggestion ?

File: cmd/gossamer/configcmd.go (hunk 5 above)
Comment (thomasmodeneis) [reply cmd/gossamer/configcmd.go]: what do you mean ? you want to remove it ?

File: cmd/gossamer/configcmd.go (hunk 6 above)
Comment (thomasmodeneis) [reply cmd/gossamer/configcmd.go]: sure

File: cmd/gossamer/configcmd.go (hunk 2 above)
Comment (thomasmodeneis) [reply cmd/gossamer/configcmd.go]: ok, how about calling it currentConfig ?

File: cmd/utils/flags.go (hunk 3 above)
Comment (ansermino) [reply cmd/utils/flags.go]: `--genesis` only applies to the `init` command, `gossamer --genesis genesis.json` shouldn't be allowed as the flag isn't relevant.

File: cmd/gossamer/configcmd.go (hunk 4 above)
Comment (ansermino) [reply cmd/gossamer/configcmd.go]: Is this resolved by the comment above?

File: cmd/gossamer/configcmd.go (hunk 5 above)
Comment (ansermino) [reply cmd/gossamer/configcmd.go]: I don't think this provides any additional information. That is what I'm suggesting

File: cmd/gossamer/configcmd_test.go [hunk 7]
```diff
@@ -197,14 +185,11 @@ func TestGetConfig(t *testing.T) {
...
 		context := cli.NewContext(app, set, nil)
 
-		fig, err := getConfig(context)
-		if err != nil {
-			t.Fatalf("failed to set fig %v", err)
-		}
+		defaultConfig, err := getConfig(context)
+		require.Nil(t, err)
+
+		require.Equal(t, defaultConfig, c.expected)
```
Comment (edwardmack) [inline cmd/gossamer/configcmd_test.go]: shouldn't this be `require.Equal(t, c.expected, defaultConfig)`? I think the parameters for Equal are `t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{}` Minor, but could be confusing reading the Error Trace if this test fails.

File: cmd/gossamer/configcmd_test.go [hunk 8]
```diff
@@ -229,30 +214,24 @@ func TestSetGlobalConfig(t *testing.T) {
...
+			require.Nil(t, err)
 
 			tCfg := &cfg.GlobalConfig{}
 
 			setGlobalConfig(context, tCfg)
 
-			if !reflect.DeepEqual(*tCfg, c.expected) {
-				t.Errorf("\ngot: %+v \nexpected: %+v", tCfg, c.expected)
-			}
+			require.Equal(t, *tCfg, c.expected)
```
Comment (edwardmack) [inline cmd/gossamer/configcmd_test.go]: see above, switch actual/expected

File: cmd/gossamer/configcmd_test.go [hunk 9]
```diff
@@ -310,17 +289,13 @@ func TestSetP2pConfig(t *testing.T) {
...
+			require.Nil(t, err)
 
 			input := cfg.DefaultConfig()
 			// Must call global setup to set data dir
 			setP2pConfig(context, &input.P2p)
 
-			if !reflect.DeepEqual(input.P2p, c.expected) {
-				t.Fatalf("\ngot %+v\nexpected %+v", input.P2p, c.expected)
-			}
+			require.Equal(t, input.P2p, c.expected)
```
Comment (edwardmack) [inline cmd/gossamer/configcmd_test.go]: switch actual/expected

File: cmd/gossamer/configcmd_test.go [hunk 10]
```diff
@@ -368,16 +343,12 @@ func TestSetRpcConfig(t *testing.T) {
...
-			}
+			require.Nil(t, err)
 
 			input := cfg.DefaultConfig()
 			setRpcConfig(context, &input.Rpc)
 
-			if !reflect.DeepEqual(input.Rpc, c.expected) {
-				t.Fatalf("\ngot %+v\nexpected %+v", input.Rpc, c.expected)
-			}
+			require.Equal(t, input.Rpc, c.expected)
```
Comment (edwardmack) [inline cmd/gossamer/configcmd_test.go]: switch actual/expected

File: cmd/gossamer/configcmd_test.go (hunk 7 above)
Comment (thomasmodeneis) [reply cmd/gossamer/configcmd_test.go]: Oh, good one!

File: cmd/utils/flags.go (hunk 3 above)
Comment (thomasmodeneis) [reply cmd/utils/flags.go]: Well, the issue is like I said: 
`gossamer init --genesis genesis.json` does not parse the flags correctly, and values are nil.
When I run `gossamer --genesis genesis.json init` all works well and flags are processed.

File: cmd/gossamer/configcmd_test.go (hunk 10 above)
Comment (thomasmodeneis) [reply cmd/gossamer/configcmd_test.go]: thanks.

File: cmd/gossamer/configcmd_test.go (hunk 9 above)
Comment (thomasmodeneis) [reply cmd/gossamer/configcmd_test.go]: thanks.

File: cmd/gossamer/configcmd_test.go (hunk 8 above)
Comment (thomasmodeneis) [reply cmd/gossamer/configcmd_test.go]: thanks.

File: cmd/gossamer/configcmd.go (hunk 5 above)
Comment (ryanchristo) [reply cmd/gossamer/configcmd.go]: I agree. If everything is working as expected and there is no new information, the debug is probably not necessary.

File: cmd/gossamer/configcmd.go (hunk 4 above)
Comment (ryanchristo) [reply cmd/gossamer/configcmd.go]: I agree, and keeping this consistent with the name used in `configcmd.go` make sense

File: cmd/gossamer/configcmd.go (hunk 2 above)
Comment (ryanchristo) [reply cmd/gossamer/configcmd.go]: I agree, `currentConfig` would be probably be better or keeping it as it was.

File: cmd/utils/flags.go (hunk 3 above)
Comment (ansermino) [reply cmd/utils/flags.go]: I believe this issue lies in the usage of `context.GlobalBool` and `context.Bool`. Afaik, the first will only return flags on the main command (`gossamer`) and the other on the subcommand (`init`)

Comment (ansermino) [reply cmd/utils/flags.go]: (bool is just an example, applies for all flag types)

**Comment by thomasmodeneis** [comment]
> Looks good, minor comments mentioned in code.
> Regarding #496, when I do steps to reproduce I still have an issue. After running steps, a dir `~/.gossamer` is created in dir I'm running from. So, I now have:
> 
> * `~/.gossamer` that is `/home/emack/.gossamer` which was created from init
> * `/home/emack/projects/chainsafe/gossamer/~/.gossamer` from which `~/.gossamer` was created after running `gossamer --config ./config.toml`

I found that the culprit was `setGlobalConfig` messing up things silently, please check it again, thanks!

File: cmd/utils/flags.go (hunk 3 above)
Comment (thomasmodeneis) [reply cmd/utils/flags.go]: Right, IMHO having the method FixFlagOrder executed on all cmds reduces the complexity and avoid us having to fight with how the flags all the time. AFAIK It does not add any collateral effects as well.

File: cmd/gossamer/configcmd_test.go [hunk 11]
```diff
@@ -229,30 +213,24 @@ func TestSetGlobalConfig(t *testing.T) {
...
-			}
+			require.Equal(t, c.expected, *tCfg)
 		})
 	}
 }
 
 func TestCreateP2PService(t *testing.T) {
 	gendata := &genesis.GenesisData{
-		ProtocolId: "gossamer",
+		ProtocolID: "gossamer",
```
Comment (ryanchristo) [inline cmd/gossamer/configcmd_test.go]: Can we please change this to `/gossamer/test` to match the protocol id in other tests?

File: cmd/gossamer/genesis.go [hunk 12]
```diff
@@ -15,25 +15,25 @@ import (
...
+	log.Debug("Loading genesis", "genesisPath", genesisPath, "dataDir", dataDir)
 
-	gen, err := genesis.LoadGenesisData(fp)
+	gen, err := genesis.LoadGenesisData(genesisPath)
 	if err != nil {
 		return err
 	}
 
-	log.Info("🕸\t Initializing node", "name", gen.Name, "id", gen.Id, "protocolID", gen.ProtocolId, "bootnodes", common.BytesToStringArray(gen.Bootnodes))
+	log.Info("🕸\t Initializing node", "Name", gen.Name, "ID", gen.ID, "protocolID", gen.ProtocolID, "Bootnodes", common.BytesToStringArray(gen.Bootnodes))
```
Comment (ryanchristo) [inline cmd/gossamer/genesis.go]: I am not opposed to capitalizing values but this is inconsistent with all other logs and `protocolID` is the only one not capitalized. Maybe keep the key values lowercase for now and we can look at log formatting in an issue on its own to make sure we are looking at how we are logging as a whole.

File: cmd/gossamer/configcmd_test.go [hunk 13]
```diff
@@ -383,16 +357,12 @@ func TestSetRpcConfig(t *testing.T) {
...
-			}
+			require.Nil(t, err)
 
 			input := cfg.DefaultConfig()
 			setRpcConfig(context, &input.Rpc)
 
-			if !reflect.DeepEqual(input.Rpc, c.expected) {
-				t.Fatalf("\ngot %+v\nexpected %+v", input.Rpc, c.expected)
-			}
+			require.Equal(t, c.expected, input.Rpc)
```
Comment (ryanchristo) [inline cmd/gossamer/configcmd_test.go]: This is nice. Does it accomplish the same level of depth as `reflect.DeepEqual`?

File: cmd/gossamer/configcmd.go [hunk 14]
```diff
@@ -45,15 +46,18 @@ import (
...
-	fig, err := getConfig(ctx)
+	currentConfig, err := getConfig(ctx)
 	if err != nil {
 		return nil, nil, err
 	}
 
 	var srvcs []services.Service
 
+	dataDir := currentConfig.Global.DataDir
+	log.Debug("Will create service, initialize stateDB and blockDB", "dataDir", dataDir, "currentConfig.Global.DataDir", currentConfig.Global.DataDir)
```
Comment (noot) [inline cmd/gossamer/configcmd.go]: don't think this log is necessary

File: cmd/gossamer/configcmd.go [hunk 15]
```diff
@@ -132,21 +136,30 @@ func loadStateAndRuntime(ss *state.StorageState, ks *keystore.Keystore) (*runtim
 
 // getConfig checks for config.toml if --config flag is specified and sets CLI flags
 func getConfig(ctx *cli.Context) (*cfg.Config, error) {
-	fig := cfg.DefaultConfig()
+	currentConfig := cfg.DefaultConfig()
 	// Load config file.
 	if file := ctx.GlobalString(utils.ConfigFileFlag.Name); file != "" {
-		err := loadConfig(file, fig)
+		configFile := ctx.GlobalString(utils.ConfigFileFlag.Name)
+		log.Debug("Loading config file", "configFile", configFile)
```
Comment (noot) [inline cmd/gossamer/configcmd.go]: same with this

File: cmd/gossamer/configcmd.go [hunk 16]
```diff
@@ -132,21 +136,30 @@ func loadStateAndRuntime(ss *state.StorageState, ks *keystore.Keystore) (*runtim
...
+	//expand tilde or dot
+	newDataDir := expandTildeOrDot(currentConfig.Global.DataDir)
+	currentConfig.Global.DataDir = newDataDir
+
 	// Parse CLI flags
-	setGlobalConfig(ctx, &fig.Global)
-	setP2pConfig(ctx, &fig.P2p)
-	setRpcConfig(ctx, &fig.Rpc)
-	return fig, nil
+	log.Debug("Going set CLI flags (will override config file if set) ", "currentConfig", currentConfig)
```
Comment (noot) [inline cmd/gossamer/configcmd.go]: same with this

File: cmd/gossamer/configcmd.go [hunk 17]
```diff
@@ -163,14 +176,16 @@ func loadConfig(file string, config *cfg.Config) error {
 	if err = tomlSettings.NewDecoder(f).Decode(&config); err != nil {
 		return err
 	}
+	log.Debug("Loaded configuration", "config", config)
```
Comment (noot) [inline cmd/gossamer/configcmd.go]: same with this

File: cmd/gossamer/configcmd_test.go (hunk 13 above)
Comment (thomasmodeneis) [reply cmd/gossamer/configcmd_test.go]: yep

File: cmd/gossamer/genesis.go (hunk 12 above)
Comment (thomasmodeneis) [reply cmd/gossamer/genesis.go]: Well the basic rule is you log the field name with the exact same name as the variable. protocolID is not missing, I am not sure what you mean.

File: cmd/gossamer/configcmd.go (hunk 14 above)
Comment (thomasmodeneis) [reply cmd/gossamer/configcmd.go]: sure

File: cmd/gossamer/configcmd.go (hunk 15 above)
Comment (thomasmodeneis) [reply cmd/gossamer/configcmd.go]: ok

File: cmd/gossamer/configcmd.go (hunk 16 above)
Comment (thomasmodeneis) [reply cmd/gossamer/configcmd.go]: ok

File: cmd/gossamer/configcmd.go (hunk 17 above)
Comment (thomasmodeneis) [reply cmd/gossamer/configcmd.go]: ok

File: cmd/gossamer/configcmd_test.go (hunk 11 above)
Comment (thomasmodeneis) [reply cmd/gossamer/configcmd_test.go]: I dont understand your request

Comment (ryanchristo) [reply cmd/gossamer/configcmd_test.go]:
```
ProtocolID: "/gossamer/test"
```

File: cmd/gossamer/genesis.go (hunk 12 above)
Comment (ryanchristo) [reply cmd/gossamer/genesis.go]: `"protocolID"` should be `"ProtocolID"` if you are following that rule

**Comment by ryanchristo** [comment]
cc @thomasmodeneis can you please re-review when you get a chance?

If I change `Id` and `ProtocolId` where suggested, I would be required to change it everywhere, which is already addressed in #555 and therefore will be addressed here if #555 is merged first

File: cmd/gossamer/genesis.go (hunk 12 above)
Comment (thomasmodeneis) [reply cmd/gossamer/genesis.go]: oh you mean the log string, sure, good point :)

File: cmd/gossamer/configcmd_test.go (hunk 11 above)
Comment (thomasmodeneis) [reply cmd/gossamer/configcmd_test.go]: sure

File: Makefile [hunk 18]
```diff
@@ -45,6 +45,10 @@ build:
 	@echo "  >  \033[32mBuilding binary...\033[0m "
 	GOBIN=$(PWD)/build/bin go run scripts/ci.go install
 
+# init: Init the gossamer folder using  gssmr0.json genesis file and default config file
+init:
+	./build/bin/gossamer init --genesis config/gssmr0.json --verbosity debug --config ./config.toml
+
```
Comment (ryanchristo) [inline Makefile]: `--genesis config/gssmr0.json` is the default, is it needed here?

Comment (thomasmodeneis) [reply Makefile]: yes, the obvious should be mentioned to allow for change in case you want to do it differently. That is the whole point of adding the task to the Makefile.
