### PR TITLE
fix(dot/network): update BlockRequestMessage number to be of type uint32

### LINKED ISSUE #1854: dot/network: update `BlockRequestMessage.FromBlock(Number)` to be of type uint32
## Task summary

- the `BlockRequestMessage.FromBlock/StartingBlock` field is a variadic type, either a uint representing a block number or a hash representing a block hash
- the uint is currently uint64, but should be updated to uint32, as this is the type used to represent block numbers in substrate

### LINKED ISSUE #2252: cross-client devnet: substrate shouldn't drop us as a peer
## Task summary

- on the cross-client devnet, occassionally the substrate node will show 0 peers, but gossamer shows 1 peer still. this is concerning because it seems substrate dropped us, but gossamer thinks it's still connected
- firstly we shouldn't be getting dropped, secondly gossamer should correctly determine if it's been dropped.

### PR DESCRIPTION
**Pull request by noot**
## Changes

- update number within variadic type used for block requests to be uint32, as this is what polkadot uses

## Tests

```
go test ./dot/sync
go test ./lib/common/variadic
go test ./dot/network
```

## Issues

- closes #1854
- probably closes #2252 (will test it more)

## Primary Reviewer

- @EclesioMeloJunior

### CODE REVIEW

File: dot/network/message.go [hunk 1]
```diff
@@ -155,21 +155,19 @@ func (bm *BlockRequestMessage) Decode(in []byte) error {
...
 	case *pb.BlockRequest_Number:
-		// TODO: we are receiving block requests w/ 4-byte From field; this should probably be
-		// 4-bytes as it represents a block number which is uint32 (#1854)
-		if len(from.Number) != 8 {
-			return errors.New("invalid BlockResponseMessage.From; uint64 is not 8 bytes")
+		if len(from.Number) != 4 {
+			return errors.New("invalid BlockRequestMessage.From; number is not 4 bytes")
 		}
-		startingBlock, err = variadic.NewUint64OrHash(binary.LittleEndian.Uint64(from.Number))
+		startingBlock, err = variadic.NewUint32OrHash(binary.LittleEndian.Uint32(from.Number))
```
Comment (EclesioMeloJunior) [inline dot/network/message.go:170]:
```suggestion
                number := binary.LittleEndian.Uint32(from.Number)
		startingBlock, err = variadic.NewUint32OrHash(number)
```

File: dot/network/message.go [hunk 2]
```diff
@@ -155,21 +155,19 @@ func (bm *BlockRequestMessage) Decode(in []byte) error {
...
 	case *pb.BlockRequest_Hash:
-		startingBlock, err = variadic.NewUint64OrHash(common.BytesToHash(from.Hash))
+		startingBlock, err = variadic.NewUint32OrHash(common.BytesToHash(from.Hash))
 	case *pb.BlockRequest_Number:
-		// TODO: we are receiving block requests w/ 4-byte From field; this should probably be
-		// 4-bytes as it represents a block number which is uint32 (#1854)
-		if len(from.Number) != 8 {
-			return errors.New("invalid BlockResponseMessage.From; uint64 is not 8 bytes")
+		if len(from.Number) != 4 {
+			return errors.New("invalid BlockRequestMessage.From; number is not 4 bytes")
```
Comment (EclesioMeloJunior) [inline dot/network/message.go:168]:
```suggestion
			return fmt.Errorf("invalid BlockRequestMessage.From; expected 4 bytes long. got %d bytes long", len(from.Number))
```

**Review by EclesioMeloJunior — CHANGES_REQUESTED** [review]

File: dot/network/message.go (hunk 1 above)
Comment (noot) [reply dot/network/message.go]: done

**Review by EclesioMeloJunior — APPROVED** [review]
LGTM

File: dot/network/message.go [hunk 3]
```diff
@@ -76,7 +76,7 @@ func (sd SyncDirection) String() string {
 // BlockRequestMessage is sent to request some blocks from a peer
 type BlockRequestMessage struct {
 	RequestedData byte
-	StartingBlock variadic.Uint64OrHash // first byte 0 = block hash (32 byte), first byte 1 = block number (int64)
+	StartingBlock variadic.Uint32OrHash // first byte 0 = block hash (32 byte), first byte 1 = block number (int64)
```
Comment (qdm12) [inline dot/network/message.go:79]: I think comment needs to be updated? :thinking: 

```suggestion
	StartingBlock variadic.Uint32OrHash // first byte 0 = block hash (32 byte), first byte 1 = block number (uint32)
```

File: dot/network/message.go [hunk 4]
```diff
@@ -155,21 +155,21 @@ func (bm *BlockRequestMessage) Decode(in []byte) error {
...
 	case *pb.BlockRequest_Hash:
-		startingBlock, err = variadic.NewUint64OrHash(common.BytesToHash(from.Hash))
+		startingBlock, err = variadic.NewUint32OrHash(common.BytesToHash(from.Hash))
 	case *pb.BlockRequest_Number:
-		// TODO: we are receiving block requests w/ 4-byte From field; this should probably be
-		// 4-bytes as it represents a block number which is uint32 (#1854)
-		if len(from.Number) != 8 {
-			return errors.New("invalid BlockResponseMessage.From; uint64 is not 8 bytes")
+		if len(from.Number) != 4 {
+			return fmt.Errorf("invalid BlockRequestMessage.From; expected 4 bytes, got %d bytes", len(from.Number))
```
Comment (qdm12) [inline dot/network/message.go:168]: nit - a bit out of scope, but since we are modifying here, can you add a sentinel error for this?

```go
var ErrBlockRequestFromNumberNotValid = errors.New("block request message from number is not valid")
```

and

```suggestion
			return fmt.Errorf("%w: expected 4 bytes, got %d bytes",ErrBlockRequestFromNumberNotValid, len(from.Number))
```

File: dot/sync/message_test.go [hunk 5]
```diff
@@ -49,7 +49,7 @@ func TestService_CreateBlockResponse_MaxSize(t *testing.T) {
 	addTestBlocksToState(t, maxResponseSize*2, s.blockState)
 
 	// test ascending
-	start, err := variadic.NewUint64OrHash(uint64(1))
+	start, err := variadic.NewUint32OrHash(uint32(1))
```
Comment (qdm12) [inline dot/sync/message_test.go:52]: supernit I think having just `1` instead of `uint32(1)` works. No need to change though.

File: lib/common/variadic/uint64OrHash.go [hunk 6]
```diff
@@ -11,72 +11,72 @@ import (
 	"github.com/ChainSafe/gossamer/lib/common"
 )
 
-// Uint64OrHash represents an optional interface type (int,hash).
-type Uint64OrHash struct {
+// Uint32OrHash represents an optional interface type (int,hash).
```
Comment (qdm12) [inline lib/common/variadic/uint64OrHash.go:14]:
```suggestion
// Uint32OrHash represents an optional interface type (int,uint32,hash).
```

File: lib/common/variadic/uint64OrHash.go [hunk 7]
```diff
@@ -11,72 +11,72 @@ import (
...
+type Uint32OrHash struct {
 	value interface{}
 }
 
-// NewUint64OrHash returns a new variadic.Uint64OrHash given an int, uint64, or Hash
-func NewUint64OrHash(value interface{}) (*Uint64OrHash, error) {
+// NewUint32OrHash returns a new variadic.Uint32OrHash given an int, uint32, or Hash
```
Comment (qdm12) [inline lib/common/variadic/uint64OrHash.go:19]: Should we rename this to `NewIntUint32Hash`? Sounds strange not to include `int` in its name :thinking:

File: lib/common/variadic/uint64OrHash.go [hunk 8]
```diff
@@ -85,49 +85,48 @@ func (x *Uint64OrHash) IsHash() bool {
...
-	_, is := x.value.(uint64)
+	_, is := x.value.(uint32)
 	return is
 }
 
-// Uint64 returns the value as a uint64. it panics if the value is not a hash.
-func (x *Uint64OrHash) Uint64() uint64 {
-	if !x.IsUint64() {
-		panic("value is not uint64")
+// Uint32 returns the value as a uint32. it panics if the value is not a uint32.
```
Comment (qdm12) [inline lib/common/variadic/uint64OrHash.go:105]: meganit

```suggestion
// Uint32 returns the value as a uint32. It panics if the value is not a uint32.
```

File: lib/common/variadic/uint64OrHash_test.go [hunk 9]
```diff
@@ -72,22 +53,22 @@ func TestNewUint64OrHashFromBytes(t *testing.T) {
...
+			val := NewUint32OrHashFromBytes(data)
 			require.NoError(t, err)
-			require.NotNil(t, uint64OrHash)
-			require.IsType(t, x.expectedType, uint64OrHash.Value())
-			if x.expectedType == (uint64)(0) {
-				startingBlockByteArray := make([]byte, 8)
-				binary.LittleEndian.PutUint64(startingBlockByteArray, uint64OrHash.Value().(uint64))
+			require.IsType(t, x.expectedType, val.Value())
+
+			if x.expectedType == (uint32)(0) {
```
Comment (qdm12) [inline lib/common/variadic/uint64OrHash_test.go:66]: nit that should work fine

```suggestion
			if x.expectedType == 0 {
```

File: lib/common/variadic/uint64OrHash.go (hunk 7 above)
Comment (noot) [reply lib/common/variadic/uint64OrHash.go:19]: it's supposed to only be uint32 or hash, not int :p so I think it's fine to leave

File: lib/common/variadic/uint64OrHash_test.go (hunk 9 above)
Comment (noot) [reply lib/common/variadic/uint64OrHash_test.go]: sadly doesn't work :( it think it's not equal

File: lib/common/variadic/uint64OrHash.go (hunk 8 above)
Comment (noot) [reply lib/common/variadic/uint64OrHash.go]: done

File: lib/common/variadic/uint64OrHash.go (hunk 6 above)
Comment (noot) [reply lib/common/variadic/uint64OrHash.go]: updated

File: dot/sync/message_test.go (hunk 5 above)
Comment (noot) [reply dot/sync/message_test.go]: updated

File: dot/network/message.go (hunk 4 above)
Comment (noot) [reply dot/network/message.go]: updated

File: dot/network/message.go (hunk 3 above)
Comment (noot) [reply dot/network/message.go]: updated

File: lib/common/variadic/uint64OrHash.go (hunk 7 above)
Comment (qdm12) [reply lib/common/variadic/uint64OrHash.go]: Should we remove the int type check in there then?

File: lib/common/variadic/uint64OrHash_test.go (hunk 9 above)
Comment (qdm12) [reply lib/common/variadic/uint64OrHash_test.go]: Ah my bad, I didn't notice `x.expectedType` was an `interface{}`, sorry about that.

File: lib/common/variadic/uint32OrHash.go [hunk 10]
```diff
@@ -0,0 +1,150 @@
+// Copyright 2021 ChainSafe Systems (ON)
```
Comment (qdm12) [inline lib/common/variadic/uint32OrHash.go:1]: Git maniac, forgive me: can you rebase interactively your branch and have 1 commit to move the files uint64OrHash -> uint32OrHash, and then 1 commit with the rest of your changes? That way we can rebase and merge the PR (not squash and merge) so file movements are tracked and they'll be less deltas/better blame/better rebasing.

Let me know I can do it on your branch if you want.

File: lib/common/variadic/uint32OrHash.go [hunk 11]
```diff
@@ -0,0 +1,150 @@
...
+	value interface{}
+}
+
+// NewUint32OrHash returns a new variadic.Uint32OrHash given an int, uint32, or Hash
+func NewUint32OrHash(value interface{}) (*Uint32OrHash, error) {
+	switch v := value.(type) {
+	case int:
+		return &Uint32OrHash{
+			value: uint32(v),
+		}, nil
```
Comment (qdm12) [inline lib/common/variadic/uint32OrHash.go:25]: remove?

```suggestion
```

Comment (noot) [reply lib/common/variadic/uint32OrHash.go:25]: I think it's kinda nice to have this to we can just call `NewUint32OrHash(1)` instead of `NewUint32OrHash(uint32(1))`, what do you think?

File: lib/common/variadic/uint32OrHash.go (hunk 10 above)
Comment (noot) [reply lib/common/variadic/uint32OrHash.go:1]: honestly I don't usually rebase... feel free to do it for me haha, thank you!

File: lib/common/variadic/uint32OrHash.go [hunk 12]
```diff
@@ -0,0 +1,150 @@
...
+// Uint32 returns the value as a uint32. It panics if the value is not a uint32.
+func (x *Uint32OrHash) Uint32() uint32 {
+	if !x.IsUint32() {
+		panic("value is not uint32")
+	}
+
+	return x.value.(uint32)
+}
+
+// Encode will encode a Uint32OrHash using SCALE
```
Comment (kishansagathiya) [inline lib/common/variadic/uint32OrHash.go:114]: Is this comment still relevant? Or am i just unable to find where scale encoding happening here!

**Review by kishansagathiya — APPROVED** [review]
:tada:  Just a minor comment

File: lib/common/variadic/uint32OrHash.go (hunk 12 above)
Comment (noot) [reply lib/common/variadic/uint32OrHash.go:114]: it's encoding it using the SCALE spec, but not using the library!

File: lib/common/variadic/uint32OrHash.go (hunk 11 above)
Comment (qdm12) [reply lib/common/variadic/uint32OrHash.go:25]: Ah that's true, can you add a comment about it then? It confused me initially :smile:

File: lib/common/variadic/uint32OrHash.go (hunk 10 above)
Comment (qdm12) [reply lib/common/variadic/uint32OrHash.go:1]: Done, you should run `git checkout noot/fix-block-request && git reset --hard origin/noot/fix-block-request` to get the rewritten history.

For future changes, just stage your changes and run `git commit --amend --no-edit` to bundle it in the second commit, and force push to override the 2nd commit.

File: lib/common/variadic/uint32OrHash.go (hunk 11 above)
Comment (qdm12) [reply lib/common/variadic/uint32OrHash.go]: Comment added whilst I was rebasing it.

File: lib/common/variadic/uint32OrHash.go (hunk 10 above)
Comment (noot) [reply lib/common/variadic/uint32OrHash.go:1]: awesome thank you!!!
