### PR TITLE
Elizabeth/trie encoding

### LINKED ISSUE #94: Failing Put/Get Tests
## Expected Behavior

Tests should always pass.

## Current Behavior

Some CI builds have failed tests:
```
--- FAIL: TestPutAndGet (0.00s)
    trie_test.go:85: Fail to put with key 46229fdaa7902e2d2a3a4ae9401249 and value bd8e175239f6ef8f9f6ac0090a607936c5: cannot put: invalid parent node
    trie_test.go:92: Fail to get key 46229fdaa7902e2d2a3a4ae9401249 with value bd8e175239f6ef8f9f6ac0090a607936c5: got dfa8110d8ad3cf0928d33d90
    trie_test.go:85: Fail to put with key 4f69b36106b353ac522509f729b3f394e20831864f and value 237d30bcff75ef0ac118e904f124d1393a5db0f86f08fbd7ec293b32eb: cannot put: invalid parent node
    trie_test.go:92: Fail to get key 4f69b36106b353ac522509f729b3f394e20831864f with value 237d30bcff75ef0ac118e904f124d1393a5db0f86f08fbd7ec293b32eb: got dfa8110d8ad3cf0928d33d90
    trie_test.go:85: Fail to put with key 448892bc1450c8c54d8c1b2f1d94f8b43d7656206e91eb2db66c68d0260dc7 and value 625152de5c5e398f2e96ec9ec0d686c1671937d768006e80: cannot put: invalid parent node
    trie_test.go:92: Fail to get key 448892bc1450c8c54d8c1b2f1d94f8b43d7656206e91eb2db66c68d0260dc7 with value 625152de5c5e398f2e96ec9ec0d686c1671937d768006e80: got dfa8110d8ad3cf0928d33d90
    trie_test.go:85: Fail to put with key 4585151c77be0b7dce64addd65bd0a2300b6d1f36d3dc6d02c50c71981ef and value 7863dfb2d9d52b455cfdda4211e94dc346fcb7c744ce486f4067a9df8c6f: cannot put: invalid parent node
    trie_test.go:92: Fail to get key 4585151c77be0b7dce64addd65bd0a2300b6d1f36d3dc6d02c50c71981ef with value 7863dfb2d9d52b455cfdda4211e94dc346fcb7c744ce486f4067a9df8c6f: got dfa8110d8ad3cf0928d33d90
    trie_test.go:85: Fail to put with key 42b2a981e09569edab44c7b78f46adae0f9cdf261a250f199d and value 8d2de5386221e9: cannot put: invalid parent node
    trie_test.go:92: Fail to get key 42b2a981e09569edab44c7b78f46adae0f9cdf261a250f199d with value 8d2de5386221e9: got dfa8110d8ad3cf0928d33d90
    trie_test.go:85: Fail to put with key 44e338f234f6cf06a647c9b9abcb2ef493aee5d7bc7b and value 5df0f71681939c: cannot put: invalid parent node
    trie_test.go:92: Fail to get key 44e338f234f6cf06a647c9b9abcb2ef493aee5d7bc7b with value 5df0f71681939c: got dfa8110d8ad3cf0928d33d90
    trie_test.go:85: Fail to put with key 4e283c12a47a980d5088 and value 5f8cdf2673eb1e780d266dd6c0: cannot put: invalid parent node
    trie_test.go:92: Fail to get key 4e283c12a47a980d5088 with value 5f8cdf2673eb1e780d266dd6c0: got dfa8110d8ad3cf0928d33d90
FAIL
coverage: 92.6% of statements
FAIL	github.com/ChainSafe/gossamer/trie	0.006s
```
https://travis-ci.com/ChainSafe/gossamer/builds/107494082

## Possible Solution

This may be a bug in the tester (randomly generated test cases), although it is also possible the issue lies in the implementation. Would recommend attempting to run locally with a much larger number of  generated test cases.

## Steps to Reproduce (for bugs)

eg. https://travis-ci.com/ChainSafe/gossamer/builds/107494082

## Context
N/A

## Your Environment
* Version used:
* Commit hash: multiple
* Go Version: 1.12
* Operating System and version (include distro if Linux): Linux (travis default)
* Link to your project or reproducible gist: https://travis-ci.com/ChainSafe/gossamer/builds/107494082
* I intend to submit a pull request to fix this issue: [ ]

### PR DESCRIPTION
**Pull request by noot**
## Changes
- implemented encoding and hashing of nodes as per https://github.com/w3f/polkadot-re-spec/issues/8
- fixed a few bugs I found in trie `Put` and `Get`

## Tests:
```
go test ./trie/...
```

### Fixes:
Closes #94

### CODE REVIEW

File: trie/node_test.go [hunk 1]
```diff
@@ -1,9 +1,22 @@
...
 
 import (
+	"bytes"
 	"testing"
+
+	scale "github.com/ChainSafe/gossamer/codec"
+	"github.com/ChainSafe/gossamer/common"
 )
 
+// make byte array with length specified; used to test byte array encoding
```
Comment (ansermino) [inline trie/node_test.go]: `// byteArrray makes a byte array...`

File: trie/hash.go [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+		return nil, err
+	}
+
+	return &hasher{
+		hash: h,
+	}, nil
+}
+
+// Hash encodes the node and then hashes it if its encoded length is > 32 bytes
+func Hash(n node) (h []byte, err error) {
```
Comment (ansermino) [inline trie/hash.go]: Consider making this a receiver function, would allow optimizations further down the road

File: trie/node_test.go (hunk 1 above)
Comment (noot) [reply trie/node_test.go]: done

File: trie/trie.go [hunk 3]
```diff
@@ -78,6 +78,14 @@ func (t *Trie) insert(parent node, key []byte, value node) (ok bool, n node, err
 		length := lenCommonPrefix(key, p.key)
 		br.key = key[:length]
 
+		if len(key) < length {
+			br := new(branch)
```
Comment (golangcibot) [inline trie/trie.go]: shadow: declaration of "br" shadows declaration at line 77 (from `govet`)

File: trie/hash.go (hunk 2 above)
Comment (noot) [reply trie/hash.go]: done
