### PR TITLE
p2p: add foundation for status message exchange

### LINKED ISSUE #325: Send Status Message on Connection to Peer
When we connect to a new peer we need to exchange status messages. If this fails we should drop the peer.

See spec 4.4.2 (and network messages section).

### PR DESCRIPTION
**Pull request by ryanchristo**
## Changes

This pull request adds the foundation for the status message exchange between host and connected peer that will determine if the two nodes are compatible or if the peer should be dropped.

This pull request also includes some formatting, updated comments, and some added logging.

## Tests
```
go test ./p2p -v
```

## Issues

closes #325

### CODE REVIEW

File: p2p/host.go [hunk 1]
```diff
@@ -82,112 +113,172 @@ func newHost(ctx context.Context, cfg *Config) (*host, error) {
...
-		}
-	}
+// `getStream` attempts to get an existing stream (using `getExistingStream`)
+// and opens a new stream if an existing stream does not exist.
+func (h *host) getStream(p peer.ID) (stream net.Stream, err error) {
+	// stream = h.getExistingStream(p)
 
-	return nil
+	// if stream == nil {
+	stream, err = h.h.NewStream(h.ctx, p, h.protocolId)
```
Comment (noot) [inline p2p/host.go]: this no longer returns an existing stream

Comment (ryanchristo) [reply p2p/host.go]: That is true. Using an existing stream was preventing both nodes from receiving the status message (both would write to the stream but only one would receive the status message).

I commented this out rather than deleting it because I think we would want to use an existing stream if available but we might need a condition to determine when. I will take another look and either figure out what condition we need or open an issue and update the comment.

File: p2p/p2p.go [hunk 2]
```diff
@@ -19,77 +19,96 @@ package p2p
...
+	"github.com/ChainSafe/gossamer/common"
 	log "github.com/ChainSafe/log15"
 
+	"github.com/libp2p/go-libp2p-core/network"
 	net "github.com/libp2p/go-libp2p-core/network"
 )
 
-var _ services.Service = &Service{}
+// var _ module.P2pApi = &Service{}
+// var _ services.Service = &Service{}
```
Comment (ansermino) [inline p2p/p2p.go]: You can remove the first. The second is optional but should probably stay to ensure we don't change the service's compatibility with the interface.

If you're not familiar with these: they just assert that you can create an instance of `Service` and store it as a `services.Service` (ie. it adheres to the interface). It never actually gets saved due to the `_`, but the compiler will complain if its not possible.

File: p2p/p2p_test.go [hunk 3]
```diff
@@ -181,26 +196,76 @@ func TestSendRequest(t *testing.T) {
...
 	}
 
-	err = nodeB.host.connect(*addrInfoA)
+	err = nodeA.host.connect(*addrInfoB)
 	if err != nil {
 		t.Fatal(err)
 	}
 
+	// Wait for status exchange
+	time.Sleep(5 * time.Second)
```
Comment (ansermino) [inline p2p/p2p_test.go]: Lets chat some more about how to remove this

File: p2p/host.go (hunk 1 above)
Comment (ryanchristo) [reply p2p/host.go]: Ok, updated implementation in `send` method and opened #437

File: p2p/host.go [hunk 4]
```diff
@@ -6,28 +22,29 @@ import (
...
 	ma "github.com/multiformats/go-multiaddr"
-
-	"github.com/libp2p/go-libp2p/p2p/discovery"
 )
 
 const DefaultProtocolId = protocol.ID("/gossamer/dot/0")
 const mdnsPeriod = time.Minute
 
-// host is a wrapper around libp2p's host.host
+// `host` describes a wrapper for the libp2p host, dht, and mdns services
```
[the remark this answers is not in the document]
Comment (ryanchristo) [reply p2p/host.go]: Fixed. Old habit from the land of generated javascript documentation.

File: p2p/p2p.go [hunk 5]
```diff
@@ -99,25 +118,67 @@ func (s *Service) Stop() error {
...
 
-// MsgRecPoll starts polling the msgRec channel for any blocks
-func (s *Service) MsgRecPoll(e chan error) {
+// `sendStatusMessages` starts a loop that sends the current network state as
+// a status message to each connected peer every 5 seconds.
+func (s *Service) sendStatusMessages() {
 	for {
+
+		// Send status messages every 5 seconds
+		time.Sleep(5 * time.Second)
```
[the remark this answers is not in the document]
Comment (ryanchristo) [reply p2p/p2p.go]: Done. Set to 5 minutes as `StatusMessageInterval` constant.

File: p2p/p2p.go (hunk 2 above)
Comment (ryanchristo) [reply p2p/p2p.go]: Thanks for the explanation! Deleted first and uncommented second.

File: p2p/p2p_test.go (hunk 3 above)
Comment (ryanchristo) [reply p2p/p2p_test.go]: Yes, please. Definitely not ideal for CI testing.

File: p2p/host.go [hunk 6]
```diff
@@ -82,123 +112,177 @@ func newHost(ctx context.Context, cfg *Config) (*host, error) {
...
-		stream, err = h.h.NewStream(h.ctx, peer.ID, h.protocolId)
-		log.Debug("opening new stream ", "to", peer.ID)
-		if err != nil {
-			log.Error("failed to open stream", "error", err)
-			return err
-		}
-	} else {
-		log.Debug("using existing stream", "to", peer.ID)
-	}
+	// TODO: investigate existing stream breaking status exchange
```
Comment (ryanchristo) [inline p2p/host.go]: opened #437 to address this

File: p2p/p2p.go [hunk 7]
```diff
@@ -19,77 +19,92 @@ package p2p
...
+// Start starts the service
 func (s *Service) Start() error {
 	s.host.startMdns()
 	s.host.bootstrap()
-	s.host.logAddrs()
+	s.host.printHostAddresses()
 
-	log.Info("Listening for connections...")
+	// TODO: decide whether we need errors to surface here
+	// e := make(chan error)
```
Comment (ryanchristo) [inline p2p/p2p.go]: Worth pointing out. David mentioned the error channel might not be necessary here.

File: p2p/p2p.go [hunk 8]
```diff
@@ -99,86 +114,193 @@ func (s *Service) Stop() error {
...
+func (s *Service) broadcastStatusMessages() {
+
+	// Wait for node to finish starting
+	time.Sleep(time.Second)
+
+	// TODO: use generated message
+	msg := statusMessage
+
+	// send message to each connected peer
+	s.host.broadcast(msg)
```
Comment (noot) [inline p2p/p2p.go]: we don't broadcast status messages, we send point-to-point them upon connection to a peer

Comment (noot) [reply p2p/p2p.go]: i think doing it like this may cause us not to be able to connect to peers. since it's 5 mins between status message sends, the peers will definitely disconnect from us, since they are expecting it within a smaller time period (<1 min most likely, will need to confirm)

File: p2p/p2p.go [hunk 9]
```diff
@@ -99,86 +114,193 @@ func (s *Service) Stop() error {
...
+			"peer", stream.Conn().RemotePeer(),
+			"protocol", stream.Protocol(),
+			"message", msg,
+		)
+		return
+	}
 
-// ID returns the host's ID
+	// check and store message, returns true if valid new message
+	if !s.verifyNewMessage(msg) {
```
Comment (noot) [inline p2p/p2p.go]: naming may be a bit confusing, the message could still be valid but seen already. maybe change to `shouldBroadcast` or something?

File: p2p/p2p.go (hunk 8 above)
Comment (ryanchristo) [reply p2p/p2p.go]: Correct, status messages need be sent whenever a peer is connected. This only send status messages to connected peers when a new service is started and then every 5 minutes thereafter.

File: p2p/p2p.go (hunk 9 above)
Comment (ryanchristo) [reply p2p/p2p.go]: Good point. I can update.

File: p2p/host.go [hunk 10]
```diff
@@ -51,154 +72,225 @@ func newHost(ctx context.Context, cfg *Config) (*host, error) {
...
+	for _, addr := range h.h.Addrs() {
+		fmt.Println(addr.Encapsulate(h.address).String())
 	}
 }
 
-func (h *host) registerStreamHandler(handler func(net.Stream)) {
+// registerConnHandler registers the connection handler (see handleConn)
+func (h *host) registerConnHandler(handler func(network.Conn)) {
+	h.h.Network().SetConnHandler(handler)
+}
```
Comment (ryanchristo) [inline p2p/host.go]: This ended up being much easier than the approach with the connection manager.

File: p2p/host.go [hunk 11]
```diff
@@ -51,154 +73,245 @@ func newHost(ctx context.Context, cfg *Config) (*host, error) {
...
-		stream, err = h.h.NewStream(h.ctx, peer.ID, h.protocolId)
-		log.Debug("opening new stream ", "to", peer.ID)
-		if err != nil {
-			log.Error("failed to open stream", "error", err)
-			return err
-		}
-	} else {
-		log.Debug("using existing stream", "to", peer.ID)
-	}
+	// TODO: investigate get existing stream breaking tests
```
Comment (ryanchristo) [inline p2p/host.go]: addressed in #437

File: p2p/p2p.go [hunk 12]
```diff
@@ -19,30 +19,46 @@ package p2p
...
+	host         *host
+	msgRec       <-chan Message
+	msgSend      chan<- Message
+	blockAnnRec  map[string]bool
+	blockReqRec  map[string]bool
+	blockRespRec map[string]bool
+	txMessageRec map[string]bool
+}
+
+// TODO: use generated status message
```
Comment (ryanchristo) [inline p2p/p2p.go]: addresses in #443

File: p2p/config.go [hunk 13]
```diff
@@ -48,6 +51,8 @@ type Config struct {
 	RandSeed int64
 	// Disable bootstrapping altogether. BootstrapNodes has no effect over this.
 	NoBootstrap bool
+	// Disables gossiping
+	NoGossip bool
```
Comment (ryanchristo) [inline p2p/config.go]: This is a solution for testing that also seemed useful as a configuration option.

File: p2p/host.go [hunk 14]
```diff
@@ -6,41 +22,47 @@ import (
...
 	dht         *kaddht.IpfsDHT
+	mdns        discovery.Service
 	bootnodes   []peer.AddrInfo
 	noBootstrap bool
+	noGossip    bool
 	noMdns      bool
-	mdns        discovery.Service
+	address     ma.Multiaddr
 	protocolId  protocol.ID
+	peerStatus  map[peer.ID]bool // TODO: investigate peer status storage options
```
Comment (ryanchristo) [inline p2p/host.go]: addressed in #444

File: p2p/p2p.go [hunk 15]
```diff
@@ -51,134 +67,253 @@ func NewService(conf *Config, msgSend chan<- Message, msgRec <-chan Message) (*S
...
+
+// handleStreamStatus handles status messages written to the stream
+func (s *Service) handleStreamStatus(stream network.Stream, msg Message) {
+
+	// TODO: use generated status message
+	hostStatus := statusMessage
+
+	switch {
+
+	// TODO: implement status message validation
```
Comment (ryanchristo) [inline p2p/p2p.go]: addressed in #444

File: p2p/p2p_test.go [hunk 16]
```diff
@@ -45,18 +48,70 @@ func TestStartService(t *testing.T) {
...
 	node := startNewService(t, config, nil, nil)
 	node.Stop()
 }
 
+func TestConnect(t *testing.T) {
+	configA := &Config{
+		Port:        7001,
+		RandSeed:    1,
+		NoBootstrap: true,
+		NoMdns:      true, // TODO: investigate failed dials, disable for now
```
Comment (ryanchristo) [inline p2p/p2p_test.go]: addressed in #423

File: p2p/host.go [hunk 17]
```diff
@@ -209,31 +322,11 @@ func (h *host) peerCount() int {
 	return len(peers)
 }
 
-// close shuts down the host and its components
-func (h *host) close() error {
```
Comment (noot) [inline p2p/host.go]: was this removed?

Comment (ryanchristo) [reply p2p/host.go]: Nope just moved [here](https://github.com/ChainSafe/gossamer/pull/427/files#diff-697b58a8ad3efb7d1ebbd09bcf39efb0R123)

File: p2p/connmgr.go [hunk 18]
```diff
@@ -19,63 +19,99 @@ package p2p
...
+		"disconnected",
+		"host", c.LocalPeer(),
+		"peer", c.RemotePeer(),
+	)
+}
+
+// OpenedStream is called when a stream opened
+func (cm *ConnManager) OpenedStream(n network.Network, s network.Stream) {
+	protocol := s.Protocol()
+	if protocol != "" {
```
[the remark this answers is not in the document]
Comment (ryanchristo) [reply p2p/connmgr.go]: There are a number of streams with an empty protocol id being logged. This will only log opened streams with a protocol id. Essentially this cleans up the logs for debugging purposes.

File: p2p/host.go [hunk 19]
```diff
@@ -51,154 +72,225 @@ func newHost(ctx context.Context, cfg *Config) (*host, error) {
...
+		log.Trace(
+			"bootstrap",
+			"host", h.id(),
+			"peer", peerInfo.ID,
+		)
+		// connect to each peer
+		err := h.connect(peerInfo)
 		if err != nil {
-			log.Debug("failed to dial bootstrap peer", "err", err)
+			log.Error("connect", "error", err)
```
[the remark this answers is not in the document]
Comment (ryanchristo) [reply p2p/host.go]: Hmm... I can revert but `err` will provide the error message for why `connect` failed. Also, will `connect` throw any other errors rather than just a failed dial error?

File: p2p/host.go [hunk 20]
```diff
@@ -51,154 +72,225 @@ func newHost(ctx context.Context, cfg *Config) (*host, error) {
...
+		// create new mdns service
+		mdns, err := discovery.NewMdnsService(
+			h.ctx,
+			h.h,
+			mdnsPeriod,
+			string(h.protocolId),
+		)
 		if err != nil {
-			log.Error("error starting MDNS", "err", err)
+			log.Error("start mdns", "error", err)
```
[the remark this answers is not in the document]
Comment (ryanchristo) [reply p2p/host.go]: I can revert just thought it might be helpful to be consistent. No need to include "error" as the first word for the message being passed to `log.Error`, which is labeled error in the logs.

File: p2p/p2p.go [hunk 21]
```diff
@@ -51,134 +67,253 @@ func NewService(conf *Config, msgSend chan<- Message, msgRec <-chan Message) (*S
...
+		log.Debug(
+			"received message",
+			"host", s.host.id(),
+			"type", msg.GetType(),
+		)
+
+		// check if message should be broadcasted
+		if !s.shouldBroadcast(msg) {
+			log.Error(
+				"message ignored",
```
[the remark this answers is not in the document]
Comment (ryanchristo) [reply p2p/p2p.go]: good catch

File: go.mod [hunk 22]
```diff
@@ -19,6 +19,7 @@ require (
 	github.com/libp2p/go-libp2p v0.4.1
 	github.com/libp2p/go-libp2p-core v0.2.5
 	github.com/libp2p/go-libp2p-kad-dht v0.3.0
+	github.com/libp2p/go-libp2p-peerstore v0.1.4
```
[the remark this answers is not in the document]
Comment (ryanchristo) [reply go.mod]: fixed

File: p2p/p2p.go (hunk 21 above)
[the remark this answers is not in the document]
Comment (ryanchristo) [reply p2p/p2p.go]: fixed

File: p2p/connmgr.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (ansermino) [reply p2p/connmgr.go]: I don't think that's sufficient reason not to log them. You are hiding information this might be relevant to debugging.

[the remark this answers is not in the document]
Comment (ryanchristo) [reply p2p/connmgr.go]: This is true. I think maybe just something I was using at the time. Fixed.

File: p2p/host.go (hunk 20 above)
[the remark this answers is not in the document]
Comment (ryanchristo) [reply p2p/host.go]: Yea, still getting the hang of how to use logging. Fixed here and elsewhere.

File: p2p/host.go (hunk 19 above)
[the remark this answers is not in the document]
Comment (ryanchristo) [reply p2p/host.go]: Fixed.

File: p2p/p2p.go [hunk 23]
```diff
@@ -51,134 +66,248 @@ func NewService(conf *Config, msgSend chan<- Message, msgRec <-chan Message) (*S
...
+	// broadcast to all connected peers if gossip enabled
+	if !s.host.noGossip {
 
-// ID returns the host's ID
+		log.Trace(
+			"gossiping",
+			"host", stream.Conn().LocalPeer(),
+			"type", msg.GetType(),
+		)
+
```
Comment (ansermino) [inline p2p/p2p.go]: Also seems unnecessary, once gossiping is migrated this might have more relevance

File: p2p/p2p.go [hunk 24]
```diff
@@ -198,50 +327,28 @@ func (s *Service) NoBootstrapping() bool {
...
 	}
 
-	// read entire message
-	rawMsg, err := rw.Reader.Peek(int(length))
+	// check message type
+	_, err = rw.Reader.Peek(1)
 	if err != nil {
-		log.Error("failed to read message", "err", err)
-		return nil, nil, err
+		return nil, err
```
Comment (ansermino) [inline p2p/p2p.go]: I don't think this is needed any more. `Peek` shouldn't change anything, iirc this was to check what type of message it was, which is no longer necessary.

File: p2p/p2p.go [hunk 25]
```diff
@@ -51,134 +66,248 @@ func NewService(conf *Config, msgSend chan<- Message, msgRec <-chan Message) (*S
...
+
+	// check if message should be broadcasted
+	if !s.shouldBroadcast(msg) {
+		log.Trace(
+			"message ignored",
+			"host", s.host.id(),
+			"type", msg.GetType(),
+		)
+		return
+	}
```
[the remark this answers is not in the document]
Comment (ryanchristo) [reply p2p/p2p.go]: It was useful for debugging when writing the tests to know if a non-status message was sent and ignored before a status message was sent and confirmed. Would be nice to keep as `Trace` level logging in my opinion but I can remove.

File: p2p/p2p.go (hunk 23 above)
Comment (ryanchristo) [reply p2p/p2p.go]: Once again, it was helpful at the time when writing tests but I can remove.

File: p2p/p2p.go (hunk 24 above)
Comment (ryanchristo) [reply p2p/p2p.go]: Removed.
